blueprint:
  name: "Lights: Dim Up"
  description: "Dim up a light when a button is held down"
  domain: script

fields:
  dim_level:
    description: "Target dim level entity"
  button:
    description: "Button entity controlling the dim up action"
  max_level:
    description: "Maximum dim level"

sequence:
  - repeat:
      sequence:
        - alias: Increase dim level
          action: input_number.set_value
          target:
            entity_id: "{{ dim_level }}"
          data:
            value: "{{ (states(dim_level) | int | abs) + 1 }}"
        - delay:
            milliseconds: 50.0
      while:
        - condition: template
          value_template: "{{ is_state(button, 'on') }}"
        - condition: template
          value_template: "{{ states(dim_level) | int < max_level | int }}"
        - condition: template
          value_template: "{{ states(dim_level) | int > 0 }}"
