[project]
name = "zero-data"
version = "0.9.3"
description = ""
readme = "README.md"
authors = [
    { name = "Boudewijn van Groos", email = "boudewijn.vangroos@foundationzero.org>" },
    { name = "Dustin van Weersel", email = "dustin.vanweersel@foundationzero.org>" }
]
requires-python = ">= 3.13.1,<4.0"
dependencies = [
    "aiomqtt (>=2.3.0,<3.0.0)",
    "gspread (>=6.2.1,<7.0.0)",
    "openpyxl (>=3.1.5,<4.0.0)",
    "polars (>=1.16.0,<2.0.0)",
    "pydantic (>=2.11.7,<3.0.0)",
    "pydantic-settings (>=2.7.1,<3.0.0)"
]

[project.scripts]
zero-data = "zero_data.__main__:run"

[tool.poetry.group.dbt.dependencies]
dbt-core = "^1.9.3"
dbt-risingwave = "^1.9.0"

[tool.poetry.group.dev]
optional = true

[tool.poetry.group.dev.dependencies]
ipykernel = "^6.29.5"
mypy = "^1.14.1"
notebook = "^7.3.2"
pandas = "^2.2.3"
python-dotenv = "^1.1.0"
ruff = "^0.9.3"
types-openpyxl = "^3.1.5.20250602"
sqlalchemy = "^2.0.43"

[tool.poetry.group.test]
optional = true

[tool.poetry.group.test.dependencies]
freezegun = "^1.5.5"
pytest = "^8.3.4"
pytest-asyncio = "^0.25.3"
pytest-env = "^1.1.5"
pytest-mock = "^3.14.0"

[tool.mypy]
plugins = "pydantic.mypy"
check_untyped_defs = true

[tool.pytest.ini_options]
testpaths = ["tests"]
asyncio_default_fixture_loop_scope = "function"
asyncio_mode = "auto"
pythonpath = ["src"]

[tool.ruff]
# Needs to be included for Ruff to read required-version

[tool.dotenv]
location = ".env"

[tool.uv.workspace]
members = ["validate-io-list-tool2"]

[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"
