import { Roles } from "../../src/@types";

export const tokens: Record<Roles, string> = {
  [Roles.Admin]:
    "eyJ0eXAiOiJKV1QiLCJhbGciOiJFUzI1NiIsImtpZCI6ImNlMTdlMWQ2MGY5YTBkODRmOTA2YmVhZGRlYjkxYTBhIn0.eyJodHRwczovL2hhc3VyYS5pby9qd3QvY2xhaW1zIjp7IngtaGFzdXJhLWRlZmF1bHQtcm9sZSI6InVzZXIiLCJ4LWhhc3VyYS1hbGxvd2VkLXJvbGVzIjpbInVzZXIiLCJhZG1pbiJdfX0.cPDZfwzO8fnrEZPZrW3kdtiGWiUvD680fsqTgyoZCS-GPO5787cJFTA0koRkIuE8lLA5aS-lCtb4I2wPBv11-A",
  [Roles.User]:
    "eyJ0eXAiOiJKV1QiLCJhbGciOiJFUzI1NiIsImtpZCI6ImNlMTdlMWQ2MGY5YTBkODRmOTA2YmVhZGRlYjkxYTBhIn0.eyJodHRwczovL2hhc3VyYS5pby9qd3QvY2xhaW1zIjp7IngtaGFzdXJhLWRlZmF1bHQtcm9sZSI6InVzZXIiLCJ4LWhhc3VyYS1hbGxvd2VkLXJvbGVzIjpbInVzZXIiXSwieC1oYXN1cmEtY2FiaW4iOiJkdXRjaC1jYWJpbiJ9fQ.ITbZpZczKw7HnS2zmp2bcgYFmszWizS_1GGVTylzKowliktF57P-4wCOJo9gEJszWYRTm9AZWB6LnxI4ENThIw",
};
