apiVersion: v1
kind: Service
metadata:
  name: {{ include "..fullname" . }}-headless
  namespace: {{ .Release.Namespace }}
  labels: {{- include "..labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.serviceHeadless.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector: 
    {{- include "..selectorLabels" . | nindent 4 }}
    app.kubernetes.io/part-of: ui
    app.kubernetes.io/component: spa
