from pathlib import Path

thrusters_path = str(Path(__file__).resolve().parent / "thruster_moduleV18.fmu")
pvt_path = str(Path(__file__).resolve().parent / "pvt_moduleV15_1.fmu")
consumers_path = str(Path(__file__).resolve().parent / "Consumer_ModuleV8_2.fmu")
pcm_path = str(Path(__file__).resolve().parent / "pcm_moduleV7.fmu")
high_temperature_path = str(Path(__file__).resolve().parent / "HT_SystemV13_2.fmu")
fahrenheit_path = str(Path(__file__).resolve().parent / "Fahrenheit_ModuleV4.fmu")
boilers_path = str(Path(__file__).resolve().parent / "Boilers_ModuleV4_1.fmu")
lt1_path = str(Path(__file__).resolve().parent / "LT1_ModuleV3_1.fmu")
lt2_path = str(Path(__file__).resolve().parent / "LT2_ModuleV3_2.fmu")

# thrusters_path = str(Path(__file__).resolve().parent / "Thrusters_ModuleV19.fmu")
# pvt_path = str(Path(__file__).resolve().parent / "PVT_ModuleV16.fmu")
# consumers_path = str(Path(__file__).resolve().parent / "Consumer_ModuleV9.fmu")
# pcm_path = str(Path(__file__).resolve().parent / "PCM_ModuleV8.fmu")
# high_temperature_path = str(Path(__file__).resolve().parent / "HT_SystemV14.fmu")
# adsorption_path = str(Path(__file__).resolve().parent / "Adsorption_Module.fmu")
dhw_path = str(Path(__file__).resolve().parent / "DHW_Module.fmu")
drives_path = str(Path(__file__).resolve().parent / "Drives_Module.fmu")
# dc_path = str(Path(__file__).resolve().parent / "DC_Module.fmu")
