{{- range $instance := list "atpx" "process" }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: vector-config-{{ $instance }}
  namespace: {{ $.Release.Namespace }}
data:
  config.yaml: |-
{{ $.Files.Get (printf "config-%s.yaml" $instance) | indent 4 }}
{{- end }}
