services:
  jupyter:
#    build:
#      context: .
    image: ghcr.io/foundation-zero/zero/io_validation_tool:0.9.3
    ports:
      - "8888:8888"
    volumes:
      - ./io_lists:/app/io_lists
      - ./notebooks:/app/notebooks
