import { VariableId } from "./consts.variables";

export type FiberOpticCard = {
  titleKey: string;
  variableIds: VariableId[];
};

export type FiberOpticMastColumn = {
  titleKey: string;
  cards: FiberOpticCard[];
};

export const FIBER_MAIN_CARDS: FiberOpticCard[] = [
  {
    titleKey: "loads.fiberOptics.cards.bendingMomentForeAft",
    variableIds: [
      "fiber-optic-main-mast-bending-moment-fore-aft-s9",
      "fiber-optic-main-mast-bending-moment-fore-aft-s8",
      "fiber-optic-main-mast-bending-moment-fore-aft-s7",
      "fiber-optic-main-mast-bending-moment-fore-aft-s6",
      "fiber-optic-main-mast-bending-moment-fore-aft-s5",
      "fiber-optic-main-mast-bending-moment-fore-aft-s4",
      "fiber-optic-main-mast-bending-moment-fore-aft-s3",
      "fiber-optic-main-mast-bending-moment-fore-aft-s2",
      "fiber-optic-main-mast-bending-moment-fore-aft-s1",
    ],
  },
  {
    titleKey: "loads.fiberOptics.cards.bendingMomentSideWay",
    variableIds: [
      "fiber-optic-main-mast-bending-moment-side-way-s9",
      "fiber-optic-main-mast-bending-moment-side-way-s8",
      "fiber-optic-main-mast-bending-moment-side-way-s7",
      "fiber-optic-main-mast-bending-moment-side-way-s6",
      "fiber-optic-main-mast-bending-moment-side-way-s5",
      "fiber-optic-main-mast-bending-moment-side-way-s4",
      "fiber-optic-main-mast-bending-moment-side-way-s3",
      "fiber-optic-main-mast-bending-moment-side-way-s2",
      "fiber-optic-main-mast-bending-moment-side-way-s1",
    ],
  },
  {
    titleKey: "loads.fiberOptics.cards.bendingStrainForeAft",
    variableIds: [
      "fiber-optic-main-mast-bending-strain-fore-aft-s9",
      "fiber-optic-main-mast-bending-strain-fore-aft-s8",
      "fiber-optic-main-mast-bending-strain-fore-aft-s7",
      "fiber-optic-main-mast-bending-strain-fore-aft-s6",
      "fiber-optic-main-mast-bending-strain-fore-aft-s5",
      "fiber-optic-main-mast-bending-strain-fore-aft-s4",
      "fiber-optic-main-mast-bending-strain-fore-aft-s3",
      "fiber-optic-main-mast-bending-strain-fore-aft-s2",
      "fiber-optic-main-mast-bending-strain-fore-aft-s1",
    ],
  },
  {
    titleKey: "loads.fiberOptics.cards.bendingStrainSideWay",
    variableIds: [
      "fiber-optic-main-mast-bending-strain-side-way-s9",
      "fiber-optic-main-mast-bending-strain-side-way-s8",
      "fiber-optic-main-mast-bending-strain-side-way-s7",
      "fiber-optic-main-mast-bending-strain-side-way-s6",
      "fiber-optic-main-mast-bending-strain-side-way-s5",
      "fiber-optic-main-mast-bending-strain-side-way-s4",
      "fiber-optic-main-mast-bending-strain-side-way-s3",
      "fiber-optic-main-mast-bending-strain-side-way-s2",
      "fiber-optic-main-mast-bending-strain-side-way-s1",
    ],
  },
  {
    titleKey: "loads.fiberOptics.cards.longitudinalLoad",
    variableIds: [
      "fiber-optic-main-mast-longitudinal-load-s9",
      "fiber-optic-main-mast-longitudinal-load-s8",
      "fiber-optic-main-mast-longitudinal-load-s7",
      "fiber-optic-main-mast-longitudinal-load-s6",
      "fiber-optic-main-mast-longitudinal-load-s5",
      "fiber-optic-main-mast-longitudinal-load-s4",
      "fiber-optic-main-mast-longitudinal-load-s3",
      "fiber-optic-main-mast-longitudinal-load-s2",
      "fiber-optic-main-mast-longitudinal-load-s1",
    ],
  },
  {
    titleKey: "loads.fiberOptics.cards.longitudinalStrain",
    variableIds: [
      "fiber-optic-main-mast-longitudinal-strain-s9",
      "fiber-optic-main-mast-longitudinal-strain-s8",
      "fiber-optic-main-mast-longitudinal-strain-s7",
      "fiber-optic-main-mast-longitudinal-strain-s6",
      "fiber-optic-main-mast-longitudinal-strain-s5",
      "fiber-optic-main-mast-longitudinal-strain-s4",
      "fiber-optic-main-mast-longitudinal-strain-s3",
      "fiber-optic-main-mast-longitudinal-strain-s2",
      "fiber-optic-main-mast-longitudinal-strain-s1",
    ],
  },
  {
    titleKey: "loads.fiberOptics.cards.strainFore",
    variableIds: [
      "fiber-optic-main-mast-strain-s9-fore",
      "fiber-optic-main-mast-strain-s8-fore",
      "fiber-optic-main-mast-strain-s7-fore",
      "fiber-optic-main-mast-strain-s6-fore",
      "fiber-optic-main-mast-strain-s5-fore",
      "fiber-optic-main-mast-strain-s4-fore",
      "fiber-optic-main-mast-strain-s3-fore",
      "fiber-optic-main-mast-strain-s2-fore",
      "fiber-optic-main-mast-strain-s1-fore",
    ],
  },
  {
    titleKey: "loads.fiberOptics.cards.strainSidePort",
    variableIds: [
      "fiber-optic-main-mast-strain-s9-side-port",
      "fiber-optic-main-mast-strain-s8-side-port",
      "fiber-optic-main-mast-strain-s7-side-port",
      "fiber-optic-main-mast-strain-s6-side-port",
      "fiber-optic-main-mast-strain-s5-side-port",
      "fiber-optic-main-mast-strain-s4-side-port",
      "fiber-optic-main-mast-strain-s3-side-port",
      "fiber-optic-main-mast-strain-s2-side-port",
      "fiber-optic-main-mast-strain-s1-side-port",
    ],
  },
  {
    titleKey: "loads.fiberOptics.cards.strainSideStbd",
    variableIds: [
      "fiber-optic-main-mast-strain-s9-side-stbd",
      "fiber-optic-main-mast-strain-s8-side-stbd",
      "fiber-optic-main-mast-strain-s7-side-stbd",
      "fiber-optic-main-mast-strain-s6-side-stbd",
      "fiber-optic-main-mast-strain-s5-side-stbd",
      "fiber-optic-main-mast-strain-s4-side-stbd",
      "fiber-optic-main-mast-strain-s3-side-stbd",
      "fiber-optic-main-mast-strain-s2-side-stbd",
      "fiber-optic-main-mast-strain-s1-side-stbd",
    ],
  },
  {
    titleKey: "loads.fiberOptics.cards.strainAftPort",
    variableIds: [
      "fiber-optic-main-mast-strain-s9-aft-port",
      "fiber-optic-main-mast-strain-s8-aft-port",
      "fiber-optic-main-mast-strain-s7-aft-port",
      "fiber-optic-main-mast-strain-s6-aft-port",
      "fiber-optic-main-mast-strain-s5-aft-port",
      "fiber-optic-main-mast-strain-s4-aft-port",
      "fiber-optic-main-mast-strain-s3-aft-port",
      "fiber-optic-main-mast-strain-s2-aft-port",
      "fiber-optic-main-mast-strain-s1-aft-port",
    ],
  },
  {
    titleKey: "loads.fiberOptics.cards.strainAftStbd",
    variableIds: [
      "fiber-optic-main-mast-strain-s9-aft-stbd",
      "fiber-optic-main-mast-strain-s8-aft-stbd",
      "fiber-optic-main-mast-strain-s7-aft-stbd",
      "fiber-optic-main-mast-strain-s6-aft-stbd",
      "fiber-optic-main-mast-strain-s5-aft-stbd",
      "fiber-optic-main-mast-strain-s4-aft-stbd",
      "fiber-optic-main-mast-strain-s3-aft-stbd",
      "fiber-optic-main-mast-strain-s2-aft-stbd",
      "fiber-optic-main-mast-strain-s1-aft-stbd",
    ],
  },
  {
    titleKey: "loads.fiberOptics.cards.faDeflection",
    variableIds: [
      "fiber-optic-main-mast-fa-deflection100",
      "fiber-optic-main-mast-fa-deflection090",
      "fiber-optic-main-mast-fa-deflection080",
      "fiber-optic-main-mast-fa-deflection070",
      "fiber-optic-main-mast-fa-deflection060",
      "fiber-optic-main-mast-fa-deflection050",
      "fiber-optic-main-mast-fa-deflection040",
      "fiber-optic-main-mast-fa-deflection030",
      "fiber-optic-main-mast-fa-deflection020",
      "fiber-optic-main-mast-fa-deflection010",
      "fiber-optic-main-mast-fa-deflection000",
    ],
  },
  {
    titleKey: "loads.fiberOptics.cards.faDeflectionSpr",
    variableIds: [
      "fiber-optic-main-mast-fa-deflection-spr5",
      "fiber-optic-main-mast-fa-deflection-spr4",
      "fiber-optic-main-mast-fa-deflection-spr3",
      "fiber-optic-main-mast-fa-deflection-spr2",
      "fiber-optic-main-mast-fa-deflection-spr1",
    ],
  },
  {
    titleKey: "loads.fiberOptics.cards.swDeflection",
    variableIds: [
      "fiber-optic-main-mast-sw-deflection100",
      "fiber-optic-main-mast-sw-deflection090",
      "fiber-optic-main-mast-sw-deflection080",
      "fiber-optic-main-mast-sw-deflection070",
      "fiber-optic-main-mast-sw-deflection060",
      "fiber-optic-main-mast-sw-deflection050",
      "fiber-optic-main-mast-sw-deflection040",
      "fiber-optic-main-mast-sw-deflection030",
      "fiber-optic-main-mast-sw-deflection020",
      "fiber-optic-main-mast-sw-deflection010",
      "fiber-optic-main-mast-sw-deflection000",
    ],
  },
  {
    titleKey: "loads.fiberOptics.cards.swDeflectionSpr",
    variableIds: [
      "fiber-optic-main-mast-sw-deflection-spr5",
      "fiber-optic-main-mast-sw-deflection-spr4",
      "fiber-optic-main-mast-sw-deflection-spr3",
      "fiber-optic-main-mast-sw-deflection-spr2",
      "fiber-optic-main-mast-sw-deflection-spr1",
    ],
  },
  {
    titleKey: "loads.fiberOptics.cards.temperature",
    variableIds: [
      "fiber-optic-main-mast-temperature-spr0-port",
      "fiber-optic-main-mast-temperature-spr1-fore",
      "fiber-optic-main-mast-temperature-spr1-port",
      "fiber-optic-main-mast-temperature-spr1-stbd",
      "fiber-optic-main-mast-temperature-spr2-fore",
      "fiber-optic-main-mast-temperature-spr2-port",
      "fiber-optic-main-mast-temperature-spr2-stbd",
      "fiber-optic-main-mast-temperature-spr3-port",
      "fiber-optic-main-mast-temperature-spr3-stbd",
      "fiber-optic-main-mast-temperature-spr4-aft-port",
      "fiber-optic-main-mast-temperature-spr4-aft-stbd",
      "fiber-optic-main-mast-temperature-spr4-fore",
      "fiber-optic-main-mast-temperature-spr5-fore",
      "fiber-optic-main-mast-temperature-spr5-side-port",
      "fiber-optic-main-mast-temperature-spr5-side-stbd",
    ],
  },
  {
    titleKey: "loads.fiberOptics.cards.riggingLoad",
    variableIds: [
      "fiber-optic-main-d1-ps",
      "fiber-optic-main-d1-sb",
      "fiber-optic-main-rigging-load-d2-port",
      "fiber-optic-main-rigging-load-d2-stbd",
      "fiber-optic-main-rigging-load-d3-port",
      "fiber-optic-main-rigging-load-d3-stbd",
      "fiber-optic-main-rigging-load-d4-port",
      "fiber-optic-main-rigging-load-d4-stbd",
      "fiber-optic-main-rigging-load-d5-port",
      "fiber-optic-main-rigging-load-d5-stbd",
      "fiber-optic-main-v1-ps",
      "fiber-optic-main-v1-sb",
    ],
  },
  {
    titleKey: "loads.fiberOptics.cards.riggingStrain",
    variableIds: [
      "fiber-optic-main-rigging-strain-d1-port",
      "fiber-optic-main-rigging-strain-d1-stbd",
      "fiber-optic-main-rigging-strain-d2-port",
      "fiber-optic-main-rigging-strain-d2-stbd",
      "fiber-optic-main-rigging-strain-d3-port",
      "fiber-optic-main-rigging-strain-d3-stbd",
      "fiber-optic-main-rigging-strain-d4-port",
      "fiber-optic-main-rigging-strain-d4-stbd",
      "fiber-optic-main-rigging-strain-d5-port",
      "fiber-optic-main-rigging-strain-d5-stbd",
      "fiber-optic-main-rigging-strain-v1-port",
      "fiber-optic-main-rigging-strain-v1-stbd",
    ],
  },
  {
    titleKey: "loads.fiberOptics.cards.riggingSumLoad",
    variableIds: [
      "fiber-optic-main-rigging-sum-load-v1-port",
      "fiber-optic-main-rigging-sum-load-v1-stbd",
      "fiber-optic-main-rigging-sum-load-v2-port",
      "fiber-optic-main-rigging-sum-load-v2-stbd",
      "fiber-optic-main-rigging-sum-load-v3-port",
      "fiber-optic-main-rigging-sum-load-v3-stbd",
      "fiber-optic-main-rigging-sum-load-v4-port",
      "fiber-optic-main-rigging-sum-load-v4-stbd",
    ],
  },
  {
    titleKey: "loads.fiberOptics.cards.riggingTemperature",
    variableIds: [
      "fiber-optic-main-rigging-temperature-d1-port",
      "fiber-optic-main-rigging-temperature-d1-stbd",
      "fiber-optic-main-rigging-temperature-d2-port",
      "fiber-optic-main-rigging-temperature-d2-stbd",
      "fiber-optic-main-rigging-temperature-d3-port",
      "fiber-optic-main-rigging-temperature-d3-stbd",
      "fiber-optic-main-rigging-temperature-d4-port",
      "fiber-optic-main-rigging-temperature-d4-stbd",
      "fiber-optic-main-rigging-temperature-d5-port",
      "fiber-optic-main-rigging-temperature-d5-stbd",
      "fiber-optic-main-rigging-temperature-v1-port",
      "fiber-optic-main-rigging-temperature-v1-stbd",
    ],
  },
];

export const FIBER_MIZZEN_CARDS: FiberOpticCard[] = [
  {
    titleKey: "loads.fiberOptics.cards.bendingMomentForeAft",
    variableIds: [
      "fiber-optic-mizzen-mast-bending-moment-fore-aft-s9",
      "fiber-optic-mizzen-mast-bending-moment-fore-aft-s8",
      "fiber-optic-mizzen-mast-bending-moment-fore-aft-s7",
      "fiber-optic-mizzen-mast-bending-moment-fore-aft-s6",
      "fiber-optic-mizzen-mast-bending-moment-fore-aft-s5",
      "fiber-optic-mizzen-mast-bending-moment-fore-aft-s4",
      "fiber-optic-mizzen-mast-bending-moment-fore-aft-s3",
      "fiber-optic-mizzen-mast-bending-moment-fore-aft-s2",
      "fiber-optic-mizzen-mast-bending-moment-fore-aft-s1",
    ],
  },
  {
    titleKey: "loads.fiberOptics.cards.bendingMomentSideWay",
    variableIds: [
      "fiber-optic-mizzen-mast-bending-moment-side-way-s9",
      "fiber-optic-mizzen-mast-bending-moment-side-way-s8",
      "fiber-optic-mizzen-mast-bending-moment-side-way-s7",
      "fiber-optic-mizzen-mast-bending-moment-side-way-s6",
      "fiber-optic-mizzen-mast-bending-moment-side-way-s5",
      "fiber-optic-mizzen-mast-bending-moment-side-way-s4",
      "fiber-optic-mizzen-mast-bending-moment-side-way-s3",
      "fiber-optic-mizzen-mast-bending-moment-side-way-s2",
      "fiber-optic-mizzen-mast-bending-moment-side-way-s1",
    ],
  },
  {
    titleKey: "loads.fiberOptics.cards.bendingStrainForeAft",
    variableIds: [
      "fiber-optic-mizzen-mast-bending-strain-fore-aft-s9",
      "fiber-optic-mizzen-mast-bending-strain-fore-aft-s8",
      "fiber-optic-mizzen-mast-bending-strain-fore-aft-s7",
      "fiber-optic-mizzen-mast-bending-strain-fore-aft-s6",
      "fiber-optic-mizzen-mast-bending-strain-fore-aft-s5",
      "fiber-optic-mizzen-mast-bending-strain-fore-aft-s4",
      "fiber-optic-mizzen-mast-bending-strain-fore-aft-s3",
      "fiber-optic-mizzen-mast-bending-strain-fore-aft-s2",
      "fiber-optic-mizzen-mast-bending-strain-fore-aft-s1",
    ],
  },
  {
    titleKey: "loads.fiberOptics.cards.bendingStrainSideWay",
    variableIds: [
      "fiber-optic-mizzen-mast-bending-strain-side-way-s9",
      "fiber-optic-mizzen-mast-bending-strain-side-way-s8",
      "fiber-optic-mizzen-mast-bending-strain-side-way-s7",
      "fiber-optic-mizzen-mast-bending-strain-side-way-s6",
      "fiber-optic-mizzen-mast-bending-strain-side-way-s5",
      "fiber-optic-mizzen-mast-bending-strain-side-way-s4",
      "fiber-optic-mizzen-mast-bending-strain-side-way-s3",
      "fiber-optic-mizzen-mast-bending-strain-side-way-s2",
      "fiber-optic-mizzen-mast-bending-strain-side-way-s1",
    ],
  },
  {
    titleKey: "loads.fiberOptics.cards.longitudinalLoad",
    variableIds: [
      "fiber-optic-mizzen-mast-longitudinal-load-s9",
      "fiber-optic-mizzen-mast-longitudinal-load-s8",
      "fiber-optic-mizzen-mast-longitudinal-load-s7",
      "fiber-optic-mizzen-mast-longitudinal-load-s6",
      "fiber-optic-mizzen-mast-longitudinal-load-s5",
      "fiber-optic-mizzen-mast-longitudinal-load-s4",
      "fiber-optic-mizzen-mast-longitudinal-load-s3",
      "fiber-optic-mizzen-mast-longitudinal-load-s2",
      "fiber-optic-mizzen-mast-longitudinal-load-s1",
    ],
  },
  {
    titleKey: "loads.fiberOptics.cards.longitudinalStrain",
    variableIds: [
      "fiber-optic-mizzen-mast-longitudinal-strain-s9",
      "fiber-optic-mizzen-mast-longitudinal-strain-s8",
      "fiber-optic-mizzen-mast-longitudinal-strain-s7",
      "fiber-optic-mizzen-mast-longitudinal-strain-s6",
      "fiber-optic-mizzen-mast-longitudinal-strain-s5",
      "fiber-optic-mizzen-mast-longitudinal-strain-s4",
      "fiber-optic-mizzen-mast-longitudinal-strain-s3",
      "fiber-optic-mizzen-mast-longitudinal-strain-s2",
      "fiber-optic-mizzen-mast-longitudinal-strain-s1",
    ],
  },
  {
    titleKey: "loads.fiberOptics.cards.strainFore",
    variableIds: [
      "fiber-optic-mizzen-mast-strain-s9-fore",
      "fiber-optic-mizzen-mast-strain-s8-fore",
      "fiber-optic-mizzen-mast-strain-s7-fore",
      "fiber-optic-mizzen-mast-strain-s6-fore",
      "fiber-optic-mizzen-mast-strain-s5-fore",
      "fiber-optic-mizzen-mast-strain-s4-fore",
      "fiber-optic-mizzen-mast-strain-s3-fore",
      "fiber-optic-mizzen-mast-strain-s2-fore",
      "fiber-optic-mizzen-forestay",
    ],
  },
  {
    titleKey: "loads.fiberOptics.cards.strainSidePort",
    variableIds: [
      "fiber-optic-mizzen-mast-strain-s9-side-port",
      "fiber-optic-mizzen-mast-strain-s8-side-port",
      "fiber-optic-mizzen-mast-strain-s7-side-port",
      "fiber-optic-mizzen-mast-strain-s6-side-port",
      "fiber-optic-mizzen-mast-strain-s5-side-port",
      "fiber-optic-mizzen-mast-strain-s4-side-port",
      "fiber-optic-mizzen-mast-strain-s3-side-port",
      "fiber-optic-mizzen-mast-strain-s2-side-port",
      "fiber-optic-mizzen-mast-strain-s1-side-port",
    ],
  },
  {
    titleKey: "loads.fiberOptics.cards.strainSideStbd",
    variableIds: [
      "fiber-optic-mizzen-mast-strain-s9-side-stbd",
      "fiber-optic-mizzen-mast-strain-s8-side-stbd",
      "fiber-optic-mizzen-mast-strain-s7-side-stbd",
      "fiber-optic-mizzen-mast-strain-s6-side-stbd",
      "fiber-optic-mizzen-mast-strain-s5-side-stbd",
      "fiber-optic-mizzen-mast-strain-s4-side-stbd",
      "fiber-optic-mizzen-mast-strain-s3-side-stbd",
      "fiber-optic-mizzen-mast-strain-s2-side-stbd",
      "fiber-optic-mizzen-mast-strain-s1-side-stbd",
    ],
  },
  {
    titleKey: "loads.fiberOptics.cards.strainAftPort",
    variableIds: [
      "fiber-optic-mizzen-mast-strain-s9-aft-port",
      "fiber-optic-mizzen-mast-strain-s8-aft-port",
      "fiber-optic-mizzen-mast-strain-s7-aft-port",
      "fiber-optic-mizzen-mast-strain-s6-aft-port",
      "fiber-optic-mizzen-mast-strain-s5-aft-port",
      "fiber-optic-mizzen-mast-strain-s4-aft-port",
      "fiber-optic-mizzen-mast-strain-s3-aft-port",
      "fiber-optic-mizzen-mast-strain-s2-aft-port",
      "fiber-optic-mizzen-mast-strain-s1-aft-port",
    ],
  },
  {
    titleKey: "loads.fiberOptics.cards.strainAftStbd",
    variableIds: [
      "fiber-optic-mizzen-mast-strain-s9-aft-stbd",
      "fiber-optic-mizzen-mast-strain-s8-aft-stbd",
      "fiber-optic-mizzen-mast-strain-s7-aft-stbd",
      "fiber-optic-mizzen-mast-strain-s6-aft-stbd",
      "fiber-optic-mizzen-mast-strain-s5-aft-stbd",
      "fiber-optic-mizzen-mast-strain-s4-aft-stbd",
      "fiber-optic-mizzen-mast-strain-s3-aft-stbd",
      "fiber-optic-mizzen-mast-strain-s2-aft-stbd",
      "fiber-optic-mizzen-mast-strain-s1-aft-stbd",
    ],
  },
  {
    titleKey: "loads.fiberOptics.cards.faDeflection",
    variableIds: [
      "fiber-optic-mizzen-mast-fa-deflection100",
      "fiber-optic-mizzen-mast-fa-deflection090",
      "fiber-optic-mizzen-mast-fa-deflection080",
      "fiber-optic-mizzen-mast-fa-deflection070",
      "fiber-optic-mizzen-mast-fa-deflection060",
      "fiber-optic-mizzen-mast-fa-deflection050",
      "fiber-optic-mizzen-mast-fa-deflection040",
      "fiber-optic-mizzen-mast-fa-deflection030",
      "fiber-optic-mizzen-mast-fa-deflection020",
      "fiber-optic-mizzen-mast-fa-deflection010",
      "fiber-optic-mizzen-mast-fa-deflection000",
    ],
  },
  {
    titleKey: "loads.fiberOptics.cards.faDeflectionSpr",
    variableIds: [
      "fiber-optic-mizzen-mast-fa-deflection-spr5",
      "fiber-optic-mizzen-mast-fa-deflection-spr4",
      "fiber-optic-mizzen-mast-fa-deflection-spr3",
      "fiber-optic-mizzen-mast-fa-deflection-spr2",
      "fiber-optic-mizzen-mast-fa-deflection-spr1",
    ],
  },
  {
    titleKey: "loads.fiberOptics.cards.swDeflection",
    variableIds: [
      "fiber-optic-mizzen-mast-sw-deflection100",
      "fiber-optic-mizzen-mast-sw-deflection090",
      "fiber-optic-mizzen-mast-sw-deflection080",
      "fiber-optic-mizzen-mast-sw-deflection070",
      "fiber-optic-mizzen-mast-sw-deflection060",
      "fiber-optic-mizzen-mast-sw-deflection050",
      "fiber-optic-mizzen-mast-sw-deflection040",
      "fiber-optic-mizzen-mast-sw-deflection030",
      "fiber-optic-mizzen-mast-sw-deflection020",
      "fiber-optic-mizzen-mast-sw-deflection010",
      "fiber-optic-mizzen-mast-sw-deflection000",
    ],
  },
  {
    titleKey: "loads.fiberOptics.cards.swDeflectionSpr",
    variableIds: [
      "fiber-optic-mizzen-mast-sw-deflection-spr5",
      "fiber-optic-mizzen-mast-sw-deflection-spr4",
      "fiber-optic-mizzen-mast-sw-deflection-spr3",
      "fiber-optic-mizzen-mast-sw-deflection-spr2",
      "fiber-optic-mizzen-mast-sw-deflection-spr1",
    ],
  },
  {
    titleKey: "loads.fiberOptics.cards.temperature",
    variableIds: [
      "fiber-optic-mizzen-mast-temperature-spr0-port",
      "fiber-optic-mizzen-mast-temperature-spr1-fore",
      "fiber-optic-mizzen-mast-temperature-spr1-port",
      "fiber-optic-mizzen-mast-temperature-spr1-stbd",
      "fiber-optic-mizzen-mast-temperature-spr2-fore",
      "fiber-optic-mizzen-mast-temperature-spr2-port",
      "fiber-optic-mizzen-mast-temperature-spr2-stbd",
      "fiber-optic-mizzen-mast-temperature-spr3-port",
      "fiber-optic-mizzen-mast-temperature-spr3-stbd",
      "fiber-optic-mizzen-mast-temperature-spr4-aft-port",
      "fiber-optic-mizzen-mast-temperature-spr4-aft-stbd",
      "fiber-optic-mizzen-mast-temperature-spr4-fore",
      "fiber-optic-mizzen-mast-temperature-spr5-fore",
      "fiber-optic-mizzen-mast-temperature-spr5-side-port",
      "fiber-optic-mizzen-mast-temperature-spr5-side-stbd",
    ],
  },
  {
    titleKey: "loads.fiberOptics.cards.riggingLoad",
    variableIds: [
      "fiber-optic-mizzen-d1-ps",
      "fiber-optic-mizzen-d1-sb",
      "fiber-optic-mizzen-rigging-load-d2-port",
      "fiber-optic-mizzen-rigging-load-d2-stbd",
      "fiber-optic-mizzen-rigging-load-d3-port",
      "fiber-optic-mizzen-rigging-load-d3-stbd",
      "fiber-optic-mizzen-rigging-load-d4-port",
      "fiber-optic-mizzen-rigging-load-d4-stbd",
      "fiber-optic-mizzen-rigging-load-d5-port",
      "fiber-optic-mizzen-rigging-load-d5-stbd",
      "fiber-optic-mizzen-v1-ps",
      "fiber-optic-mizzen-v1-sb",
    ],
  },
  {
    titleKey: "loads.fiberOptics.cards.riggingStrain",
    variableIds: [
      "fiber-optic-mizzen-rigging-strain-d1-port",
      "fiber-optic-mizzen-rigging-strain-d1-stbd",
      "fiber-optic-mizzen-rigging-strain-d2-port",
      "fiber-optic-mizzen-rigging-strain-d2-stbd",
      "fiber-optic-mizzen-rigging-strain-d3-port",
      "fiber-optic-mizzen-rigging-strain-d3-stbd",
      "fiber-optic-mizzen-rigging-strain-d4-port",
      "fiber-optic-mizzen-rigging-strain-d4-stbd",
      "fiber-optic-mizzen-rigging-strain-d5-port",
      "fiber-optic-mizzen-rigging-strain-d5-stbd",
      "fiber-optic-mizzen-rigging-strain-v1-port",
      "fiber-optic-mizzen-rigging-strain-v1-stbd",
    ],
  },
  {
    titleKey: "loads.fiberOptics.cards.riggingSumLoad",
    variableIds: [
      "fiber-optic-mizzen-rigging-sum-load-v1-port",
      "fiber-optic-mizzen-rigging-sum-load-v1-stbd",
      "fiber-optic-mizzen-rigging-sum-load-v2-port",
      "fiber-optic-mizzen-rigging-sum-load-v2-stbd",
      "fiber-optic-mizzen-rigging-sum-load-v3-port",
      "fiber-optic-mizzen-rigging-sum-load-v3-stbd",
      "fiber-optic-mizzen-rigging-sum-load-v4-port",
      "fiber-optic-mizzen-rigging-sum-load-v4-stbd",
    ],
  },
  {
    titleKey: "loads.fiberOptics.cards.riggingTemperature",
    variableIds: [
      "fiber-optic-mizzen-rigging-temperature-d1-port",
      "fiber-optic-mizzen-rigging-temperature-d1-stbd",
      "fiber-optic-mizzen-rigging-temperature-d2-port",
      "fiber-optic-mizzen-rigging-temperature-d2-stbd",
      "fiber-optic-mizzen-rigging-temperature-d3-port",
      "fiber-optic-mizzen-rigging-temperature-d3-stbd",
      "fiber-optic-mizzen-rigging-temperature-d4-port",
      "fiber-optic-mizzen-rigging-temperature-d4-stbd",
      "fiber-optic-mizzen-rigging-temperature-d5-port",
      "fiber-optic-mizzen-rigging-temperature-d5-stbd",
      "fiber-optic-mizzen-rigging-temperature-v1-port",
      "fiber-optic-mizzen-rigging-temperature-v1-stbd",
    ],
  },
];

export const FIBER_OPTICS_COLUMNS: FiberOpticMastColumn[] = [
  { titleKey: "loads.fiberOptics.columns.mizzenMast", cards: FIBER_MIZZEN_CARDS },
  { titleKey: "loads.fiberOptics.columns.mainMast", cards: FIBER_MAIN_CARDS },
];
