{{ config(materialized='table_with_connector') }}
CREATE TABLE {{ this }} (
	TIMESTAMP	TIMESTAMP,
	BCKUP_GEN_SERV_PUMP_FIELD_RUNN_FDBCK	BOOLEAN,
	BCKUP_GEN_SERV_PUMP_FIELD_START	BOOLEAN,
	BCKUP_GEN_SERV_PUMP_FIELD_STOP	BOOLEAN,
	BCKUP_GEN_SERV_PUMP_REM_AVAIL	BOOLEAN,
	BCKUP_GEN_SERV_PUMP_START_RUN	BOOLEAN,
	GEN_SERV_PUMP1_REM_AVAIL	BOOLEAN,
	GEN_SERV_PUMP1_REM_START	BOOLEAN,
	GEN_SERV_PUMP2_FIELD_AVAIL_FDBCK	BOOLEAN,
	GEN_SERV_PUMP2_FIELD_FAULT_FDBCK	BOOLEAN,
	GEN_SERV_PUMP2_FIELD_RUNN_FDBCK	BOOLEAN,
	GEN_SERV_PUMP2_FIELD_START	BOOLEAN,
	GEN_SERV_PUMP2_FIELD_STOP	BOOLEAN,
	GEN_SERV_PUMP2_REM_AVAIL	BOOLEAN,
	GEN_SERV_PUMP2_REM_START	BOOLEAN,
)
{{ mqtt_with('marpower/2100_general_service') }}
