{{ config(materialized='table_with_connector') }}
CREATE TABLE {{ this }} (
	DRAIN_VLV_Y01_POS_OVERBOARD	BOOLEAN,
	DRAIN_VLV_Y01_POS_TO_PURO	BOOLEAN,
	DRAIN_VLV_Y02_POS_OVERBOARD	BOOLEAN,
	DRAIN_VLV_Y02_POS_TO_PURO	BOOLEAN,
	TECH_WATER_CHLORINE_UNIT_ALARM	BOOLEAN,
	TECH_WAT_FLOW_ADIABATIC_COOL_B03	REAL,
	TECH_WAT_FLOW_ADIABATIC_COOL_B07	REAL,
	TECH_WAT_FLOW_ADIABATIC_COOL_B08	REAL,
	TECH_WAT_FLOW_ADIABATIC_COOL_B09	REAL,
	TECH_WAT_FLOW_CHARCOAL_FILTER_B01	REAL,
	TECH_WAT_FLOW_CHARCOAL_FILTER_B02	REAL,
	TECH_WAT_FLOW_REEL_FOR_DECKWASH_B04	REAL,
	TECH_WAT_FLOW_REEL_FOR_DECKWASH_B05	REAL,
	TECH_WAT_FLOW_REEL_FOR_DECKWASH_B06	REAL,
	TECH_WAT_SALINITY	REAL,
	TECH_WAT_TANK1_LEVEL	REAL,
	TECH_WAT_TANK2_LEVEL	REAL,
	TECH_WAT_VALVE_COLD_AIR_FR32_Y04_OPEN_CLOSE	BOOLEAN,
	TECH_WAT_VALVE_COLD_AIR_FR32_Y05_OPEN_CLOSE	BOOLEAN,
	TECH_WAT_VALVE_COLD_AIR_FR68_Y03_OPEN_CLOSE	BOOLEAN,
)
{{ mqtt_with('marpower/2500_techwater') }}
