{{ config(materialized='table_with_connector') }}
CREATE TABLE {{ this }} (
	TRANS_PUMP_BLCK_WAT_REM_AVAIL	BOOLEAN,
	TRANS_PUMP_BLCK_WAT_RUNNING	BOOLEAN,
	TRANS_PUMP_GREY_WAT_REM_AVAIL	BOOLEAN,
	TRANS_PUMP_GREY_WAT_RUNNING	BOOLEAN,
	PUMP_FWD_GREY_WAT_REM_AVAIL	BOOLEAN,
	PUMP_FWD_GREY_WAT_RUNNING	BOOLEAN,
	SEW_TREAT_RUNNING	BOOLEAN,
	SEW_TREAT_RELEASE	BOOLEAN,
	SEW_TREAT_GEN_ALARM	BOOLEAN,
	SEW_TREAT_DRY_RUNN_PROT	BOOLEAN,
	LEVEL_GREY_WATER_TANK_AFT_SB	REAL,
	LEVEL_GREY_WATER_TANK_AFT_PS	REAL,
	LEVEL_SLUDGE_TANK	REAL,
	TRANS_PUMP_BLCK_WAT_START_STOP	BOOLEAN,
	TRANS_PUMP_GREY_WAT_START_STOP	BOOLEAN,
	PUMP_FWD_GREY_WAT_START_STOP	BOOLEAN,
	LEVEL_GREY_WATER_TANK_FWD_SB	REAL,
)
{{ mqtt_with('3400_sewage') }}