{{ config(materialized='table_with_connector') }}
CREATE TABLE {{ this }} (
	TECH_WAT_FLOW_REEL_FOR_DECKWASH_B04	REAL,
	TECH_WAT_FLOW_CHARCOAL_FILTER_B02	REAL,
	TECH_WAT_FLOW_ADIABATIC_COOL_B03	REAL,
	TECH_WAT_FLOW_ADIABATIC_COOL_B07	REAL,
)
{{ mqtt_with('KEB1_AI29') }}