{{ config(materialized='table_with_connector') }}
CREATE TABLE {{ this }} (
	STRIP_PUMP_RUNNING	BOOLEAN,
	GEN_SERV_PUMP1_REM_START	BOOLEAN,
	CHAIN_LOCK_PUMP_REM_AVAIL	BOOLEAN,
	CHAIN_LOCK_PUMP_RUNNING	BOOLEAN,
	GEN_SERV_PUMP2_REM_START	BOOLEAN,
	SUBMERS_PUMP1_REM_AVAIL	BOOLEAN,
	SUBMERS_PUMP1_RUNNING	BOOLEAN,
)
{{ mqtt_with('KEB1_DI21') }}