{{ config(materialized='table_with_connector') }}
CREATE TABLE {{ this }} (
	FLOW_GUEST_CABIN_PS_FWD_HOT_WATER	REAL,
	FLOW_GUEST_CABIN_PS_FWD_COLD_WATER	REAL,
	FLOW_GUEST_CABIN_PS_AFT_HOT_WATER	REAL,
	FLOW_GUEST_CABIN_PS_AFT_COLD_WATER	REAL,
)
{{ mqtt_with('KEB1_AI21') }}