{{ config(materialized='table_with_connector') }}
CREATE TABLE {{ this }} (
	SEW_TREAT_RELEASE	BOOLEAN,
	SEW_TREAT_GEN_ALARM	BOOLEAN,
	SEW_TREAT_DRY_RUNN_PROT	BOOLEAN,
	PASS_HATCH_CL_LOCK	BOOLEAN,
	SBL_SB_CLOSED_LOCKED	BOOLEAN,
	SBL_SPARE_INPUT	BOOLEAN,
	NOVEC_RELEASED_ALARM	BOOLEAN,
)
{{ mqtt_with('KEB1_DI24') }}