{{ config(materialized='table_with_connector') }}
CREATE TABLE {{ this }} (
	VENT_EXTR_TECH_SPACE_START_STOP	BOOLEAN,
	VENT_FP_FR10_PS_ON_OFF	BOOLEAN,
	VENT_FP_FR10_PS_SPEED_LOW_HIGH	BOOLEAN,
	VENT_LOCK_FR19_PS_ON_OFF	BOOLEAN,
	VENT_LOCK_FR19_PS_SPEED_LOW_HIGH	BOOLEAN,
	VENT_LOCK_FR27_PS_ON_OFF	BOOLEAN,
	VENT_LOCK_FR27_PS_SPEED_LOW_HIGH	BOOLEAN,
	VENT_LOCK_FR27_SB_ON_OFF	BOOLEAN,
	VENT_LOCK_FR27_SB_SPEED_LOW_HIGH	BOOLEAN,
	VENT_LOCK_FR40_PS_ON_OFF	BOOLEAN,
	VENT_LOCK_FR40_PS_SPEED_LOW_HIGH	BOOLEAN,
	VENT_LOCK_FR40_SB_ON_OFF	BOOLEAN,
	VENT_LOCK_FR40_SB_SPEED_LOW_HIGH	BOOLEAN,
	VENT_LOCK_FR48_PS_ON_OFF	BOOLEAN,
	VENT_FLOCK_R48_PS_SPEED_LOW_HIGH	BOOLEAN,
	VENT_LAZ_FR73_PS_ON_OFF	BOOLEAN,
)
{{ mqtt_with('KEB1_DO61') }}