{{ config(materialized='table_with_connector') }}
CREATE TABLE {{ this }} (
	SUBMERS_PUMP2_REM_AVAIL	BOOLEAN,
	SUBMERS_PUMP2_RUNNING	BOOLEAN,
	SUBMERS_PUMP3_REM_AVAIL	BOOLEAN,
	SUBMERS_PUMP3_RUNNING	BOOLEAN,
	FRESH_WATER_MAK1_ALARM	BOOLEAN,
	FRESH_WATER_MAK2_ALARM	BOOLEAN,
)
{{ mqtt_with('KEB1_DI22') }}