{{ config(materialized='table_with_connector') }}
CREATE TABLE {{ this }} (
	LAZA_ACCESS_HATCH_SB_MID	BOOLEAN,
	LAZA_ACCESS_HATCH_PS_MID	BOOLEAN,
	LAZA_ACCESS_HATCH_SB_AFT	BOOLEAN,
	LAZA_ACCESS_HATCH_PS_AFT	BOOLEAN,
	AFT_DECKH_VENT_HATCH	BOOLEAN,
	SBP_PS_CLOSED_LOCKED	BOOLEAN,
	VENT_SUPP_TECH_SPACE_REM_AVAIL	BOOLEAN,
	VENT_SUPP_TECH_SPACE_RUNNING	BOOLEAN,
)
{{ mqtt_with('KEB1_DI26') }}