{{ config(materialized='table_with_connector') }}
CREATE TABLE {{ this }} (
	VENT_EXTR_TECH_SPACE_REM_AVAIL	BOOLEAN,
	VENT_EXTR_TECH_SPACE_RUNNING	BOOLEAN,
	BATT_VENT_AFT_PS_ON_RUN	BOOLEAN,
	BATT_VENT_AFT_PS_ON_FAULT	BOOLEAN,
	BATT_VENT_AFT_PS_ON_READY	BOOLEAN,
	BATT_VENT_AFT_SB_ON_RUN	BOOLEAN,
	BATT_VENT_AFT_SB_ON_FAULT	BOOLEAN,
	BATT_VENT_AFT_SB_ON_READY	BOOLEAN,
)
{{ mqtt_with('KEB1_DI27') }}