{{ config(materialized='table_with_connector') }}
CREATE TABLE {{ this }} (
	FLOW_LOWER_SALOON_COLD_WATER	REAL,
	FLOW_DAYHEAD_COLD_WATER	REAL,
	FLOW_GUEST_CABIN_SB_HOT_WATER	REAL,
	FLOW_GUEST_CABIN_SB_COLD_WATER	REAL,
)
{{ mqtt_with('KEB1_AI20') }}