{{ config(materialized='table_with_connector') }}
CREATE TABLE {{ this }} (
	FRESH_WATER_CHLORINE_UNIT_ALARM	BOOLEAN,
	TRANS_PUMP_BLCK_WAT_REM_AVAIL	BOOLEAN,
	TRANS_PUMP_BLCK_WAT_RUNNING	BOOLEAN,
	TRANS_PUMP_GREY_WAT_REM_AVAIL	BOOLEAN,
	TRANS_PUMP_GREY_WAT_RUNNING	BOOLEAN,
	PUMP_FWD_GREY_WAT_REM_AVAIL	BOOLEAN,
	PUMP_FWD_GREY_WAT_RUNNING	BOOLEAN,
	SEW_TREAT_RUNNING	BOOLEAN,
)
{{ mqtt_with('KEB1_DI23') }}