{{ config(materialized='table_with_connector') }}
CREATE TABLE {{ this }} (
	DRAIN_VLV_Y01_POS_OVERBOARD	BOOLEAN,
	DRAIN_VLV_Y01_POS_TO_PURO	BOOLEAN,
	TECH_WATER_CHLORINE_UNIT_ALARM	BOOLEAN,
	MTS_INLET_FIRE_FLAP_RELEASED	BOOLEAN,
	MTS_INLET_FIRE_FLAP_FULLY_RESET	BOOLEAN,
	MTS_EXHAUST_FIRE_FLAP_RELEASED	BOOLEAN,
	MTS_EXHAUST_FIRE_FLAP_FULLY_RESET	BOOLEAN,
)
{{ mqtt_with('KEB1_DI28') }}