{{ config(materialized='table_with_connector') }}
CREATE TABLE {{ this }} (
	GEN_SERV_PUMP2_FIELD_RUNN_FDBCK	BOOLEAN,
	STRIP_PUMP_START	BOOLEAN,
	STRIP_PUMP_STOP	BOOLEAN,
	CHAIN_LOCK_PUMP_START	BOOLEAN,
	CHAIN_LOCK_PUMP_STOP	BOOLEAN,
	SUBMERS_PUMP1_LEVEL_HIGH	BOOLEAN,
	SUBMERS_PUMP2_LEVEL_HIGH	BOOLEAN,
	SUBMERS_PUMP3_LEVEL_HIGH	BOOLEAN,
	SEPARATOR_START	BOOLEAN,
	GEN_SERV_PUMP2_FIELD_AVAIL_FDBCK	BOOLEAN,
	GEN_SERV_PUMP2_FIELD_FAULT_FDBCK	BOOLEAN,
	ACTIVATE_HULL_TEMP_MEASUREMENT	BOOLEAN,
	TRANS_PUMP_BLCK_WAT_START_STOP	BOOLEAN,
	TRANS_PUMP_GREY_WAT_START_STOP	BOOLEAN,
	PUMP_FWD_GRAY_WAT_START_STOP	BOOLEAN,
	VENT_SUPP_TECH_SPACE_START_STOP	BOOLEAN,
)
{{ mqtt_with('KEB1_DO60') }}