{{ config(materialized='table_with_connector') }}
CREATE TABLE {{ this }} (
	VENT_LAZ_FR73_PS_SPEED_LOW_HIGH	BOOLEAN,
	VENT_LAZ_FR73_SB_ON_OFF	BOOLEAN,
	VENT_LAZ_FR73_SB_SPEED_LOW_HIGH	BOOLEAN,
	TECH_WAT_VALVE_COLD_AIR_FR68_Y03_OPEN_CLOSE	BOOLEAN,
	TECH_WAT_VALVE_COLD_AIR_FR32_Y04_OPEN_CLOSE	BOOLEAN,
	TECH_WAT_VALVE_COLD_AIR_FR32_Y05_OPEN_CLOSE	BOOLEAN,
)
{{ mqtt_with('KEB1_DO62') }}