{{ config(materialized='table_with_connector') }}
CREATE TABLE {{ this }} (
	TECH_CORRIDOR_ESC_HATCH_SB	BOOLEAN,
	TECH_ROOM_ESC_HATCH_PS	BOOLEAN,
	MAIN_DECKH_VENT_HATCH_SB	BOOLEAN,
	MAIN_DECKH_VENT_HATCH_PS	BOOLEAN,
	MAIN_DECKH_ACCESS_DOOR	BOOLEAN,
	AFT_DECKH_ACCESS_DOOR	BOOLEAN,
	LAZA_ACCESS_HATCH_SB_FWD	BOOLEAN,
	LAZA_ACCESS_HATCH_PS_FWD	BOOLEAN,
)
{{ mqtt_with('KEB1_DI25') }}