{{ config(materialized='table_with_connector') }}
CREATE TABLE {{ this }} (
	BILGE_LEVEL_SUB_PUMP1_ALARM	BOOLEAN,
	BILGE_LEVEL_SUB_PUMP2_ALARM	BOOLEAN,
	BILGE_LEVEL_SUB_PUMP3_ALARM	BOOLEAN,
	GEN_SERV_PUMP1_REM_AVAIL	BOOLEAN,
	GEN_SERV_PUMP2_REM_AVAIL	BOOLEAN,
	GEN_SERV_PUMP2_FIELD_START	BOOLEAN,
	GEN_SERV_PUMP2_FIELD_STOP	BOOLEAN,
	STRIP_PUMP_REM_AVAIL	BOOLEAN,
)
{{ mqtt_with('KEB1_DI20') }}