{{ config(materialized='table_with_connector') }}
CREATE TABLE {{ this }} (
	FLOW_CREW_CABIN_SB_AFT_HOT_WATER	REAL,
	FLOW_CREW_CABIN_SB_AFT_COLD_WATER	REAL,
	FLOW_CREW_CABIN_SB_MID_HOT_WATER	REAL,
	FLOW_CREW_CABIN_SB_MID_COLD_WATER	REAL,
)
{{ mqtt_with('KEB2_AI24') }}