{{ config(materialized='table_with_connector') }}
CREATE TABLE {{ this }} (
	WTID_FWD_CORRIDOR_DOOR	BOOLEAN,
	WTID_AFT_CORRIDOR_DOOR	BOOLEAN,
	WTSD_CLOSE_DOOR	BOOLEAN,
	WTSD_MAIN_BACKUP_PWR_FAIL	BOOLEAN,
	WTSD_DOOR_OPENED	BOOLEAN,
	WTSD_DOOR_CLOSED	BOOLEAN,
	WTSD_LOW_AIR_PRESS	BOOLEAN,
)
{{ mqtt_with('KEB2_DI25') }}