{{ config(materialized='table_with_connector') }}
CREATE TABLE {{ this }} (
	BILGE_FRAME47SB_ALARM	BOOLEAN,
	BILGE_FRAME54PS_ALARM	BOOLEAN,
	BILGE_FRAME54SB_ALARM	BOOLEAN,
	BILGE_FRAME38PS_ALARM	BOOLEAN,
	BILGE_FRAME38SB_ALARM	BOOLEAN,
	BCKUP_GEN_SERV_PUMP_REM_AVAIL	BOOLEAN,
	BCKUP_GEN_SERV_PUMP_FIELD_START	BOOLEAN,
	BCKUP_GEN_SERV_PUMP_FIELD_STOP	BOOLEAN,
)
{{ mqtt_with('KEB2_DI21') }}