{{ config(materialized='table_with_connector') }}
CREATE TABLE {{ this }} (
	BCKUP_GEN_SERV_PUMP_START_RUN	BOOLEAN,
	BATT_VENT_FWD_PS_ON_RUN	BOOLEAN,
	BATT_VENT_FWD_PS_ON_FAULT	BOOLEAN,
	BATT_VENT_FWD_PS_ON_READY	BOOLEAN,
	BATT_VENT_FWD_SB_ON_RUN	BOOLEAN,
	BATT_VENT_FWD_SB_ON_FAULT	BOOLEAN,
	BATT_VENT_FWD_SB_ON_READY	BOOLEAN,
	WTID_TECH_ROOM_ACCESS_DOOR	BOOLEAN,
)
{{ mqtt_with('KEB2_DI24') }}