{{ config(materialized='table_with_connector') }}
CREATE TABLE {{ this }} (
	BILGE_FRAME68_ALARM	BOOLEAN,
	BILGE_FRAME53_ALARM	BOOLEAN,
	BILGE_FRAME48_ALARM	BOOLEAN,
	BILGE_FRAME46_ALARM	BOOLEAN,
	BILGE_FRAME38_ALARM	BOOLEAN,
	BILGE_FRAME30_ALARM	BOOLEAN,
	BILGE_FRAME15_ALARM	BOOLEAN,
	BILGE_FRAME13_ALARM	BOOLEAN,
)
{{ mqtt_with('KEB2_DI20') }}