{{ config(materialized='table_with_connector') }}
CREATE TABLE {{ this }} (
	MON_SCROLL_INPUT_PS_HELMSTATION	BOOLEAN,
	MON_SCROLL_INPUT_SB_HELMSTATION	BOOLEAN,
	MON_SCROLL_INPUT_SHIPS_OFFICE	BOOLEAN,
	MON_SCROLL_INPUT_CREW_MESS	BOOLEAN,
	MON_SCROLL_INPUT_CAPTAINS_CABIN	BOOLEAN,
	DECK_CRANE_GEN_ALARM	BOOLEAN,
	MOB_TENDER_HATCH_CL_LOCK	BOOLEAN,
	GUEST_TENDER_HATCH_CL_LOCK	BOOLEAN,
)
{{ mqtt_with('KEB2_DI22') }}