{{ config(materialized='table_with_connector') }}
CREATE TABLE {{ this }} (
	SAIL_STOR_HATCH	BOOLEAN,
	FOREPEAK_ACC_HATCH	BOOLEAN,
	DINGHY_STOR_ACC_FWD	BOOLEAN,
	CRANE__HATCH_AFT	BOOLEAN,
	FORESHIP_STOR_AREA_ACC_HATCH	BOOLEAN,
	CREW_ESCAPE_HATCH	BOOLEAN,
	CREW_AREA_ACC_DOOR	BOOLEAN,
	FIRE_DETECT_FAULT	BOOLEAN,
)
{{ mqtt_with('KEB2_DI23') }}