{{ config(materialized='table_with_connector') }}
CREATE TABLE {{ this }} (
	STEER_OIL_LEVEL_TOO_LOW	BOOLEAN,
	STEER_OIL_FILTER_CLOGGED	BOOLEAN,
	STEER_24V_MONITORING	BOOLEAN,
	STEER_FREQ_DR_POWER_FAIL	BOOLEAN,
	DRAIN_VLV_Y02_POS_OVERBOARD	BOOLEAN,
	DRAIN_VLV_Y02_POS_TO_PURO	BOOLEAN,
)
{{ mqtt_with('KEB2_DI26') }}