{{ config(materialized='table_with_connector') }}
CREATE TABLE {{ this }} (
	CAPT_CAB_DISP_TOGG	BOOLEAN,
	CREW_MESS_DISP_TOGG	BOOLEAN,
	HELM_PS_IN_DISP_AMCS	BOOLEAN,
	HELM_PS_IN_DISP_ON_OFF	BOOLEAN,
	HELM_PS_IN_DISP_TOGG	BOOLEAN,
	HELM_PS_IN_MOUSE_TOGG	BOOLEAN,
	HELM_PS_OUT_DISP_ON_OFF	BOOLEAN,
	HELM_PS_OUT_DISP_TOGG	BOOLEAN,
	HELM_SB_IN_DISP_ON_OFF	BOOLEAN,
	HELM_SB_IN_DISP_TOGG	BOOLEAN,
	HELM_SB_IN_MOUSE_TOGG	BOOLEAN,
	HELM_SB_OUT_DISP_ON_OFF	BOOLEAN,
	HELM_SB_OUT_DISP_TOGG	BOOLEAN,
	MISSION_RM_DISP_TOGG	BOOLEAN,
	SHIPS_OFF_DISP_TOGG	BOOLEAN,
)
{{ mqtt_with('marpower/kvm_switching') }}
