{{ config(materialized='table_with_connector') }}
CREATE TABLE {{ this }} (
	BATT_VENT_FWD_PS_ON_RUN	BOOLEAN,
	BATT_VENT_FWD_PS_ON_FAULT	BOOLEAN,
	BATT_VENT_FWD_PS_ON_READY	BOOLEAN,
	BATT_VENT_FWD_SB_ON_RUN	BOOLEAN,
	BATT_VENT_FWD_SB_ON_FAULT	BOOLEAN,
	BATT_VENT_FWD_SB_ON_READY	BOOLEAN,
	BATT_VENT_AFT_PS_SPEED	BOOLEAN,
	BATT_VENT_FWD_SB_SPEED	BOOLEAN,
)
{{ mqtt_with('xxxx_ventilation') }}