{{ config(materialized='table_with_connector') }}
CREATE TABLE {{ this }} (
	BATT_VENT_FWD_PS_ON_RUN	BOOLEAN,
	BATT_VENT_FWD_PS_ON_FAULT	BOOLEAN,
	BATT_VENT_FWD_PS_ON_READY	BOOLEAN,
	BATT_VENT_FWD_SB_ON_RUN	BOOLEAN,
	BATT_VENT_FWD_SB_ON_FAULT	BOOLEAN,
	BATT_VENT_FWD_SB_ON_READY	BOOLEAN,
	EMERG_STOP_MTS_VENT_ACTIVE	BOOLEAN,
	EMERG_STOP_ACC_VENT_ACTIVE	BOOLEAN,
	EMERG_STOP_GAL_VENT_ACTIVE	BOOLEAN,
	BATT_VENT_AFT_PS_SPEED	REAL,
	BATT_VENT_FWD_SB_SPEED	REAL,
	EMERG_STOP_ACC_VENT_ACTIVATED	BOOLEAN,
	EMERG_STOP_GAL_VENT_ACTIVATED	BOOLEAN,
)
{{ mqtt_with('xxxx_ventilation') }}