{
 "title": "Bilge/Fifi",
 "tags": [ "commissioning" ],
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "datasource", "query": "info8fcc-greptimedb-datasource" }
  ]
 },
 "panels": [
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 0 },
   "options": {
    "content": "<center>\r\n  <h1>Bilge & Fifi</h1>\r\n</center>\r\n"
   }
  },
  { "title": "General", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 } },
  {
   "title": "Alarms",
   "type": "canvas",
   "gridPos": { "h": 9, "w": 9, "x": 0, "y": 3 },
   "targets": [
    {
     "dataset": "dev",
     "rawSql": "SELECT\r\n  timestamp,\r\n  level_sub_pump_1_alarm__value    AS sub_pump1_alarm,\r\n  level_sub_pump_2_alarm__value    AS sub_pump2_alarm,\r\n  level_sub_pump_3_alarm__value    AS sub_pump3_alarm,\r\n  batt_comp_5_alarm__value         AS batt_comp_5_alarm,\r\n  batt_comp_6_alarm__value         AS batt_comp_6_alarm,\r\n  frame_13_alarm__value            AS frame13_alarm,\r\n  frame_15_alarm__value            AS frame15_alarm,\r\n  frame_30_alarm__value            AS frame30_alarm,\r\n  frame_38_alarm__value            AS frame38_alarm,\r\n  frame_38_ps_alarm__value         AS frame38ps_alarm,\r\n  frame_38_sb_alarm__value         AS frame38sb_alarm,\r\n  frame_46_alarm__value            AS frame46_alarm,\r\n  frame_47_sb_alarm__value         AS frame47sb_alarm,\r\n  frame_48_alarm__value            AS frame48_alarm,\r\n  frame_53_alarm__value            AS frame53_alarm,\r\n  frame_68_alarm__value            AS frame68_alarm,\r\n  water_separator_ppm_alarm__value AS water_separator_ppm_alarm\r\nFROM marpower__210000_bilge_fifi_general\r\nORDER BY timestamp DESC\r\nLIMIT 1"
    },
    {
     "dataset": "dev",
     "rawSql": "SELECT\r\n  MAX(CASE WHEN mqtt_json_path = LOWER('LEVEL_SUB_PUMP_1_ALARM') THEN '(' || yard_tag || ')' ELSE NULL END) AS sub_pump1_alarm_tag,\r\n  MAX(CASE WHEN mqtt_json_path = LOWER('LEVEL_SUB_PUMP_2_ALARM') THEN '(' || yard_tag || ')' ELSE NULL END) AS sub_pump2_alarm_tag,\r\n  MAX(CASE WHEN mqtt_json_path = LOWER('LEVEL_SUB_PUMP_3_ALARM') THEN '(' || yard_tag || ')' ELSE NULL END) AS sub_pump3_alarm_tag,\r\n  MAX(CASE WHEN mqtt_json_path = LOWER('BATT_COMP_5_ALARM')      THEN '(' || yard_tag || ')' ELSE NULL END) AS batt_comp_5_alarm_tag,\r\n  MAX(CASE WHEN mqtt_json_path = LOWER('BATT_COMP_6_ALARM')      THEN '(' || yard_tag || ')' ELSE NULL END) AS batt_comp_6_alarm_tag,\r\n  MAX(CASE WHEN mqtt_json_path = LOWER('FRAME_13_ALARM')         THEN '(' || yard_tag || ')' ELSE NULL END) AS frame13_alarm_tag,\r\n  MAX(CASE WHEN mqtt_json_path = LOWER('FRAME_15_ALARM')         THEN '(' || yard_tag || ')' ELSE NULL END) AS frame15_alarm_tag,\r\n  MAX(CASE WHEN mqtt_json_path = LOWER('FRAME_30_ALARM')         THEN '(' || yard_tag || ')' ELSE NULL END) AS frame30_alarm_tag,\r\n  MAX(CASE WHEN mqtt_json_path = LOWER('FRAME_38_ALARM')         THEN '(' || yard_tag || ')' ELSE NULL END) AS frame38_alarm_tag,\r\n  MAX(CASE WHEN mqtt_json_path = LOWER('FRAME_38_PS_ALARM')      THEN '(' || yard_tag || ')' ELSE NULL END) AS frame38ps_alarm_tag,\r\n  MAX(CASE WHEN mqtt_json_path = LOWER('FRAME_38_SB_ALARM')      THEN '(' || yard_tag || ')' ELSE NULL END) AS frame38sb_alarm_tag,\r\n  MAX(CASE WHEN mqtt_json_path = LOWER('FRAME_46_ALARM')         THEN '(' || yard_tag || ')' ELSE NULL END) AS frame46_alarm_tag,\r\n  MAX(CASE WHEN mqtt_json_path = LOWER('FRAME_47_SB_ALARM')      THEN '(' || yard_tag || ')' ELSE NULL END) AS frame47sb_alarm_tag,\r\n  MAX(CASE WHEN mqtt_json_path = LOWER('FRAME_48_ALARM')         THEN '(' || yard_tag || ')' ELSE NULL END) AS frame48_alarm_tag,\r\n  MAX(CASE WHEN mqtt_json_path = LOWER('FRAME_53_ALARM')         THEN '(' || yard_tag || ')' ELSE NULL END) AS frame53_alarm_tag,\r\n  MAX(CASE WHEN mqtt_json_path = LOWER('FRAME_68_ALARM')         THEN '(' || yard_tag  || ')' ELSE NULL END) AS frame68_alarm_tag,\r\n  MAX(CASE WHEN mqtt_json_path = LOWER('BILGE_WATER_SEPARATOR_PPM_ALARM') THEN '(' || yard_tag  || ')' ELSE NULL END) AS water_separator_ppm_alarm_tag\r\nFROM marpower__io_metadata\r\nWHERE mqtt_topic = 'marpower/210000-bilge-fifi-general'\r\nLIMIT 1"
    }
   ]
  },
  {
   "title": "Status",
   "type": "canvas",
   "gridPos": { "h": 9, "w": 15, "x": 9, "y": 3 },
   "targets": [
    {
     "dataset": "dev",
     "rawSql": "select timestamp as time,\r\n\t\t\tsubmers_pump_1_remavail__value as submers_pump1_remavail,\r\n\t\t\tsubmers_pump_1_running__value as submers_pump1_running,\r\n\t\t\tsubmers_pump_2_remavail__value as submers_pump2_remavail,\r\n\t\t\tsubmers_pump_2_running__value as submers_pump2_running,\r\n\t\t\tsubmers_pump_3_remavail__value as submers_pump3_remavail,\r\n\t\t\tsubmers_pump_3_running__value as submers_pump3_running,\r\n\t\t\tbckup_gen_serv_pump_remavail__value as bckup_gen_serv_pump_remavail,\r\n\t\t\tgen_serv_pump_1_remavail__value as gen_serv_pump1_remavail,\r\n\t\t\tgen_serv_pump_2_remavail__value as gen_serv_pump2_remavail,\r\n\t\t\tgen_serv_pump_2_field_start__value as gen_serv_pump2_field_start,\r\n\t\t\tgen_serv_pump_2_field_stop__value as gen_serv_pump2_field_stop,\r\n\t\t\tstrip_pump_remavail__value as strip_pump_remavail,\r\n\t\t\tstrip_pump_running__value as strip_pump_running,\r\n\t\t\tchain_lock_pump_remavail__value as chain_lock_pump_remavail,\r\n\t\t\tchain_lock_pump_running__value as chain_lock_pump_running\r\nfrom marpower__210000_bilge_fifi_general\r\nORDER BY timestamp DESC\r\nLIMIT 1;"
    },
    {
     "dataset": "dev",
     "rawSql": "select max(ts) as ts,\r\n\t\t\tmax(case\r\n\t\t\t\t\t\t\twhen mqtt_json_path = lower('SUBMERS_PUMP1_REMAVAIL') then '(' || yard_tag || ')'\r\n\t\t\t\t\t\t\telse null\r\n\t\t\t\t\tend) as submers_pump1_remavail_tag,\r\n\t\t\tmax(case\r\n\t\t\t\t\t\t\twhen mqtt_json_path = lower('SUBMERS_PUMP1_RUNNING') then '(' || yard_tag || ')'\r\n\t\t\t\t\t\t\telse null\r\n\t\t\t\t\tend) as submers_pump1_running_tag,\r\n\t\t\tmax(case\r\n\t\t\t\t\t\t\twhen mqtt_json_path = lower('SUBMERS_PUMP2_REMAVAIL') then '(' || yard_tag || ')'\r\n\t\t\t\t\t\t\telse null\r\n\t\t\t\t\tend) as submers_pump2_remavail_tag,\r\n\t\t\tmax(case\r\n\t\t\t\t\t\t\twhen mqtt_json_path = lower('SUBMERS_PUMP2_RUNNING') then '(' || yard_tag || ')'\r\n\t\t\t\t\t\t\telse null\r\n\t\t\t\t\tend) as submers_pump2_running_tag,\r\n\t\t\tmax(case\r\n\t\t\t\t\t\t\twhen mqtt_json_path = lower('SUBMERS_PUMP3_REMAVAIL') then '(' || yard_tag || ')'\r\n\t\t\t\t\t\t\telse null\r\n\t\t\t\t\tend) as submers_pump3_remavail_tag,\r\n\t\t\tmax(case\r\n\t\t\t\t\t\t\twhen mqtt_json_path = lower('SUBMERS_PUMP3_RUNNING') then '(' || yard_tag || ')'\r\n\t\t\t\t\t\t\telse null\r\n\t\t\t\t\tend) as submers_pump3_running_tag,\r\n\t\t\tmax(case\r\n\t\t\t\t\t\t\twhen mqtt_json_path = lower('BCKUP_GEN_SERV_PUMP_REMAVAIL') then '(' || yard_tag || ')'\r\n\t\t\t\t\t\t\telse null\r\n\t\t\t\t\tend) as bckup_gen_serv_pump_remavail_tag,\r\n\t\t\tmax(case\r\n\t\t\t\t\t\t\twhen mqtt_json_path = lower('GEN_SERV_PUMP1_REMAVAIL') then '(' || yard_tag || ')'\r\n\t\t\t\t\t\t\telse null\r\n\t\t\t\t\tend) as gen_serv_pump1_remavail_tag,\r\n\t\t\tmax(case\r\n\t\t\t\t\t\t\twhen mqtt_json_path = lower('GEN_SERV_PUMP2_REMAVAIL') then '(' || yard_tag || ')'\r\n\t\t\t\t\t\t\telse null\r\n\t\t\t\t\tend) as gen_serv_pump2_remavail_tag,\r\n\t\t\tmax(case\r\n\t\t\t\t\t\t\twhen mqtt_json_path = lower('GEN_SERV_PUMP2_FIELD_START') then '(' || yard_tag || ')'\r\n\t\t\t\t\t\t\telse null\r\n\t\t\t\t\tend) as gen_serv_pump2_field_start_tag,\r\n\t\t\tmax(case\r\n\t\t\t\t\t\t\twhen mqtt_json_path = lower('GEN_SERV_PUMP2_FIELD_STOP') then '(' || yard_tag || ')'\r\n\t\t\t\t\t\t\telse null\r\n\t\t\t\t\tend) as gen_serv_pump2_field_stop_tag,\r\n\t\t\tmax(case\r\n\t\t\t\t\t\t\twhen mqtt_json_path = lower('STRIP_PUMP_REMAVAIL') then '(' || yard_tag || ')'\r\n\t\t\t\t\t\t\telse null\r\n\t\t\t\t\tend) as strip_pump_remavail_tag,\r\n\t\t\tmax(case\r\n\t\t\t\t\t\t\twhen mqtt_json_path = lower('STRIP_PUMP_RUNNING') then '(' || yard_tag || ')'\r\n\t\t\t\t\t\t\telse null\r\n\t\t\t\t\tend) as strip_pump_running_tag,\r\n\t\t\tmax(case\r\n\t\t\t\t\t\t\twhen mqtt_json_path = lower('CHAIN_LOCK_PUMP_REMAVAIL') then '(' || yard_tag || ')'\r\n\t\t\t\t\t\t\telse null\r\n\t\t\t\t\tend) as chain_lock_pump_remavail_tag,\r\n\t\t\tmax(case\r\n\t\t\t\t\t\t\twhen mqtt_json_path = lower('CHAIN_LOCK_PUMP_RUNNING') then '(' || yard_tag || ')'\r\n\t\t\t\t\t\t\telse null\r\n\t\t\t\t\tend) as chain_lock_pump_running_tag\r\nfrom marpower__io_metadata\r\nwhere mqtt_topic = 'marpower/210000-bilge-fifi-general'\r\nORDER BY ts DESC\r\nLIMIT 1;"
    }
   ]
  },
  {
   "title": "Control signals",
   "type": "canvas",
   "gridPos": { "h": 7, "w": 7, "x": 0, "y": 12 },
   "targets": [
    {
     "dataset": "dev",
     "rawSql": "select timestamp as time,\r\n\t\t\tsubmers_pump_1_startstop__value as submers_pump1_startstop,\r\n\t\t\tsubmers_pump_2_startstop__value as submers_pump2_startstop,\r\n\t\t\tsubmers_pump_3_startstop__value as submers_pump3_startstop,\r\n\t\t\tstrip_pump_startstop__value as strip_pump_startstop,\r\n\t\t\tchain_lock_pump_startstop__value as chain_lock_pump_startstop,\r\n\t\t\tseparator_start__value as separator_start,\r\n\t\t\tgen_serv_pump_1_fdbck_fault__value as gen_serv_pump1_fdbck_fault\r\nfrom marpower__210000_bilge_fifi_general\r\nORDER BY timestamp DESC\r\nLIMIT 1;"
    },
    {
     "dataset": "dev",
     "rawSql": "select max(ts) as ts,\r\n\t\t\tmax(case\r\n\t\t\t\t\t\t\twhen mqtt_json_path = lower('SUBMERS_PUMP1_STARTSTOP') then '(' || yard_tag || ')'\r\n\t\t\t\t\t\t\telse null\r\n\t\t\t\t\tend) as submers_pump1_startstop_tag,\r\n\t\t\tmax(case\r\n\t\t\t\t\t\t\twhen mqtt_json_path = lower('SUBMERS_PUMP2_STARTSTOP') then '(' || yard_tag || ')'\r\n\t\t\t\t\t\t\telse null\r\n\t\t\t\t\tend) as submers_pump2_startstop_tag,\r\n\t\t\tmax(case\r\n\t\t\t\t\t\t\twhen mqtt_json_path = lower('SUBMERS_PUMP3_STARTSTOP') then '(' || yard_tag || ')'\r\n\t\t\t\t\t\t\telse null\r\n\t\t\t\t\tend) as submers_pump3_startstop_tag,\r\n\t\t\tmax(case\r\n\t\t\t\t\t\t\twhen mqtt_json_path = lower('STRIP_PUMP_STARTSTOP') then '(' || yard_tag || ')'\r\n\t\t\t\t\t\t\telse null\r\n\t\t\t\t\tend) as strip_pump_startstop_tag,\r\n\t\t\tmax(case\r\n\t\t\t\t\t\t\twhen mqtt_json_path = lower('CHAIN_LOCK_PUMP_STARTSTOP') then '(' || yard_tag || ')'\r\n\t\t\t\t\t\t\telse null\r\n\t\t\t\t\tend) as chain_lock_pump_startstop_tag,\r\n\t\t\tmax(case\r\n\t\t\t\t\t\t\twhen mqtt_json_path = lower('SEPARATOR_START') then '(' || yard_tag || ')'\r\n\t\t\t\t\t\t\telse null\r\n\t\t\t\t\tend) as separator_start_tag,\r\n\t\t\tmax(case\r\n\t\t\t\t\t\t\twhen mqtt_json_path = lower('GEN_SERV_PUMP1_FDBCK_FAULT') then '(' || yard_tag || ')'\r\n\t\t\t\t\t\t\telse null\r\n\t\t\t\t\tend) as gen_serv_pump1_fdbck_fault_tag\r\nfrom marpower__io_metadata\r\nwhere mqtt_topic = 'marpower/210000-bilge-fifi-general'\r\nORDER BY ts DESC\r\nLIMIT 1;"
    }
   ]
  },
  {
   "title": "Sensors",
   "type": "canvas",
   "gridPos": { "h": 7, "w": 17, "x": 7, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "pressurebar" } },
   "targets": [
    {
     "dataset": "dev",
     "rawSql": "select timestamp as time,\r\n\t\t\tpress_sensor_fwd_ps_battery__value as press_sensor_fwd_ps_battery,\r\n\t\t\tpress_sensor_fwd_sb_battery__value as press_sensor_fwd_sb_battery,\r\n\t\t\tpress_sensor_aft_ps_battery__value as press_sensor_aft_ps_battery,\r\n\t\t\tpress_sensor_aft_sb_battery__value as press_sensor_aft_sb_battery,\r\n\t\t\tchain_lock_presssensor__value as chain_lock_presssensor,\r\n\t\t\tpressure_sensor_210010691__value as pressure_sensor_210010691,\r\n\t\t\tpressure_sensor_210010692__value as pressure_sensor_210010692,\r\n\t\t\tpressure_sensor_210010693__value as pressure_sensor_210010693,\r\n\t\t\ttank_level__value as tank_level,\r\n\t\t\tforepeak_tempsensor__value as forepeak_tempsensor\r\nfrom marpower__210000_bilge_fifi_general\r\nORDER BY timestamp DESC\r\nLIMIT 1;"
    },
    {
     "dataset": "dev",
     "rawSql": "select max(ts) as ts,\r\n\t\t\tmax(case\r\n\t\t\t\t\t\t\twhen mqtt_json_path = lower('PRESS_SENSOR_FWD_PS_BATTERY') then '(' || yard_tag || ')'\r\n\t\t\t\t\t\t\telse null\r\n\t\t\t\t\tend) as press_sensor_fwd_ps_battery_tag,\r\n\t\t\tmax(case\r\n\t\t\t\t\t\t\twhen mqtt_json_path = lower('PRESS_SENSOR_FWD_SB_BATTERY') then '(' || yard_tag || ')'\r\n\t\t\t\t\t\t\telse null\r\n\t\t\t\t\tend) as press_sensor_fwd_sb_battery_tag,\r\n\t\t\tmax(case\r\n\t\t\t\t\t\t\twhen mqtt_json_path = lower('PRESS_SENSOR_AFT_PS_BATTERY') then '(' || yard_tag || ')'\r\n\t\t\t\t\t\t\telse null\r\n\t\t\t\t\tend) as press_sensor_aft_ps_battery_tag,\r\n\t\t\tmax(case\r\n\t\t\t\t\t\t\twhen mqtt_json_path = lower('PRESS_SENSOR_AFT_SB_BATTERY') then '(' || yard_tag || ')'\r\n\t\t\t\t\t\t\telse null\r\n\t\t\t\t\tend) as press_sensor_aft_sb_battery_tag,\r\n\t\t\tmax(case\r\n\t\t\t\t\t\t\twhen mqtt_json_path = lower('CHAIN_LOCK_PRESSSENSOR') then '(' || yard_tag || ')'\r\n\t\t\t\t\t\t\telse null\r\n\t\t\t\t\tend) as chain_lock_presssensor_tag,\r\n\t\t\tmax(case\r\n\t\t\t\t\t\t\twhen mqtt_json_path = lower('PRESSURE_SENSOR_210010691') then '(' || yard_tag || ')'\r\n\t\t\t\t\t\t\telse null\r\n\t\t\t\t\tend) as pressure_sensor_210010691_tag,\r\n\t\t\tmax(case\r\n\t\t\t\t\t\t\twhen mqtt_json_path = lower('PRESSURE_SENSOR_210010692') then '(' || yard_tag || ')'\r\n\t\t\t\t\t\t\telse null\r\n\t\t\t\t\tend) as pressure_sensor_210010692_tag,\r\n\t\t\tmax(case\r\n\t\t\t\t\t\t\twhen mqtt_json_path = lower('PRESSURE_SENSOR_210010693') then '(' || yard_tag || ')'\r\n\t\t\t\t\t\t\telse null\r\n\t\t\t\t\tend) as pressure_sensor_210010693_tag,\r\n\t\t\tmax(case\r\n\t\t\t\t\t\t\twhen mqtt_json_path = lower('TANK_LEVEL') then '(' || yard_tag || ')'\r\n\t\t\t\t\t\t\telse null\r\n\t\t\t\t\tend) as tank_level_tag,\r\n\t\t\tmax(case\r\n\t\t\t\t\t\t\twhen mqtt_json_path = lower('FOREPEAK_TEMPSENSOR') then '(' || yard_tag || ')'\r\n\t\t\t\t\t\t\telse null\r\n\t\t\t\t\tend) as forepeak_tempsensor_tag\r\nfrom marpower__io_metadata\r\nwhere mqtt_topic = 'marpower/210000-bilge-fifi-general'\r\nORDER BY ts DESC\r\nLIMIT 1;"
    }
   ]
  },
  { "title": "Valves", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 19 } },
  {
   "type": "table",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 20 },
   "targets": [
    {
     "dataset": "dev",
     "rawSql": "SELECT DISTINCT ON (topic)\r\n  topic,\r\n  alarm__value                  AS alarm,\r\n  close__value                  AS close,\r\n  closed__value                 AS closed,\r\n  hmi_cmd_close__value          AS hmi_cmd_close,\r\n  hmi_cmd_open__value           AS hmi_cmd_open,\r\n  hmi_control_available__value  AS hmi_control_available,\r\n  open__value                   AS open,\r\n  opened__value                 AS opened,\r\n  should_be_open__value         AS should_be_open,\r\n  multi_state_alarm__value      AS multi_state_alarm,\r\n  power_detected__value         AS power_detected\r\nFROM marpower__210000_bilge_fifi\r\nWHERE $__timeFilter(timestamp)\r\nORDER BY topic, timestamp DESC"
    }
   ]
  }
 ]
}