{
 "title": "Bilge/Fifi",
 "tags": [ "commisssioning" ],
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "datasource", "query": "grafana-postgresql-datasource" }
  ]
 },
 "panels": [
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 0 },
   "options": {
    "content": "<center>\r\n  <h1>Bilge & Fifi</h1>\r\n</center>\r\n"
   }
  },
  { "title": "General", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 } },
  {
   "title": "Alarms",
   "type": "canvas",
   "gridPos": { "h": 8, "w": 9, "x": 0, "y": 3 },
   "targets": [
    {
     "dataset": "dev",
     "rawSql": "SELECT\r\n  LAST_VALUE(time ORDER BY time) AS time,\r\n  LAST_VALUE((\"LEVEL_SUB_PUMP1_ALARM\").value ORDER BY time) AS sub_pump1_alarm,\r\n  LAST_VALUE((\"LEVEL_SUB_PUMP2_ALARM\").value ORDER BY time) AS sub_pump2_alarm,\r\n  LAST_VALUE((\"LEVEL_SUB_PUMP3_ALARM\").value ORDER BY time) AS sub_pump3_alarm,\r\n  LAST_VALUE((\"BATT_COMP_5_ALARM\").value ORDER BY time) AS batt_comp_5_alarm,\r\n  LAST_VALUE((\"BATT_COMP_6_ALARM\").value ORDER BY time) AS batt_comp_6_alarm,\r\n  LAST_VALUE((\"FRAME13_ALARM\").value ORDER BY time) AS frame13_alarm,\r\n  LAST_VALUE((\"FRAME15_ALARM\").value ORDER BY time) AS frame15_alarm,\r\n  LAST_VALUE((\"FRAME30_ALARM\").value ORDER BY time) AS frame30_alarm,\r\n  LAST_VALUE((\"FRAME38_ALARM\").value ORDER BY time) AS frame38_alarm,\r\n  LAST_VALUE((\"FRAME38PS_ALARM\").value ORDER BY time) AS frame38ps_alarm,\r\n  LAST_VALUE((\"FRAME38SB_ALARM\").value ORDER BY time) AS frame38sb_alarm,\r\n  LAST_VALUE((\"FRAME46_ALARM\").value ORDER BY time) AS frame46_alarm,\r\n  LAST_VALUE((\"FRAME47SB_ALARM\").value ORDER BY time) AS frame47sb_alarm,\r\n  LAST_VALUE((\"FRAME48_ALARM\").value ORDER BY time) AS frame48_alarm,\r\n  LAST_VALUE((\"FRAME53_ALARM\").value ORDER BY time) AS frame53_alarm,\r\n  LAST_VALUE((\"FRAME68_ALARM\").value ORDER BY time) AS frame68_alarm\r\nFROM marpower.\"210000_bilge_fifi_general\""
    }
   ]
  },
  {
   "title": "Status",
   "type": "canvas",
   "gridPos": { "h": 8, "w": 15, "x": 9, "y": 3 },
   "targets": [
    {
     "dataset": "dev",
     "rawSql": "SELECT\r\n  LAST_VALUE(time ORDER BY time) AS time,\r\n  LAST_VALUE((\"SUBMERS_PUMP1_REMAVAIL\").value ORDER BY time) AS submers_pump1_remavail,\r\n  LAST_VALUE((\"SUBMERS_PUMP1_RUNNING\").value ORDER BY time) AS submers_pump1_running,\r\n  LAST_VALUE((\"SUBMERS_PUMP2_REMAVAIL\").value ORDER BY time) AS submers_pump2_remavail,\r\n  LAST_VALUE((\"SUBMERS_PUMP2_RUNNING\").value ORDER BY time) AS submers_pump2_running,\r\n  LAST_VALUE((\"SUBMERS_PUMP2_REMAVAIL\").value ORDER BY time) AS submers_pump3_remavail,\r\n  LAST_VALUE((\"SUBMERS_PUMP3_RUNNING\").value ORDER BY time) AS submers_pump3_running,\r\n  LAST_VALUE((\"BCKUP_GEN_SERV_PUMP_REMAVAIL\").value ORDER BY time) AS bckup_gen_serv_pump_remavail,\r\n  LAST_VALUE((\"GEN_SERV_PUMP1_REMAVAIL\").value ORDER BY time) AS gen_serv_pump1_remavail,\r\n  LAST_VALUE((\"GEN_SERV_PUMP2_REMAVAIL\").value ORDER BY time) AS gen_serv_pump2_remavail,\r\n  LAST_VALUE((\"GEN_SERV_PUMP2_FIELD_START\").value ORDER BY time) AS gen_serv_pump2_field_start,\r\n  LAST_VALUE((\"GEN_SERV_PUMP2_FIELD_STOP\").value ORDER BY time) AS gen_serv_pump2_field_stop,\r\n  LAST_VALUE((\"STRIP_PUMP_REMAVAIL\").value ORDER BY time) AS strip_pump_remavail,\r\n  LAST_VALUE((\"STRIP_PUMP_RUNNING\").value ORDER BY time) AS strip_pump_running,\r\n  LAST_VALUE((\"CHAIN_LOCK_PUMP_REMAVAIL\").value ORDER BY time) AS chain_lock_pump_remavail,\r\n  LAST_VALUE((\"CHAIN_LOCK_PUMP_RUNNING\").value ORDER BY time) AS chain_lock_pump_running\r\nFROM marpower.\"210000_bilge_fifi_general\""
    }
   ]
  },
  {
   "title": "Control signals",
   "type": "canvas",
   "gridPos": { "h": 7, "w": 7, "x": 0, "y": 11 },
   "targets": [
    {
     "dataset": "dev",
     "rawSql": "SELECT\r\n  LAST_VALUE(time ORDER BY time) AS time,\r\n  LAST_VALUE((\"SUBMERS_PUMP1_STARTSTOP\").value ORDER BY time) AS submers_pump1_startstop,\r\n  LAST_VALUE((\"SUBMERS_PUMP2_STARTSTOP\").value ORDER BY time) AS submers_pump2_startstop,\r\n  LAST_VALUE((\"SUBMERS_PUMP3_STARTSTOP\").value ORDER BY time) AS submers_pump3_startstop,\r\n  LAST_VALUE((\"STRIP_PUMP_STARTSTOP\").value ORDER BY time) AS strip_pump_startstop,\r\n  LAST_VALUE((\"CHAIN_LOCK_PUMP_STARTSTOP\").value ORDER BY time) AS chain_lock_pump_startstop,\r\n  LAST_VALUE((\"SEPARATOR_START\").value ORDER BY time) AS separator_start,\r\n  LAST_VALUE((\"GEN_SERV_PUMP1_FDBCK_FAULT\").value ORDER BY time) AS gen_serv_pump1_fdbck_fault\r\nFROM marpower.\"210000_bilge_fifi_general\""
    }
   ]
  },
  {
   "title": "Sensors",
   "type": "canvas",
   "gridPos": { "h": 7, "w": 17, "x": 7, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "pressurebar" } },
   "targets": [
    {
     "dataset": "dev",
     "rawSql": "SELECT\r\n  LAST_VALUE(time ORDER BY time) AS time,\r\n  LAST_VALUE((\"PRESS_SENSOR_FWD_PS_BATTERY\").value ORDER BY time) AS press_sensor_fwd_ps_battery,\r\n  LAST_VALUE((\"PRESS_SENSOR_FWD_SB_BATTERY\").value ORDER BY time) AS press_sensor_fwd_sb_battery,\r\n  LAST_VALUE((\"PRESS_SENSOR_AFT_PS_BATTERY\").value ORDER BY time) AS press_sensor_aft_ps_battery,\r\n  LAST_VALUE((\"PRESS_SENSOR_AFT_SB_BATTERY\").value ORDER BY time) AS press_sensor_aft_sb_battery,\r\n  LAST_VALUE((\"CHAIN_LOCK_PRESSSENSOR\").value ORDER BY time) AS chain_lock_presssensor,\r\n  LAST_VALUE((\"PRESSURE_SENSOR_210010691\").value ORDER BY time) AS pressure_sensor_210010691,\r\n  LAST_VALUE((\"PRESSURE_SENSOR_210010692\").value ORDER BY time) AS pressure_sensor_210010692,\r\n  LAST_VALUE((\"PRESSURE_SENSOR_210010693\").value ORDER BY time) AS pressure_sensor_210010693,\r\n  LAST_VALUE((\"TANK_LEVEL\").value ORDER BY time) AS tank_level,\r\n  LAST_VALUE((\"FOREPEAK_TEMPSENSOR\").value ORDER BY time) AS forepeak_tempsensor\r\nFROM marpower.\"210000_bilge_fifi_general\""
    }
   ]
  },
  { "title": "Valves", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 18 } },
  {
   "type": "table",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 19 },
   "targets": [
    {
     "dataset": "dev",
     "rawSql": "SELECT\r\n  topic,\r\n  ARG_MAX((\"Opened\").Value, (\"Opened\").Timestamp)                           AS Opened,\r\n  ARG_MAX((\"Closed\").Value, (\"Closed\").Timestamp)                           AS Closed,\r\n  ARG_MAX((\"HmiCmdOpen\").Value, (\"HmiCmdOpen\").Timestamp)                   AS HmiCmdOpen,\r\n  ARG_MAX((\"HmiCmdClose\").Value, (\"HmiCmdClose\").Timestamp)                 AS HmiCmdClose,\r\n  ARG_MAX((\"ShouldBeOpen\").Value, (\"ShouldBeOpen\").Timestamp)               AS ShouldBeOpen,\r\n  ARG_MAX((\"HmiControlAvailable\").Value, (\"HmiControlAvailable\").Timestamp) AS HmiControlAvailable,\r\n  ARG_MAX((\"Open\").Value, (\"Open\").Timestamp)                               AS Open,\r\n  ARG_MAX((\"Close\").Value, (\"Close\").Timestamp)                             AS Close,\r\n  ARG_MAX((\"Alarm\").Value, (\"Alarm\").Timestamp)                             AS Alarm\r\nFROM marpower.\"210000_bilge_fifi\"\r\nGROUP BY topic\r\nORDER BY topic"
    }
   ]
  }
 ]
}