{
 "title": "Doors & Hatches",
 "tags": [ "commissioning" ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "datasource", "query": "info8fcc-greptimedb-datasource" }
  ]
 },
 "panels": [
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 0 },
   "options": {
    "content": "<center>\r\n  <h1>Doors & Hatches</h1>\r\n</center>\r\n"
   }
  },
  {
   "title": "Alarms",
   "type": "canvas",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 2 },
   "targets": [
    {
     "dataset": "dev",
     "rawSql": "SELECT\r\n  timestamp                              AS time,\r\n\tdeck_slide_wind_drive_fail__value      AS deck_slide_wind_drive_fail,\r\n\tw_tight_hatch_rm_35_commonalarm__value AS wt_hatch_rm35_alarm,\r\n\tw_tight_hatch_rm_36_commonalarm__value AS wt_hatch_rm36_alarm,\r\n\twtsd_mainbackuppwrfail__value          AS wtsd_pwr_fail,\r\n\tsos_lock_supply_14_e_11_fail__value    AS sos_lock_supply_fail1,\r\n\tsos_lock_supply_14_e_12_fail__value    AS sos_lock_supply_fail2,\r\n\tsos_lock_supply_14_e_13_fail__value    AS sos_lock_supply_fail3,\r\n\thaz_consumers_emergstopactive__value   AS em_stop_haz_cons_active\r\nFROM marpower__090000_doors_hatches\r\nWHERE $__timeFilter(timestamp)\r\nORDER BY timestamp DESC\r\nLIMIT 1"
    }
   ]
  },
  {
   "title": "Control signals",
   "type": "canvas",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 2 },
   "targets": [
    {
     "dataset": "dev",
     "rawSql": "SELECT\r\n  timestamp                          AS time,\r\n\tdeck_slide_wind_onoff__value       AS deck_slide_wind_on,\r\n\taft_slide_wind_onoff__value        AS aft_slide_wind_on,\r\n\tps_slide_wind_onoff__value         AS ps_slide_wind_on,\r\n\tsb_slide_wind_onoff__value         AS sb_slide_wind_on,\r\n\thull_valves_allgreenclosed__value  AS hull_valves_all_closed,\r\n\thull_valves_redopened__value       AS hull_valves_not_all_closed,\r\n\twtd_pneumatic_support_onoff__value AS wtd_pneumatic_support_onoff\r\nFROM marpower__090000_doors_hatches\r\nWHERE $__timeFilter(timestamp)\r\nORDER BY timestamp DESC\r\nLIMIT 1"
    }
   ]
  },
  {
   "title": "Crew areas",
   "type": "canvas",
   "gridPos": { "h": 7, "w": 16, "x": 0, "y": 10 },
   "targets": [
    {
     "dataset": "dev",
     "rawSql": "SELECT\r\n  timestamp                                        AS time,\r\n\tw_tight_door_rm_19_sealinflated__value           AS rm19_wtd_seal_infl,\r\n\tw_tight_door_rm_19_horizontal_door_closed__value AS rm19_wtd_hor_closed,\r\n\tw_tight_door_rm_19_vertical_door_closed__value   AS rm19_wtd_ver_closed,\r\n\tw_tight_hatch_rm_35_sealinflated__value          AS rm35_wth_seal_infl,\r\n\tw_tight_hatch_rm_35_doorclosed__value            AS rm35_wth_closed,\r\n\tw_tight_hatch_rm_35_posprogswitch__value         AS rm35_wth_pos_prog_switch,\r\n\tw_tight_hatch_rm_36_sealinflated__value          AS rm36_wth_seal_infl,\r\n\tw_tight_hatch_rm_36_doorclosed__value            AS rm36_wth_closed,\r\n\tw_tight_hatch_rm_36_posprogswitch__value         AS rm36_wth_pos_prog_switch,\r\n\tfire_door_galley_keel_closed__value              AS fire_door_galley_keel_closed,\r\n\tfire_slide_door_gall_crew_closed__value          AS fire_door_galley_closed,\r\n\tcrew_escape_hatch_closed__value                  AS crew_esc_hatch_closed\r\nFROM public.marpower__090000_doors_hatches\r\nWHERE $__timeFilter(timestamp)\r\nORDER BY timestamp DESC\r\nLIMIT 1"
    }
   ]
  },
  {
   "title": "Deckhouses",
   "type": "canvas",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 10 },
   "targets": [
    {
     "dataset": "dev",
     "rawSql": "SELECT timestamp AS time,\r\n\t\t\tmain_deckh_vent_hatch_ps_closed__value AS main_deckh_hatch_ps_closed,\r\n\t\t\tmain_deckh_vent_hatch_sb_closed__value AS main_deckh_hatch_sb_closed,\r\n\t\t\taft_deckh_vent_hatch_closed__value AS aft_deckh_hatch_closed,\r\n\t\t\tdeck_slide_wind_remavail__value AS owner_deckh_wind_remavail,\r\n\t\t\tdeck_slide_wind_drive_runn__value AS owner_deckh_wind_running\r\nFROM marpower__090000_doors_hatches\r\nWHERE $__timeFilter(timestamp)\r\nORDER BY timestamp DESC\r\nLIMIT 1"
    }
   ]
  },
  {
   "title": "Deck",
   "type": "canvas",
   "gridPos": { "h": 10, "w": 16, "x": 0, "y": 17 },
   "targets": [
    {
     "dataset": "dev",
     "rawSql": "SELECT\r\n\ttimestamp AS time,\r\n\tlaza_access_hatch_sb_fwd_closed__value     AS laz_hatch_fwd_sb_closed,\r\n\tlaza_access_hatch_ps_fwd_closed__value     AS laz_hatch_fwd_ps_closed,\r\n\tlaza_access_hatch_sb_mid_closed__value     AS laz_hatch_mid_sb_closed,\r\n\tlaza_access_hatch_ps_mid_closed__value     AS laz_hatch_mid_ps_closed,\r\n\tlaza_access_hatch_sb_aft_closed__value     AS laz_hatch_aft_sb_closed,\r\n\tlaza_access_hatch_ps_aft_closed__value     AS laz_hatch_aft_ps_closed,\r\n\tforeship_stor_area_acc_hatch_closed__value AS foreship_stor_hatch_closed,\r\n\tcrane_hatch_aft_closed__value              AS crane_hatch_closed,\r\n\tforepeak_acc_hatch_closed__value           AS forepeak_hatch_closed,\r\n\tsail_stor_hatch_closed__value              AS sail_stor_hatch_closed,\r\n\tplatfrom_closed_locked__value              AS crew_platform_closed,\r\n\tdinghy_stor_acc_fwd_closed__value          AS dinghy_stor_closed,\r\n\thatch_chainlocker_sensor_1_closed__value   AS chainlocker_hatch_ps_closed,\r\n\thatch_chainlocker_sensor_2_closed__value   AS chainlocker_hatch_sb_closed,\r\n\tall_hull_valves_close__value               AS close_all_hull_valves,\r\n\twtsd_doorclose__value                      AS wtsd_close,\r\n\twtsd_dooropened__value                     AS wtsd_opened,\r\n\twtsd_doorclosed__value                     AS wtsd_closed,\r\n\twtsd_lowairpress__value                    AS wtsd_low_air_pressure\r\nFROM marpower__090000_doors_hatches\r\nWHERE $__timeFilter(timestamp)\r\nORDER BY timestamp DESC\r\nLIMIT 1"
    },
    {
     "dataset": "dev",
     "rawSql": "SELECT\r\n  MAX(CASE WHEN mqtt_json_path = 'hatch_chainlocker_sensor1_closed' THEN '(' || yard_tag || ')' ELSE NULL END) AS chainlocker_hatch_ps_closed_tag,\r\n  MAX(CASE WHEN mqtt_json_path = 'hatch_chainlocker_sensor2_closed' THEN '(' || yard_tag || ')' ELSE NULL END) AS chainlocker_hatch_sb_closed_tag\r\nFROM public.marpower__io_metadata\r\nWHERE mqtt_topic = 'marpower/090000-doors-hatches'"
    }
   ]
  },
  {
   "title": "Technical areas",
   "type": "canvas",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 17 },
   "targets": [
    {
     "dataset": "dev",
     "rawSql": "SELECT\r\n  timestamp                                AS time,\r\n\twtid_tech_room_access_door_closed__value AS tech_room_door_closed,\r\n\ttech_room_esc_hatch_ps_closed__value     AS tech_room_esc_hatch_closed,\r\n\ttech_corridor_esc_hatch_sb_closed__value AS tech_corr_esc_hatch_closed,\r\n\twtid_fwd_corridor_door_closed__value     AS fwd_corr_door_closed,\r\n\twtid_aft_corridor_door_closed__value     AS aft_corr_door_closed\r\nFROM marpower__090000_doors_hatches\r\nWHERE $__timeFilter(timestamp)\r\nORDER BY timestamp DESC\r\nLIMIT 1"
    }
   ]
  }
 ]
}