{
 "title": "Doors & Hatches",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "datasource", "query": "grafana-postgresql-datasource" }
  ]
 },
 "panels": [
  {
   "title": "Alarms",
   "type": "canvas",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 0 },
   "targets": [
    {
     "dataset": "dev",
     "rawSql": "SELECT\r\n  LAST_VALUE(time ORDER BY time) AS time,\r\n  LAST_VALUE((\"DECK_SLIDE_WIND_DRIVE_FAIL\").value ORDER BY time)     AS deck_slide_wind_drive_fail,\r\n  LAST_VALUE((\"W_TIGHT_HATCH_RM35_COMMONALARM\").value ORDER BY time) AS wt_hatch_rm35_alarm,\r\n  LAST_VALUE((\"W_TIGHT_HATCH_RM36_COMMONALARM\").value ORDER BY time) AS wt_hatch_rm36_alarm,\r\n  LAST_VALUE((\"WTSD_MAINBACKUPPWRFAIL\").value ORDER BY time)         AS wtsd_pwr_fail,\r\n  LAST_VALUE((\"SOS_LOCK_SUPPLY14E11FAIL\").value ORDER BY time)       AS sos_lock_supply_fail1,\r\n  LAST_VALUE((\"SOS_LOCK_SUPPLY14E12FAIL\").value ORDER BY time)       AS sos_lock_supply_fail2,\r\n  LAST_VALUE((\"SOS_LOCK_SUPPLY14E13FAIL\").value ORDER BY time)       AS sos_lock_supply_fail3,\r\n  LAST_VALUE((\"HAZ_CONSUMERS_EMERGSTOPACTIVE\").value ORDER BY time)  AS em_stop_haz_cons_active\r\nFROM marpower.\"090000_doors_hatches\""
    }
   ]
  },
  {
   "title": "Control signals",
   "type": "canvas",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 0 },
   "targets": [
    {
     "dataset": "dev",
     "rawSql": "SELECT\r\n  LAST_VALUE(time ORDER BY time) AS time,\r\n  LAST_VALUE((\"DECK_SLIDE_WIND_ONOFF\").value ORDER BY time)      AS deck_slide_wind_on,\r\n  LAST_VALUE((\"AFT_SLIDE_WIND_ONOFF\").value ORDER BY time)       AS aft_slide_wind_on,\r\n  LAST_VALUE((\"PS_SLIDE_WIND_ONOFF\").value ORDER BY time)        AS ps_slide_wind_on,\r\n  LAST_VALUE((\"SB_SLIDE_WIND_ONOFF\").value ORDER BY time)        AS sb_slide_wind_on,\r\n  LAST_VALUE((\"HULL_VALVES_ALLGREENCLOSED\").value ORDER BY time) AS hull_valves_all_closed,\r\n  LAST_VALUE((\"HULL_VALVES_REDOPENED\").value ORDER BY time)      AS hull_valves_not_all_closed\r\nFROM marpower.\"090000_doors_hatches\""
    }
   ]
  },
  {
   "title": "Sensors",
   "type": "canvas",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "dataset": "dev",
     "rawSql": "SELECT\r\n  LAST_VALUE(time ORDER BY time) AS time,\r\n  LAST_VALUE((\"MAIN_DECKH_VENT_HATCH_PS_PERC\").value ORDER BY time) AS main_deckh_hatch_ps_perc,\r\n  LAST_VALUE((\"MAIN_DECKH_VENT_HATCH_SB_PERC\").value ORDER BY time) AS main_deckh_hatch_sb_perc,\r\n  LAST_VALUE((\"AFT_DECKH_VENT_HATCH_PERC\").value ORDER BY time)     AS aft_deckh_hatch_perc\r\nFROM marpower.\"090000_doors_hatches\""
    }
   ]
  },
  {
   "title": "Crew areas",
   "type": "canvas",
   "gridPos": { "h": 7, "w": 16, "x": 0, "y": 8 },
   "targets": [
    {
     "dataset": "dev",
     "rawSql": "SELECT\r\n  LAST_VALUE(time ORDER BY time) AS time,\r\n  LAST_VALUE((\"W_TIGHT_DOOR_RM19_SEALINFLATED\").value ORDER BY time)    AS rm19_wtd_seal_infl,\r\n  LAST_VALUE((\"W_TIGHT_DOOR_RM19_DOOR_OPEN\").value ORDER BY time)       AS rm19_wtd_open,\r\n  LAST_VALUE((\"W_TIGHT_DOOR_RM19_POS_PROG_SWITCH\").value ORDER BY time) AS rm19_wtd_pos_prog_switch,\r\n  LAST_VALUE((\"W_TIGHT_HATCH_RM35_SEALINFLATED\").value ORDER BY time)   AS rm35_wth_seal_infl,\r\n  LAST_VALUE((\"W_TIGHT_HATCH_RM35_DOOROPEN\").value ORDER BY time)       AS rm35_wth_open,\r\n  LAST_VALUE((\"W_TIGHT_HATCH_RM35_POSPROGSWITCH\").value ORDER BY time)  AS rm35_wth_pos_prog_switch,\r\n  LAST_VALUE((\"W_TIGHT_HATCH_RM36_SEALINFLATED\").value ORDER BY time)   AS rm36_wth_seal_infl,\r\n  LAST_VALUE((\"W_TIGHT_HATCH_RM36_DOOROPEN\").value ORDER BY time)       AS rm36_wth_open,\r\n  LAST_VALUE((\"W_TIGHT_HATCH_RM36_POSPROGSWITCH\").value ORDER BY time)  AS rm36_wth_pos_prog_switch,\r\n  LAST_VALUE((\"FIRE_SLIDE_DOOR_GALL_CREW_OPEN\").value ORDER BY time)    AS fire_door_galley_open,\r\n  LAST_VALUE((\"CREW_ESCAPE_HATCH_OPEN\").value ORDER BY time)            AS crew_esc_hatch_open\r\nFROM marpower.\"090000_doors_hatches\""
    }
   ]
  },
  {
   "title": "Deckhouses",
   "type": "canvas",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 8 },
   "targets": [
    {
     "dataset": "dev",
     "rawSql": "SELECT\r\n  LAST_VALUE(time ORDER BY time) AS time,\r\n  LAST_VALUE((\"MAIN_DECKH_VENT_HATCH_PS_OPENED\").value ORDER BY time) AS main_deckh_hatch_ps_open,\r\n  LAST_VALUE((\"MAIN_DECKH_VENT_HATCH_SB_OPENED\").value ORDER BY time) AS main_deckh_hatch_sb_open,\r\n  LAST_VALUE((\"AFT_DECKH_VENT_HATCH_OPEN\").value ORDER BY time)       AS aft_deckh_hatch_open,\r\n  LAST_VALUE((\"DECK_SLIDE_WIND_REMAVAIL\").value ORDER BY time)        AS owner_deckh_wind_remavail,\r\n  LAST_VALUE((\"DECK_SLIDE_WIND_DRIVE_RUNN\").value ORDER BY time)      AS owner_deckh_wind_running\r\nFROM marpower.\"090000_doors_hatches\""
    }
   ]
  },
  {
   "title": "Deck",
   "type": "canvas",
   "gridPos": { "h": 10, "w": 16, "x": 0, "y": 15 },
   "targets": [
    {
     "dataset": "dev",
     "rawSql": "SELECT\r\n  LAST_VALUE(time ORDER BY time) AS time,\r\n  LAST_VALUE((\"LAZA_ACCESS_HATCH_SB_FWD_OPEN\").value ORDER BY time)     AS laz_hatch_fwd_sb_open,\r\n  LAST_VALUE((\"LAZA_ACCESS_HATCH_PS_FWD_OPEN\").value ORDER BY time)     AS laz_hatch_fwd_ps_open,\r\n  LAST_VALUE((\"LAZA_ACCESS_HATCH_SB_MID_OPEN\").value ORDER BY time)     AS laz_hatch_mid_sb_open,\r\n  LAST_VALUE((\"LAZA_ACCESS_HATCH_PS_MID_OPEN\").value ORDER BY time)     AS laz_hatch_mid_ps_open,\r\n  LAST_VALUE((\"LAZA_ACCESS_HATCH_SB_AFT_OPEN\").value ORDER BY time)     AS laz_hatch_aft_sb_open,\r\n  LAST_VALUE((\"LAZA_ACCESS_HATCH_PS_AFT_OPEN\").value ORDER BY time)     AS laz_hatch_aft_ps_open,\r\n  LAST_VALUE((\"FORESHIP_STOR_AREA_ACC_HATCH_OPEN\").value ORDER BY time) AS foreship_stor_hatch_open,\r\n  LAST_VALUE((\"CRANE_HATCH_AFT_OPEN\").value ORDER BY time)              AS crane_hatch_open,\r\n  LAST_VALUE((\"FOREPEAK_ACC_HATCH_OPEN\").value ORDER BY time)           AS forepeak_hatch_open,\r\n  LAST_VALUE((\"SAIL_STOR_HATCH_OPEN\").value ORDER BY time)              AS sail_stor_hatch_open,\r\n  LAST_VALUE((\"PLATFROM_CLOSED_LOCKED\").value ORDER BY time)            AS crew_platform_closed,\r\n  LAST_VALUE((\"DINGHY_STOR_ACC_FWD_OPEN\").value ORDER BY time)          AS dinghy_stor_open,\r\n  LAST_VALUE((\"HATCH_ANCHOR_SENSOR1_OPEN\").value ORDER BY time)         AS anchor_hatch1_open,\r\n  LAST_VALUE((\"HATCH_ANCHOR_SENSOR2_OPEN\").value ORDER BY time)         AS anchor_hatch2_open,\r\n  LAST_VALUE((\"ALL_HULL_VALVES_CLOSE\").value ORDER BY time)             AS close_all_hull_valves,\r\n  LAST_VALUE((\"WTSD_DOORCLOSE\").value ORDER BY time)                    AS wtsd_close,\r\n  LAST_VALUE((\"WTSD_DOOROPENED\").value ORDER BY time)                   AS wtsd_opened,\r\n  LAST_VALUE((\"WTSD_DOORCLOSED\").value ORDER BY time)                   AS wtsd_closed,\r\n  LAST_VALUE((\"WTSD_LOWAIRPRESS\").value ORDER BY time)                  AS wtsd_low_air_pressure\r\nFROM marpower.\"090000_doors_hatches\""
    }
   ]
  },
  {
   "title": "Technical areas",
   "type": "canvas",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 15 },
   "targets": [
    {
     "dataset": "dev",
     "rawSql": "SELECT\r\n  LAST_VALUE(time ORDER BY time) AS time,\r\n  LAST_VALUE((\"WTID_TECH_ROOM_ACCESS_DOOR\").value ORDER BY time)      AS tech_room_door,\r\n  LAST_VALUE((\"TECH_ROOM_ESC_HATCH_PS_OPEN\").value ORDER BY time)     AS tech_room_esc_hatch_open,\r\n  LAST_VALUE((\"TECH_CORRIDOR_ESC_HATCH_SB_OPEN\").value ORDER BY time) AS tech_corr_esc_hatch_open,\r\n  LAST_VALUE((\"WTID_FWD_CORRIDOR_DOOR_OPEN\").value ORDER BY time)     AS fwd_corr_door_open,\r\n  LAST_VALUE((\"WTID_AFT_CORRIDOR_DOOR_OPEN\").value ORDER BY time)     AS aft_corr_door_open\r\nFROM marpower.\"090000_doors_hatches\""
    }
   ]
  }
 ]
}