{
 "title": "Firedetection",
 "tags": [ "commisssioning" ],
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "datasource", "query": "grafana-postgresql-datasource" }
  ]
 },
 "panels": [
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 0 },
   "options": {
    "content": "<center>\r\n  <h1>Fire detection</h1>\r\n</center>\r\n"
   }
  },
  { "title": "General", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 } },
  {
   "title": "Alarms",
   "type": "canvas",
   "gridPos": { "h": 4, "w": 14, "x": 0, "y": 3 },
   "targets": [
    {
     "dataset": "dev",
     "rawSql": "SELECT\r\n  LAST_VALUE(time ORDER BY time) AS time,\r\n  LAST_VALUE((\"DETECT_FAULT\").value ORDER BY time)                         AS detect_fault,\r\n  LAST_VALUE((\"DOOR_POWERSUPPLYFAIL\").value ORDER BY time)                 AS door_power_supply_fail,\r\n  LAST_VALUE((\"AUXILIARY_SYSTEM_SERVICESUPPLYFAIL\").value ORDER BY time)   AS aux_sys_service_supply_fail,\r\n  LAST_VALUE((\"AUXILIARY_SYSTEM_EMERGENCYSUPPLYFAIL\").value ORDER BY time) AS aux_sys_emergency_supply_fail\r\nFROM marpower.\"450000_firedetection_general\""
    }
   ]
  },
  {
   "title": "Status",
   "type": "canvas",
   "gridPos": { "h": 4, "w": 10, "x": 14, "y": 3 },
   "targets": [
    {
     "dataset": "dev",
     "rawSql": "SELECT\r\n  LAST_VALUE(time ORDER BY time) AS time,\r\n  LAST_VALUE((\"DOORS_RELEASE\").value ORDER BY time)         AS doors_release\r\nFROM marpower.\"450000_firedetection_general\""
    }
   ]
  },
  {
   "title": "Historical",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 },
   "collapsed": true,
   "panels": [
    {
     "title": "Alarm, status & control signal history",
     "type": "status-history",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 8 },
     "targets": [
      {
       "dataset": "dev",
       "rawSql": "SELECT\r\n  time,\r\n\r\n  -- Alarm\r\n  (\"DETECT_FAULT\").value                         AS detect_fault,\r\n  (\"DOOR_POWERSUPPLYFAIL\").value                 AS door_power_supply_fail,\r\n  (\"AUXILIARY_SYSTEM_SERVICESUPPLYFAIL\").value   AS aux_sys_service_supply_fail,\r\n  (\"AUXILIARY_SYSTEM_EMERGENCYSUPPLYFAIL\").value AS aux_sys_emergency_supply_fail,\r\n\r\n  -- Status\r\n  (\"DOORS_RELEASE\").value                        AS doors_release,\r\n  (\"DOOR_GALLEY_KEEL_OPEN\").value                AS door_galley_keel_open\r\nFROM marpower.\"450000_firedetection_general\"\r\nWHERE $__timeFilter(time)"
      }
     ]
    }
   ]
  },
  { "title": "Accommodations", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 } },
  {
   "title": "Cabins",
   "type": "table",
   "gridPos": { "h": 22, "w": 12, "x": 0, "y": 9 },
   "targets": [
    {
     "dataset": "dev",
     "rawSql": "SELECT\r\n  meta.\"description\",\r\n  ARG_MAX((fire.\"disabled\").Value, (fire.\"disabled\").Timestamp) AS disabled,\r\n  ARG_MAX((fire.\"fault\").Value, (fire.\"fault\").Timestamp)       AS fault,\r\n  ARG_MAX((fire.\"prealarm\").Value, (fire.\"prealarm\").Timestamp) AS prealarm,\r\n  ARG_MAX((fire.\"alarm\").Value, (fire.\"alarm\").Timestamp)       AS alarm,\r\n  ARG_MAX((fire.\"test\").Value, (fire.\"test\").Timestamp)         AS test\r\nFROM marpower.\"450000_firedetection\" AS fire\r\nJOIN marpower.firedetection_metadata AS meta ON fire.topic = meta.topic\r\nWHERE meta.section = 'Accommodation'\r\n  AND meta.room_or_area LIKE '%Cabin%'\r\nGROUP BY meta.\"description\"\r\nORDER BY meta.\"description\""
    }
   ]
  },
  {
   "title": "Corridors",
   "type": "table",
   "gridPos": { "h": 21, "w": 12, "x": 12, "y": 9 },
   "targets": [
    {
     "dataset": "dev",
     "rawSql": "SELECT\r\n  meta.\"description\",\r\n  ARG_MAX((fire.\"disabled\").Value, (fire.\"disabled\").Timestamp) AS disabled,\r\n  ARG_MAX((fire.\"fault\").Value, (fire.\"fault\").Timestamp)       AS fault,\r\n  ARG_MAX((fire.\"prealarm\").Value, (fire.\"prealarm\").Timestamp) AS prealarm,\r\n  ARG_MAX((fire.\"alarm\").Value, (fire.\"alarm\").Timestamp)       AS alarm,\r\n  ARG_MAX((fire.\"test\").Value, (fire.\"test\").Timestamp)         AS test\r\nFROM marpower.\"450000_firedetection\" AS fire\r\nJOIN marpower.firedetection_metadata AS meta ON fire.topic = meta.topic\r\nWHERE meta.section = 'Accommodation'\r\n  AND meta.room_or_area LIKE '%Corridor%'\r\nGROUP BY meta.\"description\"\r\nORDER BY meta.\"description\""
    }
   ]
  },
  {
   "title": "Owner",
   "type": "table",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 30 },
   "targets": [
    {
     "dataset": "dev",
     "rawSql": "SELECT\r\n  meta.\"description\",\r\n  ARG_MAX((fire.\"disabled\").Value, (fire.\"disabled\").Timestamp) AS disabled,\r\n  ARG_MAX((fire.\"fault\").Value, (fire.\"fault\").Timestamp)       AS fault,\r\n  ARG_MAX((fire.\"prealarm\").Value, (fire.\"prealarm\").Timestamp) AS prealarm,\r\n  ARG_MAX((fire.\"alarm\").Value, (fire.\"alarm\").Timestamp)       AS alarm,\r\n  ARG_MAX((fire.\"test\").Value, (fire.\"test\").Timestamp)         AS test\r\nFROM marpower.\"450000_firedetection\" AS fire\r\nJOIN marpower.firedetection_metadata AS meta ON fire.topic = meta.topic\r\nWHERE meta.section = 'Accommodation'\r\n  AND meta.room_or_area LIKE '%Owner%'\r\n  AND meta.room_or_area NOT LIKE '%Cabin%'\r\n  AND meta.room_or_area NOT LIKE '%Corridor%'\r\nGROUP BY meta.\"description\"\r\nORDER BY meta.\"description\""
    }
   ]
  },
  {
   "title": "Lounges",
   "type": "table",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 31 },
   "targets": [
    {
     "dataset": "dev",
     "rawSql": "SELECT\r\n  meta.\"description\",\r\n  ARG_MAX((fire.\"disabled\").Value, (fire.\"disabled\").Timestamp) AS disabled,\r\n  ARG_MAX((fire.\"fault\").Value, (fire.\"fault\").Timestamp)       AS fault,\r\n  ARG_MAX((fire.\"prealarm\").Value, (fire.\"prealarm\").Timestamp) AS prealarm,\r\n  ARG_MAX((fire.\"alarm\").Value, (fire.\"alarm\").Timestamp)       AS alarm,\r\n  ARG_MAX((fire.\"test\").Value, (fire.\"test\").Timestamp)         AS test\r\nFROM marpower.\"450000_firedetection\" AS fire\r\nJOIN marpower.firedetection_metadata AS meta ON fire.topic = meta.topic\r\nWHERE meta.section = 'Accommodation'\r\n  AND (meta.room_or_area LIKE '%Lounge%' OR meta.room_or_area LIKE '%Salon%')\r\n  AND meta.room_or_area NOT LIKE '%Cabin%'\r\n  AND meta.room_or_area NOT LIKE '%Corridor%'\r\n  AND meta.room_or_area NOT LIKE '%Crew%'\r\n  AND meta.room_or_area NOT LIKE '%Owner%'\r\nGROUP BY meta.\"description\"\r\nORDER BY meta.\"description\""
    }
   ]
  },
  { "title": "Crew service", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 40 } },
  {
   "title": "Rooms & storage",
   "type": "table",
   "gridPos": { "h": 16, "w": 12, "x": 0, "y": 41 },
   "targets": [
    {
     "dataset": "dev",
     "rawSql": "SELECT\r\n  meta.\"description\",\r\n  ARG_MAX((fire.\"disabled\").Value, (fire.\"disabled\").Timestamp) AS disabled,\r\n  ARG_MAX((fire.\"fault\").Value, (fire.\"fault\").Timestamp)       AS fault,\r\n  ARG_MAX((fire.\"prealarm\").Value, (fire.\"prealarm\").Timestamp) AS prealarm,\r\n  ARG_MAX((fire.\"alarm\").Value, (fire.\"alarm\").Timestamp)       AS alarm,\r\n  ARG_MAX((fire.\"test\").Value, (fire.\"test\").Timestamp)         AS test\r\nFROM marpower.\"450000_firedetection\" AS fire\r\nJOIN marpower.firedetection_metadata AS meta ON fire.topic = meta.topic\r\nWHERE meta.section = 'Accommodation'\r\n  AND (meta.room_or_area LIKE '%Storage%' OR meta.room_or_area LIKE '%Office%' OR meta.room_or_area LIKE '%Galley%' OR meta.room_or_area LIKE '%Laundry%')\r\n  AND meta.room_or_area NOT LIKE '%Cabin%'\r\n  AND meta.room_or_area NOT LIKE '%Corridor%'\r\nGROUP BY meta.\"description\"\r\nORDER BY meta.\"description\""
    }
   ]
  },
  {
   "title": "Crew areas",
   "type": "table",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 41 },
   "targets": [
    {
     "dataset": "dev",
     "rawSql": "SELECT\r\n  meta.\"description\",\r\n  ARG_MAX((fire.\"disabled\").Value, (fire.\"disabled\").Timestamp) AS disabled,\r\n  ARG_MAX((fire.\"fault\").Value, (fire.\"fault\").Timestamp)       AS fault,\r\n  ARG_MAX((fire.\"prealarm\").Value, (fire.\"prealarm\").Timestamp) AS prealarm,\r\n  ARG_MAX((fire.\"alarm\").Value, (fire.\"alarm\").Timestamp)       AS alarm,\r\n  ARG_MAX((fire.\"test\").Value, (fire.\"test\").Timestamp)         AS test\r\nFROM marpower.\"450000_firedetection\" AS fire\r\nJOIN marpower.firedetection_metadata AS meta ON fire.topic = meta.topic\r\nWHERE meta.section = 'Accommodation'\r\n  AND meta.room_or_area LIKE '%Crew%'\r\n  AND meta.room_or_area NOT LIKE '%Cabin%'\r\n  AND meta.room_or_area NOT LIKE '%Corridor%'\r\nGROUP BY meta.\"description\"\r\nORDER BY meta.\"description\""
    }
   ]
  },
  { "title": "Technical", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 57 } },
  {
   "title": "Batteries",
   "type": "table",
   "gridPos": { "h": 15, "w": 12, "x": 0, "y": 58 },
   "targets": [
    {
     "dataset": "dev",
     "rawSql": "SELECT\r\n  meta.\"description\",\r\n  ARG_MAX((fire.\"disabled\").Value, (fire.\"disabled\").Timestamp) AS disabled,\r\n  ARG_MAX((fire.\"fault\").Value, (fire.\"fault\").Timestamp)       AS fault,\r\n  ARG_MAX((fire.\"prealarm\").Value, (fire.\"prealarm\").Timestamp) AS prealarm,\r\n  ARG_MAX((fire.\"alarm\").Value, (fire.\"alarm\").Timestamp)       AS alarm,\r\n  ARG_MAX((fire.\"test\").Value, (fire.\"test\").Timestamp)         AS test\r\nFROM marpower.\"450000_firedetection\" AS fire\r\nJOIN marpower.firedetection_metadata AS meta ON fire.topic = meta.topic\r\nWHERE meta.section = 'Technical'\r\nAND meta.room_or_area LIKE '%Battery%'\r\nGROUP BY meta.\"description\"\r\nORDER BY meta.\"description\""
    }
   ]
  },
  {
   "title": "Other",
   "type": "table",
   "gridPos": { "h": 17, "w": 12, "x": 12, "y": 58 },
   "targets": [
    {
     "dataset": "dev",
     "rawSql": "SELECT\r\n  meta.\"description\",\r\n  ARG_MAX((fire.\"disabled\").Value, (fire.\"disabled\").Timestamp) AS disabled,\r\n  ARG_MAX((fire.\"fault\").Value, (fire.\"fault\").Timestamp)       AS fault,\r\n  ARG_MAX((fire.\"prealarm\").Value, (fire.\"prealarm\").Timestamp) AS prealarm,\r\n  ARG_MAX((fire.\"alarm\").Value, (fire.\"alarm\").Timestamp)       AS alarm,\r\n  ARG_MAX((fire.\"test\").Value, (fire.\"test\").Timestamp)         AS test\r\nFROM marpower.\"450000_firedetection\" AS fire\r\nJOIN marpower.firedetection_metadata AS meta ON fire.topic = meta.topic\r\nWHERE meta.section = 'Technical'\r\nAND (meta.room_or_area LIKE '%Fore%' OR meta.room_or_area LIKE '%Lazarette%' OR meta.room_or_area LIKE '%Bilge%' OR meta.room_or_area LIKE '%Pod%')\r\nGROUP BY meta.\"description\"\r\nORDER BY meta.\"description\""
    }
   ]
  },
  {
   "title": "Technical spaces",
   "type": "table",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 73 },
   "targets": [
    {
     "dataset": "dev",
     "rawSql": "SELECT\r\n  meta.\"description\",\r\n  ARG_MAX((fire.\"disabled\").Value, (fire.\"disabled\").Timestamp) AS disabled,\r\n  ARG_MAX((fire.\"fault\").Value, (fire.\"fault\").Timestamp)       AS fault,\r\n  ARG_MAX((fire.\"prealarm\").Value, (fire.\"prealarm\").Timestamp) AS prealarm,\r\n  ARG_MAX((fire.\"alarm\").Value, (fire.\"alarm\").Timestamp)       AS alarm,\r\n  ARG_MAX((fire.\"test\").Value, (fire.\"test\").Timestamp)         AS test\r\nFROM marpower.\"450000_firedetection\" AS fire\r\nJOIN marpower.firedetection_metadata AS meta ON fire.topic = meta.topic\r\nWHERE meta.section = 'Technical'\r\nAND meta.room_or_area LIKE '%Technical%'\r\nGROUP BY meta.\"description\"\r\nORDER BY meta.\"description\""
    }
   ]
  },
  { "title": "Other", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 83 } },
  {
   "title": "Hatches",
   "type": "table",
   "gridPos": { "h": 14, "w": 12, "x": 0, "y": 84 },
   "targets": [
    {
     "dataset": "dev",
     "rawSql": "SELECT\r\n  meta.\"description\",\r\n  ARG_MAX((fire.\"disabled\").Value, (fire.\"disabled\").Timestamp) AS disabled,\r\n  ARG_MAX((fire.\"fault\").Value, (fire.\"fault\").Timestamp)       AS fault,\r\n  ARG_MAX((fire.\"prealarm\").Value, (fire.\"prealarm\").Timestamp) AS prealarm,\r\n  ARG_MAX((fire.\"alarm\").Value, (fire.\"alarm\").Timestamp)       AS alarm,\r\n  ARG_MAX((fire.\"test\").Value, (fire.\"test\").Timestamp)         AS test\r\nFROM marpower.\"450000_firedetection\" AS fire\r\nJOIN marpower.firedetection_metadata AS meta ON fire.topic = meta.topic\r\nWHERE meta.section = 'Hatch'\r\nGROUP BY meta.\"description\"\r\nORDER BY meta.\"description\""
    }
   ]
  },
  {
   "title": "General storage",
   "type": "table",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 84 },
   "targets": [
    {
     "dataset": "dev",
     "rawSql": "SELECT\r\n  meta.\"description\",\r\n  ARG_MAX((fire.\"disabled\").Value, (fire.\"disabled\").Timestamp) AS disabled,\r\n  ARG_MAX((fire.\"fault\").Value, (fire.\"fault\").Timestamp)       AS fault,\r\n  ARG_MAX((fire.\"prealarm\").Value, (fire.\"prealarm\").Timestamp) AS prealarm,\r\n  ARG_MAX((fire.\"alarm\").Value, (fire.\"alarm\").Timestamp)       AS alarm,\r\n  ARG_MAX((fire.\"test\").Value, (fire.\"test\").Timestamp)         AS test\r\nFROM marpower.\"450000_firedetection\" AS fire\r\nJOIN marpower.firedetection_metadata AS meta ON fire.topic = meta.topic\r\nWHERE meta.section = 'Storage'\r\nGROUP BY meta.\"description\"\r\nORDER BY meta.\"description\""
    }
   ]
  }
 ]
}