{
 "title": "Firedetection",
 "tags": [ "commisssioning" ],
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "datasource", "query": "info8fcc-greptimedb-datasource" }
  ]
 },
 "panels": [
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 0 },
   "options": {
    "content": "<center>\r\n  <h1>Fire detection</h1>\r\n</center>\r\n"
   }
  },
  { "title": "General", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 } },
  {
   "title": "Alarms",
   "type": "canvas",
   "gridPos": { "h": 4, "w": 14, "x": 0, "y": 3 },
   "targets": [
    {
     "dataset": "dev",
     "rawSql": "select timestamp as timestamp,\r\n\t\t\tdetect_fault__value as detect_fault,\r\n\t\t\tdoor_powersupplyfail__value as door_power_supply_fail,\r\n\t\t\tauxiliary_system_servicesupplyfail__value as aux_sys_service_supply_fail,\r\n\t\t\tauxiliary_system_emergencysupplyfail__value as aux_sys_emergency_supply_fail\r\nfrom marpower__450000_firedetection_general\r\norder by timestamp desc\r\nlimit 1;"
    }
   ]
  },
  {
   "title": "Status",
   "type": "canvas",
   "gridPos": { "h": 4, "w": 10, "x": 14, "y": 3 },
   "targets": [
    {
     "dataset": "dev",
     "rawSql": "select timestamp as timestamp,\r\n\t\t\tdoors_release__value as doors_release\r\nfrom marpower__450000_firedetection_general\r\norder by timestamp desc\r\nlimit 1;"
    }
   ]
  },
  {
   "title": "Historical",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 },
   "collapsed": true,
   "panels": [
    {
     "title": "Alarm, status & control signal history",
     "type": "status-history",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 8 },
     "targets": [
      {
       "dataset": "dev",
       "rawSql": "SELECT timestamp, detect_fault__value AS detect_fault,\r\n\t\t\t\t\t\t\t\t\tdoor_powersupplyfail__value AS door_power_supply_fail,\r\n\t\t\t\t\t\t\t\t\tauxiliary_system_servicesupplyfail__value AS aux_sys_service_supply_fail,\r\n\t\t\t\t\t\t\t\t\tauxiliary_system_emergencysupplyfail__value AS aux_sys_emergency_supply_fail,\r\n\t\t\t\t\t\t\t\t\tdoors_release__value AS doors_release\r\nFROM marpower__450000_firedetection_general\r\nWHERE $__timeFilter(timestamp)"
      }
     ]
    }
   ]
  },
  { "title": "Accommodations", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 } },
  {
   "title": "Cabins",
   "type": "table",
   "gridPos": { "h": 22, "w": 12, "x": 0, "y": 9 },
   "targets": [
    {
     "dataset": "dev",
     "rawSql": "select timestamp as timestamp,\r\n\t\t\tdetect_fault__value as detect_fault,\r\n\t\t\tdoor_powersupplyfail__value as door_power_supply_fail,\r\n\t\t\tauxiliary_system_servicesupplyfail__value as aux_sys_service_supply_fail,\r\n\t\t\tauxiliary_system_emergencysupplyfail__value as aux_sys_emergency_supply_fail\r\nfrom marpower__450000_firedetection_general\r\norder by timestamp desc\r\nlimit 1;"
    }
   ]
  },
  {
   "title": "Corridors",
   "type": "table",
   "gridPos": { "h": 21, "w": 12, "x": 12, "y": 9 },
   "targets": [
    {
     "dataset": "dev",
     "rawSql": "select timestamp as timestamp,\r\n\t\t\tdoors_release__value as doors_release\r\nfrom marpower__450000_firedetection_general\r\norder by timestamp desc\r\nlimit 1;"
    }
   ]
  },
  {
   "title": "Owner",
   "type": "table",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 30 },
   "targets": [
    {
     "dataset": "dev",
     "rawSql": "select timestamp, detect_fault__value as detect_fault,\r\n\t\t\t\t\t\t\t\t\tdoor_powersupplyfail__value as door_power_supply_fail,\r\n\t\t\t\t\t\t\t\t\tauxiliary_system_servicesupplyfail__value as aux_sys_service_supply_fail,\r\n\t\t\t\t\t\t\t\t\tauxiliary_system_emergencysupplyfail__value as aux_sys_emergency_supply_fail,\r\n\t\t\t\t\t\t\t\t\tdoors_release__value as doors_release\r\nfrom marpower__450000_firedetection_general\r\nwhere $__timefilter(timestamp);"
    }
   ]
  },
  {
   "title": "Lounges",
   "type": "table",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 31 },
   "targets": [
    {
     "dataset": "dev",
     "rawSql": "select distinct meta.description,\r\n\t\t\t\t\t\t\t\tfire.disabled__value as disabled,\r\n\t\t\t\t\t\t\t\tfire.fault__value as fault,\r\n\t\t\t\t\t\t\t\tfire.prealarm__value as prealarm,\r\n\t\t\t\t\t\t\t\tfire.alarm__value as alarm,\r\n\t\t\t\t\t\t\t\tfire.test__value as test\r\nfrom marpower__450000_firedetection as fire\r\njoin marpower__firedetection_metadata as meta on fire.topic = meta.topic\r\nwhere meta.section = 'Accommodation'\r\n\tand meta.room_or_area like '%Cabin%'\r\norder by timestamp desc\r\nlimit 1;"
    }
   ]
  },
  { "title": "Crew service", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 40 } },
  {
   "title": "Rooms & storage",
   "type": "table",
   "gridPos": { "h": 16, "w": 12, "x": 0, "y": 41 },
   "targets": [
    {
     "dataset": "dev",
     "rawSql": "select meta.description,\r\n\t\t\tfire.disabled__value as disabled,\r\n\t\t\tfire.fault__value as fault,\r\n\t\t\tfire.prealarm__value as prealarm,\r\n\t\t\tfire.alarm__value as alarm,\r\n\t\t\tfire.test__value as test\r\nfrom marpower__450000_firedetection as fire\r\njoin marpower__firedetection_metadata as meta on fire.topic = meta.topic\r\nwhere meta.section = 'Accommodation'\r\n\tand meta.room_or_area like '%Corridor%'\r\norder by timestamp desc\r\nlimit 1;"
    }
   ]
  },
  {
   "title": "Crew areas",
   "type": "table",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 41 },
   "targets": [
    {
     "dataset": "dev",
     "rawSql": "select meta.description,\r\n\t\t\tfire.disabled__value as disabled,\r\n\t\t\tfire.fault__value as fault,\r\n\t\t\tfire.prealarm__value as prealarm,\r\n\t\t\tfire.alarm__value as alarm,\r\n\t\t\tfire.test__value as test\r\nfrom marpower__450000_firedetection as fire\r\njoin marpower__firedetection_metadata as meta on fire.topic = meta.topic\r\nwhere meta.section = 'Accommodation'\r\n\tand meta.room_or_area like '%Owner%'\r\n\tand meta.room_or_area not like '%Cabin%'\r\n\tand meta.room_or_area not like '%Corridor%'\r\norder by timestamp desc\r\nlimit 1;"
    }
   ]
  },
  { "title": "Technical", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 57 } },
  {
   "title": "Batteries",
   "type": "table",
   "gridPos": { "h": 15, "w": 12, "x": 0, "y": 58 },
   "targets": [
    {
     "dataset": "dev",
     "rawSql": "select meta.description,\r\n\t\t\tfire.disabled__value as disabled,\r\n\t\t\tfire.fault__value as fault,\r\n\t\t\tfire.prealarm__value as prealarm,\r\n\t\t\tfire.alarm__value as alarm,\r\n\t\t\tfire.test__value as test\r\nfrom marpower__450000_firedetection as fire\r\njoin marpower__firedetection_metadata as meta on fire.topic = meta.topic\r\nwhere meta.section = 'Accommodation'\r\n\tand (meta.room_or_area like '%Lounge%'\r\n\t\t\tor meta.room_or_area like '%Salon%')\r\n\tand meta.room_or_area not like '%Cabin%'\r\n\tand meta.room_or_area not like '%Corridor%'\r\n\tand meta.room_or_area not like '%Crew%'\r\n\tand meta.room_or_area not like '%Owner%'\r\norder by timestamp desc\r\nlimit 1;"
    }
   ]
  },
  {
   "title": "Other",
   "type": "table",
   "gridPos": { "h": 17, "w": 12, "x": 12, "y": 58 },
   "targets": [
    {
     "dataset": "dev",
     "rawSql": "select meta.description,\r\n\t\t\tfire.disabled__value as disabled,\r\n\t\t\tfire.fault__value as fault,\r\n\t\t\tfire.prealarm__value as prealarm,\r\n\t\t\tfire.alarm__value as alarm,\r\n\t\t\tfire.test__value as test\r\nfrom marpower__450000_firedetection as fire\r\njoin marpower__firedetection_metadata as meta on fire.topic = meta.topic\r\nwhere meta.section = 'Accommodation'\r\n\tand (meta.room_or_area like '%Storage%'\r\n\t\t\tor meta.room_or_area like '%Office%'\r\n\t\t\tor meta.room_or_area like '%Galley%'\r\n\t\t\tor meta.room_or_area like '%Laundry%')\r\n\tand meta.room_or_area not like '%Cabin%'\r\n\tand meta.room_or_area not like '%Corridor%'\r\norder by timestamp desc\r\nlimit 1;"
    }
   ]
  },
  {
   "title": "Technical spaces",
   "type": "table",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 73 },
   "targets": [
    {
     "dataset": "dev",
     "rawSql": "select meta.description,\r\n\t\t\tfire.disabled__value as disabled,\r\n\t\t\tfire.fault__value as fault,\r\n\t\t\tfire.prealarm__value as prealarm,\r\n\t\t\tfire.alarm__value as alarm,\r\n\t\t\tfire.test__value as test\r\nfrom marpower__450000_firedetection as fire\r\njoin marpower__firedetection_metadata as meta on fire.topic = meta.topic\r\nwhere meta.section = 'Accommodation'\r\n\tand meta.room_or_area like '%Crew%'\r\n\tand meta.room_or_area not like '%Cabin%'\r\n\tand meta.room_or_area not like '%Corridor%'\r\norder by timestamp desc\r\nlimit 1;"
    }
   ]
  },
  { "title": "Other", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 83 } },
  {
   "title": "Hatches",
   "type": "table",
   "gridPos": { "h": 14, "w": 12, "x": 0, "y": 84 },
   "targets": [
    {
     "dataset": "dev",
     "rawSql": "select meta.description,\r\n\t\t\tfire.disabled__value as disabled,\r\n\t\t\tfire.fault__value as fault,\r\n\t\t\tfire.prealarm__value as prealarm,\r\n\t\t\tfire.alarm__value as alarm,\r\n\t\t\tfire.test__value as test\r\nfrom marpower__450000_firedetection as fire\r\njoin marpower__firedetection_metadata as meta on fire.topic = meta.topic\r\nwhere meta.section = 'Technical'\r\n\tand meta.room_or_area like '%Battery%'\r\norder by timestamp desc\r\nlimit 1;"
    }
   ]
  },
  {
   "title": "General storage",
   "type": "table",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 84 },
   "targets": [
    {
     "dataset": "dev",
     "rawSql": "select meta.description,\r\n\t\t\tfire.disabled__value as disabled,\r\n\t\t\tfire.fault__value as fault,\r\n\t\t\tfire.prealarm__value as prealarm,\r\n\t\t\tfire.alarm__value as alarm,\r\n\t\t\tfire.test__value as test\r\nfrom marpower__450000_firedetection as fire\r\njoin marpower__firedetection_metadata as meta on fire.topic = meta.topic\r\nwhere meta.section = 'Technical'\r\n\tand (meta.room_or_area like '%Fore%'\r\n\t\t\tor meta.room_or_area like '%Lazarette%'\r\n\t\t\tor meta.room_or_area like '%Bilge%'\r\n\t\t\tor meta.room_or_area like '%Pod%')\r\norder by timestamp desc\r\nlimit 1;"
    }
   ]
  }
 ]
}