{
 "title": "Fresh water",
 "tags": [ "commisssioning" ],
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "datasource", "query": "grafana-postgresql-datasource" }
  ]
 },
 "panels": [
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 0 },
   "options": {
    "content": "<center>\r\n  <h1>Fresh water</h1>\r\n</center>\r\n"
   }
  },
  { "title": "General", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 } },
  {
   "title": "Alarms",
   "type": "canvas",
   "gridPos": { "h": 4, "w": 5, "x": 0, "y": 3 },
   "targets": [
    {
     "dataset": "dev",
     "rawSql": "SELECT\r\n  LAST_VALUE(time ORDER BY time) AS time,\r\n  LAST_VALUE((\"MAK1_ALARM\").value ORDER BY time) AS fresh_water_mak1_alarm,\r\n  LAST_VALUE((\"MAK2_ALARM\").value ORDER BY time) AS fresh_water_mak2_alarm,\r\n  LAST_VALUE((\"CHLORINE_UNIT_ALARM\").value ORDER BY time) AS fresh_water_chlorine_unit_alarm\r\nFROM marpower.\"250000_fresh_water\""
    }
   ]
  },
  {
   "title": "Status",
   "type": "canvas",
   "gridPos": { "h": 4, "w": 6, "x": 5, "y": 3 },
   "targets": [
    {
     "dataset": "dev",
     "rawSql": "SELECT\r\n  LAST_VALUE(time ORDER BY time) AS time,\r\n  LAST_VALUE((\"CIRC_PUMP_RUNNING\").value ORDER BY time) AS fresh_water_circ_pump_running\r\nFROM marpower.\"250000_fresh_water\""
    }
   ]
  },
  {
   "title": "Control signals",
   "type": "canvas",
   "gridPos": { "h": 4, "w": 6, "x": 11, "y": 3 },
   "targets": [
    {
     "dataset": "dev",
     "rawSql": "SELECT\r\n  LAST_VALUE(time ORDER BY time) AS time,\r\n  LAST_VALUE((\"CIRC_PUMP_ONOFF\").value ORDER BY time) AS fresh_water_circ_pump_onoff\r\nFROM marpower.\"250000_fresh_water\""
    }
   ]
  },
  {
   "title": "Historical",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 },
   "collapsed": true,
   "panels": [
    {
     "title": "Alarm, status & control signal history",
     "type": "status-history",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 26 },
     "targets": [
      {
       "dataset": "dev",
       "rawSql": "SELECT\r\n  time,\r\n\r\n  -- Alarm\r\n  (\"MAK1_ALARM\").value AS fresh_water_mak1_alarm,\r\n  (\"MAK2_ALARM\").value AS fresh_water_mak2_alarm,\r\n  (\"CHLORINE_UNIT_ALARM\").value AS fresh_water_chlorine_unit_alarm,\r\n\r\n  -- Status\r\n  (\"CIRC_PUMP_RUNNING\").value AS fresh_water_circ_pump_running,\r\n\r\n  -- Control signals\r\n  (\"CIRC_PUMP_ONOFF\").value AS fresh_water_circ_pump_onoff\r\nFROM marpower.\"250000_fresh_water\"\r\nWHERE $__timeFilter(time)"
      }
     ]
    }
   ]
  },
  { "title": "Cold water flow", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 } },
  {
   "title": "Accommodations",
   "type": "canvas",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "flowlpm" } },
   "targets": [
    {
     "rawSql": "SELECT\n  LAST_VALUE(time ORDER BY time) AS time,  \n  LAST_VALUE((\"COLDWATER_GUEST_CABIN_SB_FLOW\").value ORDER BY time)          AS coldwater_guest_cabin_sb_flow,\n  LAST_VALUE((\"COLDWATER_GUEST_CABIN_PS_FWD_FLOW\").value ORDER BY time)      AS coldwater_guest_cabin_ps_fwd_flow,\n  LAST_VALUE((\"COLDWATER_GUEST_CABIN_PS_AFT_FLOW\").value ORDER BY time)      AS coldwater_guest_cabin_ps_aft_flow,\n  LAST_VALUE((\"COLDWATER_MASTER_CABIN_SB_FLOW\").value ORDER BY time)         AS coldwater_master_cabin_sb_flow,\n  LAST_VALUE((\"COLDWATER_MASTER_CABIN_PS_FLOW\").value ORDER BY time)         AS coldwater_master_cabin_ps_flow,\n  LAST_VALUE((\"COLDWATER_GUEST_BATHR_PS_FWD_FLOW\").value ORDER BY time)      AS coldwater_guest_bathroom_flow,\n  LAST_VALUE((\"COLDWATER_CAPTAINS_CABIN_FLOW\").value ORDER BY time)          AS coldwater_captains_cabin_flow,\n  LAST_VALUE((\"COLDWATER_CREW_CABIN_SB_AFT_FLOW\").value ORDER BY time)       AS coldwater_crew_cabin_sb_aft_flow,\n  LAST_VALUE((\"COLDWATER_CREW_CABIN_SB_MID_FLOW\").value ORDER BY time)       AS coldwater_crew_cabin_sb_mid_flow,\n  LAST_VALUE((\"COLDWATER_CREW_CABIN_PS_MID_FLOW\").value ORDER BY time)       AS coldwater_crew_cabin_ps_mid_flow,\n  LAST_VALUE((\"COLDWATER_CREW_CABIN_SB_FWD_FLOW\").value ORDER BY time)       AS coldwater_crew_cabin_sb_fwd_flow,\n  LAST_VALUE((\"COLDWATER_CREW_CABIN_PS_FWD_FLOW\").value ORDER BY time)       AS coldwater_crew_cabin_ps_fwd_flow\nFROM marpower.\"250000_fresh_water\";\n"
    }
   ]
  },
  {
   "title": "Other areas",
   "type": "canvas",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "flowlpm" } },
   "targets": [
    {
     "rawSql": "SELECT\n  LAST_VALUE(time ORDER BY time) AS time,\n  LAST_VALUE((\"COLDWATER_CAPTAINS_CABIN_FLOW\").value ORDER BY time)          AS coldwater_captains_cabin_flow,\n  LAST_VALUE((\"COLDWATER_CREW_CABIN_SB_AFT_FLOW\").value ORDER BY time)       AS coldwater_crew_cabin_sb_aft_flow,\n  LAST_VALUE((\"COLDWATER_CREW_CABIN_SB_MID_FLOW\").value ORDER BY time)       AS coldwater_crew_cabin_sb_mid_flow,\n  LAST_VALUE((\"COLDWATER_CREW_CABIN_PS_MID_FLOW\").value ORDER BY time)       AS coldwater_crew_cabin_ps_mid_flow,\n  LAST_VALUE((\"COLDWATER_CREW_CABIN_SB_FWD_FLOW\").value ORDER BY time)       AS coldwater_crew_cabin_sb_fwd_flow,\n  LAST_VALUE((\"COLDWATER_CREW_CABIN_PS_FWD_FLOW\").value ORDER BY time)       AS coldwater_crew_cabin_ps_fwd_flow,\n\n  LAST_VALUE((\"COLDWATER_LOWER_SALOON_FLOW\").value ORDER BY time)            AS coldwater_lower_saloon_flow,\n  LAST_VALUE((\"COLDWATER_CREW_MESS_FLOW\").value ORDER BY time)               AS coldwater_crew_mess_flow,\n  LAST_VALUE((\"COLDWATER_GALLEY_2_FLOW\").value ORDER BY time)               AS coldwater_galley_2_flow,\n  LAST_VALUE((\"COLDWATER_DAYHEAD_FLOW\").value ORDER BY time)                AS coldwater_dayhead_flow,\n  LAST_VALUE((\"COLDWATER_LAZARET_FLOW\").value ORDER BY time)                 AS coldwater_lazaret_flow,\n  LAST_VALUE((\"COLDWATER_LAUNDRY_PS_FLOW\").value ORDER BY time)             AS coldwater_laundry_ps_flow,\n  LAST_VALUE((\"COLDWATER_DECKHOUSE_FLOW\").value ORDER BY time)              AS coldwater_deckhouse_flow,\n  LAST_VALUE((\"COLDWATER_DECK_FR48_SB_TECH_COR_FLOW\").value ORDER BY time)   AS coldwater_deck_fr48_sb_tech_cor_flow,\n  LAST_VALUE((\"COLDWATER_WATER_SOFTNER_FLOW\").value ORDER BY time)          AS coldwater_water_softner_flow,\n  LAST_VALUE((\"COLDWATER_MAIN_TECH_SPACE_FLOW\").value ORDER BY time)        AS coldwater_main_tech_space_flow,\n  LAST_VALUE((\"COLDWATER_MAIN_TECH_SPACE_FR45_FLOW\").value ORDER BY time)   AS coldwater_main_tech_space_fr45_flow\nFROM marpower.\"250000_fresh_water\";\n"
    }
   ]
  },
  { "title": "Hot water flow", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 } },
  {
   "title": "Accommodations",
   "type": "canvas",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "flowlpm" } },
   "targets": [
    {
     "rawSql": "SELECT\n  LAST_VALUE(time ORDER BY time) AS time,  \n  LAST_VALUE((\"HOTWATER_GUEST_CABIN_SB_FLOW\").value ORDER BY time)           AS hotwater_guest_cabin_sb_flow,\n  LAST_VALUE((\"HOTWATER_GUEST_CABIN_PS_FWD_FLOW\").value ORDER BY time)       AS hotwater_guest_cabin_ps_fwd_flow,\n  LAST_VALUE((\"HOTWATER_GUEST_CABIN_PS_AFT_FLOW\").value ORDER BY time)       AS hotwater_guest_cabin_ps_aft_flow,\n  LAST_VALUE((\"HOTWATER_MASTER_CABIN_SB_FLOW\").value ORDER BY time)          AS hotwater_master_cabin_sb_flow,\n  LAST_VALUE((\"HOTWATER_MASTER_CABIN_PS_FLOW\").value ORDER BY time)          AS hotwater_master_cabin_ps_flow,\n  LAST_VALUE((\"HOTWATER_GUEST_BATHR_PS_FWD_FLOW\").value ORDER BY time)       AS hotwater_guest_bathroom_flow,\n  LAST_VALUE((\"HOTWATER_CAPTAINS_CABIN_FLOW\").value ORDER BY time)           AS hotwater_captains_cabin_flow,\n  LAST_VALUE((\"HOTWATER_CREW_CABIN_SB_AFT_FLOW\").value ORDER BY time)        AS hotwater_crew_cabin_sb_aft_flow,\n  LAST_VALUE((\"HOTWATER_CREW_CABIN_SB_MID_FLOW\").value ORDER BY time)        AS hotwater_crew_cabin_sb_mid_flow,\n  LAST_VALUE((\"HOTWATER_CREW_CABIN_PS_MID_FLOW\").value ORDER BY time)        AS hotwater_crew_cabin_ps_mid_flow,\n  LAST_VALUE((\"HOTWATER_CREW_CABIN_SB_FWD_FLOW\").value ORDER BY time)        AS hotwater_crew_cabin_sb_fwd_flow,\n  LAST_VALUE((\"HOTWATER_CREW_CABIN_PS_FWD_FLOW\").value ORDER BY time)        AS hotwater_crew_cabin_ps_fwd_flow\nFROM marpower.\"250000_fresh_water\"\n"
    }
   ]
  },
  {
   "title": "Hot water flow",
   "type": "canvas",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "flowlpm" } },
   "targets": [
    {
     "rawSql": "SELECT\n  LAST_VALUE(time ORDER BY time) AS time,\n  LAST_VALUE((\"HOTWATER_CREW_MESS_FLOW\").value ORDER BY time)                AS hotwater_crew_mess_flow,\n  LAST_VALUE((\"HOTWATER_GALLEY_2_FLOW\").value ORDER BY time)                 AS hotwater_galley_2_flow,\n  LAST_VALUE((\"HOTWATER_DAYHEAD_FLOW\").value ORDER BY time)                  AS hotwater_dayhead_flow,\n  LAST_VALUE((\"HOTWATER_LAZARET_FLOW\").value ORDER BY time)                  AS hotwater_lazaret_flow,\n  LAST_VALUE((\"HOTWATER_LAUNDRY_PS_1_FLOW\").value ORDER BY time)             AS hotwater_laundry_ps_1_flow,\n  LAST_VALUE((\"HOTWATER_DECKHOUSE_FLOW\").value ORDER BY time)                AS hotwater_deckhouse_flow,\n  LAST_VALUE((\"HOTWATER_DECK_FR48_SB_TECH_COR_FLOW\").value ORDER BY time)    AS hotwater_deck_fr48_sb_tech_cor_flow,\n  LAST_VALUE((\"HOTWATER_MAIN_TECH_SPACE_FLOW\").value ORDER BY time)          AS hotwater_main_tech_space_flow\nFROM marpower.\"250000_fresh_water\"\n"
    }
   ]
  },
  { "title": "Miscellaneous", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 26 } },
  {
   "title": "Other flow",
   "type": "canvas",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "flowlpm" } },
   "targets": [
    {
     "rawSql": "SELECT\n  LAST_VALUE(time ORDER BY time) AS time,\n  LAST_VALUE((\"TECHNICAL_ROOM_ENERG_REC_FLOW\").value ORDER BY time)          AS technical_room_energ_rec_flow,\n  LAST_VALUE((\"FLOW_SENSOR_25001137C1\").value ORDER BY time)                AS flow_sensor_25001137c1,\n  LAST_VALUE((\"FLOW_SENSOR_25001037C3\").value ORDER BY time)                AS flow_sensor_25001037c3,\n  LAST_VALUE((\"FLOW_SENSOR_25001037C4\").value ORDER BY time)                AS flow_sensor_25001037c4\nFROM marpower.\"250000_fresh_water\";\n"
    }
   ]
  },
  {
   "title": "Temperature",
   "type": "canvas",
   "gridPos": { "h": 7, "w": 9, "x": 8, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "rawSql": "SELECT\n  LAST_VALUE(time ORDER BY time) AS time,\n  LAST_VALUE((\"ENERGY_REC_SYSTEM_TEMP4\").value ORDER BY time)               AS energy_rec_temp4,\n  LAST_VALUE((\"ENERGY_REC_SYSTEM_TEMP5\").value ORDER BY time)               AS energy_rec_temp5,\n  LAST_VALUE((\"ENERGY_REC_SYSTEM_TEMP6\").value ORDER BY time)               AS energy_rec_temp6,\n  LAST_VALUE((\"ENERGY_REC_SYSTEM_TEMP7\").value ORDER BY time)               AS energy_rec_temp7,\n  LAST_VALUE((\"ENERGY_REC_SYSTEM_TEMP8\").value ORDER BY time)               AS energy_rec_temp8\nFROM marpower.\"250000_fresh_water\";\n"
    }
   ]
  },
  {
   "title": "Tank level",
   "type": "canvas",
   "gridPos": { "h": 4, "w": 7, "x": 17, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "rawSql": "SELECT\n  LAST_VALUE(time ORDER BY time) AS time,\n  LAST_VALUE((\"TANK_1_FR_45_PS_LEVEL\").value ORDER BY time)      AS fresh_water_tank_1_level,\n  LAST_VALUE((\"TANK_2_FR_45_SB_LEVEL\").value ORDER BY time)      AS fresh_water_tank_2_level\nFROM marpower.\"250000_fresh_water\";\n"
    }
   ]
  },
  {
   "title": "Pressure",
   "type": "canvas",
   "gridPos": { "h": 3, "w": 7, "x": 17, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "pressurebar" } },
   "targets": [
    {
     "rawSql": "SELECT\n  LAST_VALUE(time ORDER BY time) AS time,\n  LAST_VALUE((\"FR_46_SYSTEM_BEH_PRES_PUMPS_PRESS\").value ORDER BY time) AS fr46_system_pressure\nFROM marpower.\"250000_fresh_water\";\n"
    }
   ]
  }
 ]
}