{
 "title": "Fresh water",
 "tags": [ "commisssioning" ],
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "datasource", "query": "info8fcc-greptimedb-datasource" }
  ]
 },
 "panels": [
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 0 },
   "options": {
    "content": "<center>\r\n  <h1>Fresh water</h1>\r\n</center>\r\n"
   }
  },
  { "title": "General", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 } },
  {
   "title": "Alarms",
   "type": "canvas",
   "gridPos": { "h": 4, "w": 5, "x": 0, "y": 3 },
   "targets": [
    {
     "dataset": "dev",
     "rawSql": "SELECT\r\n  timestamp                  AS time,\r\n  mak_1_alarm__value         AS fresh_water_mak1_alarm,\r\n  mak_2_alarm__value         AS fresh_water_mak2_alarm,\r\n  chlorine_unit_alarm__value AS fresh_water_chlorine_unit_alarm\r\nFROM public.marpower__250000_fresh_water\r\nORDER BY timestamp DESC\r\nLIMIT 1"
    }
   ]
  },
  {
   "title": "Status",
   "type": "canvas",
   "gridPos": { "h": 4, "w": 6, "x": 5, "y": 3 },
   "targets": [
    {
     "dataset": "dev",
     "rawSql": "SELECT\r\n  timestamp                AS time,\r\n  circ_pump_running__value AS fresh_water_circ_pump_running\r\nFROM public.marpower__250000_fresh_water\r\nORDER BY timestamp DESC\r\nLIMIT 1"
    }
   ]
  },
  {
   "title": "Control signals",
   "type": "canvas",
   "gridPos": { "h": 4, "w": 6, "x": 11, "y": 3 },
   "targets": [
    {
     "dataset": "dev",
     "rawSql": "SELECT\r\n  timestamp              AS time,\r\n  circ_pump_onoff__value AS fresh_water_circ_pump_onoff\r\nFROM public.marpower__250000_fresh_water\r\nORDER BY timestamp DESC\r\nLIMIT 1"
    }
   ]
  },
  {
   "title": "Historical",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 },
   "collapsed": true,
   "panels": [
    {
     "title": "Alarm, status & control signal history",
     "type": "status-history",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 8 },
     "targets": [
      {
       "dataset": "dev",
       "rawSql": "SELECT\r\n  timestamp                  AS time,\r\n\r\n  -- Alarm\r\n  mak_1_alarm__value         AS fresh_water_mak1_alarm,\r\n  mak_2_alarm__value         AS fresh_water_mak2_alarm,\r\n  chlorine_unit_alarm__value AS fresh_water_chlorine_unit_alarm,\r\n\r\n  -- Status\r\n  circ_pump_running__value AS fresh_water_circ_pump_running,\r\n\r\n  -- Control signals\r\n  circ_pump_onoff__value AS fresh_water_circ_pump_onoff\r\nFROM public.marpower__250000_fresh_water\r\nWHERE $__timeFilter(timestamp)"
      }
     ]
    }
   ]
  },
  { "title": "Cold water flow", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 } },
  {
   "title": "Accommodations",
   "type": "canvas",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "flowlpm" } },
   "targets": [
    {
     "rawSql": "SELECT\r\n  timestamp                                AS time,\r\n  coldwater_guest_cabin_sb_flow__value     AS guest_cabin_sb_flow,\r\n  coldwater_guest_cabin_ps_fwd_flow__value AS guest_cabin_ps_fwd_flow,\r\n  coldwater_guest_cabin_ps_aft_flow__value AS guest_cabin_ps_aft_flow,\r\n  coldwater_master_cabin_sb_flow__value    AS master_cabin_sb_flow,\r\n  coldwater_master_cabin_ps_flow__value    AS master_cabin_ps_flow,\r\n  coldwater_guest_bathr_ps_fwd_flow__value AS guest_bathroom_flow,\r\n  coldwater_captains_cabin_flow__value     AS captains_cabin_flow,\r\n  coldwater_crew_cabin_sb_aft_flow__value  AS crew_cabin_sb_aft_flow,\r\n  coldwater_crew_cabin_sb_mid_flow__value  AS crew_cabin_sb_mid_flow,\r\n  coldwater_crew_cabin_ps_mid_flow__value  AS crew_cabin_ps_mid_flow,\r\n  coldwater_crew_cabin_sb_fwd_flow__value  AS crew_cabin_sb_fwd_flow,\r\n  coldwater_crew_cabin_ps_fwd_flow__value  AS crew_cabin_ps_fwd_flow\r\nFROM public.marpower__250000_fresh_water\r\nORDER BY timestamp DESC\r\nLIMIT 1\r\n"
    }
   ]
  },
  {
   "title": "Other areas",
   "type": "canvas",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "flowlpm" } },
   "targets": [
    {
     "rawSql": "SELECT\r\n  timestamp                                     AS time,\r\n  coldwater_lower_saloon_flow__value            AS lower_saloon_flow,\r\n  coldwater_crew_mess_flow__value               AS crew_mess_flow,\r\n  coldwater_galley_2_flow__value                AS galley_2_flow,\r\n  coldwater_dayhead_flow__value                 AS dayhead_flow,\r\n  coldwater_lazaret_flow__value                 AS lazaret_flow,\r\n  coldwater_laundry_ps_flow__value              AS laundry_ps_flow,\r\n  coldwater_deckhouse_flow__value               AS deckhouse_flow,\r\n  coldwater_deck_fr_48_sb_tech_cor_flow__value  AS deck_fr_48_sb_tech_cor_flow,\r\n  coldwater_water_softner_flow__value           AS water_softner_flow,\r\n  coldwater_main_tech_space_flow__value         AS main_tech_space_flow,\r\n  coldwater_main_tech_space_fr_45_flow__value   AS main_tech_space_fr_45_flow\r\nFROM public.marpower__250000_fresh_water\r\nORDER BY timestamp DESC\r\nLIMIT 1"
    }
   ]
  },
  { "title": "Hot water flow", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 } },
  {
   "title": "Accommodations",
   "type": "canvas",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "flowlpm" } },
   "targets": [
    {
     "rawSql": "SELECT\r\n  timestamp                                AS time,\r\n  hotwater_guest_cabin_sb_flow__value     AS guest_cabin_sb_flow,\r\n  hotwater_guest_cabin_ps_fwd_flow__value AS guest_cabin_ps_fwd_flow,\r\n  hotwater_guest_cabin_ps_aft_flow__value AS guest_cabin_ps_aft_flow,\r\n  hotwater_master_cabin_sb_flow__value    AS master_cabin_sb_flow,\r\n  hotwater_master_cabin_ps_flow__value    AS master_cabin_ps_flow,\r\n  hotwater_guest_bathr_ps_fwd_flow__value AS guest_bathroom_flow,\r\n  hotwater_captains_cabin_flow__value     AS captains_cabin_flow,\r\n  hotwater_crew_cabin_sb_aft_flow__value  AS crew_cabin_sb_aft_flow,\r\n  hotwater_crew_cabin_sb_mid_flow__value  AS crew_cabin_sb_mid_flow,\r\n  hotwater_crew_cabin_ps_mid_flow__value  AS crew_cabin_ps_mid_flow,\r\n  hotwater_crew_cabin_sb_fwd_flow__value  AS crew_cabin_sb_fwd_flow,\r\n  hotwater_crew_cabin_ps_fwd_flow__value  AS crew_cabin_ps_fwd_flow\r\nFROM public.marpower__250000_fresh_water\r\nORDER BY timestamp DESC\r\nLIMIT 1\r\n"
    }
   ]
  },
  {
   "title": "Other areas",
   "type": "canvas",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "flowlpm" } },
   "targets": [
    {
     "rawSql": "SELECT\r\n  timestamp                                    AS time,\r\n  hotwater_crew_mess_flow__value               AS crew_mess_flow,\r\n  hotwater_galley_2_flow__value                AS galley_2_flow,\r\n  hotwater_dayhead_flow__value                 AS dayhead_flow,\r\n  hotwater_lazaret_flow__value                 AS lazaret_flow,\r\n  hotwater_laundry_ps_1_flow__value            AS laundry_ps_flow,\r\n  hotwater_deckhouse_flow__value               AS deckhouse_flow,\r\n  hotwater_deck_fr_48_sb_tech_cor_flow__value  AS deck_fr_48_sb_tech_cor_flow,\r\n  hotwater_main_tech_space_flow__value         AS main_tech_space_flow\r\nFROM public.marpower__250000_fresh_water\r\nORDER BY timestamp DESC\r\nLIMIT 1"
    }
   ]
  },
  { "title": "Miscellaneous", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 26 } },
  {
   "title": "Other flow",
   "type": "canvas",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "flowlpm" } },
   "targets": [
    {
     "rawSql": "SELECT\r\n  timestamp                            AS time,\r\n  technical_room_energ_rec_flow__value AS technical_room_energ_rec_flow,\r\n  flow_sensor_25001137_c_1__value      AS flow_sensor_25001137c1,\r\n  flow_sensor_25001037_c_3__value      AS flow_sensor_25001037c3,\r\n  flow_sensor_25001037_c_4__value      AS flow_sensor_25001037c4\r\nFROM public.marpower__250000_fresh_water\r\nORDER BY timestamp DESC\r\nLIMIT 1"
    }
   ]
  },
  {
   "title": "Temperature",
   "type": "canvas",
   "gridPos": { "h": 7, "w": 9, "x": 8, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "rawSql": "SELECT\r\n  timestamp                       AS time,\r\n  energy_rec_system_temp_4__value AS energy_rec_temp4,\r\n  energy_rec_system_temp_5__value AS energy_rec_temp5,\r\n  energy_rec_system_temp_6__value AS energy_rec_temp6,\r\n  energy_rec_system_temp_7__value AS energy_rec_temp7,\r\n  energy_rec_system_temp_8__value AS energy_rec_temp8\r\nFROM public.marpower__250000_fresh_water\r\nORDER BY timestamp DESC\r\nLIMIT 1"
    }
   ]
  },
  {
   "title": "Tank level",
   "type": "canvas",
   "gridPos": { "h": 4, "w": 7, "x": 17, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "rawSql": "SELECT\r\n  timestamp                    AS time,\r\n  tank_1_fr_45_ps_level__value AS fresh_water_tank_1_level,\r\n  tank_2_fr_45_sb_level__value AS fresh_water_tank_2_level\r\nFROM public.marpower__250000_fresh_water\r\nORDER BY timestamp DESC\r\nLIMIT 1"
    }
   ]
  },
  {
   "title": "Pressure",
   "type": "canvas",
   "gridPos": { "h": 3, "w": 7, "x": 17, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "pressurebar" } },
   "targets": [
    {
     "rawSql": "SELECT\r\n  timestamp                                AS time,\r\n  fr_46_system_beh_pres_pumps_press__value AS fr46_system_pressure\r\nFROM public.marpower__250000_fresh_water\r\nORDER BY timestamp DESC\r\nLIMIT 1"
    }
   ]
  }
 ]
}