{
 "title": "Grey & black water",
 "tags": [ "commissioning" ],
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "datasource", "query": "info8fcc-greptimedb-datasource" }
  ]
 },
 "panels": [
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 0 },
   "options": {
    "content": "<center>\r\n  <h1>Grey & Black water</h1>\r\n</center>\r\n"
   }
  },
  { "title": "General", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 } },
  {
   "title": "Alarms",
   "type": "canvas",
   "gridPos": { "h": 3, "w": 7, "x": 0, "y": 3 },
   "targets": [
    {
     "dataset": "dev",
     "rawSql": "select timestamp as time,\r\n\t\t\ttreat_gen_warning_alarm__value AS treatment_general_warning_alarm,\r\n\t\t\tsewage_treatment_plant_general_alarm__value AS treatment_general_alarm\r\nfrom marpower__340000_sewage\r\nORDER BY timestamp DESC\r\nLIMIT 1;"
    },
    {
     "dataset": "dev",
     "rawSql": "select max(case\r\n\t\t\t\t\t\t\twhen mqtt_json_path = lower('treat_gen_warning_alarm') then '(' || yard_tag || ')'\r\n\t\t\t\t\t\t\telse null\r\n\t\t\t\t\tend) AS treatment_general_warning_alarm_tag,\r\n\t\t\tmax(case\r\n\t\t\t\t\t\t\twhen mqtt_json_path = lower('sewage_treatment_plant_general_alarm') then '(' || yard_tag || ')'\r\n\t\t\t\t\t\t\telse null\r\n\t\t\t\t\tend) AS treatment_general_alarm_tag\r\nfrom marpower__io_metadata\r\nwhere mqtt_topic = 'marpower/340000-sewage';"
    }
   ]
  },
  {
   "title": "Status",
   "type": "canvas",
   "gridPos": { "h": 7, "w": 17, "x": 7, "y": 3 },
   "targets": [
    {
     "dataset": "dev",
     "rawSql": "select timestamp as time,\r\n\t\t\tpump_fwd_grey_wat_remavail__value AS fwd_pump_grey_remavail,\r\n\t\t\tpump_fwd_grey_wat_running__value AS fwd_pump_grey_running,\r\n\t\t\ttrans_pump_grey_wat_remavail__value AS trans_pump_grey_remavail,\r\n\t\t\ttrans_pump_grey_wat_running__value AS trans_pump_grey_running,\r\n\t\t\ttrans_pump_blck_wat_remavail__value AS trans_pump_black_remavail,\r\n\t\t\ttrans_pump_blck_wat_running__value AS trans_pump_black_running,\r\n\t\t\tsewage_treatment_plant_on__value AS treatment_on,\r\n\t\t\ttreat_release__value AS treatment_release,\r\n\t\t\ttreat_dryrunnprot__value AS treatment_dry_run_protection\r\nfrom marpower__340000_sewage\r\nORDER BY timestamp DESC\r\nLIMIT 1;"
    },
    {
     "dataset": "dev",
     "rawSql": "select max(case\r\n\t\t\t\t\t\t\twhen mqtt_json_path = lower('pump_fwd_grey_wat_remavail') then '(' || yard_tag || ')'\r\n\t\t\t\t\t\t\telse null\r\n\t\t\t\t\tend) AS fwd_pump_grey_remavail_tag,\r\n\t\t\tmax(case\r\n\t\t\t\t\t\t\twhen mqtt_json_path = lower('pump_fwd_grey_wat_running') then '(' || yard_tag || ')'\r\n\t\t\t\t\t\t\telse null\r\n\t\t\t\t\tend) AS fwd_pump_grey_running_tag,\r\n\t\t\tmax(case\r\n\t\t\t\t\t\t\twhen mqtt_json_path = lower('trans_pump_grey_wat_remavail') then '(' || yard_tag || ')'\r\n\t\t\t\t\t\t\telse null\r\n\t\t\t\t\tend) AS trans_pump_grey_remavail_tag,\r\n\t\t\tmax(case\r\n\t\t\t\t\t\t\twhen mqtt_json_path = lower('trans_pump_grey_wat_running') then '(' || yard_tag || ')'\r\n\t\t\t\t\t\t\telse null\r\n\t\t\t\t\tend) AS trans_pump_grey_running_tag,\r\n\t\t\tmax(case\r\n\t\t\t\t\t\t\twhen mqtt_json_path = lower('trans_pump_blck_wat_remavail') then '(' || yard_tag || ')'\r\n\t\t\t\t\t\t\telse null\r\n\t\t\t\t\tend) AS trans_pump_black_remavail_tag,\r\n\t\t\tmax(case\r\n\t\t\t\t\t\t\twhen mqtt_json_path = lower('trans_pump_blck_wat_running') then '(' || yard_tag || ')'\r\n\t\t\t\t\t\t\telse null\r\n\t\t\t\t\tend) AS trans_pump_black_running_tag,\r\n\t\t\tmax(case\r\n\t\t\t\t\t\t\twhen mqtt_json_path = lower('sewage_treatment_plant_on') then '(' || yard_tag || ')'\r\n\t\t\t\t\t\t\telse null\r\n\t\t\t\t\tend) AS treatment_on_tag,\r\n\t\t\tmax(case\r\n\t\t\t\t\t\t\twhen mqtt_json_path = lower('treat_release') then '(' || yard_tag || ')'\r\n\t\t\t\t\t\t\telse null\r\n\t\t\t\t\tend) AS treatment_release_tag,\r\n\t\t\tmax(case\r\n\t\t\t\t\t\t\twhen mqtt_json_path = lower('treat_dryrunnprot') then '(' || yard_tag || ')'\r\n\t\t\t\t\t\t\telse null\r\n\t\t\t\t\tend) AS treatment_dry_run_protection_tag\r\nfrom marpower__io_metadata\r\nwhere mqtt_topic = 'marpower/340000-sewage';"
    }
   ]
  },
  {
   "title": "Control signals",
   "type": "canvas",
   "gridPos": { "h": 4, "w": 7, "x": 0, "y": 6 },
   "targets": [
    {
     "dataset": "dev",
     "rawSql": "select timestamp as time,\r\n\t\t\tpump_fwd_grey_wat_startstop__value AS grey_wat_fwd_pump_startstop,\r\n\t\t\ttrans_pump_grey_wat_startstop__value AS grey_wat_transfer_pump_startstop,\r\n\t\t\ttrans_pump_blck_wat_startstop__value AS black_wat_transfer_pump_startstop\r\nfrom marpower__340000_sewage\r\nORDER BY timestamp DESC\r\nLIMIT 1;"
    },
    {
     "dataset": "dev",
     "rawSql": "select max(case\r\n\t\t\t\t\t\t\twhen mqtt_json_path = lower('pump_fwd_grey_wat_startstop') then '(' || yard_tag || ')'\r\n\t\t\t\t\t\t\telse null\r\n\t\t\t\t\tend) AS grey_wat_fwd_pump_startstop_tag,\r\n\t\t\tmax(case\r\n\t\t\t\t\t\t\twhen mqtt_json_path = lower('trans_pump_grey_wat_startstop') then '(' || yard_tag || ')'\r\n\t\t\t\t\t\t\telse null\r\n\t\t\t\t\tend) AS grey_wat_transfer_pump_startstop_tag,\r\n\t\t\tmax(case\r\n\t\t\t\t\t\t\twhen mqtt_json_path = lower('trans_pump_blck_wat_startstop') then '(' || yard_tag || ')'\r\n\t\t\t\t\t\t\telse null\r\n\t\t\t\t\tend) AS black_wat_transfer_pump_startstop_tag\r\nfrom marpower__io_metadata\r\nwhere mqtt_topic = 'marpower/340000-sewage';"
    }
   ]
  },
  {
   "title": "Tank levels",
   "type": "canvas",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "mamp" } },
   "targets": [
    {
     "dataset": "dev",
     "rawSql": "select timestamp as time,\r\n\t\t\tgrey_water_tank_aft_sb_level__value AS grey_wat_aft_tank,\r\n\t\t\tgrey_water_tank_fwd_sb_level__value AS grey_wat_fwd_tank,\r\n\t\t\tblack_grey_water_tank_aft_ps_level__value AS black_wat_aft_tank,\r\n\t\t\ttreat_holding_tank_level__value AS treatment_holding_tank,\r\n\t\t\ttreat_sludge_tank_level__value AS treatment_sludge_tank,\r\n\t\t\tsludge_tank_ps_level__value AS sludge_tank\r\nfrom marpower__340000_sewage\r\nORDER BY timestamp DESC\r\nLIMIT 1;"
    },
    {
     "dataset": "dev",
     "rawSql": "select max(case\r\n\t\t\t\t\t\t\twhen mqtt_json_path = lower('grey_water_tank_aft_sb_level') then '(' || yard_tag || ')'\r\n\t\t\t\t\t\t\telse null\r\n\t\t\t\t\tend) AS grey_wat_aft_tank_tag,\r\n\t\t\tmax(case\r\n\t\t\t\t\t\t\twhen mqtt_json_path = lower('grey_water_tank_fwd_sb_level') then '(' || yard_tag || ')'\r\n\t\t\t\t\t\t\telse null\r\n\t\t\t\t\tend) AS grey_wat_fwd_tank_tag,\r\n\t\t\tmax(case\r\n\t\t\t\t\t\t\twhen mqtt_json_path = lower('black_grey_water_tank_aft_ps_level') then '(' || yard_tag || ')'\r\n\t\t\t\t\t\t\telse null\r\n\t\t\t\t\tend) AS black_wat_aft_tank_tag,\r\n\t\t\tmax(case\r\n\t\t\t\t\t\t\twhen mqtt_json_path = lower('treat_holding_tank_level') then '(' || yard_tag || ')'\r\n\t\t\t\t\t\t\telse null\r\n\t\t\t\t\tend) AS treatment_holding_tank_tag,\r\n\t\t\tmax(case\r\n\t\t\t\t\t\t\twhen mqtt_json_path = lower('treat_sludge_tank_level') then '(' || yard_tag || ')'\r\n\t\t\t\t\t\t\telse null\r\n\t\t\t\t\tend) AS treatment_sludge_tank_tag,\r\n\t\t\tmax(case\r\n\t\t\t\t\t\t\twhen mqtt_json_path = lower('sludge_tank_ps_level') then '(' || yard_tag || ')'\r\n\t\t\t\t\t\t\telse null\r\n\t\t\t\t\tend) AS sludge_tank_tag\r\nfrom marpower__io_metadata\r\nwhere mqtt_topic = 'marpower/340000-sewage';"
    }
   ]
  },
  {
   "title": "Historical",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 15 },
   "collapsed": true,
   "panels": [
    {
     "title": "Alarm history",
     "type": "status-history",
     "gridPos": { "h": 4, "w": 24, "x": 0, "y": 16 },
     "targets": [
      {
       "dataset": "dev",
       "rawSql": "SELECT timestamp as time,\r\n\t\t\ttreat_gen_warning_alarm__value AS treat_gen_warning_alarm,\r\n\t\t\tsewage_treatment_plant_general_alarm__value AS treat_gen_alarm\r\nFROM marpower__340000_sewage\r\nWHERE $__timeFilter(timestamp)\r\nORDER BY timestamp DESC"
      }
     ]
    },
    {
     "title": "Status history",
     "type": "status-history",
     "gridPos": { "h": 10, "w": 24, "x": 0, "y": 20 },
     "targets": [
      {
       "dataset": "dev",
       "rawSql": "SELECT timestamp as time,\r\n\t\t\tpump_fwd_grey_wat_remavail__value AS fwd_pump_grey_wat_remavail,\r\n\t\t\tpump_fwd_grey_wat_running__value AS fwd_pump_grey_wat_running,\r\n\t\t\ttrans_pump_grey_wat_remavail__value AS trans_pump_grey_wat_remavail,\r\n\t\t\ttrans_pump_grey_wat_running__value AS trans_pump_grey_wat_running,\r\n\t\t\ttrans_pump_blck_wat_remavail__value AS trans_pump_black_wat_remavail,\r\n\t\t\ttrans_pump_blck_wat_running__value AS trans_pump_black_wat_running,\r\n\t\t\tsewage_treatment_plant_on__value AS treatment_on,\r\n\t\t\ttreat_release__value AS treatment_release,\r\n\t\t\ttreat_dryrunnprot__value AS treatment_dry_run_protect\r\nFROM marpower__340000_sewage\r\nWHERE $__timeFilter(timestamp)\r\nORDER BY timestamp DESC"
      }
     ]
    },
    {
     "title": "Control signal history",
     "type": "status-history",
     "gridPos": { "h": 5, "w": 24, "x": 0, "y": 30 },
     "targets": [
      {
       "dataset": "dev",
       "rawSql": "SELECT timestamp as time,\r\n\t\t\tpump_fwd_grey_wat_startstop__value AS fwr_pump_grey_wat_start,\r\n\t\t\ttrans_pump_grey_wat_startstop__value AS trans_pump_grey_wat_start,\r\n\t\t\ttrans_pump_blck_wat_startstop__value AS trans_pump_black_wat_start\r\nFROM marpower__340000_sewage\r\nWHERE $__timeFilter(timestamp)\r\nORDER BY timestamp DESC"
      }
     ]
    },
    {
     "title": "Grey/Black water tank level",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 35 },
     "fieldConfig": { "defaults": { "unit": "mamp" } },
     "targets": [
      {
       "dataset": "dev",
       "rawSql": "SELECT timestamp as time,\r\n\t\t\tgrey_water_tank_aft_sb_level__value as grey_wat_aft_tank,\r\n\t\t\tgrey_water_tank_fwd_sb_level__value as grey_wat_fwd_tank,\r\n\t\t\tblack_grey_water_tank_aft_ps_level__value as black_wat_aft_tank\r\nFROM marpower__340000_sewage\r\nWHERE $__timeFilter(timestamp)\r\nORDER BY timestamp DESC"
      }
     ]
    },
    {
     "title": "Treatment plant tank level",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 42 },
     "fieldConfig": { "defaults": { "unit": "mamp" } },
     "targets": [
      {
       "dataset": "dev",
       "rawSql": "SELECT timestamp as time,\r\n\t\t\ttreat_holding_tank_level__value as treatment_holding_tank,\r\n\t\t\ttreat_sludge_tank_level__value as treatment_sludge_tank\r\nFROM marpower__340000_sewage\r\nWHERE $__timeFilter(timestamp)\r\nORDER BY timestamp DESC"
      }
     ]
    },
    {
     "title": "Sludge tank level",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 49 },
     "fieldConfig": { "defaults": { "unit": "mamp" } },
     "targets": [
      {
       "dataset": "dev",
       "rawSql": "SELECT timestamp as time,\r\n\t\t\tsludge_tank_ps_level__value as sludge_tank\r\nFROM marpower__340000_sewage\r\nWHERE $__timeFilter(timestamp)\r\nORDER BY timestamp DESC"
      }
     ]
    }
   ]
  }
 ]
}