{
 "title": "Grey & black water",
 "tags": [ "commisssioning" ],
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "datasource", "query": "grafana-postgresql-datasource" }
  ]
 },
 "panels": [
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 0 },
   "options": {
    "content": "<center>\r\n  <h1>Grey & Black water</h1>\r\n</center>\r\n"
   }
  },
  { "title": "General", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 } },
  {
   "title": "Alarms",
   "type": "canvas",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 3 },
   "targets": [
    {
     "dataset": "dev",
     "rawSql": "SELECT\r\n  LAST_VALUE(time ORDER BY time) AS time,\r\n  LAST_VALUE((\"TREAT_GEN_WARNING_ALARM\").value ORDER BY time) AS treatment_general_warning_alarm,\r\n  LAST_VALUE((\"SEWAGE_TREATMENT_PLANT_GENERAL_ALARM\").value ORDER BY time) AS treatment_general_alarm\r\nFROM marpower.\"340000_sewage\""
    }
   ]
  },
  {
   "title": "Status",
   "type": "canvas",
   "gridPos": { "h": 7, "w": 13, "x": 6, "y": 3 },
   "targets": [
    {
     "dataset": "dev",
     "rawSql": "SELECT\r\n  LAST_VALUE(time ORDER BY time) AS time,\r\n  LAST_VALUE((\"PUMP_FWD_GREY_WAT_REMAVAIL\").value ORDER BY time)   AS fwd_pump_grey_remavail,\r\n  LAST_VALUE((\"PUMP_FWD_GREY_WAT_RUNNING\").value ORDER BY time)    AS fwd_pump_grey_running,\r\n  LAST_VALUE((\"TRANS_PUMP_GREY_WAT_REMAVAIL\").value ORDER BY time) AS trans_pump_grey_remavail,\r\n  LAST_VALUE((\"TRANS_PUMP_GREY_WAT_RUNNING\").value ORDER BY time)  AS trans_pump_grey_running,\r\n  LAST_VALUE((\"TRANS_PUMP_BLCK_WAT_REMAVAIL\").value ORDER BY time) AS trans_pump_black_remavail,\r\n  LAST_VALUE((\"TRANS_PUMP_BLCK_WAT_RUNNING\").value ORDER BY time)  AS trans_pump_black_running,\r\n  LAST_VALUE((\"SEWAGE_TREATMENT_PLANT_ON\").value ORDER BY time)    AS treatment_on,\r\n  LAST_VALUE((\"TREAT_RELEASE\").value ORDER BY time)                AS treatment_release,\r\n  LAST_VALUE((\"TREAT_DRYRUNNPROT\").value ORDER BY time)            AS treatment_dry_run_protection\r\nFROM marpower.\"340000_sewage\""
    }
   ]
  },
  {
   "title": "Control signals",
   "type": "canvas",
   "gridPos": { "h": 7, "w": 5, "x": 19, "y": 3 },
   "targets": [
    {
     "dataset": "dev",
     "rawSql": "SELECT\r\n  LAST_VALUE(time ORDER BY time) AS time,\r\n  LAST_VALUE((\"PUMP_FWD_GREY_WAT_STARTSTOP\").value ORDER BY time) AS grey_wat_fwd_pump_startstop,\r\n  LAST_VALUE((\"TRANS_PUMP_GREY_WAT_STARTSTOP\").value ORDER BY time) AS grey_wat_transfer_pump_startstop,\r\n  LAST_VALUE((\"TRANS_PUMP_BLCK_WAT_STARTSTOP\").value ORDER BY time) AS black_wat_transfer_pump_startstop\r\nFROM marpower.\"340000_sewage\""
    }
   ]
  },
  {
   "title": "Tank levels",
   "type": "canvas",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "dataset": "dev",
     "rawSql": "SELECT\r\n  LAST_VALUE(time ORDER BY time) AS time,\r\n  LAST_VALUE((\"GREY_WATER_TANK_AFT_SB_LEVEL\").value ORDER BY time)       AS grey_wat_aft_tank,\r\n  LAST_VALUE((\"GREY_WATER_TANK_FWD_SB_LEVEL\").value ORDER BY time)       AS grey_wat_fwd_tank,\r\n  LAST_VALUE((\"BLACK_GREY_WATER_TANK_AFT_PS_LEVEL\").value ORDER BY time) AS black_wat_aft_tank,\r\n  LAST_VALUE((\"TREAT_HOLDING_TANK_LEVEL\").value ORDER BY time)           AS treatment_holding_tank,\r\n  LAST_VALUE((\"TREAT_SLUDGE_TANK_LEVEL\").value ORDER BY time)            AS treatment_sludge_tank,\r\n  LAST_VALUE((\"SLUDGE_TANK_PS_LEVEL\").value ORDER BY time)               AS sludge_tank\r\nFROM marpower.\"340000_sewage\""
    }
   ]
  },
  {
   "title": "Historical",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 15 },
   "collapsed": true,
   "panels": [
    {
     "title": "Alarm history",
     "type": "status-history",
     "gridPos": { "h": 4, "w": 24, "x": 0, "y": 14 },
     "targets": [
      {
       "dataset": "dev",
       "rawSql": "SELECT\r\n  time,\r\n  (\"TREAT_GEN_WARNING_ALARM\").value AS treat_gen_warning_alarm,\r\n  (\"SEWAGE_TREATMENT_PLANT_GENERAL_ALARM\").value AS treat_gen_alarm\r\nFROM marpower.\"340000_sewage\"\r\nWHERE $__timeFilter(time)"
      }
     ]
    },
    {
     "title": "Status history",
     "type": "status-history",
     "gridPos": { "h": 10, "w": 24, "x": 0, "y": 18 },
     "targets": [
      {
       "dataset": "dev",
       "rawSql": "SELECT\r\n  time,\r\n  (\"PUMP_FWD_GREY_WAT_REMAVAIL\").value AS fwd_pump_grey_wat_remavail,\r\n  (\"PUMP_FWD_GREY_WAT_RUNNING\").value AS fwd_pump_grey_wat_running,\r\n  (\"TRANS_PUMP_GREY_WAT_REMAVAIL\").value AS trans_pump_grey_wat_remavail,\r\n  (\"TRANS_PUMP_GREY_WAT_RUNNING\").value AS trans_pump_grey_wat_running,\r\n  (\"TRANS_PUMP_BLCK_WAT_REMAVAIL\").value AS trans_pump_black_wat_remavail,\r\n  (\"TRANS_PUMP_BLCK_WAT_RUNNING\").value AS trans_pump_black_wat_running,\r\n  (\"SEWAGE_TREATMENT_PLANT_ON\").value AS treatment_on,\r\n  (\"TREAT_RELEASE\").value AS treatment_release,\r\n  (\"TREAT_DRYRUNNPROT\").value AS treatment_dry_run_protect\r\nFROM marpower.\"340000_sewage\"\r\nWHERE $__timeFilter(time)"
      }
     ]
    },
    {
     "title": "Control signal history",
     "type": "status-history",
     "gridPos": { "h": 5, "w": 24, "x": 0, "y": 28 },
     "targets": [
      {
       "dataset": "dev",
       "rawSql": "SELECT\r\n  time,\r\n  (\"PUMP_FWD_GREY_WAT_STARTSTOP\").value AS fwr_pump_grey_wat_start,\r\n  (\"TRANS_PUMP_GREY_WAT_STARTSTOP\").value AS trans_pump_grey_wat_start,\r\n  (\"TRANS_PUMP_BLCK_WAT_STARTSTOP\").value AS trans_pump_black_wat_start\r\nFROM marpower.\"340000_sewage\"\r\nWHERE $__timeFilter(time)"
      }
     ]
    },
    {
     "title": "Grey/Black water tank level",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 33 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "dataset": "dev",
       "rawSql": "SELECT\r\n  time,\r\n  (\"GREY_WATER_TANK_AFT_SB_LEVEL\").value as grey_wat_aft_tank,\r\n  (\"GREY_WATER_TANK_FWD_SB_LEVEL\").value as grey_wat_fwd_tank,\r\n  (\"BLACK_GREY_WATER_TANK_AFT_PS_LEVEL\").value as black_wat_aft_tank\r\nFROM marpower.\"340000_sewage\""
      }
     ]
    },
    {
     "title": "Treatment plant tank level",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 40 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "dataset": "dev",
       "rawSql": "SELECT\r\n  time,\r\n  (\"TREAT_HOLDING_TANK_LEVEL\").value as treatment_holding_tank,\r\n  (\"TREAT_SLUDGE_TANK_LEVEL\").value as treatment_sludge_tank\r\nFROM marpower.\"340000_sewage\""
      }
     ]
    },
    {
     "title": "Sludge tank level",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 47 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "dataset": "dev",
       "rawSql": "SELECT\r\n  time,\r\n  (\"SLUDGE_TANK_PS_LEVEL\").value as sludge_tank\r\nFROM marpower.\"340000_sewage\""
      }
     ]
    }
   ]
  }
 ]
}