{
 "title": "Hull temperatures",
 "tags": [ "commissioning" ],
 "time": { "from": "now-5m", "to": "now" },
 "panels": [
  {
   "title": "Below water temperatures",
   "type": "canvas",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "rawSql": "SELECT\r\n    timestamp                   AS time,\r\n    \"temperatures__94455001-46\" AS temp_46,\r\n    \"temperatures__94455001-45\" AS temp_45,\r\n    \"temperatures__94455001-44\" AS temp_44,\r\n    \"temperatures__94455001-43\" AS temp_43,\r\n    \"temperatures__94455001-42\" AS temp_42,\r\n    \"temperatures__94455001-41\" AS temp_41,\r\n    \"temperatures__94455001-40\" AS temp_40,\r\n    \"temperatures__94455001-39\" AS temp_39,\r\n    \"temperatures__94455001-38\" AS temp_38\r\nFROM public.hull_temperature__temperatures\r\nWHERE $__timeFilter(timestamp)\r\nORDER BY timestamp DESC\r\nLIMIT 1;"
    }
   ]
  },
  {
   "title": "Above water temperatures",
   "type": "canvas",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "rawSql": "SELECT\r\n    timestamp                   AS time, \r\n    \"temperatures__94455001-30\" AS temp_30,\r\n    \"temperatures__94455001-31\" AS temp_31,\r\n    \"temperatures__94455001-26\" AS temp_26,\r\n    \"temperatures__94455001-27\" AS temp_27,\r\n    \"temperatures__94455001-20\" AS temp_20,\r\n    \"temperatures__94455001-21\" AS temp_21,\r\n    \"temperatures__94455001-16\" AS temp_16,\r\n    \"temperatures__94455001-17\" AS temp_17,\r\n    \"temperatures__94455001-12\" AS temp_12,\r\n    \"temperatures__94455001-13\" AS temp_13,\r\n    \"temperatures__94455001-6\" AS temp_6,\r\n    \"temperatures__94455001-7\" AS temp_7,\r\n    \"temperatures__94455001-4\" AS temp_4,\r\n    \"temperatures__94455001-5\" AS temp_5,\r\n    \"temperatures__94455001-2\" AS temp_2,\r\n    \"temperatures__94455001-3\" AS temp_3\r\nFROM public.hull_temperature__temperatures\r\nWHERE $__timeFilter(timestamp)\r\nORDER BY timestamp DESC\r\nLIMIT 1;"
    }
   ]
  },
  {
   "title": "Deck temperatures",
   "type": "canvas",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "rawSql": "SELECT\r\n    timestamp                   AS time, \r\n    \"temperatures__94455001-35\" AS temp_35,\r\n    \"temperatures__94455001-34\" AS temp_34,\r\n    \"temperatures__94455001-32\" AS temp_32,\r\n    \"temperatures__94455001-33\" AS temp_33,\r\n    \"temperatures__94455001-28\" AS temp_28,\r\n    \"temperatures__94455001-29\" AS temp_29,\r\n    \"temperatures__94455001-24\" AS temp_24,\r\n    \"temperatures__94455001-25\" AS temp_25,\r\n    \"temperatures__94455001-36\" AS temp_36,\r\n    \"temperatures__94455001-37\" AS temp_37,\r\n    \"temperatures__94455001-22\" AS temp_22,\r\n    \"temperatures__94455001-23\" AS temp_23,\r\n    \"temperatures__94455001-18\" AS temp_18,\r\n    \"temperatures__94455001-19\" AS temp_19,\r\n    \"temperatures__94455001-14\" AS temp_14,\r\n    \"temperatures__94455001-15\" AS temp_15,\r\n    \"temperatures__94455001-8\" AS temp_8,\r\n    \"temperatures__94455001-9\" AS temp_9,\r\n    \"temperatures__94455001-10\" AS temp_10,\r\n    \"temperatures__94455001-11\" AS temp_11,\r\n    \"temperatures__94455001-1\" AS temp_1\r\nFROM public.hull_temperature__temperatures\r\nWHERE $__timeFilter(timestamp)\r\nORDER BY timestamp DESC\r\nLIMIT 1;"
    }
   ]
  }
 ]
}