{
 "title": "Propulsion Control System",
 "tags": [ "commisssioning" ],
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "datasource", "query": "grafana-postgresql-datasource" }
  ]
 },
 "panels": [
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 0 },
   "options": {
    "content": "<center>\r\n  <h1>Propulsion Control System</h1>\r\n</center>\r\n"
   }
  },
  {
   "title": "Alarms - AFT",
   "type": "canvas",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 2 },
   "targets": [
    {
     "dataset": "dev",
     "rawSql": "SELECT\r\n  LAST_VALUE(time ORDER BY time) AS time,\r\n  LAST_VALUE((\"CB_10_COMALARM\").value ORDER BY time)              AS communication_alarm,\r\n  LAST_VALUE((\"CB_10_24VDCSERVFAIL\").value ORDER BY time)         AS \"24v_service_failure\",\r\n  LAST_VALUE((\"CB_10_24VDCEMERGFAIL\").value ORDER BY time)        AS \"24v_emergency_failure\",\r\n  LAST_VALUE((\"CB_10_POWERDISTRINS\").value ORDER BY time)         AS power_distr_insul_alarm,\r\n  LAST_VALUE((\"CB_10_HYDRPRESSALARM\").value ORDER BY time)        AS hydraulic_pressure_alarm,\r\n  LAST_VALUE((\"CB_10_OILLEVALARMSEALTANK\").value ORDER BY time)   AS seal_tank_oil_level_alarm,\r\n  LAST_VALUE((\"CB_10_GEAROILLEVALARM\").value ORDER BY time)       AS gear_oil_level_alarm,\r\n  LAST_VALUE((\"CB_10_GEAROILTEMPALARM\").value ORDER BY time)      AS gear_oil_temp_alarm,\r\n  LAST_VALUE((\"CB_10_OVERSPEEDALARM\").value ORDER BY time)        AS overspeed_alarm,\r\n  LAST_VALUE((\"CB_10_OVERLOADALARM\").value ORDER BY time)         AS overload_alarm,\r\n  LAST_VALUE((\"CB_10_AZIFOLLUPFAILALARM\").value ORDER BY time)    AS azimuth_follow_up_alarm,\r\n  LAST_VALUE((\"CB_10_PITCHFOLLUPFAILALARM\").value ORDER BY time)  AS pitch_follow_up_alarm\r\nFROM marpower.\"150000_pcs\""
    },
    {
     "dataset": "dev",
     "rawSql": "SELECT\r\n  LAST_VALUE(time ORDER BY time) AS time,\r\n  LAST_VALUE((\"AFT_THRUSTER_WATERLEAKALARM\").value ORDER BY time) AS water_leak_alarm\r\nFROM marpower.\"150000_propulsion_general\""
    },
    {
     "dataset": "dev",
     "rawSql": "SELECT\r\n  LAST_VALUE(time ORDER BY time) AS time,\r\n  LAST_VALUE((\"NAMURFAULT\").value ORDER BY time)    AS e_stop_namur_fault_aradex_1\r\nFROM marpower.\"150000_propulsion\"\r\nWHERE topic = 'marpower/150000-propulsion/aft-ara1-pcs'"
    },
    {
     "dataset": "dev",
     "rawSql": "SELECT\r\n  LAST_VALUE(time ORDER BY time) AS time,\r\n  LAST_VALUE((\"NAMURFAULT\").value ORDER BY time)    AS e_stop_namur_fault_aradex_2\r\nFROM marpower.\"150000_propulsion\"\r\nWHERE topic = 'marpower/150000-propulsion/aft-ara2-pcs'"
    }
   ]
  },
  {
   "title": "Alarms - FWD",
   "type": "canvas",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 2 },
   "targets": [
    {
     "dataset": "dev",
     "rawSql": "SELECT\r\n  LAST_VALUE(time ORDER BY time) AS time,\r\n  LAST_VALUE((\"CB_11_COMALARM\").value ORDER BY time)              AS communication_alarm,\r\n  LAST_VALUE((\"CB_11_24VDCSERVFAIL\").value ORDER BY time)         AS \"24v_service_failure\",\r\n  LAST_VALUE((\"CB_11_24VDCEMERGFAIL\").value ORDER BY time)        AS \"24v_emergency_failure\",\r\n  LAST_VALUE((\"CB_11_POWERDISTRINS\").value ORDER BY time)         AS power_distr_insul_alarm,\r\n  LAST_VALUE((\"CB_11_HYDRPRESSALARM\").value ORDER BY time)        AS hydraulic_pressure_alarm,\r\n  LAST_VALUE((\"CB_11_OILLEVALARMSEALTANK\").value ORDER BY time)   AS seal_tank_oil_level_alarm,\r\n  LAST_VALUE((\"CB_11_GEAROILLEVALARM\").value ORDER BY time)       AS gear_oil_level_alarm,\r\n  LAST_VALUE((\"CB_11_GEAROILTEMPALARM\").value ORDER BY time)      AS gear_oil_temp_alarm,\r\n  LAST_VALUE((\"CB_11_OVERSPALARM\").value ORDER BY time)        AS overspeed_alarm,\r\n  LAST_VALUE((\"CB_11_OVERLALARM\").value ORDER BY time)         AS overload_alarm,\r\n  LAST_VALUE((\"CB_11_AZIFOLLUPFAILALARM\").value ORDER BY time)    AS azimuth_follow_up_alarm,\r\n  LAST_VALUE((\"CB_11_PITCHFOLLUPFAILALARM\").value ORDER BY time)  AS pitch_follow_up_alarm\r\nFROM marpower.\"150000_pcs\""
    },
    {
     "dataset": "dev",
     "rawSql": "SELECT\r\n  LAST_VALUE(time ORDER BY time) AS time,\r\n  LAST_VALUE((\"FWD_THRUSTER_WATERLEAKALARM\").value ORDER BY time) AS water_leak_alarm\r\nFROM marpower.\"150000_propulsion_general\""
    },
    {
     "dataset": "dev",
     "rawSql": "SELECT\r\n  LAST_VALUE(time ORDER BY time) AS time,\r\n  LAST_VALUE((\"NAMURFAULT\").value ORDER BY time)    AS e_stop_namur_fault_aradex_1\r\nFROM marpower.\"150000_propulsion\"\r\nWHERE topic = 'marpower/150000-propulsion/fwd-ara1-pcs'"
    },
    {
     "dataset": "dev",
     "rawSql": "SELECT\r\n  LAST_VALUE(time ORDER BY time) AS time,\r\n  LAST_VALUE((\"NAMURFAULT\").value ORDER BY time)    AS e_stop_namur_fault_aradex_2\r\nFROM marpower.\"150000_propulsion\"\r\nWHERE topic = 'marpower/150000-propulsion/fwd-ara2-pcs'"
    }
   ]
  },
  {
   "title": "Status - AFT",
   "type": "canvas",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 10 },
   "targets": [
    {
     "dataset": "dev",
     "rawSql": "SELECT\r\n  LAST_VALUE(time ORDER BY time) AS time,\r\n  LAST_VALUE((\"STARTCOMM\").value ORDER BY time)     AS ara1_start_command,\r\n  LAST_VALUE((\"STOPCOMM\").value ORDER BY time)      AS ara1_stop_command,\r\n  LAST_VALUE((\"RESETCOMM\").value ORDER BY time)     AS ara1_reset_command,\r\n  LAST_VALUE((\"EMSTOPACT\").value ORDER BY time)     AS ara1_e_stop_active,\r\n  LAST_VALUE((\"SECTHRSEL\").value ORDER BY time)     AS ara1_secundary_throttle_signal_selected,\r\n  LAST_VALUE((\"SHAFTBRAKEENG\").value ORDER BY time) AS ara1_shaft_brake_engaged\r\nFROM marpower.\"150000_propulsion\"\r\nWHERE topic = 'marpower/150000-propulsion/aft-ara1-pcs'"
    },
    {
     "dataset": "dev",
     "rawSql": "SELECT\r\n  LAST_VALUE(time ORDER BY time) AS time,\r\n  LAST_VALUE((\"STARTCOMM\").value ORDER BY time)     AS ara2_start_command,\r\n  LAST_VALUE((\"STOPCOMM\").value ORDER BY time)      AS ara2_stop_command,\r\n  LAST_VALUE((\"RESETCOMM\").value ORDER BY time)     AS ara2_reset_command,\r\n  LAST_VALUE((\"EMSTOPACT\").value ORDER BY time)     AS ara2_e_stop_active,\r\n  LAST_VALUE((\"SECTHRSEL\").value ORDER BY time)     AS ara2_secundary_throttle_signal_selected,\r\n  LAST_VALUE((\"SHAFTBRAKEENG\").value ORDER BY time) AS ara2_shaft_brake_engaged\r\nFROM marpower.\"150000_propulsion\"\r\nWHERE topic = 'marpower/150000-propulsion/aft-ara2-pcs'"
    }
   ]
  },
  {
   "title": "Status - FWD",
   "type": "canvas",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 10 },
   "targets": [
    {
     "dataset": "dev",
     "rawSql": "SELECT\r\n  LAST_VALUE(time ORDER BY time) AS time,\r\n  LAST_VALUE((\"STARTCOMM\").value ORDER BY time)     AS ara1_start_command,\r\n  LAST_VALUE((\"STOPCOMM\").value ORDER BY time)      AS ara1_stop_command,\r\n  LAST_VALUE((\"RESETCOMM\").value ORDER BY time)     AS ara1_reset_command,\r\n  LAST_VALUE((\"EMSTOPACT\").value ORDER BY time)     AS ara1_e_stop_active,\r\n  LAST_VALUE((\"SECTHRSEL\").value ORDER BY time)     AS ara1_secundary_throttle_signal_selected,\r\n  LAST_VALUE((\"SHAFTBRAKEENG\").value ORDER BY time) AS ara1_shaft_brake_engaged\r\nFROM marpower.\"150000_propulsion\"\r\nWHERE topic = 'marpower/150000-propulsion/fwd-ara1-pcs'"
    },
    {
     "dataset": "dev",
     "rawSql": "SELECT\r\n  LAST_VALUE(time ORDER BY time) AS time,\r\n  LAST_VALUE((\"STARTCOMM\").value ORDER BY time)     AS ara2_start_command,\r\n  LAST_VALUE((\"STOPCOMM\").value ORDER BY time)      AS ara2_stop_command,\r\n  LAST_VALUE((\"RESETCOMM\").value ORDER BY time)     AS ara2_reset_command,\r\n  LAST_VALUE((\"EMSTOPACT\").value ORDER BY time)     AS ara2_e_stop_active,\r\n  LAST_VALUE((\"SECTHRSEL\").value ORDER BY time)     AS ara2_secundary_throttle_signal_selected,\r\n  LAST_VALUE((\"SHAFTBRAKEENG\").value ORDER BY time) AS ara2_shaft_brake_engaged\r\nFROM marpower.\"150000_propulsion\"\r\nWHERE topic = 'marpower/150000-propulsion/fwd-ara2-pcs'"
    }
   ]
  },
  {
   "title": "Control signals - AFT",
   "type": "canvas",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 17 },
   "targets": [
    {
     "dataset": "dev",
     "rawSql": "SELECT\r\n  LAST_VALUE(time ORDER BY time) AS time,\r\n  LAST_VALUE((\"DRIVEREADYFDBCK\").value ORDER BY time)     AS ara1_drive_ready,\r\n  LAST_VALUE((\"DRIVERUNNINGFDBCK\").value ORDER BY time)   AS ara1_drive_running,\r\n  LAST_VALUE((\"DRIVEWARNFDBCK\").value ORDER BY time)      AS ara1_drive_warning,\r\n  LAST_VALUE((\"DRIVEFAILFDBCK\").value ORDER BY time)      AS ara1_drive_fail,\r\n  LAST_VALUE((\"DRIVEPWRREDUCEFDBCK\").value ORDER BY time) AS ara1_drive_power_reduce\r\nFROM marpower.\"150000_propulsion\"\r\nWHERE topic = 'marpower/150000-propulsion/aft-ara1-pcs'"
    },
    {
     "dataset": "dev",
     "rawSql": "SELECT\r\n  LAST_VALUE(time ORDER BY time) AS time,\r\n  LAST_VALUE((\"DRIVEREADYFDBCK\").value ORDER BY time)     AS ara2_drive_ready,\r\n  LAST_VALUE((\"DRIVERUNNINGFDBCK\").value ORDER BY time)   AS ara2_drive_running,\r\n  LAST_VALUE((\"DRIVEWARNFDBCK\").value ORDER BY time)      AS ara2_drive_warning,\r\n  LAST_VALUE((\"DRIVEFAILFDBCK\").value ORDER BY time)      AS ara2_drive_fail,\r\n  LAST_VALUE((\"DRIVEPWRREDUCEFDBCK\").value ORDER BY time) AS ara2_drive_power_reduce\r\nFROM marpower.\"150000_propulsion\"\r\nWHERE topic = 'marpower/150000-propulsion/aft-ara2-pcs'"
    },
    {
     "dataset": "dev",
     "rawSql": "SELECT\r\n  LAST_VALUE(time ORDER BY time) AS time,\r\n  LAST_VALUE((\"AFT_MOTOR_HEATINGONOFF\").value ORDER BY time) AS heating_on_off\r\nFROM marpower.\"150000_propulsion_general\""
    }
   ]
  },
  {
   "title": "Control signals - FWD",
   "type": "canvas",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 17 },
   "targets": [
    {
     "dataset": "dev",
     "rawSql": "SELECT\r\n  LAST_VALUE(time ORDER BY time) AS time,\r\n  LAST_VALUE((\"DRIVEREADYFDBCK\").value ORDER BY time)     AS ara1_drive_ready,\r\n  LAST_VALUE((\"DRIVERUNNINGFDBCK\").value ORDER BY time)   AS ara1_drive_running,\r\n  LAST_VALUE((\"DRIVEWARNFDBCK\").value ORDER BY time)      AS ara1_drive_warning,\r\n  LAST_VALUE((\"DRIVEFAILFDBCK\").value ORDER BY time)      AS ara1_drive_fail,\r\n  LAST_VALUE((\"DRIVEPWRREDUCEFDBCK\").value ORDER BY time) AS ara1_drive_power_reduce\r\nFROM marpower.\"150000_propulsion\"\r\nWHERE topic = 'marpower/150000-propulsion/fwd-ara1-pcs'"
    },
    {
     "dataset": "dev",
     "rawSql": "SELECT\r\n  LAST_VALUE(time ORDER BY time) AS time,\r\n  LAST_VALUE((\"DRIVEREADYFDBCK\").value ORDER BY time)     AS ara2_drive_ready,\r\n  LAST_VALUE((\"DRIVERUNNINGFDBCK\").value ORDER BY time)   AS ara2_drive_running,\r\n  LAST_VALUE((\"DRIVEWARNFDBCK\").value ORDER BY time)      AS ara2_drive_warning,\r\n  LAST_VALUE((\"DRIVEFAILFDBCK\").value ORDER BY time)      AS ara2_drive_fail,\r\n  LAST_VALUE((\"DRIVEPWRREDUCEFDBCK\").value ORDER BY time) AS ara2_drive_power_reduce\r\nFROM marpower.\"150000_propulsion\"\r\nWHERE topic = 'marpower/150000-propulsion/fwd-ara2-pcs'"
    },
    {
     "dataset": "dev",
     "rawSql": "SELECT\r\n  LAST_VALUE(time ORDER BY time) AS time,\r\n  LAST_VALUE((\"FWD_MOTOR_HEATINGONOFF\").value ORDER BY time) AS heating_on_off\r\nFROM marpower.\"150000_propulsion_general\""
    }
   ]
  },
  {
   "title": "Temperatures - AFT",
   "type": "canvas",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "dataset": "dev",
     "rawSql": "SELECT\r\n  LAST_VALUE(time ORDER BY time) AS time,\r\n  LAST_VALUE((\"AFT_THRUST_WINDINGTEMPU1\").value ORDER BY time)      AS winding_U1_temp,\r\n  LAST_VALUE((\"AFT_THRUST_WINDINGTEMPV1\").value ORDER BY time)      AS winding_V1_temp,\r\n  LAST_VALUE((\"AFT_THRUST_WINDINGTEMPW1\").value ORDER BY time)      AS winding_W1_temp,\r\n  LAST_VALUE((\"AFT_THRUST_VENTTEMP1\").value ORDER BY time)          AS ventilation1_temp,\r\n  LAST_VALUE((\"AFT_THRUST_WINDINGTEMPU2\").value ORDER BY time)      AS winding_U2_temp,\r\n  LAST_VALUE((\"AFT_THRUST_WINDINGTEMPV2\").value ORDER BY time)      AS winding_V2_temp,\r\n  LAST_VALUE((\"AFT_THRUST_WINDINGTEMPW2\").value ORDER BY time)      AS winding_W2_temp,\r\n  LAST_VALUE((\"AFT_THRUST_VENTTEMP2\").value ORDER BY time)          AS ventilation2_temp,\r\n  LAST_VALUE((\"STERN_THRUST_BEARING_DE_TEMP\").value ORDER BY time)  AS bearing_de_temp,\r\n  LAST_VALUE((\"STERN_THRUST_BEARING_NDE_TEMP\").value ORDER BY time) AS bearing_nde_temp\r\nFROM marpower.\"150000_propulsion_general\""
    }
   ]
  },
  {
   "title": "Temperatures - FWD",
   "type": "canvas",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "dataset": "dev",
     "rawSql": "SELECT\r\n  LAST_VALUE(time ORDER BY time) AS time,\r\n  LAST_VALUE((\"FWD_THRUST_WINDINGTEMPU1\").value ORDER BY time)      AS winding_U1_temp,\r\n  LAST_VALUE((\"FWD_THRUST_WINDINGTEMPV1\").value ORDER BY time)      AS winding_V1_temp,\r\n  LAST_VALUE((\"FWD_THRUST_WINDING_TEMP_W1\").value ORDER BY time)    AS winding_W1_temp,\r\n  LAST_VALUE((\"FWD_THRUST_VENTTEMP1\").value ORDER BY time)          AS ventilation1_temp,\r\n  LAST_VALUE((\"BOW_THRUST_WINDINGTEMPU2\").value ORDER BY time)      AS winding_U2_temp,\r\n  LAST_VALUE((\"BOW_THRUST_WINDINGTEMPV2\").value ORDER BY time)      AS winding_V2_temp,\r\n  LAST_VALUE((\"BOW_THRUST_WINDINGTEMPW2\").value ORDER BY time)      AS winding_W2_temp,\r\n  LAST_VALUE((\"FWD_THRUST_VENTTEMP2\").value ORDER BY time)          AS ventilation2_temp,\r\n  LAST_VALUE((\"BOW_THRUST_BEARING_DE_TEMP\").value ORDER BY time)    AS bearing_de_temp,\r\n  LAST_VALUE((\"BOW_THRUST_BEARING_NDE_TEMP\").value ORDER BY time)   AS bearing_nde_temp\r\nFROM marpower.\"150000_propulsion_general\""
    }
   ]
  }
 ]
}