{
 "title": "Propulsion Control System",
 "tags": [ "commissioning" ],
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "datasource", "query": "info8fcc-greptimedb-datasource" }
  ]
 },
 "panels": [
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 0 },
   "options": {
    "content": "<center>\r\n  <h1>Propulsion Control System</h1>\r\n</center>\r\n"
   }
  },
  { "title": "Alarms", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 } },
  {
   "title": "AFT",
   "type": "canvas",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 3 },
   "targets": [
    {
     "dataset": "dev",
     "rawSql": "SELECT\r\n  timestamp,\r\n  comalarm__value                                  AS communication_alarm,\r\n  \"24_vdcservfail__value\"                          AS \"24v_service_failure\",\r\n  \"24_vdcemergfail__value\"                         AS \"24v_emergency_failure\",\r\n  waterleakalarm__value                            AS water_leak_alarm,\r\n  em_stop_main_power_fail__value                   AS em_stop_main_power_failure,\r\n  hydr_aft_return_press_filter_alarm__value        AS hydr_aft_return_press_filter_alarm,\r\n  hydr_filter_water_alarm__value                   AS hydr_filter_water_alarm,\r\n  hydr_pump_freq_drive_temp_alarm__value           AS hydr_pump_freq_drive_temp_alarm,\r\n  hydr_tank_temp_alarm__value                      AS hydr_tank_temp_alarm,\r\n  level_alarm_gravity_tank_shaftseal_system__value AS level_alarm_gravity_tank_shaftseal_system\r\nFROM public.marpower__150000_propulsion__pcs_aft\r\nWHERE $__timeFilter(timestamp)\r\nORDER BY timestamp\r\nDESC LIMIT 1"
    }
   ]
  },
  {
   "title": "FWD",
   "type": "canvas",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 3 },
   "targets": [
    {
     "dataset": "dev",
     "rawSql": "SELECT\r\n  timestamp,\r\n  comalarm__value                                  AS communication_alarm,\r\n  \"24_vdcservfail__value\"                          AS \"24v_service_failure\",\r\n  \"24_vdcemergfail__value\"                         AS \"24v_emergency_failure\",\r\n  waterleakalarm__value                            AS water_leak_alarm,\r\n  em_stop_main_power_fail__value                   AS em_stop_main_power_failure,\r\n  hydr_aft_return_press_filter_alarm__value        AS hydr_aft_return_press_filter_alarm,\r\n  hydr_filter_water_alarm__value                   AS hydr_filter_water_alarm,\r\n  hydr_pump_freq_drive_temp_alarm__value           AS hydr_pump_freq_drive_temp_alarm,\r\n  hydr_tank_temp_alarm__value                      AS hydr_tank_temp_alarm,\r\n  level_alarm_gravity_tank_shaftseal_system__value AS level_alarm_gravity_tank_shaftseal_system\r\nFROM public.marpower__150000_propulsion__pcs_fwd\r\nWHERE $__timeFilter(timestamp)\r\nORDER BY timestamp\r\nDESC LIMIT 1"
    }
   ]
  },
  {
   "title": "AFT - Aradex 1",
   "type": "canvas",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "targets": [
    {
     "dataset": "dev",
     "rawSql": "SELECT\r\n  timestamp,\r\n  comm_warning__value               AS comm_warning,\r\n  comm_error__value                 AS comm_error,\r\n  control_warning__value            AS control_warning,\r\n  control_error__value              AS control_error,\r\n  encoder_warning__value            AS encoder_warning,\r\n  encodererror__value               AS encoder_error,\r\n  fc_temp_warning__value            AS fc_temp_warning,\r\n  fc_temp_error__value              AS fc_temp_error,\r\n  hv_input_warning__value           AS hv_input_warning,\r\n  hv_inputerror__value              AS hv_input_error,\r\n  motor_temp_warning__value         AS motor_temp_warning,\r\n  motor_temp_error__value           AS motor_temp_error,\r\n  motor_output_igbt_warnings__value AS motor_output_igbt_warnings,\r\n  motor_output_igbt_errors__value   AS motor_output_igbt_errors,\r\n  other_warning__value              AS other_warning,\r\n  other_error__value                AS other_error\r\nFROM public.marpower__150000_propulsion__pcs_aft_ara1\r\nWHERE $__timeFilter(timestamp)\r\nORDER BY timestamp DESC\r\nLIMIT 1;"
    }
   ]
  },
  {
   "title": "FWD - Aradex 1",
   "type": "canvas",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "targets": [
    {
     "dataset": "dev",
     "rawSql": "SELECT\r\n  timestamp,\r\n  comm_warning__value               AS comm_warning,\r\n  comm_error__value                 AS comm_error,\r\n  control_warning__value            AS control_warning,\r\n  control_error__value              AS control_error,\r\n  encoder_warning__value            AS encoder_warning,\r\n  encodererror__value               AS encoder_error,\r\n  fc_temp_warning__value            AS fc_temp_warning,\r\n  fc_temp_error__value              AS fc_temp_error,\r\n  hv_input_warning__value           AS hv_input_warning,\r\n  hv_inputerror__value              AS hv_input_error,\r\n  motor_temp_warning__value         AS motor_temp_warning,\r\n  motor_temp_error__value           AS motor_temp_error,\r\n  motor_output_igbt_warnings__value AS motor_output_igbt_warnings,\r\n  motor_output_igbt_errors__value   AS motor_output_igbt_errors,\r\n  other_warning__value              AS other_warning,\r\n  other_error__value                AS other_error\r\nFROM public.marpower__150000_propulsion__pcs_fwd_ara1\r\nWHERE $__timeFilter(timestamp)\r\nORDER BY timestamp DESC\r\nLIMIT 1;"
    }
   ]
  },
  {
   "title": "AFT - Aradex 2",
   "type": "canvas",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
   "targets": [
    {
     "dataset": "dev",
     "rawSql": "SELECT\r\n  timestamp,\r\n  comm_warning__value               AS comm_warning,\r\n  comm_error__value                 AS comm_error,\r\n  control_warning__value            AS control_warning,\r\n  control_error__value              AS control_error,\r\n  encoder_warning__value            AS encoder_warning,\r\n  encoder_error__value              AS encoder_error,\r\n  fc_temp_warning__value            AS fc_temp_warning,\r\n  fc_temp_error__value              AS fc_temp_error,\r\n  hv_input_warning__value           AS hv_input_warning,\r\n  hv_input_error__value             AS hv_input_error,\r\n  motor_temp_warning__value         AS motor_temp_warning,\r\n  motor_temp_error__value           AS motor_temp_error,\r\n  motor_output_igbt_warnings__value AS motor_output_igbt_warnings,\r\n  motor_output_igbt_errors__value   AS motor_output_igbt_errors,\r\n  other_warning__value              AS other_warning,\r\n  other_error__value                AS other_error\r\nFROM public.marpower__150000_propulsion__pcs_aft_ara2\r\nWHERE $__timeFilter(timestamp)\r\nORDER BY timestamp DESC\r\nLIMIT 1"
    }
   ]
  },
  {
   "title": "FWD - Aradex 2",
   "type": "canvas",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 17 },
   "targets": [
    {
     "dataset": "dev",
     "rawSql": "SELECT\r\n  timestamp,\r\n  comm_warning__value               AS comm_warning,\r\n  comm_error__value                 AS comm_error,\r\n  control_warning__value            AS control_warning,\r\n  control_error__value              AS control_error,\r\n  encoder_warning__value            AS encoder_warning,\r\n  encoder_error__value              AS encoder_error,\r\n  fc_temp_warning__value            AS fc_temp_warning,\r\n  fc_temp_error__value              AS fc_temp_error,\r\n  hv_input_warning__value           AS hv_input_warning,\r\n  hv_input_error__value             AS hv_input_error,\r\n  motor_temp_warning__value         AS motor_temp_warning,\r\n  motor_temp_error__value           AS motor_temp_error,\r\n  motor_output_igbt_warnings__value AS motor_output_igbt_warnings,\r\n  motor_output_igbt_errors__value   AS motor_output_igbt_errors,\r\n  other_warning__value              AS other_warning,\r\n  other_error__value                AS other_error\r\nFROM public.marpower__150000_propulsion__pcs_fwd_ara2\r\nWHERE $__timeFilter(timestamp)\r\nORDER BY timestamp DESC\r\nLIMIT 1"
    }
   ]
  },
  { "title": "Status", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 25 } },
  {
   "title": "AFT",
   "type": "canvas",
   "gridPos": { "h": 3, "w": 12, "x": 0, "y": 26 },
   "targets": [
    {
     "dataset": "dev",
     "rawSql": "SELECT\r\n  timestamp,\r\n  hydr_pump_freq_drive_enable__value    AS hydr_pump_freq_drive_enable,\r\n  hydr_pump_freq_drive_rdy__value       AS hydr_pump_freq_drive_rdy,\r\n  hydr_tank_level_low__value            AS hydr_tank_level_low,\r\n  shaft_brake_actuator_engage__value    AS shaft_brake_actuator_engage,\r\n  shaft_brake_actuator_disengage__value AS shaft_brake_actuator_disengage\r\nFROM public.marpower__150000_propulsion__pcs_aft\r\nWHERE $__timeFilter(timestamp)\r\nORDER BY timestamp DESC\r\nLIMIT 1"
    }
   ]
  },
  {
   "title": "FWD",
   "type": "canvas",
   "gridPos": { "h": 3, "w": 12, "x": 12, "y": 26 },
   "targets": [
    {
     "dataset": "dev",
     "rawSql": "SELECT\r\n  timestamp,\r\n  hydr_pump_freq_drive_enable__value    AS hydr_pump_freq_drive_enable,\r\n  hydr_pump_freq_drive_rdy__value       AS hydr_pump_freq_drive_rdy,\r\n  hydr_tank_level_low__value            AS hydr_tank_level_low,\r\n  shaft_brake_actuator_engage__value    AS shaft_brake_actuator_engage,\r\n  shaft_brake_actuator_disengage__value AS shaft_brake_actuator_disengage\r\nFROM public.marpower__150000_propulsion__pcs_fwd\r\nWHERE $__timeFilter(timestamp)\r\nORDER BY timestamp DESC\r\nLIMIT 1"
    }
   ]
  },
  {
   "title": "AFT - Aradex 1",
   "type": "canvas",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 29 },
   "targets": [
    {
     "dataset": "dev",
     "rawSql": "SELECT\r\n  timestamp,\r\n  vp_enable__value                AS vp_enable,\r\n  not_ready_for_use__value        AS not_ready_for_use,\r\n  speed_or_torque_setpoint__value AS speed_or_torque_setpoint\r\nFROM public.marpower__150000_propulsion__pcs_aft_ara1\r\nWHERE $__timeFilter(timestamp)\r\nORDER BY timestamp DESC\r\nLIMIT 1"
    }
   ]
  },
  {
   "title": "AFT - Aradex 2",
   "type": "canvas",
   "gridPos": { "h": 4, "w": 6, "x": 6, "y": 29 },
   "targets": [
    {
     "dataset": "dev",
     "rawSql": "SELECT\r\n  timestamp,\r\n  vp_enable__value                AS vp_enable,\r\n  not_ready_for_use__value        AS not_ready_for_use,\r\n  speed_or_torque_setpoint__value AS speed_or_torque_setpoint\r\nFROM public.marpower__150000_propulsion__pcs_aft_ara2\r\nWHERE $__timeFilter(timestamp)\r\nORDER BY timestamp DESC\r\nLIMIT 1"
    }
   ]
  },
  {
   "title": "FWD - Aradex 1",
   "type": "canvas",
   "gridPos": { "h": 4, "w": 6, "x": 12, "y": 29 },
   "targets": [
    {
     "dataset": "dev",
     "rawSql": "SELECT\r\n  timestamp,\r\n  vp_enable__value                AS vp_enable,\r\n  not_ready_for_use__value        AS not_ready_for_use,\r\n  speed_or_torque_setpoint__value AS speed_or_torque_setpoint\r\nFROM public.marpower__150000_propulsion__pcs_fwd_ara1\r\nWHERE $__timeFilter(timestamp)\r\nORDER BY timestamp DESC\r\nLIMIT 1"
    }
   ]
  },
  {
   "title": "FWD - Aradex 2",
   "type": "canvas",
   "gridPos": { "h": 4, "w": 6, "x": 18, "y": 29 },
   "targets": [
    {
     "dataset": "dev",
     "rawSql": "SELECT\r\n  timestamp,\r\n  vp_enable__value                AS vp_enable,\r\n  not_ready_for_use__value        AS not_ready_for_use,\r\n  speed_or_torque_setpoint__value AS speed_or_torque_setpoint\r\nFROM public.marpower__150000_propulsion__pcs_fwd_ara2\r\nWHERE $__timeFilter(timestamp)\r\nORDER BY timestamp DESC\r\nLIMIT 1"
    }
   ]
  },
  { "title": "Control signals", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 33 } },
  {
   "title": "AFT",
   "type": "canvas",
   "gridPos": { "h": 4, "w": 12, "x": 0, "y": 34 },
   "targets": [
    {
     "dataset": "dev",
     "rawSql": "SELECT\r\n  timestamp,\r\n  heatingonoff__value                AS heating_on_off,\r\n  flush_valve__value                 AS flush_valve,\r\n  hydr_pump_freq_drive_enable__value AS hydr_pump_freq_drive_enable\r\nFROM public.marpower__150000_propulsion__pcs_aft\r\nWHERE $__timeFilter(timestamp)\r\nORDER BY timestamp DESC\r\nLIMIT 1"
    }
   ]
  },
  {
   "title": "FWD",
   "type": "canvas",
   "gridPos": { "h": 4, "w": 12, "x": 12, "y": 34 },
   "targets": [
    {
     "dataset": "dev",
     "rawSql": "SELECT\r\n  timestamp,\r\n  heatingonoff__value                AS heating_on_off,\r\n  flush_valve__value                 AS flush_valve,\r\n  hydr_pump_freq_drive_enable__value AS hydr_pump_freq_drive_enable\r\nFROM public.marpower__150000_propulsion__pcs_fwd\r\nWHERE $__timeFilter(timestamp)\r\nORDER BY timestamp DESC\r\nLIMIT 1"
    }
   ]
  },
  { "title": "Sensor values", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 38 } },
  {
   "title": "AFT - Temperatures",
   "type": "canvas",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 39 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "dataset": "dev",
     "rawSql": "SELECT\r\n  timestamp               AS time,\r\n  windingtempu_1__value   AS winding_U1_temp,\r\n  windingtempv_1__value   AS winding_V1_temp,\r\n  windingtempw_1__value   AS winding_W1_temp,\r\n  venttemp_1__value       AS ventilation1_temp,\r\n  windingtempu_2__value   AS winding_U2_temp,\r\n  windingtempv_2__value   AS winding_V2_temp,\r\n  windingtempw_2__value   AS winding_W2_temp,\r\n  venttemp_2__value       AS ventilation2_temp,\r\n  bearing_de_temp__value  AS bearing_de_temp,\r\n  bearing_nde_temp__value AS bearing_nde_temp\r\nFROM public.marpower__150000_propulsion__pcs_aft\r\nWHERE $__timeFilter(timestamp)\r\nORDER BY timestamp DESC\r\nLIMIT 1"
    }
   ]
  },
  {
   "title": "FWD - Temperatures",
   "type": "canvas",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 39 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "dataset": "dev",
     "rawSql": "SELECT\r\n  timestamp               AS time,\r\n  windingtempu_1__value   AS winding_U1_temp,\r\n  windingtempv_1__value   AS winding_V1_temp,\r\n  winding_temp_w_1__value   AS winding_W1_temp,\r\n  venttemp_1__value       AS ventilation1_temp,\r\n  windingtempu_2__value   AS winding_U2_temp,\r\n  windingtempv_2__value   AS winding_V2_temp,\r\n  windingtempw_2__value   AS winding_W2_temp,\r\n  venttemp_2__value       AS ventilation2_temp,\r\n  bearing_de_temp__value  AS bearing_de_temp,\r\n  bearing_nde_temp__value AS bearing_nde_temp\r\nFROM public.marpower__150000_propulsion__pcs_fwd\r\nWHERE $__timeFilter(timestamp)\r\nORDER BY timestamp DESC\r\nLIMIT 1"
    }
   ]
  },
  {
   "title": "AFT - Load pins",
   "type": "table",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 46 },
   "fieldConfig": { "defaults": { "unit": "forcekN" } },
   "targets": [
    {
     "rawSql": "WITH loadpins AS (\r\n  SELECT\r\n    timestamp,\r\n    loadpin_1_horizontal__value,\r\n    loadpin_1_vertical__value,\r\n    loadpin_2_horizontal__value,\r\n    loadpin_2_vertical__value,\r\n    loadpin_3_horizontal__value,\r\n    loadpin_3_vertical__value,\r\n    loadpin_4_horizontal__value,\r\n    loadpin_4_vertical__value\r\n  FROM public.marpower__150000_propulsion__pcs_aft\r\n  WHERE $__timeFilter(timestamp)\r\n  ORDER BY timestamp DESC\r\n  LIMIT 1\r\n)\r\nSELECT timestamp AS time, 1 AS pin, loadpin_1_horizontal__value AS horizontal, loadpin_1_vertical__value AS vertical FROM loadpins\r\nUNION ALL\r\nSELECT timestamp AS time, 2 AS pin, loadpin_2_horizontal__value AS horizontal, loadpin_2_vertical__value AS vertical FROM loadpins\r\nUNION ALL\r\nSELECT timestamp AS time, 3 AS pin, loadpin_3_horizontal__value AS horizontal, loadpin_3_vertical__value AS vertical FROM loadpins\r\nUNION ALL\r\nSELECT timestamp AS time, 4 AS pin, loadpin_4_horizontal__value AS horizontal, loadpin_4_vertical__value AS vertical FROM loadpins\r\nORDER BY pin"
    }
   ]
  },
  {
   "title": "FWD - Load pins",
   "type": "table",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 46 },
   "fieldConfig": { "defaults": { "unit": "forcekN" } },
   "targets": [
    {
     "rawSql": "WITH loadpins AS (\r\n  SELECT\r\n    timestamp,\r\n    loadpin_1_horizontal__value,\r\n    loadpin_1_vertical__value,\r\n    loadpin_2_horizontal__value,\r\n    loadpin_2_vertical__value,\r\n    loadpin_3_horizontal__value,\r\n    loadpin_3_vertical__value,\r\n    loadpin_4_horizontal__value,\r\n    loadpin_4_vertical__value\r\n  FROM public.marpower__150000_propulsion__pcs_fwd\r\n  WHERE $__timeFilter(timestamp)\r\n  ORDER BY timestamp DESC\r\n  LIMIT 1\r\n)\r\nSELECT timestamp AS time, 1 AS pin, loadpin_1_horizontal__value AS horizontal, loadpin_1_vertical__value AS vertical FROM loadpins\r\nUNION ALL\r\nSELECT timestamp AS time, 2 AS pin, loadpin_2_horizontal__value AS horizontal, loadpin_2_vertical__value AS vertical FROM loadpins\r\nUNION ALL\r\nSELECT timestamp AS time, 3 AS pin, loadpin_3_horizontal__value AS horizontal, loadpin_3_vertical__value AS vertical FROM loadpins\r\nUNION ALL\r\nSELECT timestamp AS time, 4 AS pin, loadpin_4_horizontal__value AS horizontal, loadpin_4_vertical__value AS vertical FROM loadpins\r\nORDER BY pin"
    }
   ]
  },
  {
   "title": "AFT - Shear beams",
   "type": "table",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 53 },
   "fieldConfig": { "defaults": { "unit": "forceNm" } },
   "targets": [
    {
     "rawSql": "WITH shear_beams AS (\r\n  SELECT\r\n    timestamp,\r\n    shear_beam_1__value,\r\n    shear_beam_2__value,\r\n    shear_beam_3__value,\r\n    shear_beam_4__value,\r\n    shear_beam_calculated__value\r\n  FROM public.marpower__150000_propulsion__pcs_aft\r\n  WHERE $__timeFilter(timestamp)\r\n  ORDER BY timestamp DESC\r\n  LIMIT 1\r\n)\r\nSELECT timestamp AS time, '1' AS shear_beam, shear_beam_1__value AS value FROM shear_beams\r\nUNION ALL\r\nSELECT timestamp AS time, '2' AS shear_beam, shear_beam_2__value AS value FROM shear_beams\r\nUNION ALL\r\nSELECT timestamp AS time, '3' AS shear_beam, shear_beam_3__value AS value FROM shear_beams\r\nUNION ALL\r\nSELECT timestamp AS time, '4' AS shear_beam, shear_beam_4__value AS value FROM shear_beams\r\nUNION ALL\r\nSELECT timestamp AS time, 'Calculated' AS shear_beam, shear_beam_calculated__value AS value FROM shear_beams\r\nORDER BY shear_beam"
    }
   ]
  },
  {
   "title": "FWD - Shear beams",
   "type": "table",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 53 },
   "fieldConfig": { "defaults": { "unit": "forceNm" } },
   "targets": [
    {
     "rawSql": "WITH shear_beams AS (\r\n  SELECT\r\n    timestamp,\r\n    shear_beam_1__value,\r\n    shear_beam_2__value,\r\n    shear_beam_3__value,\r\n    shear_beam_4__value,\r\n    shear_beam_calculated__value\r\n  FROM public.marpower__150000_propulsion__pcs_fwd\r\n  WHERE $__timeFilter(timestamp)\r\n  ORDER BY timestamp DESC\r\n  LIMIT 1\r\n)\r\nSELECT timestamp AS time, '1' AS shear_beam, shear_beam_1__value AS value FROM shear_beams\r\nUNION ALL\r\nSELECT timestamp AS time, '2' AS shear_beam, shear_beam_2__value AS value FROM shear_beams\r\nUNION ALL\r\nSELECT timestamp AS time, '3' AS shear_beam, shear_beam_3__value AS value FROM shear_beams\r\nUNION ALL\r\nSELECT timestamp AS time, '4' AS shear_beam, shear_beam_4__value AS value FROM shear_beams\r\nUNION ALL\r\nSELECT timestamp AS time, 'Calculated' AS shear_beam, shear_beam_calculated__value AS value FROM shear_beams\r\nORDER BY shear_beam"
    }
   ]
  }
 ]
}