{
 "title": "Seawater",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "datasource", "query": "grafana-postgresql-datasource" }
  ]
 },
 "panels": [
  { "title": "General", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Alarms",
   "type": "canvas",
   "gridPos": { "h": 5, "w": 5, "x": 0, "y": 1 },
   "targets": [
    {
     "dataset": "dev",
     "rawSql": "SELECT\r\n  LAST_VALUE(time ORDER BY time) AS time,\r\n  LAST_VALUE((\"VACUUMALARM\").value ORDER BY time) AS vacuumalarm\r\nFROM marpower.\"380000_seawater\""
    }
   ]
  },
  {
   "title": "Status",
   "type": "canvas",
   "gridPos": { "h": 5, "w": 6, "x": 5, "y": 1 },
   "targets": [
    {
     "dataset": "dev",
     "rawSql": "SELECT\r\n  LAST_VALUE(time ORDER BY time) AS time,\r\n  LAST_VALUE((\"COOL_PMP1_REMOTE\").value ORDER BY time) AS pmp1_remote,\r\n  LAST_VALUE((\"COOL_PMP1_RUNNING\").value ORDER BY time) AS pmp1_running,\r\n  LAST_VALUE((\"COOL_PMP2_REMOTE\").value ORDER BY time) AS pmp2_remote,\r\n  LAST_VALUE((\"COOL_PMP2_RUNNING\").value ORDER BY time) AS pmp2_running\r\nFROM marpower.\"380000_seawater\""
    }
   ]
  },
  {
   "title": "Control signals",
   "type": "canvas",
   "gridPos": { "h": 5, "w": 6, "x": 11, "y": 1 },
   "targets": [
    {
     "dataset": "dev",
     "rawSql": "SELECT\r\n  LAST_VALUE(time ORDER BY time) AS time,\r\n  LAST_VALUE((\"COOL_PMP1_STARTSTOP\").value ORDER BY time) AS pmp1_startstop,\r\n  LAST_VALUE((\"COOL_PMP2_STARTSTOP\").value ORDER BY time) AS pmp2_startstop\r\nFROM marpower.\"380000_seawater\""
    }
   ]
  },
  {
   "title": "Sensors",
   "type": "canvas",
   "gridPos": { "h": 5, "w": 7, "x": 17, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "flowlpm" } },
   "targets": [
    {
     "dataset": "dev",
     "rawSql": "SELECT\r\n  LAST_VALUE(time ORDER BY time) AS time,\r\n  LAST_VALUE((\"FLOW\").value ORDER BY time) AS flow\r\nFROM marpower.\"380000_seawater\""
    }
   ]
  },
  {
   "title": "Historical",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 6 },
   "collapsed": true,
   "panels": [
    {
     "title": "Alarm, status & control signal history",
     "type": "status-history",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 7 },
     "targets": [
      {
       "dataset": "dev",
       "rawSql": "SELECT\r\n  time,\r\n\r\n  -- Alarm\r\n  (\"VACUUMALARM\").value AS vacuum_alarm,\r\n\r\n  -- Status\r\n  (\"COOL_PMP1_REMOTE\").value AS cooling_pump1_remavail,\r\n  (\"COOL_PMP1_RUNNING\").value AS cooling_pump1_running,\r\n  (\"COOL_PMP2_REMOTE\").value AS cooling_pump2_remavail,\r\n  (\"COOL_PMP2_RUNNING\").value AS cooling_pump2_running,\r\n\r\n  -- Control signals\r\n  (\"COOL_PMP1_STARTSTOP\").value AS cooling_pump1_onoff,\r\n  (\"COOL_PMP2_STARTSTOP\").value AS cooling_pump2_onoff\r\nFROM marpower.\"380000_seawater\"\r\nWHERE $__timeFilter(time)"
      }
     ]
    },
    {
     "title": "Flow",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 14 },
     "fieldConfig": { "defaults": { "unit": "flowlpm" } },
     "targets": [
      {
       "dataset": "dev",
       "rawSql": "SELECT\r\n  time,\r\n  (\"FLOW\").value as flow\r\nFROM marpower.\"380000_seawater\""
      }
     ]
    }
   ]
  },
  { "title": "Valves", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 } },
  {
   "type": "table",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 8 },
   "targets": [
    {
     "dataset": "dev",
     "rawSql": "SELECT\r\n  topic,\r\n  ARG_MAX((\"Opened\").Value, (\"Opened\").Timestamp) AS Opened,\r\n  ARG_MAX((\"Closed\").Value, (\"Closed\").Timestamp) AS Closed,\r\n  ARG_MAX((\"HmiCmdOpen\").Value, (\"HmiCmdOpen\").Timestamp) AS HmiCmdOpen,\r\n  ARG_MAX((\"HmiCmdClose\").Value, (\"HmiCmdClose\").Timestamp) AS HmiCmdClose,\r\n  ARG_MAX((\"ShouldBeOpen\").Value, (\"ShouldBeOpen\").Timestamp) AS ShouldBeOpen,\r\n  ARG_MAX((\"HmiControlAvailable\").Value, (\"HmiControlAvailable\").Timestamp) AS HmiControlAvailable,\r\n  ARG_MAX((\"Open\").Value, (\"Open\").Timestamp) AS Open,\r\n  ARG_MAX((\"Close\").Value, (\"Close\").Timestamp) AS Close,\r\n  ARG_MAX((\"Alarm\").Value, (\"Alarm\").Timestamp) AS Alarm\r\nFROM marpower.\"380000_seawater_cooling\"\r\nGROUP BY topic\r\nORDER BY topic"
    }
   ]
  }
 ]
}