{
 "title": "Seawater",
 "tags": [ "commisssioning" ],
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "datasource", "query": "info8fcc-greptimedb-datasource" }
  ]
 },
 "panels": [
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 0 },
   "options": {
    "content": "<center>\r\n  <h1>Sea water</h1>\r\n</center>\r\n"
   }
  },
  { "title": "General", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 } },
  {
   "title": "Alarms",
   "type": "canvas",
   "gridPos": { "h": 3, "w": 8, "x": 0, "y": 3 },
   "targets": [
    {
     "dataset": "dev",
     "rawSql": "SELECT timestamp AS time,\r\n\t\t\tvacuumalarm__value AS vacuumalarm\r\nFROM marpower__380000_seawater\r\nORDER BY timestamp DESC\r\nLIMIT 1;"
    },
    {
     "dataset": "dev",
     "rawSql": "SELECT MAX(CASE\r\n\t\t\t\t\t\t\tWHEN mqtt_json_path = LOWER('vacuumalarm') THEN '(' || yard_tag || ')'\r\n\t\t\t\t\t\t\tELSE NULL\r\n\t\t\t\t\tEND) AS vacuumalarm_tag\r\nFROM marpower__io_metadata\r\nWHERE mqtt_topic = 'marpower/380000-seawater';"
    }
   ]
  },
  {
   "title": "Status",
   "type": "canvas",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 3 },
   "targets": [
    {
     "dataset": "dev",
     "rawSql": "SELECT timestamp AS time,\r\n\t\t\tcool_pmp_1_remote__value AS pmp1_remote,\r\n\t\t\tcool_pmp_1_running__value AS pmp1_running,\r\n\t\t\tcool_pmp_2_remote__value AS pmp2_remote,\r\n\t\t\tcool_pmp_2_running__value AS pmp2_running\r\nFROM marpower__380000_seawater\r\nORDER BY timestamp DESC\r\nLIMIT 1;"
    },
    {
     "dataset": "dev",
     "rawSql": "SELECT MAX(CASE\r\n\t\t\t\t\t\t\tWHEN mqtt_json_path = LOWER('cool_pmp1_remote') THEN '(' || yard_tag || ')'\r\n\t\t\t\t\t\t\tELSE NULL\r\n\t\t\t\t\tEND) AS pmp1_remote_tag,\r\n\t\t\tMAX(CASE\r\n\t\t\t\t\t\t\tWHEN mqtt_json_path = LOWER('cool_pmp1_running') THEN '(' || yard_tag || ')'\r\n\t\t\t\t\t\t\tELSE NULL\r\n\t\t\t\t\tEND) AS pmp1_running_tag,\r\n\t\t\tMAX(CASE\r\n\t\t\t\t\t\t\tWHEN mqtt_json_path = LOWER('cool_pmp2_remote') THEN '(' || yard_tag || ')'\r\n\t\t\t\t\t\t\tELSE NULL\r\n\t\t\t\t\tEND) AS pmp2_remote_tag,\r\n\t\t\tMAX(CASE\r\n\t\t\t\t\t\t\tWHEN mqtt_json_path = LOWER('cool_pmp2_running') THEN '(' || yard_tag || ')'\r\n\t\t\t\t\t\t\tELSE NULL\r\n\t\t\t\t\tEND) AS pmp2_running_tag\r\nFROM marpower__io_metadata\r\nWHERE mqtt_topic = 'marpower/380000-seawater';"
    }
   ]
  },
  {
   "title": "Control signals",
   "type": "canvas",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 3 },
   "targets": [
    {
     "dataset": "dev",
     "rawSql": "SELECT timestamp AS time,\r\n\t\t\tcool_pmp_1_startstop__value AS pmp1_startstop,\r\n\t\t\tcool_pmp_2_startstop__value AS pmp2_startstop\r\nFROM marpower__380000_seawater\r\nORDER BY timestamp DESC\r\nLIMIT 1;"
    },
    {
     "dataset": "dev",
     "rawSql": "SELECT MAX(CASE\r\n\t\t\t\t\t\t\tWHEN mqtt_json_path = LOWER('cool_pmp1_startstop') THEN '(' || yard_tag || ')'\r\n\t\t\t\t\t\t\tELSE NULL\r\n\t\t\t\t\tEND) AS pmp1_startstop_tag,\r\n\t\t\tMAX(CASE\r\n\t\t\t\t\t\t\tWHEN mqtt_json_path = LOWER('cool_pmp2_startstop') THEN '(' || yard_tag || ')'\r\n\t\t\t\t\t\t\tELSE NULL\r\n\t\t\t\t\tEND) AS pmp2_startstop_tag\r\nFROM marpower__io_metadata\r\nWHERE mqtt_topic = 'marpower/380000-seawater';"
    }
   ]
  },
  {
   "title": "Sensors",
   "type": "canvas",
   "gridPos": { "h": 3, "w": 8, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "flowlpm" } },
   "targets": [
    {
     "dataset": "dev",
     "rawSql": "SELECT timestamp AS time,\r\n\t\t\tflow__value AS flow\r\nFROM marpower__380000_seawater\r\nORDER BY timestamp DESC\r\nLIMIT 1;"
    },
    {
     "dataset": "dev",
     "rawSql": "SELECT MAX(CASE\r\n\t\t\t\t\t\t\tWHEN mqtt_json_path = LOWER('flow') THEN '(' || yard_tag || ')'\r\n\t\t\t\t\t\t\tELSE NULL\r\n\t\t\t\t\tEND) AS flow_tag\r\nFROM marpower__io_metadata\r\nWHERE mqtt_topic = 'marpower/380000-seawater';"
    }
   ]
  },
  {
   "title": "Historical",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 },
   "collapsed": true,
   "panels": [
    {
     "title": "Alarm, status & control signal history",
     "type": "status-history",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 7 },
     "targets": [
      {
       "dataset": "dev",
       "rawSql": "SELECT timestamp as time,\r\n\t\t\tvacuumalarm__value AS vacuum_alarm,\r\n\t\t\tcool_pmp_1_remote__value AS cooling_pump_1_remavail,\r\n\t\t\tcool_pmp_1_running__value AS cooling_pump_1_running,\r\n\t\t\tcool_pmp_2_remote__value AS cooling_pump_2_remavail,\r\n\t\t\tcool_pmp_2_running__value AS cooling_pump_2_running,\r\n\t\t\tcool_pmp_1_startstop__value AS cooling_pump_1_onoff,\r\n\t\t\tcool_pmp_2_startstop__value AS cooling_pump_2_onoff\r\nFROM marpower__380000_seawater\r\nWHERE $__timeFilter(timestamp)\r\nORDER BY timestamp DESC;"
      }
     ]
    },
    {
     "title": "Flow",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 14 },
     "fieldConfig": { "defaults": { "unit": "flowlpm" } },
     "targets": [
      {
       "dataset": "dev",
       "rawSql": "SELECT timestamp as time,\r\n\t\t\tflow__value AS flow\r\nFROM marpower__380000_seawater\r\nWHERE $__timeFilter(timestamp)\r\nORDER BY timestamp DESC;"
      }
     ]
    }
   ]
  },
  { "title": "Valves", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 10 } },
  {
   "type": "table",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 11 },
   "targets": [
    {
     "dataset": "dev",
     "rawSql": "SELECT DISTINCT ON (topic) topic,\r\n\t\t\t\t\t\t\t\t\talarm__value AS Alarm,\r\n\t\t\t\t\t\t\t\t\tclose__value AS Close,\r\n\t\t\t\t\t\t\t\t\tclosed__value AS Closed,\r\n\t\t\t\t\t\t\t\t\thmi_cmd_close__value AS HmiCmdClose,\r\n\t\t\t\t\t\t\t\t\thmi_cmd_open__value AS HmiCmdOpen,\r\n\t\t\t\t\t\t\t\t\thmi_control_available__value AS HmiControlAvailable,\r\n\t\t\t\t\t\t\t\t\topen__value AS Open,\r\n\t\t\t\t\t\t\t\t\topened__value AS Opened,\r\n\t\t\t\t\t\t\t\t\tshould_be_open__value AS ShouldBeOpen\r\nFROM marpower__380000_seawater_cooling\r\nWHERE $__timeFilter(timestamp)\r\nORDER BY topic, timestamp DESC;"
    }
   ]
  }
 ]
}