{
 "title": "Tank levels",
 "tags": [ "commisssioning" ],
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "datasource", "query": "info8fcc-greptimedb-datasource" }
  ]
 },
 "panels": [
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 0 },
   "options": {
    "content": "<center>\r\n  <h1>Tank levels</h1>\r\n</center>\r\n"
   }
  },
  { "title": "General", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 } },
  {
   "title": "Fresh water",
   "type": "canvas",
   "gridPos": { "h": 4, "w": 8, "x": 0, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "mamp" } },
   "targets": [
    {
     "rawSql": "select timestamp as time, tank_1_fr_45_ps_level__value AS fresh_water_tank_1_level, tank_2_fr_45_sb_level__value AS fresh_water_tank_2_level from marpower__250000_fresh_water ORDER BY timestamp DESC LIMIT 1;"
    },
    {
     "dataset": "dev",
     "rawSql": "select max(case when mqtt_json_path = lower('tank_1_fr_45_ps_level') then '(' || yard_tag || ')' else null end) AS fresh_water_tank_1_level_tag, max(case when mqtt_json_path = lower('tank_2_fr_45_sb_level') then '(' || yard_tag || ')' else null end) AS fresh_water_tank_2_level_tag from marpower__io_metadata where mqtt_topic = 'marpower/250000-fresh-water';"
    }
   ]
  },
  {
   "title": "Hot water",
   "type": "canvas",
   "gridPos": { "h": 5, "w": 8, "x": 8, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "mamp" } },
   "targets": [
    {
     "rawSql": "SELECT\r\n  timestamp AS time,\r\n  hotwater_11_level__value AS tank11_level,\r\n  hotwater_13_level__value AS tank13_level,\r\n  hotwater_15_level__value AS tank15_level\r\nFROM marpower__340000_tankage\r\nORDER BY timestamp\r\nDESC LIMIT 1"
    },
    {
     "dataset": "dev",
     "rawSql": "SELECT\r\n  MAX(CASE WHEN mqtt_json_path = LOWER('HOTWATER11_LEVEL') THEN '(' || yard_tag || ')' ELSE NULL END) AS tank11_level_tag,\r\n  MAX(CASE WHEN mqtt_json_path = LOWER('HOTWATER13_LEVEL') THEN '(' || yard_tag || ')' ELSE NULL END) AS tank13_level_tag,\r\n  MAX(CASE WHEN mqtt_json_path = LOWER('HOTWATER15_LEVEL') THEN '(' || yard_tag || ')' ELSE NULL END) AS tank15_level_tag\r\nFROM marpower__io_metadata\r\nWHERE mqtt_topic = 'marpower/340000-tankage'"
    }
   ]
  },
  {
   "title": "Bilge",
   "type": "canvas",
   "gridPos": { "h": 3, "w": 8, "x": 16, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "pressurebar" } },
   "targets": [
    {
     "dataset": "dev",
     "rawSql": "select timestamp as time, tank_level__value AS tank_level from marpower__210000_bilge_fifi_general ORDER BY timestamp DESC LIMIT 1;"
    },
    {
     "dataset": "dev",
     "rawSql": "select max(case when mqtt_json_path = lower('tank_level') then '(' || yard_tag || ')' else null end) AS tank_level_tag from marpower__io_metadata where mqtt_topic = 'marpower/210000-bilge-fifi-general';"
    }
   ]
  },
  {
   "title": "Sludge",
   "type": "canvas",
   "gridPos": { "h": 3, "w": 8, "x": 16, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "mamp" } },
   "targets": [
    {
     "dataset": "dev",
     "rawSql": "select timestamp as time, sludge_tank_ps_level__value AS sludge_tank from marpower__340000_sewage ORDER BY timestamp DESC LIMIT 1;"
    },
    {
     "dataset": "dev",
     "rawSql": "select max(case when mqtt_json_path = lower('sludge_tank_ps_level') then '(' || yard_tag || ')' else null end) AS sludge_tank_tag from marpower__io_metadata where mqtt_topic = 'marpower/340000-sewage';"
    }
   ]
  },
  {
   "title": "Grey/Black water",
   "type": "canvas",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "mamp" } },
   "targets": [
    {
     "dataset": "dev",
     "rawSql": "select timestamp as time, grey_water_tank_aft_sb_level__value AS grey_wat_aft_tank, grey_water_tank_fwd_sb_level__value AS grey_wat_fwd_tank, black_grey_water_tank_aft_ps_level__value AS black_wat_aft_tank from marpower__340000_sewage ORDER BY timestamp DESC LIMIT 1;"
    },
    {
     "dataset": "dev",
     "rawSql": "select max(case when mqtt_json_path = lower('grey_water_tank_aft_sb_level') then '(' || yard_tag || ')' else null end) AS grey_wat_aft_tank_tag, max(case when mqtt_json_path = lower('grey_water_tank_fwd_sb_level') then '(' || yard_tag || ')' else null end) AS grey_wat_fwd_tank_tag, max(case when mqtt_json_path = lower('black_grey_water_tank_aft_ps_level') then '(' || yard_tag || ')' else null end) AS black_wat_aft_tank_tag from marpower__io_metadata where mqtt_topic = 'marpower/340000-sewage';"
    }
   ]
  },
  {
   "title": "Technical water",
   "type": "canvas",
   "gridPos": { "h": 4, "w": 8, "x": 8, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "mamp" } },
   "targets": [
    {
     "rawSql": "SELECT\r\n  timestamp            AS time,\r\n  tank_1_level__value  AS tank1_level,\r\n  tank_2_level__value  AS tank2_level\r\nFROM marpower__250000_techwater\r\nORDER BY timestamp DESC\r\nLIMIT 1"
    },
    {
     "dataset": "dev",
     "rawSql": "SELECT\r\n  MAX(CASE WHEN mqtt_json_path = LOWER('TANK1_LEVEL') THEN '(' || yard_tag || ')' ELSE NULL END) AS tank1_level_tag,\r\n  MAX(CASE WHEN mqtt_json_path = LOWER('TANK2_LEVEL') THEN '(' || yard_tag || ')' ELSE NULL END) AS tank2_level_tag\r\nFROM marpower__io_metadata\r\nWHERE mqtt_topic = 'marpower/250000-techwater';"
    }
   ]
  },
  {
   "title": "Dirty oil",
   "type": "canvas",
   "gridPos": { "h": 3, "w": 8, "x": 16, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "pressurebar" } },
   "targets": [
    {
     "dataset": "dev",
     "rawSql": "select timestamp as time, sludge_tank_level__value AS tank_level from marpower__300000_dirty_oil ORDER BY timestamp DESC LIMIT 1;"
    },
    {
     "dataset": "dev",
     "rawSql": "select max(case when mqtt_json_path = lower('sludge_tank_level') then '(' || yard_tag || ')' else null end) AS tank_level_tag from marpower__io_metadata where mqtt_topic = 'marpower/300000-dirty-oil';"
    }
   ]
  },
  {
   "title": "Historical",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 12 },
   "collapsed": true,
   "panels": [
    {
     "title": "Fresh water tanks",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 13 },
     "fieldConfig": { "defaults": { "unit": "mamp" } },
     "targets": [
      {
       "dataset": "dev",
       "rawSql": "select timestamp as time, TANK_1_FR_45_PS_LEVEL__value as tank1_level, TANK_2_FR_45_SB_LEVEL__value as tank2_level from marpower__250000_fresh_water WHERE $__timeFilter(timestamp) ORDER BY timestamp DESC ;"
      }
     ]
    },
    {
     "title": "Hot water tanks",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 22 },
     "fieldConfig": { "defaults": { "unit": "mamp" } },
     "targets": [
      {
       "dataset": "dev",
       "rawSql": "SELECT\r\n  timestamp                AS time,\r\n  hotwater_11_level__value AS tank11_level,\r\n  hotwater_13_level__value AS tank13_level,\r\n  hotwater_15_level__value AS tank15_level\r\nFROM marpower__340000_tankage\r\nWHERE $__timeFilter(timestamp)"
      }
     ]
    },
    {
     "title": "Technical water tanks",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 31 },
     "fieldConfig": { "defaults": { "unit": "mamp" } },
     "targets": [
      {
       "dataset": "dev",
       "rawSql": "SELECT\r\n  timestamp            AS time,\r\n  tank_1_level__value  AS tank1_level,\r\n  tank_2_level__value  AS tank2_level\r\nFROM marpower__250000_techwater\r\nWHERE $__timeFilter(timestamp)"
      }
     ]
    },
    {
     "title": "Grey/Black water tanks",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 40 },
     "fieldConfig": { "defaults": { "unit": "mamp" } },
     "targets": [
      {
       "dataset": "dev",
       "rawSql": "select timestamp as time, GREY_WATER_TANK_AFT_SB_LEVEL__value as grey_wat_aft_tank, GREY_WATER_TANK_FWD_SB_LEVEL__value as grey_wat_fwd_tank, BLACK_GREY_WATER_TANK_AFT_PS_LEVEL__value as black_wat_aft_tank from marpower__340000_sewage WHERE $__timeFilter(timestamp) ORDER BY timestamp DESC ;"
      }
     ]
    },
    {
     "title": "Bilge tank",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 48 },
     "fieldConfig": { "defaults": { "unit": "mamp" } },
     "targets": [
      {
       "dataset": "dev",
       "rawSql": "select timestamp as time, TANK_LEVEL__value as bilge_tank from marpower__210000_bilge_fifi_general WHERE $__timeFilter(timestamp) ORDER BY timestamp DESC ;"
      }
     ]
    },
    {
     "title": "Sludge tank",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 56 },
     "fieldConfig": { "defaults": { "unit": "mamp" } },
     "targets": [
      {
       "dataset": "dev",
       "rawSql": "select timestamp as time, SLUDGE_TANK_PS_LEVEL__value as sludge_tank from marpower__340000_sewage WHERE $__timeFilter(timestamp) ORDER BY timestamp DESC ;"
      }
     ]
    },
    {
     "title": "Dirty oil sludge tank",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 64 },
     "fieldConfig": { "defaults": { "unit": "mamp" } },
     "targets": [
      {
       "dataset": "dev",
       "rawSql": "select timestamp as time, SLUDGE_TANK_LEVEL__value as sludge_tank from marpower__300000_dirty_oil WHERE $__timeFilter(timestamp) ORDER BY timestamp DESC ;"
      }
     ]
    }
   ]
  }
 ]
}