{
 "title": "Tank levels",
 "tags": [ "commisssioning" ],
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "datasource", "query": "grafana-postgresql-datasource" }
  ]
 },
 "panels": [
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 0 },
   "options": {
    "content": "<center>\r\n  <h1>Tank levels</h1>\r\n</center>\r\n"
   }
  },
  { "title": "General", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 } },
  {
   "title": "Fresh water",
   "type": "canvas",
   "gridPos": { "h": 4, "w": 8, "x": 0, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "rawSql": "SELECT\n  LAST_VALUE(time ORDER BY time) AS time,\n  LAST_VALUE((\"TANK_1_FR_45_PS_LEVEL\").value ORDER BY time)      AS fresh_water_tank_1_level,\n  LAST_VALUE((\"TANK_2_FR_45_SB_LEVEL\").value ORDER BY time)      AS fresh_water_tank_2_level\nFROM marpower.\"250000_fresh_water\";\n"
    }
   ]
  },
  {
   "title": "Technical water",
   "type": "canvas",
   "gridPos": { "h": 4, "w": 8, "x": 8, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "rawSql": "SELECT\n  LAST_VALUE(time ORDER BY time) AS time,\n  LAST_VALUE((\"TANK1_LEVEL\").value ORDER BY time)                   AS tank1_level,\n  LAST_VALUE((\"TANK2_LEVEL\").value ORDER BY time)                   AS tank2_level\nFROM marpower.\"250000_techwater\";\n"
    }
   ]
  },
  {
   "title": "Bilge",
   "type": "canvas",
   "gridPos": { "h": 4, "w": 8, "x": 16, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "pressurebar" } },
   "targets": [
    {
     "dataset": "dev",
     "rawSql": "SELECT\r\n  LAST_VALUE(time ORDER BY time) AS time,\r\n  LAST_VALUE((\"TANK_LEVEL\").value ORDER BY time) AS tank_level\r\nFROM marpower.\"210000_bilge_fifi_general\""
    }
   ]
  },
  {
   "title": "Grey/Black water",
   "type": "canvas",
   "gridPos": { "h": 5, "w": 16, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "dataset": "dev",
     "rawSql": "SELECT\r\n  LAST_VALUE(time ORDER BY time) AS time,\r\n  LAST_VALUE((\"GREY_WATER_TANK_AFT_SB_LEVEL\").value ORDER BY time)       AS grey_wat_aft_tank,\r\n  LAST_VALUE((\"GREY_WATER_TANK_FWD_SB_LEVEL\").value ORDER BY time)       AS grey_wat_fwd_tank,\r\n  LAST_VALUE((\"BLACK_GREY_WATER_TANK_AFT_PS_LEVEL\").value ORDER BY time) AS black_wat_aft_tank,\r\n  LAST_VALUE((\"SLUDGE_TANK_PS_LEVEL\").value ORDER BY time)               AS sludge_tank\r\nFROM marpower.\"340000_sewage\""
    }
   ]
  },
  {
   "title": "Dirty oil",
   "type": "canvas",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "pressurebar" } },
   "targets": [
    {
     "dataset": "dev",
     "rawSql": "SELECT\r\n  LAST_VALUE(time ORDER BY time) AS time,\r\n  LAST_VALUE((\"SLUDGE_TANK_LEVEL\").value ORDER BY time) AS tank_level\r\nFROM marpower.\"300000_dirty_oil\""
    }
   ]
  },
  {
   "title": "Historical",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 12 },
   "collapsed": true,
   "panels": [
    {
     "title": "Fresh water tanks",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 61 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "dataset": "dev",
       "rawSql": "SELECT\r\n  time,\r\n  (\"TANK_1_FR_45_PS_LEVEL\").value as tank1_level,\r\n  (\"TANK_2_FR_45_SB_LEVEL\").value as tank2_level\r\nFROM marpower.\"250000_fresh_water\""
      }
     ]
    },
    {
     "title": "Technical water tanks",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 70 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "dataset": "dev",
       "rawSql": "SELECT\r\n  time,\r\n  (\"TANK1_LEVEL\").value as tank1_level,\r\n  (\"TANK2_LEVEL\").value as tank2_level\r\nFROM marpower.\"250000_techwater\""
      }
     ]
    },
    {
     "title": "Bilge tank",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 79 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "dataset": "dev",
       "rawSql": "SELECT\r\n  time,\r\n  (\"TANK_LEVEL\").value as bilge_tank\r\nFROM marpower.\"210000_bilge_fifi_general\""
      }
     ]
    },
    {
     "title": "Grey/Black water tanks",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 87 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "dataset": "dev",
       "rawSql": "SELECT\r\n  time,\r\n  (\"GREY_WATER_TANK_AFT_SB_LEVEL\").value as grey_wat_aft_tank,\r\n  (\"GREY_WATER_TANK_FWD_SB_LEVEL\").value as grey_wat_fwd_tank,\r\n  (\"BLACK_GREY_WATER_TANK_AFT_PS_LEVEL\").value as black_wat_aft_tank\r\nFROM marpower.\"340000_sewage\""
      }
     ]
    },
    {
     "title": "Sludge tank",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 95 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "dataset": "dev",
       "rawSql": "SELECT\r\n  time,\r\n  (\"SLUDGE_TANK_PS_LEVEL\").value as sludge_tank\r\nFROM marpower.\"340000_sewage\""
      }
     ]
    },
    {
     "title": "Dirty oil sludge tank",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 103 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "dataset": "dev",
       "rawSql": "SELECT\r\n  time,\r\n  (\"SLUDGE_TANK_LEVEL\").value as sludge_tank\r\nFROM marpower.\"300000_dirty_oil\""
      }
     ]
    }
   ]
  }
 ]
}