{
 "title": "Technical water",
 "tags": [ "commisssioning" ],
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "datasource", "query": "grafana-postgresql-datasource" }
  ]
 },
 "panels": [
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 0 },
   "options": {
    "content": "<center>\r\n  <h1>Technical water</h1>\r\n</center>\r\n"
   }
  },
  { "title": "General", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 } },
  {
   "title": "Alarms",
   "type": "canvas",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 3 },
   "targets": [
    {
     "dataset": "dev",
     "rawSql": "SELECT\r\n  LAST_VALUE(time ORDER BY time) AS time,\r\n  LAST_VALUE((\"CHLORINE_UNIT_ALARM\").value ORDER BY time) AS chlorine_unit_alarm\r\nFROM marpower.\"250000_techwater\""
    }
   ]
  },
  {
   "title": "Status",
   "type": "canvas",
   "gridPos": { "h": 4, "w": 15, "x": 3, "y": 3 },
   "targets": [
    {
     "dataset": "dev",
     "rawSql": "SELECT\r\n  LAST_VALUE(time ORDER BY time) AS time,\r\n  LAST_VALUE((\"MTS_INLET_FIRE_FLAP_RELEASED\").value ORDER BY time) AS mts_inlet_flap_released,\r\n  LAST_VALUE((\"MTS_INLET_FIRE_FLAP_FULLY_RESET\").value ORDER BY time) AS mts_inlet_flap_reset,\r\n  LAST_VALUE((\"MTS_EXHAUST_FIRE_FLAP_RELEASED\").value ORDER BY time) AS mts_exhaust_flap_released,\r\n  LAST_VALUE((\"MTS_EXHAUST_FIRE_FLAP_FULLY_RESET\").value ORDER BY time) AS mts_exhaust_flap_reset,\r\n  LAST_VALUE((\"DRAIN_VLV_Y02_POS_OVERBOARD\").value ORDER BY time) AS drain_valve_pos_overboard\r\nFROM marpower.\"250000_techwater\""
    }
   ]
  },
  {
   "title": "Control signals",
   "type": "canvas",
   "gridPos": { "h": 4, "w": 6, "x": 18, "y": 3 },
   "targets": [
    {
     "dataset": "dev",
     "rawSql": "SELECT\r\n  LAST_VALUE(time ORDER BY time) AS time,\r\n  LAST_VALUE((\"VALVE_COLD_AIR_FR68_Y03_OPENCLOSE\").value ORDER BY time) AS valve_cold_air_cool_water_y03,\r\n  LAST_VALUE((\"VALVE_COLD_AIR_FR32_Y04_OPENCLOSE\").value ORDER BY time) AS valve_cold_air_cool_water_y04,\r\n  LAST_VALUE((\"VALVE_COLD_AIR_FR32_Y05_OPENCLOSE\").value ORDER BY time) AS valve_cold_air_cool_water_y05\r\nFROM marpower.\"250000_techwater\""
    }
   ]
  },
  {
   "title": "Historical",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 },
   "collapsed": true,
   "panels": [
    {
     "title": "Alarm, status & control signal history",
     "type": "status-history",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 6 },
     "targets": [
      {
       "dataset": "dev",
       "rawSql": "SELECT\r\n  time,\r\n\r\n  -- Alarm\r\n  (\"CHLORINE_UNIT_ALARM\").value AS fresh_water_chlorine_unit_alarm,\r\n\r\n  -- Status\r\n  (\"MTS_INLET_FIRE_FLAP_RELEASED\").value AS mts_inlet_flap_released,\r\n  (\"MTS_INLET_FIRE_FLAP_FULLY_RESET\").value AS mts_inlet_flap_reset,\r\n  (\"MTS_EXHAUST_FIRE_FLAP_RELEASED\").value AS mts_exhaust_flap_released,\r\n  (\"MTS_EXHAUST_FIRE_FLAP_FULLY_RESET\").value AS mts_exhaust_flap_reset,\r\n\r\n  -- Control signals\r\n  (\"VALVE_COLD_AIR_FR68_Y03_OPENCLOSE\").value AS valve_cold_air_cool_water_y03_openclose,\r\n  (\"VALVE_COLD_AIR_FR32_Y04_OPENCLOSE\").value AS valve_cold_air_cool_water_y04_openclose,\r\n  (\"VALVE_COLD_AIR_FR32_Y05_OPENCLOSE\").value AS valve_cold_air_cool_water_y05_openclose\r\nFROM marpower.\"250000_techwater\"\r\nWHERE $__timeFilter(time) "
      }
     ]
    }
   ]
  },
  { "title": "Sensor values", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 } },
  {
   "title": "Flow",
   "type": "canvas",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "flowlpm" } },
   "targets": [
    {
     "rawSql": "SELECT\n  LAST_VALUE(time ORDER BY time) AS time,\n  \n  LAST_VALUE((\"ADIABATIC_COOL_B03_FLOW\").value ORDER BY time)      AS adiabatic_cool_b03,\n  LAST_VALUE((\"ADIABATIC_COOL_B07_FLOW\").value ORDER BY time)      AS adiabatic_cool_b07,\n  LAST_VALUE((\"ADIABATIC_COOL_B08_FLOW\").value ORDER BY time)      AS adiabatic_cool_b08,\n  LAST_VALUE((\"ADIABATIC_COOL_B09_FLOW\").value ORDER BY time)      AS adiabatic_cool_b09,\n  LAST_VALUE((\"REEL_FOR_DECKWASH_B04_FLOW\").value ORDER BY time)   AS deckwash_reel_B04,\n  LAST_VALUE((\"REEL_FOR_DECKWASH_B05_FLOW\").value ORDER BY time)   AS deckwash_reel_B05,\n  LAST_VALUE((\"REEL_FOR_DECKWASH_B06_FLOW\").value ORDER BY time)   AS deckwash_reel_B06\n\nFROM marpower.\"250000_techwater\"\n"
    }
   ]
  },
  {
   "title": "Miscellaneous",
   "type": "canvas",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "rawSql": "SELECT\n  LAST_VALUE(time ORDER BY time) AS time,\n  \n  LAST_VALUE((\"CHARCOAL_FILTER_B01_FLOW\").value ORDER BY time)      AS charcoal_filter_flow,\n  LAST_VALUE((\"CHARCOAL_FILTER_B01_TEMP\").value ORDER BY time)      AS charcoal_filter_temp,\n  LAST_VALUE((\"SALINITY1\").value ORDER BY time)                     AS salinity1,\n  LAST_VALUE((\"SALINITY2\").value ORDER BY time)                     AS salinity2,\n  LAST_VALUE((\"TANK1_LEVEL\").value ORDER BY time)                   AS tank1_level,\n  LAST_VALUE((\"TANK2_LEVEL\").value ORDER BY time)                   AS tank2_level\n\nFROM marpower.\"250000_techwater\"\n"
    }
   ]
  },
  {
   "title": "Historical",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 15 },
   "collapsed": true,
   "panels": [
    {
     "title": "Adiabatic cooling flow",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 24 },
     "fieldConfig": { "defaults": { "unit": "flowlpm" } },
     "targets": [
      {
       "dataset": "dev",
       "rawSql": "SELECT\r\n  time,\r\n  (\"ADIABATIC_COOL_B03_FLOW\").value as adiab_cool_b03_flow,\r\n  (\"ADIABATIC_COOL_B07_FLOW\").value as adiab_cool_b07_flow,\r\n  (\"ADIABATIC_COOL_B08_FLOW\").value as adiab_cool_b08_flow,\r\n  (\"ADIABATIC_COOL_B09_FLOW\").value as adiab_cool_b09_flow\r\nFROM marpower.\"250000_techwater\""
      }
     ]
    },
    {
     "title": "Deckwash reel flow",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 32 },
     "fieldConfig": { "defaults": { "unit": "flowlpm" } },
     "targets": [
      {
       "dataset": "dev",
       "rawSql": "SELECT\r\n  time,\r\n  (\"REEL_FOR_DECKWASH_B04_FLOW\").value as deckwash_reel_b04_flow,\r\n  (\"REEL_FOR_DECKWASH_B05_FLOW\").value as deckwash_reel_b05_flow,\r\n  (\"REEL_FOR_DECKWASH_B06_FLOW\").value as deckwash_reel_b06_flow\r\nFROM marpower.\"250000_techwater\""
      }
     ]
    },
    {
     "title": "Charcoal filter",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 40 },
     "fieldConfig": { "defaults": { "unit": "flowlpm" } },
     "targets": [
      {
       "dataset": "dev",
       "rawSql": "SELECT\r\n  time,\r\n  (\"CHARCOAL_FILTER_B01_FLOW\").value as charcoal_filter_flow,\r\n  (\"CHARCOAL_FILTER_B01_TEMP\").value as charcoal_filter_temp\r\nFROM marpower.\"250000_techwater\""
      }
     ]
    },
    {
     "title": "Salinity",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 48 },
     "fieldConfig": { "defaults": { "unit": "congm3" } },
     "targets": [
      {
       "dataset": "dev",
       "rawSql": "SELECT\r\n  time,\r\n  (\"SALINITY1\").value as salinity1,\r\n  (\"SALINITY2\").value as salinity2\r\nFROM marpower.\"250000_techwater\""
      }
     ]
    },
    {
     "title": "Tank level",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 56 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "dataset": "dev",
       "rawSql": "SELECT\r\n  time,\r\n  (\"TANK1_LEVEL\").value as tank1_level,\r\n  (\"TANK2_LEVEL\").value as tank2_level\r\nFROM marpower.\"250000_techwater\""
      }
     ]
    }
   ]
  }
 ]
}