{
 "title": "THRS-pre-september",
 "tags": [ "commissioning" ],
 "time": { "from": "2026-08-25T22:00:00.000Z", "to": "2026-08-27T21:59:59.000Z" },
 "templating": {
  "list": [
   { "name": "datasource", "query": "info8fcc-greptimedb-datasource" },
   {
    "name": "section",
    "label": "Section",
    "query": "adsorption,consumers,cooling,dc,dhw,drives,pcm,pvt,thrusters"
   }
  ]
 },
 "panels": [
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 0 },
   "options": {
    "content": "<center>\r\n  <h1>THRS</h1>\r\n</center>\r\n"
   }
  },
  { "title": "Temperature sensors", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 } },
  {
   "type": "timeseries",
   "gridPos": { "h": 16, "w": 24, "x": 0, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "rawSql": "SELECT\r\n\tthrs_data.timestamp          AS time,\r\n\tmetadata.device              AS device,\r\n\tthrs_data.temperature__value AS temperature\r\nFROM public.marpower__thrs__temperatures AS thrs_data\r\nJOIN (\r\n\tSELECT\r\n\t\tmqtt_topic,\r\n\t\tregexp_replace(mqtt_topic, 'marpower/500000-thrs/([^/]+)/.*$', '$1')                              AS \"section\",\r\n\t\tconcat('[', yard_tag, '] ', regexp_replace(mqtt_topic, 'marpower/500000-thrs/.*/([^/]+)$', '$1')) AS device\r\n\tFROM public.marpower__io_metadata\r\n\tWHERE mqtt_json_path = '$.Temperature'\r\n) AS metadata\r\nON thrs_data.topic = metadata.mqtt_topic\r\nWHERE $__timeFilter(timestamp)\r\nAND metadata.\"section\" IN (${section:sqlstring})\r\nORDER BY device, time ASC"
    }
   ]
  },
  { "title": "Flow sensors", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 19 } },
  {
   "title": "Flow",
   "type": "timeseries",
   "gridPos": { "h": 16, "w": 24, "x": 0, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "flowlpm" } },
   "targets": [
    {
     "rawSql": "SELECT\r\n\tthrs_data.timestamp          AS time,\r\n\tmetadata.device              AS device,\r\n\tthrs_data.flow__value        AS flow\r\nFROM public.marpower__thrs__flows AS thrs_data\r\nJOIN (\r\n\tSELECT\r\n\t\tmqtt_topic,\r\n\t\tregexp_replace(mqtt_topic, 'marpower/500000-thrs/([^/]+)/.*$', '$1')                              AS \"section\",\r\n\t\tconcat('[', yard_tag, '] ', regexp_replace(mqtt_topic, 'marpower/500000-thrs/.*/([^/]+)$', '$1')) AS device\r\n\tFROM public.marpower__io_metadata\r\n\tWHERE mqtt_json_path = '$.Flow'\r\n) AS metadata\r\nON thrs_data.topic = metadata.mqtt_topic\r\nWHERE $__timeFilter(timestamp)\r\nAND metadata.\"section\" IN (${section:sqlstring})\r\nORDER BY device, time ASC"
    }
   ]
  },
  {
   "title": "Temperature",
   "type": "timeseries",
   "gridPos": { "h": 16, "w": 24, "x": 0, "y": 36 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "rawSql": "SELECT\r\n\tthrs_data.timestamp          AS time,\r\n\tmetadata.device              AS device,\r\n\tthrs_data.temperature__value AS temperature\r\nFROM public.marpower__thrs__flows AS thrs_data\r\nJOIN (\r\n\tSELECT\r\n\t\tmqtt_topic,\r\n\t\tregexp_replace(mqtt_topic, 'marpower/500000-thrs/([^/]+)/.*$', '$1')                              AS \"section\",\r\n\t\tconcat('[', yard_tag, '] ', regexp_replace(mqtt_topic, 'marpower/500000-thrs/.*/([^/]+)$', '$1')) AS device\r\n\tFROM public.marpower__io_metadata\r\n\tWHERE mqtt_json_path = '$.Temperature'\r\n) AS metadata\r\nON thrs_data.topic = metadata.mqtt_topic\r\nWHERE $__timeFilter(timestamp)\r\nAND metadata.\"section\" IN (${section:sqlstring})\r\nORDER BY device, time ASC"
    }
   ]
  },
  {
   "title": "Quantity",
   "type": "timeseries",
   "gridPos": { "h": 16, "w": 24, "x": 0, "y": 52 },
   "fieldConfig": { "defaults": { "unit": "litre" } },
   "targets": [
    {
     "rawSql": "SELECT\r\n\tthrs_data.timestamp       AS time,\r\n\tmetadata.device           AS device,\r\n\tthrs_data.quantity__value AS quantity\r\nFROM public.marpower__thrs__flows AS thrs_data\r\nJOIN (\r\n\tSELECT\r\n\t\tmqtt_topic,\r\n\t\tregexp_replace(mqtt_topic, 'marpower/500000-thrs/([^/]+)/.*$', '$1')                              AS \"section\",\r\n\t\tconcat('[', yard_tag, '] ', regexp_replace(mqtt_topic, 'marpower/500000-thrs/.*/([^/]+)$', '$1')) AS device\r\n\tFROM public.marpower__io_metadata\r\n\tWHERE mqtt_json_path = '$.Quantity'\r\n) AS metadata\r\nON thrs_data.topic = metadata.mqtt_topic\r\nWHERE $__timeFilter(timestamp)\r\nAND metadata.\"section\" IN (${section:sqlstring})\r\nORDER BY device, time ASC"
    }
   ]
  },
  { "title": "Pressure sensors", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 68 } },
  {
   "type": "timeseries",
   "gridPos": { "h": 16, "w": 24, "x": 0, "y": 69 },
   "fieldConfig": { "defaults": { "unit": "pressurebar" } },
   "targets": [
    {
     "rawSql": "SELECT\r\n\tthrs_data.timestamp       AS time,\r\n\tmetadata.device           AS device,\r\n\tthrs_data.pressure__value AS pressure\r\nFROM public.marpower__thrs__pressures AS thrs_data\r\nJOIN (\r\n\tSELECT\r\n\t\tmqtt_topic,\r\n\t\tregexp_replace(mqtt_topic, 'marpower/500000-thrs/([^/]+)/.*$', '$1')                              AS \"section\",\r\n\t\tconcat('[', yard_tag, '] ', regexp_replace(mqtt_topic, 'marpower/500000-thrs/.*/([^/]+)$', '$1')) AS device\r\n\tFROM public.marpower__io_metadata\r\n\tWHERE mqtt_json_path = '$.Pressure'\r\n) AS metadata\r\nON thrs_data.topic = metadata.mqtt_topic\r\nWHERE $__timeFilter(timestamp)\r\nAND metadata.\"section\" IN (${section:sqlstring})\r\nORDER BY device, time ASC"
    }
   ]
  },
  { "title": "RH33s", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 85 } },
  {
   "title": "Flow",
   "type": "timeseries",
   "gridPos": { "h": 16, "w": 24, "x": 0, "y": 86 },
   "fieldConfig": { "defaults": { "unit": "flowlpm" } },
   "targets": [
    {
     "rawSql": "SELECT\r\n\tthrs_data.timestamp   AS time,\r\n\tmetadata.device       AS device,\r\n\tthrs_data.flow__value AS flow\r\nFROM public.marpower__thrs__rh33s AS thrs_data\r\nJOIN (\r\n\tSELECT\r\n\t\tmqtt_topic,\r\n\t\tregexp_replace(mqtt_topic, 'marpower/500000-thrs/([^/]+)/.*$', '$1')                              AS \"section\",\r\n\t\tconcat('[', yard_tag, '] ', regexp_replace(mqtt_topic, 'marpower/500000-thrs/.*/([^/]+)$', '$1')) AS device\r\n\tFROM public.marpower__io_metadata\r\n\tWHERE mqtt_json_path = '$.Flow'\r\n) AS metadata\r\nON thrs_data.topic = metadata.mqtt_topic\r\nWHERE $__timeFilter(timestamp)\r\nAND metadata.\"section\" IN (${section:sqlstring})\r\nORDER BY device, time ASC"
    }
   ]
  },
  {
   "title": "Temperature Warm",
   "type": "timeseries",
   "gridPos": { "h": 16, "w": 24, "x": 0, "y": 102 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "dataset": "dev",
     "rawSql": "SELECT\r\n\tthrs_data.timestamp               AS time,\r\n\tmetadata.device                   AS device,\r\n\tthrs_data.temperature_warm__value AS temperature\r\nFROM public.marpower__thrs__rh33s AS thrs_data\r\nJOIN (\r\n\tSELECT\r\n\t\tmqtt_topic,\r\n\t\tregexp_replace(mqtt_topic, 'marpower/500000-thrs/([^/]+)/.*$', '$1')                              AS \"section\",\r\n\t\tconcat('[', yard_tag, '] ', regexp_replace(mqtt_topic, 'marpower/500000-thrs/.*/([^/]+)$', '$1')) AS device\r\n\tFROM public.marpower__io_metadata\r\n\tWHERE mqtt_json_path = '$.TemperatureWarm'\r\n) AS metadata\r\nON thrs_data.topic = metadata.mqtt_topic\r\nWHERE $__timeFilter(timestamp)\r\nAND metadata.\"section\" IN (${section:sqlstring})\r\nORDER BY device, time ASC"
    }
   ]
  },
  {
   "title": "Temperature Cold",
   "type": "timeseries",
   "gridPos": { "h": 16, "w": 24, "x": 0, "y": 118 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "dataset": "dev",
     "rawSql": "SELECT\r\n\tthrs_data.timestamp               AS time,\r\n\tmetadata.device                   AS device,\r\n\tthrs_data.temperature_cold__value AS temperature\r\nFROM public.marpower__thrs__rh33s AS thrs_data\r\nJOIN (\r\n\tSELECT\r\n\t\tmqtt_topic,\r\n\t\tregexp_replace(mqtt_topic, 'marpower/500000-thrs/([^/]+)/.*$', '$1')                              AS \"section\",\r\n\t\tconcat('[', yard_tag, '] ', regexp_replace(mqtt_topic, 'marpower/500000-thrs/.*/([^/]+)$', '$1')) AS device\r\n\tFROM public.marpower__io_metadata\r\n\tWHERE mqtt_json_path = '$.TemperatureCold'\r\n) AS metadata\r\nON thrs_data.topic = metadata.mqtt_topic\r\nWHERE $__timeFilter(timestamp)\r\nAND metadata.\"section\" IN (${section:sqlstring})\r\nORDER BY device, time ASC"
    }
   ]
  },
  {
   "title": "Temperature Delta",
   "type": "timeseries",
   "gridPos": { "h": 16, "w": 24, "x": 0, "y": 134 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "rawSql": "SELECT\r\n\tthrs_data.timestamp                                                   AS time,\r\n\tmetadata.device                                                       AS device,\r\n  thrs_data.temperature_warm__value - thrs_data.temperature_cold__value AS delta_temperature\r\nFROM public.marpower__thrs__rh33s AS thrs_data\r\nJOIN (\r\n\tSELECT\r\n\t\tmqtt_topic,\r\n\t\tregexp_replace(mqtt_topic, 'marpower/500000-thrs/([^/]+)/.*$', '$1')                              AS \"section\",\r\n\t\tconcat('[', yard_tag, '] ', regexp_replace(mqtt_topic, 'marpower/500000-thrs/.*/([^/]+)$', '$1')) AS device\r\n\tFROM public.marpower__io_metadata\r\n\tWHERE mqtt_json_path = '$.TemperatureWarm'\r\n) AS metadata\r\nON thrs_data.topic = metadata.mqtt_topic\r\nWHERE $__timeFilter(timestamp)\r\nAND metadata.\"section\" IN (${section:sqlstring})\r\nORDER BY device, time ASC"
    }
   ]
  },
  { "title": "Tank level sensors", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 150 } },
  {
   "type": "timeseries",
   "gridPos": { "h": 16, "w": 24, "x": 0, "y": 151 },
   "fieldConfig": { "defaults": { "unit": "mamp" } },
   "targets": [
    {
     "rawSql": "SELECT\r\n\tthrs_data.timestamp         AS time,\r\n\tmetadata.device        AS device,\r\n\tthrs_data.level__value AS \"level\"\r\nFROM public.marpower__thrs__level_sensors AS thrs_data\r\nJOIN (\r\n\tSELECT\r\n\t\tmqtt_topic,\r\n\t\tregexp_replace(mqtt_topic, 'marpower/500000-thrs/([^/]+)/.*$', '$1')                              AS \"section\",\r\n\t\tconcat('[', yard_tag, '] ', regexp_replace(mqtt_topic, 'marpower/500000-thrs/.*/([^/]+)$', '$1')) AS device\r\n\tFROM public.marpower__io_metadata\r\n\tWHERE mqtt_json_path = '$.Level'\r\n) AS metadata\r\nON thrs_data.topic = metadata.mqtt_topic\r\nWHERE $__timeFilter(timestamp)\r\nAND metadata.\"section\" IN (${section:sqlstring})\r\nORDER BY device, time ASC"
    }
   ]
  },
  { "title": "Pyranometers", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 167 } },
  {
   "type": "timeseries",
   "gridPos": { "h": 16, "w": 24, "x": 0, "y": 168 },
   "fieldConfig": { "defaults": { "unit": "Wm2" } },
   "targets": [
    {
     "rawSql": "SELECT\r\n\tthrs_data.timestamp          AS time,\r\n\tmetadata.device              AS device,\r\n\tthrs_data.tirradiance__value AS irradiance\r\nFROM public.marpower__thrs__rh33s AS thrs_data\r\nJOIN (\r\n\tSELECT\r\n\t\tmqtt_topic,\r\n\t\tregexp_replace(mqtt_topic, 'marpower/500000-thrs/([^/]+)/.*$', '$1')                              AS \"section\",\r\n\t\tconcat('[', yard_tag, '] ', regexp_replace(mqtt_topic, 'marpower/500000-thrs/.*/([^/]+)$', '$1')) AS device\r\n\tFROM public.marpower__io_metadata\r\n\tWHERE mqtt_json_path = '$.Irradiance'\r\n) AS metadata\r\nON thrs_data.topic = metadata.mqtt_topic\r\nWHERE $__timeFilter(timestamp)\r\nAND metadata.\"section\" IN (${section:sqlstring})\r\nORDER BY device, time ASC"
    }
   ]
  },
  {
   "title": "Pumps",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 184 },
   "collapsed": true,
   "panels": [
    {
     "title": "Speed",
     "type": "timeseries",
     "gridPos": { "h": 16, "w": 24, "x": 0, "y": 185 },
     "fieldConfig": { "defaults": { "unit": "rothz" } },
     "targets": [
      {
       "rawSql": "SELECT\r\n\tthrs_data.timestamp    AS time,\r\n\tmetadata.device        AS device,\r\n\tthrs_data.speed__value AS speed\r\nFROM public.marpower__thrs__pumps_old AS thrs_data\r\nJOIN (\r\n\tSELECT\r\n\t\tmqtt_topic,\r\n\t\tregexp_replace(mqtt_topic, 'marpower/500000-thrs/([^/]+)/.*$', '$1')                              AS \"section\",\r\n\t\tconcat('[', yard_tag, '] ', regexp_replace(mqtt_topic, 'marpower/500000-thrs/.*/([^/]+)$', '$1')) AS device\r\n\tFROM public.marpower__io_metadata\r\n\tWHERE mqtt_json_path = '$.Speed'\r\n) AS metadata\r\nON thrs_data.topic = metadata.mqtt_topic\r\nWHERE $__timeFilter(timestamp)\r\nAND metadata.\"section\" IN (${section:sqlstring})\r\nORDER BY device, time ASC"
      }
     ]
    },
    {
     "title": "Flow",
     "type": "timeseries",
     "gridPos": { "h": 16, "w": 24, "x": 0, "y": 249 },
     "fieldConfig": { "defaults": { "unit": "flowlpm" } },
     "targets": [
      {
       "dataset": "dev",
       "rawSql": "SELECT\r\n\tthrs_data.timestamp   AS time,\r\n\tmetadata.device       AS device,\r\n\tthrs_data.flow__value AS flow\r\nFROM public.marpower__thrs__pumps AS thrs_data\r\nJOIN (\r\n\tSELECT\r\n\t\tmqtt_topic,\r\n\t\tregexp_replace(mqtt_topic, 'marpower/500000-thrs/([^/]+)/.*$', '$1')                              AS \"section\",\r\n\t\tconcat('[', yard_tag, '] ', regexp_replace(mqtt_topic, 'marpower/500000-thrs/.*/([^/]+)$', '$1')) AS device\r\n\tFROM public.marpower__io_metadata\r\n\tWHERE mqtt_json_path = '$.Flow'\r\n) AS metadata\r\nON thrs_data.topic = metadata.mqtt_topic\r\nWHERE $__timeFilter(timestamp)\r\nAND metadata.\"section\" IN (${section:sqlstring})\r\nORDER BY device, time ASC"
      }
     ]
    },
    {
     "title": "Pressure",
     "type": "timeseries",
     "gridPos": { "h": 16, "w": 24, "x": 0, "y": 265 },
     "fieldConfig": { "defaults": { "unit": "pressurebar" } },
     "targets": [
      {
       "dataset": "dev",
       "rawSql": "SELECT\r\n\tthrs_data.timestamp       AS time,\r\n\tmetadata.device           AS device,\r\n\tthrs_data.pressure__value AS pressure\r\nFROM public.marpower__thrs__pumps AS thrs_data\r\nJOIN (\r\n\tSELECT\r\n\t\tmqtt_topic,\r\n\t\tregexp_replace(mqtt_topic, 'marpower/500000-thrs/([^/]+)/.*$', '$1')                              AS \"section\",\r\n\t\tconcat('[', yard_tag, '] ', regexp_replace(mqtt_topic, 'marpower/500000-thrs/.*/([^/]+)$', '$1')) AS device\r\n\tFROM public.marpower__io_metadata\r\n\tWHERE mqtt_json_path = '$.Pressure'\r\n) AS metadata\r\nON thrs_data.topic = metadata.mqtt_topic\r\nWHERE $__timeFilter(timestamp)\r\nAND metadata.\"section\" IN (${section:sqlstring})\r\nORDER BY device, time ASC"
      }
     ]
    },
    {
     "title": "Power input",
     "type": "timeseries",
     "gridPos": { "h": 16, "w": 24, "x": 0, "y": 281 },
     "fieldConfig": { "defaults": { "unit": "watt" } },
     "targets": [
      {
       "dataset": "dev",
       "rawSql": "SELECT\r\n\tthrs_data.timestamp       AS time,\r\n\tmetadata.device           AS device,\r\n\tthrs_data.power_input__value AS power_input\r\nFROM public.marpower__thrs__pumps AS thrs_data\r\nJOIN (\r\n\tSELECT\r\n\t\tmqtt_topic,\r\n\t\tregexp_replace(mqtt_topic, 'marpower/500000-thrs/([^/]+)/.*$', '$1')                              AS \"section\",\r\n\t\tconcat('[', yard_tag, '] ', regexp_replace(mqtt_topic, 'marpower/500000-thrs/.*/([^/]+)$', '$1')) AS device\r\n\tFROM public.marpower__io_metadata\r\n\tWHERE mqtt_json_path = '$.PowerInput'\r\n) AS metadata\r\nON thrs_data.topic = metadata.mqtt_topic\r\nWHERE $__timeFilter(timestamp)\r\nAND metadata.\"section\" IN (${section:sqlstring})\r\nORDER BY device, time ASC"
      }
     ]
    },
    {
     "title": "Energy consumption",
     "type": "timeseries",
     "gridPos": { "h": 16, "w": 24, "x": 0, "y": 297 },
     "fieldConfig": { "defaults": { "unit": "joule" } },
     "targets": [
      {
       "dataset": "dev",
       "rawSql": "SELECT\r\n\tthrs_data.timestamp                 AS time,\r\n\tmetadata.device                     AS device,\r\n\tthrs_data.energy_consumption__value AS energy_consumption\r\nFROM public.marpower__thrs__pumps AS thrs_data\r\nJOIN (\r\n\tSELECT\r\n\t\tmqtt_topic,\r\n\t\tregexp_replace(mqtt_topic, 'marpower/500000-thrs/([^/]+)/.*$', '$1')                              AS \"section\",\r\n\t\tconcat('[', yard_tag, '] ', regexp_replace(mqtt_topic, 'marpower/500000-thrs/.*/([^/]+)$', '$1')) AS device\r\n\tFROM public.marpower__io_metadata\r\n\tWHERE mqtt_json_path = '$.EnergyConsumption'\r\n) AS metadata\r\nON thrs_data.topic = metadata.mqtt_topic\r\nWHERE $__timeFilter(timestamp)\r\nAND metadata.\"section\" IN (${section:sqlstring})\r\nORDER BY device, time ASC"
      }
     ]
    },
    {
     "title": "Operation time",
     "type": "timeseries",
     "gridPos": { "h": 16, "w": 24, "x": 0, "y": 313 },
     "fieldConfig": { "defaults": { "unit": "h" } },
     "targets": [
      {
       "dataset": "dev",
       "rawSql": "SELECT\r\n\tthrs_data.timestamp      AS time,\r\n\tmetadata.device          AS device,\r\n\tthrs_data.op_time__value AS operation_time\r\nFROM public.marpower__thrs__pumps AS thrs_data\r\nJOIN (\r\n\tSELECT\r\n\t\tmqtt_topic,\r\n\t\tregexp_replace(mqtt_topic, 'marpower/500000-thrs/([^/]+)/.*$', '$1')                              AS \"section\",\r\n\t\tconcat('[', yard_tag, '] ', regexp_replace(mqtt_topic, 'marpower/500000-thrs/.*/([^/]+)$', '$1')) AS device\r\n\tFROM public.marpower__io_metadata\r\n\tWHERE mqtt_json_path = '$.OpTime'\r\n) AS metadata\r\nON thrs_data.topic = metadata.mqtt_topic\r\nWHERE $__timeFilter(timestamp)\r\nAND metadata.\"section\" IN (${section:sqlstring})\r\nORDER BY device, time ASC"
      }
     ]
    },
    {
     "title": "Duty point",
     "type": "timeseries",
     "gridPos": { "h": 16, "w": 24, "x": 0, "y": 329 },
     "targets": [
      {
       "dataset": "dev",
       "rawSql": "SELECT\r\n\tthrs_data.timestamp            AS time,\r\n\tmetadata.device                AS device,\r\n\tthrs_data.cc_duty_point__value AS duty_point\r\nFROM public.marpower__thrs__pumps AS thrs_data\r\nJOIN (\r\n\tSELECT\r\n\t\tmqtt_topic,\r\n\t\tregexp_replace(mqtt_topic, 'marpower/500000-thrs/([^/]+)/.*$', '$1')                              AS \"section\",\r\n\t\tconcat('[', yard_tag, '] ', regexp_replace(mqtt_topic, 'marpower/500000-thrs/.*/([^/]+)$', '$1')) AS device\r\n\tFROM public.marpower__io_metadata\r\n\tWHERE mqtt_json_path = '$.CC_DutyPoint'\r\n) AS metadata\r\nON thrs_data.topic = metadata.mqtt_topic\r\nWHERE $__timeFilter(timestamp)\r\nAND metadata.\"section\" IN (${section:sqlstring})\r\nORDER BY device, time ASC"
      }
     ]
    },
    {
     "title": "Control mode",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 345 },
     "targets": [
      {
       "dataset": "dev",
       "rawSql": "SELECT\r\n\tthrs_data.timestamp              AS time,\r\n\tmetadata.device                  AS device,\r\n\tthrs_data.cc_control_mode__value AS control_mode\r\nFROM public.marpower__thrs__pumps AS thrs_data\r\nJOIN (\r\n\tSELECT\r\n\t\tmqtt_topic,\r\n\t\tregexp_replace(mqtt_topic, 'marpower/500000-thrs/([^/]+)/.*$', '$1')                              AS \"section\",\r\n\t\tconcat('[', yard_tag, '] ', regexp_replace(mqtt_topic, 'marpower/500000-thrs/.*/([^/]+)$', '$1')) AS device\r\n\tFROM public.marpower__io_metadata\r\n\tWHERE mqtt_json_path = '$.CC_ControlMode'\r\n) AS metadata\r\nON thrs_data.topic = metadata.mqtt_topic\r\nWHERE $__timeFilter(timestamp)\r\nAND metadata.\"section\" IN (${section:sqlstring})\r\nORDER BY device, time ASC"
      }
     ]
    },
    {
     "title": "On / Off",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 353 },
     "targets": [
      {
       "dataset": "dev",
       "rawSql": "SELECT\r\n\tthrs_data.timestamp             AS time,\r\n\tmetadata.device                 AS device,\r\n\tthrs_data.cc_on_off__value::INT AS on_off\r\nFROM public.marpower__thrs__pumps AS thrs_data\r\nJOIN (\r\n\tSELECT\r\n\t\tmqtt_topic,\r\n\t\tregexp_replace(mqtt_topic, 'marpower/500000-thrs/([^/]+)/.*$', '$1')                              AS \"section\",\r\n\t\tconcat('[', yard_tag, '] ', regexp_replace(mqtt_topic, 'marpower/500000-thrs/.*/([^/]+)$', '$1')) AS device\r\n\tFROM public.marpower__io_metadata\r\n\tWHERE mqtt_json_path = '$.CC_OnOff'\r\n) AS metadata\r\nON thrs_data.topic = metadata.mqtt_topic\r\nWHERE $__timeFilter(timestamp)\r\nAND metadata.\"section\" IN (${section:sqlstring})\r\nORDER BY device, time ASC"
      }
     ]
    }
   ]
  },
  { "title": "Valves", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 185 } },
  {
   "title": "Absolute position",
   "type": "timeseries",
   "gridPos": { "h": 16, "w": 24, "x": 0, "y": 186 },
   "fieldConfig": { "defaults": { "unit": "degree" } },
   "targets": [
    {
     "dataset": "dev",
     "rawSql": "SELECT\r\n\tthrs_data.timestamp           AS time,\r\n\tmetadata.device               AS device,\r\n\tthrs_data.position_abs__value AS \"position\"\r\nFROM public.marpower__thrs__valves_old AS thrs_data\r\nJOIN (\r\n\tSELECT\r\n\t\tmqtt_topic,\r\n\t\tregexp_replace(mqtt_topic, 'marpower/500000-thrs/([^/]+)/.*$', '$1')                              AS \"section\",\r\n\t\tconcat('[', yard_tag, '] ', regexp_replace(mqtt_topic, 'marpower/500000-thrs/.*/([^/]+)$', '$1')) AS device\r\n\tFROM public.marpower__io_metadata\r\n\tWHERE mqtt_json_path = '$.PositionAbs'\r\n) AS metadata\r\nON thrs_data.topic = metadata.mqtt_topic\r\nWHERE $__timeFilter(timestamp)\r\nAND metadata.\"section\" IN (${section:sqlstring})\r\nORDER BY device, time ASC"
    }
   ]
  },
  {
   "title": "Relative position",
   "type": "timeseries",
   "gridPos": { "h": 16, "w": 24, "x": 0, "y": 202 },
   "targets": [
    {
     "dataset": "dev",
     "rawSql": "SELECT\r\n\tthrs_data.timestamp           AS time,\r\n\tmetadata.device               AS device,\r\n\tthrs_data.position_rel__value AS \"position\"\r\nFROM public.marpower__thrs__valves AS thrs_data\r\nJOIN (\r\n\tSELECT\r\n\t\tmqtt_topic,\r\n\t\tregexp_replace(mqtt_topic, 'marpower/500000-thrs/([^/]+)/.*$', '$1')                              AS \"section\",\r\n\t\tconcat('[', yard_tag, '] ', regexp_replace(mqtt_topic, 'marpower/500000-thrs/.*/([^/]+)$', '$1')) AS device\r\n\tFROM public.marpower__io_metadata\r\n\tWHERE mqtt_json_path = '$.PositionRel'\r\n) AS metadata\r\nON thrs_data.topic = metadata.mqtt_topic\r\nWHERE $__timeFilter(timestamp)\r\nAND metadata.\"section\" IN (${section:sqlstring})\r\nORDER BY device, time ASC"
    }
   ]
  },
  {
   "title": "Setpoint",
   "type": "timeseries",
   "gridPos": { "h": 16, "w": 24, "x": 0, "y": 218 },
   "targets": [
    {
     "dataset": "dev",
     "rawSql": "SELECT\r\n\tthrs_data.timestamp          AS time,\r\n\tmetadata.device              AS device,\r\n\tthrs_data.cc_setpoint__value AS setpoint\r\nFROM public.marpower__thrs__valves AS thrs_data\r\nJOIN (\r\n\tSELECT\r\n\t\tmqtt_topic,\r\n\t\tregexp_replace(mqtt_topic, 'marpower/500000-thrs/([^/]+)/.*$', '$1')                              AS \"section\",\r\n\t\tconcat('[', yard_tag, '] ', regexp_replace(mqtt_topic, 'marpower/500000-thrs/.*/([^/]+)$', '$1')) AS device\r\n\tFROM public.marpower__io_metadata\r\n\tWHERE mqtt_json_path = '$.Setpoint'\r\n) AS metadata\r\nON thrs_data.topic = metadata.mqtt_topic\r\nWHERE $__timeFilter(timestamp)\r\nAND metadata.\"section\" IN (${section:sqlstring})\r\nORDER BY device, time ASC"
    }
   ]
  }
 ]
}