{
 "title": "THRS",
 "tags": [ "commissioning" ],
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "query": "info8fcc-greptimedb-datasource" },
   {
    "name": "section",
    "label": "Section",
    "query": "adsorption,consumers,cooling,dc,dhw,drives,pcm,pvt,thrusters"
   },
   {
    "name": "device",
    "label": "Device",
    "query": "SELECT DISTINCT split_part(mqtt_topic,'/',4) AS __value, concat('[', yard_tag, '] ', split_part(mqtt_topic,'/',4)) AS __text FROM public.marpower__io_metadata WHERE mqtt_topic LIKE 'marpower/500000-thrs/%' AND yard_tag IS NOT NULL AND yard_tag <> '' AND ( '${section:raw}' = '$__all' OR split_part(mqtt_topic,'/',3) IN (${section:sqlstring}) ) ORDER BY 1"
   }
  ]
 },
 "panels": [
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 0 },
   "options": {
    "content": "<center>\r\n  <h1>THRS</h1>\r\n</center>\r\n"
   }
  },
  {
   "title": "Temperature sensors",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 },
   "collapsed": true,
   "panels": [
    {
     "type": "timeseries",
     "gridPos": { "h": 16, "w": 24, "x": 0, "y": 3 },
     "fieldConfig": { "defaults": { "unit": "celsius" } },
     "targets": [
      {
       "rawSql": "SELECT\n\tdate_bin('$__interval', thrs_data.timestamp) AS time,\n\tconcat('[', coalesce(metadata.yard_tag, ''), '] ', thrs_data.technical_name) AS device,\n\tAVG(temperature__value) AS \"temperature\"\nFROM public.marpower__thrs__temperatures AS thrs_data\nLEFT JOIN (\n  SELECT DISTINCT mqtt_topic, yard_tag FROM public.marpower__io_metadata WHERE mqtt_topic LIKE 'marpower/500000-thrs/%'\n) AS metadata ON thrs_data.topic = metadata.mqtt_topic\nWHERE $__timeFilter(timestamp)\n  AND ',' || '${section:csv}' || ',' LIKE '%,' || split_part(thrs_data.topic, '/', 3) || ',%'\n  AND ',' || '${device:csv}' || ',' LIKE '%,' || thrs_data.technical_name || ',%'\nGROUP BY 1, 2\nORDER BY 2, 1 ASC"
      }
     ]
    }
   ]
  },
  {
   "title": "Flow sensors",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 3 },
   "collapsed": true,
   "panels": [
    {
     "title": "Flow",
     "type": "timeseries",
     "gridPos": { "h": 16, "w": 24, "x": 0, "y": 4 },
     "fieldConfig": { "defaults": { "unit": "flowlpm" } },
     "targets": [
      {
       "rawSql": "SELECT\n\tdate_bin('$__interval', thrs_data.timestamp) AS time,\n\tconcat('[', coalesce(metadata.yard_tag, ''), '] ', thrs_data.technical_name) AS device,\n\tAVG(flow__value) AS \"flow\"\nFROM public.marpower__thrs__flows AS thrs_data\nLEFT JOIN (\n  SELECT DISTINCT mqtt_topic, yard_tag FROM public.marpower__io_metadata WHERE mqtt_topic LIKE 'marpower/500000-thrs/%'\n) AS metadata ON thrs_data.topic = metadata.mqtt_topic\nWHERE $__timeFilter(timestamp)\n  AND ',' || '${section:csv}' || ',' LIKE '%,' || split_part(thrs_data.topic, '/', 3) || ',%'\n  AND ',' || '${device:csv}' || ',' LIKE '%,' || thrs_data.technical_name || ',%'\nGROUP BY 1, 2\nORDER BY 2, 1 ASC"
      }
     ]
    },
    {
     "title": "Temperature",
     "type": "timeseries",
     "gridPos": { "h": 16, "w": 24, "x": 0, "y": 20 },
     "fieldConfig": { "defaults": { "unit": "celsius" } },
     "targets": [
      {
       "rawSql": "SELECT\n\tdate_bin('$__interval', thrs_data.timestamp) AS time,\n\tconcat('[', coalesce(metadata.yard_tag, ''), '] ', thrs_data.technical_name) AS device,\n\tAVG(temperature__value) AS \"temperature\"\nFROM public.marpower__thrs__flows AS thrs_data\nLEFT JOIN (\n  SELECT DISTINCT mqtt_topic, yard_tag FROM public.marpower__io_metadata WHERE mqtt_topic LIKE 'marpower/500000-thrs/%'\n) AS metadata ON thrs_data.topic = metadata.mqtt_topic\nWHERE $__timeFilter(timestamp)\n  AND ',' || '${section:csv}' || ',' LIKE '%,' || split_part(thrs_data.topic, '/', 3) || ',%'\n  AND ',' || '${device:csv}' || ',' LIKE '%,' || thrs_data.technical_name || ',%'\nGROUP BY 1, 2\nORDER BY 2, 1 ASC"
      }
     ]
    },
    {
     "title": "Quantity",
     "type": "timeseries",
     "gridPos": { "h": 16, "w": 24, "x": 0, "y": 36 },
     "fieldConfig": { "defaults": { "unit": "litre" } },
     "targets": [
      {
       "rawSql": "SELECT\n\tdate_bin('$__interval', thrs_data.timestamp) AS time,\n\tconcat('[', coalesce(metadata.yard_tag, ''), '] ', thrs_data.technical_name) AS device,\n\tMAX(quantity__value) AS \"quantity\"\nFROM public.marpower__thrs__flows AS thrs_data\nLEFT JOIN (\n  SELECT DISTINCT mqtt_topic, yard_tag FROM public.marpower__io_metadata WHERE mqtt_topic LIKE 'marpower/500000-thrs/%'\n) AS metadata ON thrs_data.topic = metadata.mqtt_topic\nWHERE $__timeFilter(timestamp)\n  AND ',' || '${section:csv}' || ',' LIKE '%,' || split_part(thrs_data.topic, '/', 3) || ',%'\n  AND ',' || '${device:csv}' || ',' LIKE '%,' || thrs_data.technical_name || ',%'\nGROUP BY 1, 2\nORDER BY 2, 1 ASC"
      }
     ]
    }
   ]
  },
  {
   "title": "Pressure sensors",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4 },
   "collapsed": true,
   "panels": [
    {
     "type": "timeseries",
     "gridPos": { "h": 16, "w": 24, "x": 0, "y": 5 },
     "fieldConfig": { "defaults": { "unit": "pressurebar" } },
     "targets": [
      {
       "rawSql": "SELECT\n\tdate_bin('$__interval', thrs_data.timestamp) AS time,\n\tconcat('[', coalesce(metadata.yard_tag, ''), '] ', thrs_data.technical_name) AS device,\n\tAVG(pressure__value) AS \"pressure\"\nFROM public.marpower__thrs__pressures AS thrs_data\nLEFT JOIN (\n  SELECT DISTINCT mqtt_topic, yard_tag FROM public.marpower__io_metadata WHERE mqtt_topic LIKE 'marpower/500000-thrs/%'\n) AS metadata ON thrs_data.topic = metadata.mqtt_topic\nWHERE $__timeFilter(timestamp)\n  AND ',' || '${section:csv}' || ',' LIKE '%,' || split_part(thrs_data.topic, '/', 3) || ',%'\n  AND ',' || '${device:csv}' || ',' LIKE '%,' || thrs_data.technical_name || ',%'\nGROUP BY 1, 2\nORDER BY 2, 1 ASC"
      }
     ]
    }
   ]
  },
  {
   "title": "RH33s",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 },
   "collapsed": true,
   "panels": [
    {
     "title": "Flow",
     "type": "timeseries",
     "gridPos": { "h": 16, "w": 24, "x": 0, "y": 6 },
     "fieldConfig": { "defaults": { "unit": "flowlpm" } },
     "targets": [
      {
       "rawSql": "SELECT\n\tdate_bin('$__interval', thrs_data.timestamp) AS time,\n\tconcat('[', coalesce(metadata.yard_tag, ''), '] ', thrs_data.technical_name) AS device,\n\tAVG(flow__value) AS \"flow\"\nFROM public.marpower__thrs__rh33s AS thrs_data\nLEFT JOIN (\n  SELECT DISTINCT mqtt_topic, yard_tag FROM public.marpower__io_metadata WHERE mqtt_topic LIKE 'marpower/500000-thrs/%'\n) AS metadata ON thrs_data.topic = metadata.mqtt_topic\nWHERE $__timeFilter(timestamp)\n  AND ',' || '${section:csv}' || ',' LIKE '%,' || split_part(thrs_data.topic, '/', 3) || ',%'\n  AND ',' || '${device:csv}' || ',' LIKE '%,' || thrs_data.technical_name || ',%'\nGROUP BY 1, 2\nORDER BY 2, 1 ASC"
      }
     ]
    },
    {
     "title": "Temperature Warm",
     "type": "timeseries",
     "gridPos": { "h": 16, "w": 24, "x": 0, "y": 22 },
     "fieldConfig": { "defaults": { "unit": "celsius" } },
     "targets": [
      {
       "dataset": "dev",
       "rawSql": "SELECT\n\tdate_bin('$__interval', thrs_data.timestamp) AS time,\n\tconcat('[', coalesce(metadata.yard_tag, ''), '] ', thrs_data.technical_name) AS device,\n\tAVG(temperature_warm__value) AS \"temperature_warm\"\nFROM public.marpower__thrs__rh33s AS thrs_data\nLEFT JOIN (\n  SELECT DISTINCT mqtt_topic, yard_tag FROM public.marpower__io_metadata WHERE mqtt_topic LIKE 'marpower/500000-thrs/%'\n) AS metadata ON thrs_data.topic = metadata.mqtt_topic\nWHERE $__timeFilter(timestamp)\n  AND ',' || '${section:csv}' || ',' LIKE '%,' || split_part(thrs_data.topic, '/', 3) || ',%'\n  AND ',' || '${device:csv}' || ',' LIKE '%,' || thrs_data.technical_name || ',%'\nGROUP BY 1, 2\nORDER BY 2, 1 ASC"
      }
     ]
    },
    {
     "title": "Temperature Cold",
     "type": "timeseries",
     "gridPos": { "h": 16, "w": 24, "x": 0, "y": 38 },
     "fieldConfig": { "defaults": { "unit": "celsius" } },
     "targets": [
      {
       "dataset": "dev",
       "rawSql": "SELECT\n\tdate_bin('$__interval', thrs_data.timestamp) AS time,\n\tconcat('[', coalesce(metadata.yard_tag, ''), '] ', thrs_data.technical_name) AS device,\n\tAVG(temperature_cold__value) AS \"temperature_cold\"\nFROM public.marpower__thrs__rh33s AS thrs_data\nLEFT JOIN (\n  SELECT DISTINCT mqtt_topic, yard_tag FROM public.marpower__io_metadata WHERE mqtt_topic LIKE 'marpower/500000-thrs/%'\n) AS metadata ON thrs_data.topic = metadata.mqtt_topic\nWHERE $__timeFilter(timestamp)\n  AND ',' || '${section:csv}' || ',' LIKE '%,' || split_part(thrs_data.topic, '/', 3) || ',%'\n  AND ',' || '${device:csv}' || ',' LIKE '%,' || thrs_data.technical_name || ',%'\nGROUP BY 1, 2\nORDER BY 2, 1 ASC"
      }
     ]
    },
    {
     "title": "Temperature Delta",
     "type": "timeseries",
     "gridPos": { "h": 16, "w": 24, "x": 0, "y": 54 },
     "fieldConfig": { "defaults": { "unit": "celsius" } },
     "targets": [
      {
       "rawSql": "SELECT\n\tdate_bin('$__interval', thrs_data.timestamp) AS time,\n\tconcat('[', coalesce(metadata.yard_tag, ''), '] ', thrs_data.technical_name) AS device,\n\tAVG(temperature_warm__value - temperature_cold__value) AS \"delta_temperature\"\nFROM public.marpower__thrs__rh33s AS thrs_data\nLEFT JOIN (\n  SELECT DISTINCT mqtt_topic, yard_tag FROM public.marpower__io_metadata WHERE mqtt_topic LIKE 'marpower/500000-thrs/%'\n) AS metadata ON thrs_data.topic = metadata.mqtt_topic\nWHERE $__timeFilter(timestamp)\n  AND ',' || '${section:csv}' || ',' LIKE '%,' || split_part(thrs_data.topic, '/', 3) || ',%'\n  AND ',' || '${device:csv}' || ',' LIKE '%,' || thrs_data.technical_name || ',%'\nGROUP BY 1, 2\nORDER BY 2, 1 ASC"
      }
     ]
    }
   ]
  },
  {
   "title": "Tank level sensors",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 6 },
   "collapsed": true,
   "panels": [
    {
     "type": "timeseries",
     "gridPos": { "h": 16, "w": 24, "x": 0, "y": 7 },
     "fieldConfig": { "defaults": { "unit": "mamp" } },
     "targets": [
      {
       "rawSql": "SELECT\n\tdate_bin('$__interval', thrs_data.timestamp) AS time,\n\tconcat('[', coalesce(metadata.yard_tag, ''), '] ', thrs_data.technical_name) AS device,\n\tAVG(level__value) AS \"level\"\nFROM public.marpower__thrs__level_sensors AS thrs_data\nLEFT JOIN (\n  SELECT DISTINCT mqtt_topic, yard_tag FROM public.marpower__io_metadata WHERE mqtt_topic LIKE 'marpower/500000-thrs/%'\n) AS metadata ON thrs_data.topic = metadata.mqtt_topic\nWHERE $__timeFilter(timestamp)\n  AND ',' || '${section:csv}' || ',' LIKE '%,' || split_part(thrs_data.topic, '/', 3) || ',%'\n  AND ',' || '${device:csv}' || ',' LIKE '%,' || thrs_data.technical_name || ',%'\nGROUP BY 1, 2\nORDER BY 2, 1 ASC"
      }
     ]
    }
   ]
  },
  {
   "title": "Pyranometers",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 },
   "collapsed": true,
   "panels": [
    {
     "type": "timeseries",
     "gridPos": { "h": 16, "w": 24, "x": 0, "y": 8 },
     "fieldConfig": { "defaults": { "unit": "Wm2" } },
     "targets": [
      {
       "rawSql": "SELECT\n\tdate_bin('$__interval', thrs_data.timestamp) AS time,\n\tconcat('[', coalesce(metadata.yard_tag, ''), '] ', thrs_data.technical_name) AS device,\n\tAVG(irradiance__value) AS \"irradiance\"\nFROM public.marpower__thrs__pyranometers AS thrs_data\nLEFT JOIN (\n  SELECT DISTINCT mqtt_topic, yard_tag FROM public.marpower__io_metadata WHERE mqtt_topic LIKE 'marpower/500000-thrs/%'\n) AS metadata ON thrs_data.topic = metadata.mqtt_topic\nWHERE $__timeFilter(timestamp)\n  AND ',' || '${section:csv}' || ',' LIKE '%,' || split_part(thrs_data.topic, '/', 3) || ',%'\n  AND ',' || '${device:csv}' || ',' LIKE '%,' || thrs_data.technical_name || ',%'\nGROUP BY 1, 2\nORDER BY 2, 1 ASC"
      }
     ]
    }
   ]
  },
  {
   "title": "Pumps",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 },
   "collapsed": true,
   "panels": [
    {
     "title": "Speed",
     "type": "timeseries",
     "gridPos": { "h": 16, "w": 24, "x": 0, "y": 9 },
     "fieldConfig": { "defaults": { "unit": "rothz" } },
     "targets": [
      {
       "rawSql": "SELECT\n\tdate_bin('$__interval', thrs_data.timestamp) AS time,\n\tconcat('[', coalesce(metadata.yard_tag, ''), '] ', thrs_data.technical_name) AS device,\n\tAVG(speed__value) AS \"speed\"\nFROM public.marpower__thrs__pumps AS thrs_data\nLEFT JOIN (\n  SELECT DISTINCT mqtt_topic, yard_tag FROM public.marpower__io_metadata WHERE mqtt_topic LIKE 'marpower/500000-thrs/%'\n) AS metadata ON thrs_data.topic = metadata.mqtt_topic\nWHERE $__timeFilter(timestamp)\n  AND ',' || '${section:csv}' || ',' LIKE '%,' || split_part(thrs_data.topic, '/', 3) || ',%'\n  AND ',' || '${device:csv}' || ',' LIKE '%,' || thrs_data.technical_name || ',%'\nGROUP BY 1, 2\nORDER BY 2, 1 ASC"
      }
     ]
    },
    {
     "title": "Flow",
     "type": "timeseries",
     "gridPos": { "h": 16, "w": 24, "x": 0, "y": 25 },
     "fieldConfig": { "defaults": { "unit": "flowlpm" } },
     "targets": [
      {
       "dataset": "dev",
       "rawSql": "SELECT\n\tdate_bin('$__interval', thrs_data.timestamp) AS time,\n\tconcat('[', coalesce(metadata.yard_tag, ''), '] ', thrs_data.technical_name) AS device,\n\tAVG(flow__value) AS \"flow\"\nFROM public.marpower__thrs__pumps AS thrs_data\nLEFT JOIN (\n  SELECT DISTINCT mqtt_topic, yard_tag FROM public.marpower__io_metadata WHERE mqtt_topic LIKE 'marpower/500000-thrs/%'\n) AS metadata ON thrs_data.topic = metadata.mqtt_topic\nWHERE $__timeFilter(timestamp)\n  AND ',' || '${section:csv}' || ',' LIKE '%,' || split_part(thrs_data.topic, '/', 3) || ',%'\n  AND ',' || '${device:csv}' || ',' LIKE '%,' || thrs_data.technical_name || ',%'\nGROUP BY 1, 2\nORDER BY 2, 1 ASC"
      }
     ]
    },
    {
     "title": "Pressure",
     "type": "timeseries",
     "gridPos": { "h": 16, "w": 24, "x": 0, "y": 41 },
     "fieldConfig": { "defaults": { "unit": "pressurebar" } },
     "targets": [
      {
       "dataset": "dev",
       "rawSql": "SELECT\n\tdate_bin('$__interval', thrs_data.timestamp) AS time,\n\tconcat('[', coalesce(metadata.yard_tag, ''), '] ', thrs_data.technical_name) AS device,\n\tAVG(pressure__value) AS \"pressure\"\nFROM public.marpower__thrs__pumps AS thrs_data\nLEFT JOIN (\n  SELECT DISTINCT mqtt_topic, yard_tag FROM public.marpower__io_metadata WHERE mqtt_topic LIKE 'marpower/500000-thrs/%'\n) AS metadata ON thrs_data.topic = metadata.mqtt_topic\nWHERE $__timeFilter(timestamp)\n  AND ',' || '${section:csv}' || ',' LIKE '%,' || split_part(thrs_data.topic, '/', 3) || ',%'\n  AND ',' || '${device:csv}' || ',' LIKE '%,' || thrs_data.technical_name || ',%'\nGROUP BY 1, 2\nORDER BY 2, 1 ASC"
      }
     ]
    },
    {
     "title": "Power input",
     "type": "timeseries",
     "gridPos": { "h": 16, "w": 24, "x": 0, "y": 57 },
     "fieldConfig": { "defaults": { "unit": "watt" } },
     "targets": [
      {
       "dataset": "dev",
       "rawSql": "SELECT\n\tdate_bin('$__interval', thrs_data.timestamp) AS time,\n\tconcat('[', coalesce(metadata.yard_tag, ''), '] ', thrs_data.technical_name) AS device,\n\tAVG(power_input__value) AS \"power_input\"\nFROM public.marpower__thrs__pumps AS thrs_data\nLEFT JOIN (\n  SELECT DISTINCT mqtt_topic, yard_tag FROM public.marpower__io_metadata WHERE mqtt_topic LIKE 'marpower/500000-thrs/%'\n) AS metadata ON thrs_data.topic = metadata.mqtt_topic\nWHERE $__timeFilter(timestamp)\n  AND ',' || '${section:csv}' || ',' LIKE '%,' || split_part(thrs_data.topic, '/', 3) || ',%'\n  AND ',' || '${device:csv}' || ',' LIKE '%,' || thrs_data.technical_name || ',%'\nGROUP BY 1, 2\nORDER BY 2, 1 ASC"
      }
     ]
    },
    {
     "title": "Energy consumption",
     "type": "timeseries",
     "gridPos": { "h": 16, "w": 24, "x": 0, "y": 73 },
     "fieldConfig": { "defaults": { "unit": "joule" } },
     "targets": [
      {
       "dataset": "dev",
       "rawSql": "SELECT\n\tdate_bin('$__interval', thrs_data.timestamp) AS time,\n\tconcat('[', coalesce(metadata.yard_tag, ''), '] ', thrs_data.technical_name) AS device,\n\tMAX(energy_consumption__value) AS \"energy_consumption\"\nFROM public.marpower__thrs__pumps AS thrs_data\nLEFT JOIN (\n  SELECT DISTINCT mqtt_topic, yard_tag FROM public.marpower__io_metadata WHERE mqtt_topic LIKE 'marpower/500000-thrs/%'\n) AS metadata ON thrs_data.topic = metadata.mqtt_topic\nWHERE $__timeFilter(timestamp)\n  AND ',' || '${section:csv}' || ',' LIKE '%,' || split_part(thrs_data.topic, '/', 3) || ',%'\n  AND ',' || '${device:csv}' || ',' LIKE '%,' || thrs_data.technical_name || ',%'\nGROUP BY 1, 2\nORDER BY 2, 1 ASC"
      }
     ]
    },
    {
     "title": "Operation time",
     "type": "timeseries",
     "gridPos": { "h": 16, "w": 24, "x": 0, "y": 89 },
     "fieldConfig": { "defaults": { "unit": "h" } },
     "targets": [
      {
       "dataset": "dev",
       "rawSql": "SELECT\n\tdate_bin('$__interval', thrs_data.timestamp) AS time,\n\tconcat('[', coalesce(metadata.yard_tag, ''), '] ', thrs_data.technical_name) AS device,\n\tMAX(op_time__value) AS \"op_time\"\nFROM public.marpower__thrs__pumps AS thrs_data\nLEFT JOIN (\n  SELECT DISTINCT mqtt_topic, yard_tag FROM public.marpower__io_metadata WHERE mqtt_topic LIKE 'marpower/500000-thrs/%'\n) AS metadata ON thrs_data.topic = metadata.mqtt_topic\nWHERE $__timeFilter(timestamp)\n  AND ',' || '${section:csv}' || ',' LIKE '%,' || split_part(thrs_data.topic, '/', 3) || ',%'\n  AND ',' || '${device:csv}' || ',' LIKE '%,' || thrs_data.technical_name || ',%'\nGROUP BY 1, 2\nORDER BY 2, 1 ASC"
      }
     ]
    },
    {
     "title": "Duty point",
     "type": "timeseries",
     "gridPos": { "h": 16, "w": 24, "x": 0, "y": 105 },
     "targets": [
      {
       "dataset": "dev",
       "rawSql": "SELECT\n\tdate_bin('$__interval', thrs_data.timestamp) AS time,\n\tconcat('[', coalesce(metadata.yard_tag, ''), '] ', thrs_data.technical_name) AS device,\n\tAVG(cc_duty_point__value) AS \"cc_duty_point\"\nFROM public.marpower__thrs__pumps AS thrs_data\nLEFT JOIN (\n  SELECT DISTINCT mqtt_topic, yard_tag FROM public.marpower__io_metadata WHERE mqtt_topic LIKE 'marpower/500000-thrs/%'\n) AS metadata ON thrs_data.topic = metadata.mqtt_topic\nWHERE $__timeFilter(timestamp)\n  AND ',' || '${section:csv}' || ',' LIKE '%,' || split_part(thrs_data.topic, '/', 3) || ',%'\n  AND ',' || '${device:csv}' || ',' LIKE '%,' || thrs_data.technical_name || ',%'\nGROUP BY 1, 2\nORDER BY 2, 1 ASC"
      }
     ]
    },
    {
     "title": "Control mode",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 121 },
     "targets": [
      {
       "dataset": "dev",
       "rawSql": "SELECT\n\tdate_bin('$__interval', thrs_data.timestamp) AS time,\n\tconcat('[', coalesce(metadata.yard_tag, ''), '] ', thrs_data.technical_name) AS device,\n\tAVG(cc_control_mode__value) AS \"cc_control_mode\"\nFROM public.marpower__thrs__pumps AS thrs_data\nLEFT JOIN (\n  SELECT DISTINCT mqtt_topic, yard_tag FROM public.marpower__io_metadata WHERE mqtt_topic LIKE 'marpower/500000-thrs/%'\n) AS metadata ON thrs_data.topic = metadata.mqtt_topic\nWHERE $__timeFilter(timestamp)\n  AND ',' || '${section:csv}' || ',' LIKE '%,' || split_part(thrs_data.topic, '/', 3) || ',%'\n  AND ',' || '${device:csv}' || ',' LIKE '%,' || thrs_data.technical_name || ',%'\nGROUP BY 1, 2\nORDER BY 2, 1 ASC"
      }
     ]
    },
    {
     "title": "On / Off",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 129 },
     "targets": [
      {
       "dataset": "dev",
       "rawSql": "SELECT\n\tdate_bin('$__interval', thrs_data.timestamp) AS time,\n\tconcat('[', coalesce(metadata.yard_tag, ''), '] ', thrs_data.technical_name) AS device,\n\tAVG(cc_on_off__value::INT) AS \"cc_on_off\"\nFROM public.marpower__thrs__pumps AS thrs_data\nLEFT JOIN (\n  SELECT DISTINCT mqtt_topic, yard_tag FROM public.marpower__io_metadata WHERE mqtt_topic LIKE 'marpower/500000-thrs/%'\n) AS metadata ON thrs_data.topic = metadata.mqtt_topic\nWHERE $__timeFilter(timestamp)\n  AND ',' || '${section:csv}' || ',' LIKE '%,' || split_part(thrs_data.topic, '/', 3) || ',%'\n  AND ',' || '${device:csv}' || ',' LIKE '%,' || thrs_data.technical_name || ',%'\nGROUP BY 1, 2\nORDER BY 2, 1 ASC"
      }
     ]
    }
   ]
  },
  {
   "title": "Valves",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 },
   "collapsed": true,
   "panels": [
    {
     "title": "Absolute position",
     "type": "timeseries",
     "gridPos": { "h": 16, "w": 24, "x": 0, "y": 10 },
     "fieldConfig": { "defaults": { "unit": "degree" } },
     "targets": [
      {
       "dataset": "dev",
       "rawSql": "SELECT\n\tdate_bin('$__interval', thrs_data.timestamp) AS time,\n\tconcat('[', coalesce(metadata.yard_tag, ''), '] ', thrs_data.technical_name) AS device,\n\tAVG(position_abs__value) AS \"position_abs\"\nFROM public.marpower__thrs__valves AS thrs_data\nLEFT JOIN (\n  SELECT DISTINCT mqtt_topic, yard_tag FROM public.marpower__io_metadata WHERE mqtt_topic LIKE 'marpower/500000-thrs/%'\n) AS metadata ON thrs_data.topic = metadata.mqtt_topic\nWHERE $__timeFilter(timestamp)\n  AND ',' || '${section:csv}' || ',' LIKE '%,' || split_part(thrs_data.topic, '/', 3) || ',%'\n  AND ',' || '${device:csv}' || ',' LIKE '%,' || thrs_data.technical_name || ',%'\nGROUP BY 1, 2\nORDER BY 2, 1 ASC"
      }
     ]
    },
    {
     "title": "Relative position",
     "type": "timeseries",
     "gridPos": { "h": 16, "w": 24, "x": 0, "y": 26 },
     "targets": [
      {
       "dataset": "dev",
       "rawSql": "SELECT\n\tdate_bin('$__interval', thrs_data.timestamp) AS time,\n\tconcat('[', coalesce(metadata.yard_tag, ''), '] ', thrs_data.technical_name) AS device,\n\tAVG(position_rel__value) AS \"position_rel\"\nFROM public.marpower__thrs__valves AS thrs_data\nLEFT JOIN (\n  SELECT DISTINCT mqtt_topic, yard_tag FROM public.marpower__io_metadata WHERE mqtt_topic LIKE 'marpower/500000-thrs/%'\n) AS metadata ON thrs_data.topic = metadata.mqtt_topic\nWHERE $__timeFilter(timestamp)\n  AND ',' || '${section:csv}' || ',' LIKE '%,' || split_part(thrs_data.topic, '/', 3) || ',%'\n  AND ',' || '${device:csv}' || ',' LIKE '%,' || thrs_data.technical_name || ',%'\nGROUP BY 1, 2\nORDER BY 2, 1 ASC"
      }
     ]
    },
    {
     "title": "Setpoint",
     "type": "timeseries",
     "gridPos": { "h": 16, "w": 24, "x": 0, "y": 42 },
     "targets": [
      {
       "dataset": "dev",
       "rawSql": "SELECT\n\tdate_bin('$__interval', thrs_data.timestamp) AS time,\n\tconcat('[', coalesce(metadata.yard_tag, ''), '] ', thrs_data.technical_name) AS device,\n\tAVG(cc_setpoint__value) AS \"cc_setpoint\"\nFROM public.marpower__thrs__valves AS thrs_data\nLEFT JOIN (\n  SELECT DISTINCT mqtt_topic, yard_tag FROM public.marpower__io_metadata WHERE mqtt_topic LIKE 'marpower/500000-thrs/%'\n) AS metadata ON thrs_data.topic = metadata.mqtt_topic\nWHERE $__timeFilter(timestamp)\n  AND ',' || '${section:csv}' || ',' LIKE '%,' || split_part(thrs_data.topic, '/', 3) || ',%'\n  AND ',' || '${device:csv}' || ',' LIKE '%,' || thrs_data.technical_name || ',%'\nGROUP BY 1, 2\nORDER BY 2, 1 ASC"
      }
     ]
    }
   ]
  }
 ]
}