<script setup lang="ts">
import { MimicComponentType } from "@/modules/thrapp/types";
import { ComponentOrientation } from "../../../components";
import { TemperatureSensorInstance } from "../../../instances";
import TemperatureLabelInstance from "../../../instances/TemperatureLabelInstance.vue";
import { PVT_MIMIC_DATA } from "../data";

const temperatureSensors = PVT_MIMIC_DATA[MimicComponentType.TemperatureSensor];
</script>

<template>
  <g>
    <TemperatureSensorInstance
      x="298"
      y="86"
      :orientation="ComponentOrientation.Down"
      v-bind="temperatureSensors['1038-03']"
    >
      <TemperatureLabelInstance
        x="283"
        y="47"
        :tag-id="temperatureSensors['1038-03'].tooltip?.yardTag"
        :temperature="temperatureSensors['1038-03'].source"
      />
    </TemperatureSensorInstance>
    <TemperatureSensorInstance
      x="298"
      y="295"
      :orientation="ComponentOrientation.Down"
      v-bind="temperatureSensors['1038-73']"
    >
      <TemperatureLabelInstance
        x="283"
        y="256"
        :tag-id="temperatureSensors['1038-73'].tooltip?.yardTag"
        :temperature="temperatureSensors['1038-73'].source"
      />
    </TemperatureSensorInstance>
    <TemperatureSensorInstance
      x="298"
      y="503"
      :orientation="ComponentOrientation.Down"
      v-bind="temperatureSensors['1038-04']"
    >
      <TemperatureLabelInstance
        x="283"
        y="465"
        :tag-id="temperatureSensors['1038-04'].tooltip?.yardTag"
        :temperature="temperatureSensors['1038-04'].source"
      />
    </TemperatureSensorInstance>
    <TemperatureSensorInstance
      x="468"
      y="190"
      :orientation="ComponentOrientation.Down"
      v-bind="temperatureSensors['1038-23']"
    >
      <TemperatureLabelInstance
        x="468"
        y="152"
        :tag-id="temperatureSensors['1038-23'].tooltip?.yardTag"
        :temperature="temperatureSensors['1038-23'].source"
      />
    </TemperatureSensorInstance>
    <TemperatureSensorInstance
      x="468"
      y="387"
      :orientation="ComponentOrientation.Down"
      v-bind="temperatureSensors['1038-22']"
    >
      <TemperatureLabelInstance
        x="468"
        y="349"
        :tag-id="temperatureSensors['1038-22'].tooltip?.yardTag"
        :temperature="temperatureSensors['1038-22'].source"
      />
    </TemperatureSensorInstance>
    <TemperatureSensorInstance
      x="468"
      y="609"
      :orientation="ComponentOrientation.Down"
      v-bind="temperatureSensors['1038-21']"
    >
      <TemperatureLabelInstance
        x="468"
        y="571"
        :tag-id="temperatureSensors['1038-21'].tooltip?.yardTag"
        :temperature="temperatureSensors['1038-21'].source"
      />
    </TemperatureSensorInstance>
    <TemperatureSensorInstance
      x="982"
      y="593"
      :orientation="ComponentOrientation.Left"
      v-bind="temperatureSensors['1038-24']"
    >
      <TemperatureLabelInstance
        x="1020"
        y="590"
        :tag-id="temperatureSensors['1038-24'].tooltip?.yardTag"
        :temperature="temperatureSensors['1038-24'].source"
      />
    </TemperatureSensorInstance>
  </g>
</template>
