apiVersion: v1
kind: Service
metadata:
  name: kiosk-vnc-service
spec:
  type: ClusterIP
  selector:
    {{- include "charts.selectorLabels" . | nindent 6 }}
  ports:
    - protocol: TCP
      port: 5900
      targetPort: 5900