-- Generated by src/sailpack/export_load_case_mapping_seed.py
-- Uses jsonb_to_recordset and resolves load cases.

BEGIN;

WITH mapping_payload AS (
    SELECT *
    FROM jsonb_to_recordset($$[
  {
    "load_case_id": "FM B Rchng",
    "awa_range_id": "upwind",
    "aws_range_id": 1,
    "sail_set_id": 1019
  },
  {
    "load_case_id": "FM B Rchng",
    "awa_range_id": "upwind",
    "aws_range_id": 2,
    "sail_set_id": 1019
  },
  {
    "load_case_id": "FM B Rchng",
    "awa_range_id": "upwind",
    "aws_range_id": 3,
    "sail_set_id": 1019
  },
  {
    "load_case_id": "FM B Rchng",
    "awa_range_id": "upwind",
    "aws_range_id": 4,
    "sail_set_id": 1019
  },
  {
    "load_case_id": "FM B Rchng",
    "awa_range_id": "upwind",
    "aws_range_id": 5,
    "sail_set_id": 1019
  },
  {
    "load_case_id": "FM B Rchng",
    "awa_range_id": "upwind",
    "aws_range_id": 6,
    "sail_set_id": 1019
  },
  {
    "load_case_id": "FM B Rchng",
    "awa_range_id": "upwind",
    "aws_range_id": 7,
    "sail_set_id": 1019
  },
  {
    "load_case_id": "FM B Rchng",
    "awa_range_id": "reaching",
    "aws_range_id": 1,
    "sail_set_id": 1019
  },
  {
    "load_case_id": "FM B Rchng",
    "awa_range_id": "reaching",
    "aws_range_id": 2,
    "sail_set_id": 1019
  },
  {
    "load_case_id": "FM B Rchng",
    "awa_range_id": "reaching",
    "aws_range_id": 3,
    "sail_set_id": 1019
  },
  {
    "load_case_id": "FM B Rchng",
    "awa_range_id": "reaching",
    "aws_range_id": 4,
    "sail_set_id": 1019
  },
  {
    "load_case_id": "FM B Rchng",
    "awa_range_id": "reaching",
    "aws_range_id": 5,
    "sail_set_id": 1019
  },
  {
    "load_case_id": "FM B Rchng",
    "awa_range_id": "reaching",
    "aws_range_id": 6,
    "sail_set_id": 1019
  },
  {
    "load_case_id": "FM B Rchng",
    "awa_range_id": "reaching",
    "aws_range_id": 7,
    "sail_set_id": 1019
  },
  {
    "load_case_id": "FM B Rchng",
    "awa_range_id": "downwind",
    "aws_range_id": 1,
    "sail_set_id": 1019
  },
  {
    "load_case_id": "FM B Rchng",
    "awa_range_id": "downwind",
    "aws_range_id": 2,
    "sail_set_id": 1019
  },
  {
    "load_case_id": "FM B Rchng",
    "awa_range_id": "downwind",
    "aws_range_id": 3,
    "sail_set_id": 1019
  },
  {
    "load_case_id": "FM B Rchng",
    "awa_range_id": "downwind",
    "aws_range_id": 4,
    "sail_set_id": 1019
  },
  {
    "load_case_id": "FM B Rchng",
    "awa_range_id": "downwind",
    "aws_range_id": 5,
    "sail_set_id": 1019
  },
  {
    "load_case_id": "FM B Rchng",
    "awa_range_id": "downwind",
    "aws_range_id": 6,
    "sail_set_id": 1019
  },
  {
    "load_case_id": "FM B Rchng",
    "awa_range_id": "downwind",
    "aws_range_id": 7,
    "sail_set_id": 1019
  }
]$$::jsonb) AS t(
        load_case_id TEXT,
        awa_range_id TEXT,
        aws_range_id INT,
        sail_set_id INT
    )
)
INSERT INTO loads.load_case_mappings (
    load_case_id,
    awa_range_id,
    aws_range_id,
    sail_set_id
)
SELECT
    payload.load_case_id,
    payload.awa_range_id,
    payload.aws_range_id,
    payload.sail_set_id
FROM mapping_payload AS payload
ON CONFLICT (awa_range_id, aws_range_id, sail_set_id) DO UPDATE
SET
    load_case_id = EXCLUDED.load_case_id;

COMMIT;
