-- Generated by src/sailpack/export_load_case_mapping_seed.py
-- Uses jsonb_to_recordset and resolves sail_set_id from sail abbreviations.

BEGIN;

WITH mapping_payload AS (
    SELECT *
    FROM jsonb_to_recordset($$[
  {
    "load_case_id": "FM B Rchng",
    "awa_range_id": "upwind",
    "aws_range_id": 1,
    "sail_abbreviations": [
      "B",
      "FM"
    ]
  },
  {
    "load_case_id": "FM B Rchng",
    "awa_range_id": "upwind",
    "aws_range_id": 2,
    "sail_abbreviations": [
      "B",
      "FM"
    ]
  },
  {
    "load_case_id": "FM B Rchng",
    "awa_range_id": "upwind",
    "aws_range_id": 3,
    "sail_abbreviations": [
      "B",
      "FM"
    ]
  },
  {
    "load_case_id": "FM B Rchng",
    "awa_range_id": "upwind",
    "aws_range_id": 4,
    "sail_abbreviations": [
      "B",
      "FM"
    ]
  },
  {
    "load_case_id": "FM B Rchng",
    "awa_range_id": "upwind",
    "aws_range_id": 5,
    "sail_abbreviations": [
      "B",
      "FM"
    ]
  },
  {
    "load_case_id": "FM B Rchng",
    "awa_range_id": "upwind",
    "aws_range_id": 6,
    "sail_abbreviations": [
      "B",
      "FM"
    ]
  },
  {
    "load_case_id": "FM B Rchng",
    "awa_range_id": "upwind",
    "aws_range_id": 7,
    "sail_abbreviations": [
      "B",
      "FM"
    ]
  },
  {
    "load_case_id": "LC1-2_ B_FM_FMZ_TWA45_TWS14_RM22_20250306",
    "awa_range_id": "upwind",
    "aws_range_id": 1,
    "sail_abbreviations": [
      "B",
      "FM",
      "FMZ"
    ]
  },
  {
    "load_case_id": "LC1-2_ B_FM_FMZ_TWA45_TWS14_RM22_20250306",
    "awa_range_id": "upwind",
    "aws_range_id": 2,
    "sail_abbreviations": [
      "B",
      "FM",
      "FMZ"
    ]
  },
  {
    "load_case_id": "LC1-2_ B_FM_FMZ_TWA45_TWS14_RM22_20250306",
    "awa_range_id": "upwind",
    "aws_range_id": 3,
    "sail_abbreviations": [
      "B",
      "FM",
      "FMZ"
    ]
  },
  {
    "load_case_id": "LC1-2_ B_FM_FMZ_TWA45_TWS14_RM22_20250306",
    "awa_range_id": "upwind",
    "aws_range_id": 4,
    "sail_abbreviations": [
      "B",
      "FM",
      "FMZ"
    ]
  },
  {
    "load_case_id": "LC1-2_ B_FM_FMZ_TWA45_TWS14_RM22_20250306",
    "awa_range_id": "upwind",
    "aws_range_id": 5,
    "sail_abbreviations": [
      "B",
      "FM",
      "FMZ"
    ]
  },
  {
    "load_case_id": "LC1-2_ B_FM_FMZ_TWA45_TWS14_RM22_20250306",
    "awa_range_id": "upwind",
    "aws_range_id": 6,
    "sail_abbreviations": [
      "B",
      "FM",
      "FMZ"
    ]
  },
  {
    "load_case_id": "LC1-2_ B_FM_FMZ_TWA45_TWS14_RM22_20250306",
    "awa_range_id": "upwind",
    "aws_range_id": 7,
    "sail_abbreviations": [
      "B",
      "FM",
      "FMZ"
    ]
  },
  {
    "load_case_id": "LC35_ B_FM_FMZ_MZSS_TWA115_TWS26_RMMax_20240411",
    "awa_range_id": "upwind",
    "aws_range_id": 1,
    "sail_abbreviations": [
      "B",
      "FM",
      "FMZ",
      "MZSS"
    ]
  },
  {
    "load_case_id": "LC35_ B_FM_FMZ_MZSS_TWA115_TWS26_RMMax_20240411",
    "awa_range_id": "upwind",
    "aws_range_id": 2,
    "sail_abbreviations": [
      "B",
      "FM",
      "FMZ",
      "MZSS"
    ]
  },
  {
    "load_case_id": "LC35_ B_FM_FMZ_MZSS_TWA115_TWS26_RMMax_20240411",
    "awa_range_id": "upwind",
    "aws_range_id": 3,
    "sail_abbreviations": [
      "B",
      "FM",
      "FMZ",
      "MZSS"
    ]
  },
  {
    "load_case_id": "LC35_ B_FM_FMZ_MZSS_TWA115_TWS26_RMMax_20240411",
    "awa_range_id": "upwind",
    "aws_range_id": 4,
    "sail_abbreviations": [
      "B",
      "FM",
      "FMZ",
      "MZSS"
    ]
  },
  {
    "load_case_id": "LC35_ B_FM_FMZ_MZSS_TWA115_TWS26_RMMax_20240411",
    "awa_range_id": "upwind",
    "aws_range_id": 5,
    "sail_abbreviations": [
      "B",
      "FM",
      "FMZ",
      "MZSS"
    ]
  },
  {
    "load_case_id": "LC35_ B_FM_FMZ_MZSS_TWA115_TWS26_RMMax_20240411",
    "awa_range_id": "upwind",
    "aws_range_id": 6,
    "sail_abbreviations": [
      "B",
      "FM",
      "FMZ",
      "MZSS"
    ]
  },
  {
    "load_case_id": "LC35_ B_FM_FMZ_MZSS_TWA115_TWS26_RMMax_20240411",
    "awa_range_id": "upwind",
    "aws_range_id": 7,
    "sail_abbreviations": [
      "B",
      "FM",
      "FMZ",
      "MZSS"
    ]
  },
  {
    "load_case_id": "LC20_ MH0_FM_FMZ_ TWA110_TWS12_RM15_NoRunner_20240630",
    "awa_range_id": "upwind",
    "aws_range_id": 1,
    "sail_abbreviations": [
      "FM",
      "FMZ"
    ]
  },
  {
    "load_case_id": "LC20_ MH0_FM_FMZ_ TWA110_TWS12_RM15_NoRunner_20240630",
    "awa_range_id": "upwind",
    "aws_range_id": 2,
    "sail_abbreviations": [
      "FM",
      "FMZ"
    ]
  },
  {
    "load_case_id": "LC20_ MH0_FM_FMZ_ TWA110_TWS12_RM15_NoRunner_20240630",
    "awa_range_id": "upwind",
    "aws_range_id": 3,
    "sail_abbreviations": [
      "FM",
      "FMZ"
    ]
  },
  {
    "load_case_id": "LC20_ MH0_FM_FMZ_ TWA110_TWS12_RM15_NoRunner_20240630",
    "awa_range_id": "upwind",
    "aws_range_id": 4,
    "sail_abbreviations": [
      "FM",
      "FMZ"
    ]
  },
  {
    "load_case_id": "LC20_ MH0_FM_FMZ_ TWA110_TWS12_RM15_NoRunner_20240630",
    "awa_range_id": "upwind",
    "aws_range_id": 5,
    "sail_abbreviations": [
      "FM",
      "FMZ"
    ]
  },
  {
    "load_case_id": "LC20_ MH0_FM_FMZ_ TWA110_TWS12_RM15_NoRunner_20240630",
    "awa_range_id": "upwind",
    "aws_range_id": 6,
    "sail_abbreviations": [
      "FM",
      "FMZ"
    ]
  },
  {
    "load_case_id": "LC20_ MH0_FM_FMZ_ TWA110_TWS12_RM15_NoRunner_20240630",
    "awa_range_id": "upwind",
    "aws_range_id": 7,
    "sail_abbreviations": [
      "FM",
      "FMZ"
    ]
  },
  {
    "load_case_id": "LC7-R_ SS_M2R_MZ2R_TWA90_TWS28_RM20_20240418",
    "awa_range_id": "upwind",
    "aws_range_id": 1,
    "sail_abbreviations": [
      "M2R",
      "MZ2R",
      "SS"
    ]
  },
  {
    "load_case_id": "LC7-R_ SS_M2R_MZ2R_TWA90_TWS28_RM20_20240418",
    "awa_range_id": "upwind",
    "aws_range_id": 2,
    "sail_abbreviations": [
      "M2R",
      "MZ2R",
      "SS"
    ]
  },
  {
    "load_case_id": "LC7-R_ SS_M2R_MZ2R_TWA90_TWS28_RM20_20240418",
    "awa_range_id": "upwind",
    "aws_range_id": 3,
    "sail_abbreviations": [
      "M2R",
      "MZ2R",
      "SS"
    ]
  },
  {
    "load_case_id": "LC7-R_ SS_M2R_MZ2R_TWA90_TWS28_RM20_20240418",
    "awa_range_id": "upwind",
    "aws_range_id": 4,
    "sail_abbreviations": [
      "M2R",
      "MZ2R",
      "SS"
    ]
  },
  {
    "load_case_id": "LC7-R_ SS_M2R_MZ2R_TWA90_TWS28_RM20_20240418",
    "awa_range_id": "upwind",
    "aws_range_id": 5,
    "sail_abbreviations": [
      "M2R",
      "MZ2R",
      "SS"
    ]
  },
  {
    "load_case_id": "LC7-R_ SS_M2R_MZ2R_TWA90_TWS28_RM20_20240418",
    "awa_range_id": "upwind",
    "aws_range_id": 6,
    "sail_abbreviations": [
      "M2R",
      "MZ2R",
      "SS"
    ]
  },
  {
    "load_case_id": "LC7-R_ SS_M2R_MZ2R_TWA90_TWS28_RM20_20240418",
    "awa_range_id": "upwind",
    "aws_range_id": 7,
    "sail_abbreviations": [
      "M2R",
      "MZ2R",
      "SS"
    ]
  }
]$$::jsonb) AS t(
        load_case_id TEXT,
        awa_range_id TEXT,
        aws_range_id INT,
        sail_abbreviations TEXT[]
    )
),
resolved_mappings AS (
    SELECT
        payload.load_case_id,
        payload.awa_range_id,
        payload.aws_range_id,
        (
            SELECT ssc.id
            FROM loads.sail_sets_combined AS ssc
            WHERE COALESCE(ssc.sails, '{}'::TEXT[]) = COALESCE(
                (
                    SELECT ARRAY_AGG(s.id ORDER BY s.id)
                    FROM loads.sails AS s
                    WHERE s.abbreviation = ANY(payload.sail_abbreviations)
                ),
                '{}'::TEXT[]
            )
            LIMIT 1
        ) AS sail_set_id
    FROM mapping_payload AS payload
)
INSERT INTO loads.load_case_mappings (
    load_case_id,
    awa_range_id,
    aws_range_id,
    sail_set_id
)
SELECT
    load_case_id,
    awa_range_id,
    aws_range_id,
    sail_set_id
FROM resolved_mappings
WHERE sail_set_id IS NOT NULL
ON CONFLICT (awa_range_id, aws_range_id, sail_set_id) DO UPDATE
SET
    load_case_id = EXCLUDED.load_case_id;

COMMIT;
