-- Generated by src/sailpack/export_load_case_mapping_seed.py
-- Uses jsonb_to_recordset and resolves sail_set_id from sail abbreviations.

BEGIN;

WITH mapping_payload AS (
    SELECT *
    FROM jsonb_to_recordset($$[
  {
    "load_case_id": "LC33_ A3_FM_FMZ_ TWA125_TWS15_RM20_20240411",
    "awa_range_id": "upwind",
    "aws_range_id": 1,
    "sail_abbreviations": [
      "A3",
      "FM",
      "FMZ"
    ]
  },
  {
    "load_case_id": "LC33_ A3_FM_FMZ_ TWA125_TWS15_RM20_20240411",
    "awa_range_id": "upwind",
    "aws_range_id": 2,
    "sail_abbreviations": [
      "A3",
      "FM",
      "FMZ"
    ]
  },
  {
    "load_case_id": "LC33_ A3_FM_FMZ_ TWA125_TWS15_RM20_20240411",
    "awa_range_id": "upwind",
    "aws_range_id": 3,
    "sail_abbreviations": [
      "A3",
      "FM",
      "FMZ"
    ]
  },
  {
    "load_case_id": "LC33_ A3_FM_FMZ_ TWA125_TWS15_RM20_20240411",
    "awa_range_id": "upwind",
    "aws_range_id": 4,
    "sail_abbreviations": [
      "A3",
      "FM",
      "FMZ"
    ]
  },
  {
    "load_case_id": "LC33_ A3_FM_FMZ_ TWA125_TWS15_RM20_20240411",
    "awa_range_id": "upwind",
    "aws_range_id": 5,
    "sail_abbreviations": [
      "A3",
      "FM",
      "FMZ"
    ]
  },
  {
    "load_case_id": "LC33_ A3_FM_FMZ_ TWA125_TWS15_RM20_20240411",
    "awa_range_id": "upwind",
    "aws_range_id": 6,
    "sail_abbreviations": [
      "A3",
      "FM",
      "FMZ"
    ]
  },
  {
    "load_case_id": "LC33_ A3_FM_FMZ_ TWA125_TWS15_RM20_20240411",
    "awa_range_id": "upwind",
    "aws_range_id": 7,
    "sail_abbreviations": [
      "A3",
      "FM",
      "FMZ"
    ]
  },
  {
    "load_case_id": "LC___FM_B_TWA45_TWS18_RM22_20241202 Main Tack Test",
    "awa_range_id": "upwind",
    "aws_range_id": 1,
    "sail_abbreviations": [
      "B",
      "FM"
    ]
  },
  {
    "load_case_id": "LC___FM_B_TWA45_TWS18_RM22_20241202 Main Tack Test",
    "awa_range_id": "upwind",
    "aws_range_id": 2,
    "sail_abbreviations": [
      "B",
      "FM"
    ]
  },
  {
    "load_case_id": "LC___FM_B_TWA45_TWS18_RM22_20241202 Main Tack Test",
    "awa_range_id": "upwind",
    "aws_range_id": 3,
    "sail_abbreviations": [
      "B",
      "FM"
    ]
  },
  {
    "load_case_id": "LC___FM_B_TWA45_TWS18_RM22_20241202 Main Tack Test",
    "awa_range_id": "upwind",
    "aws_range_id": 4,
    "sail_abbreviations": [
      "B",
      "FM"
    ]
  },
  {
    "load_case_id": "LC___FM_B_TWA45_TWS18_RM22_20241202 Main Tack Test",
    "awa_range_id": "upwind",
    "aws_range_id": 5,
    "sail_abbreviations": [
      "B",
      "FM"
    ]
  },
  {
    "load_case_id": "LC___FM_B_TWA45_TWS18_RM22_20241202 Main Tack Test",
    "awa_range_id": "upwind",
    "aws_range_id": 6,
    "sail_abbreviations": [
      "B",
      "FM"
    ]
  },
  {
    "load_case_id": "LC___FM_B_TWA45_TWS18_RM22_20241202 Main Tack Test",
    "awa_range_id": "upwind",
    "aws_range_id": 7,
    "sail_abbreviations": [
      "B",
      "FM"
    ]
  },
  {
    "load_case_id": "LC1-2_ B_FM_FMZ_TWA45_TWS14_RM22_20240409",
    "awa_range_id": "upwind",
    "aws_range_id": 1,
    "sail_abbreviations": [
      "B",
      "FM",
      "FMZ"
    ]
  },
  {
    "load_case_id": "LC1-2_ B_FM_FMZ_TWA45_TWS14_RM22_20240409",
    "awa_range_id": "upwind",
    "aws_range_id": 2,
    "sail_abbreviations": [
      "B",
      "FM",
      "FMZ"
    ]
  },
  {
    "load_case_id": "LC1-2_ B_FM_FMZ_TWA45_TWS14_RM22_20240409",
    "awa_range_id": "upwind",
    "aws_range_id": 3,
    "sail_abbreviations": [
      "B",
      "FM",
      "FMZ"
    ]
  },
  {
    "load_case_id": "LC1-2_ B_FM_FMZ_TWA45_TWS14_RM22_20240409",
    "awa_range_id": "upwind",
    "aws_range_id": 4,
    "sail_abbreviations": [
      "B",
      "FM",
      "FMZ"
    ]
  },
  {
    "load_case_id": "LC1-2R_ B_FM_FMZ_TWA110_TWS18_RM22_20240418",
    "awa_range_id": "upwind",
    "aws_range_id": 5,
    "sail_abbreviations": [
      "B",
      "FM",
      "FMZ"
    ]
  },
  {
    "load_case_id": "LC1-2R_ B_FM_FMZ_TWA110_TWS18_RM22_20240418",
    "awa_range_id": "upwind",
    "aws_range_id": 6,
    "sail_abbreviations": [
      "B",
      "FM",
      "FMZ"
    ]
  },
  {
    "load_case_id": "LC1-2R_ B_FM_FMZ_TWA110_TWS18_RM22_20240418",
    "awa_range_id": "upwind",
    "aws_range_id": 7,
    "sail_abbreviations": [
      "B",
      "FM",
      "FMZ"
    ]
  },
  {
    "load_case_id": "LC22_ B_FM_FMZ_MZJ_ TWA55_TWS14_RM22_20240519",
    "awa_range_id": "upwind",
    "aws_range_id": 1,
    "sail_abbreviations": [
      "B",
      "FM",
      "FMZ",
      "MZJ"
    ]
  },
  {
    "load_case_id": "LC22_ B_FM_FMZ_MZJ_ TWA55_TWS14_RM22_20240519",
    "awa_range_id": "upwind",
    "aws_range_id": 2,
    "sail_abbreviations": [
      "B",
      "FM",
      "FMZ",
      "MZJ"
    ]
  },
  {
    "load_case_id": "LC22_ B_FM_FMZ_MZJ_ TWA55_TWS14_RM22_20240519",
    "awa_range_id": "upwind",
    "aws_range_id": 3,
    "sail_abbreviations": [
      "B",
      "FM",
      "FMZ",
      "MZJ"
    ]
  },
  {
    "load_case_id": "LC22_ B_FM_FMZ_MZJ_ TWA55_TWS14_RM22_20240519",
    "awa_range_id": "upwind",
    "aws_range_id": 4,
    "sail_abbreviations": [
      "B",
      "FM",
      "FMZ",
      "MZJ"
    ]
  },
  {
    "load_case_id": "LC22_ B_FM_FMZ_MZJ_ TWA55_TWS14_RM22_20240519",
    "awa_range_id": "upwind",
    "aws_range_id": 5,
    "sail_abbreviations": [
      "B",
      "FM",
      "FMZ",
      "MZJ"
    ]
  },
  {
    "load_case_id": "LC22_ B_FM_FMZ_MZJ_ TWA55_TWS14_RM22_20240519",
    "awa_range_id": "upwind",
    "aws_range_id": 6,
    "sail_abbreviations": [
      "B",
      "FM",
      "FMZ",
      "MZJ"
    ]
  },
  {
    "load_case_id": "LC22_ B_FM_FMZ_MZJ_ TWA55_TWS14_RM22_20240519",
    "awa_range_id": "upwind",
    "aws_range_id": 7,
    "sail_abbreviations": [
      "B",
      "FM",
      "FMZ",
      "MZJ"
    ]
  },
  {
    "load_case_id": "LC35_B_FM_FMZ_MZSS_ TWA115_TWS14_RM17_5_20240411",
    "awa_range_id": "upwind",
    "aws_range_id": 1,
    "sail_abbreviations": [
      "B",
      "FM",
      "FMZ",
      "MZSS"
    ]
  },
  {
    "load_case_id": "LC35_B_FM_FMZ_MZSS_ TWA115_TWS14_RM17_5_20240411",
    "awa_range_id": "upwind",
    "aws_range_id": 2,
    "sail_abbreviations": [
      "B",
      "FM",
      "FMZ",
      "MZSS"
    ]
  },
  {
    "load_case_id": "LC35_B_FM_FMZ_MZSS_ TWA115_TWS14_RM17_5_20240411",
    "awa_range_id": "upwind",
    "aws_range_id": 3,
    "sail_abbreviations": [
      "B",
      "FM",
      "FMZ",
      "MZSS"
    ]
  },
  {
    "load_case_id": "LC35_B_FM_FMZ_MZSS_ TWA115_TWS14_RM17_5_20240411",
    "awa_range_id": "upwind",
    "aws_range_id": 4,
    "sail_abbreviations": [
      "B",
      "FM",
      "FMZ",
      "MZSS"
    ]
  },
  {
    "load_case_id": "LC35_B_FM_FMZ_MZSS_ TWA115_TWS14_RM17_5_20240411",
    "awa_range_id": "upwind",
    "aws_range_id": 5,
    "sail_abbreviations": [
      "B",
      "FM",
      "FMZ",
      "MZSS"
    ]
  },
  {
    "load_case_id": "LC35_B_FM_FMZ_MZSS_ TWA115_TWS14_RM17_5_20240411",
    "awa_range_id": "upwind",
    "aws_range_id": 6,
    "sail_abbreviations": [
      "B",
      "FM",
      "FMZ",
      "MZSS"
    ]
  },
  {
    "load_case_id": "LC35_B_FM_FMZ_MZSS_ TWA115_TWS14_RM17_5_20240411",
    "awa_range_id": "upwind",
    "aws_range_id": 7,
    "sail_abbreviations": [
      "B",
      "FM",
      "FMZ",
      "MZSS"
    ]
  },
  {
    "load_case_id": "LC2_ B_FM_MZ1R_TWA45_TWS16_RM22_20240409",
    "awa_range_id": "upwind",
    "aws_range_id": 1,
    "sail_abbreviations": [
      "B",
      "FM",
      "MZ1R"
    ]
  },
  {
    "load_case_id": "LC2_ B_FM_MZ1R_TWA45_TWS16_RM22_20240409",
    "awa_range_id": "upwind",
    "aws_range_id": 2,
    "sail_abbreviations": [
      "B",
      "FM",
      "MZ1R"
    ]
  },
  {
    "load_case_id": "LC2_ B_FM_MZ1R_TWA45_TWS16_RM22_20240409",
    "awa_range_id": "upwind",
    "aws_range_id": 3,
    "sail_abbreviations": [
      "B",
      "FM",
      "MZ1R"
    ]
  },
  {
    "load_case_id": "LC2_ B_FM_MZ1R_TWA45_TWS16_RM22_20240409",
    "awa_range_id": "upwind",
    "aws_range_id": 4,
    "sail_abbreviations": [
      "B",
      "FM",
      "MZ1R"
    ]
  },
  {
    "load_case_id": "LC2_ B_FM_MZ1R_TWA45_TWS16_RM22_20240409",
    "awa_range_id": "upwind",
    "aws_range_id": 5,
    "sail_abbreviations": [
      "B",
      "FM",
      "MZ1R"
    ]
  },
  {
    "load_case_id": "LC2_ B_FM_MZ1R_TWA45_TWS16_RM22_20240409",
    "awa_range_id": "upwind",
    "aws_range_id": 6,
    "sail_abbreviations": [
      "B",
      "FM",
      "MZ1R"
    ]
  },
  {
    "load_case_id": "LC2_ B_FM_MZ1R_TWA45_TWS16_RM22_20240409",
    "awa_range_id": "upwind",
    "aws_range_id": 7,
    "sail_abbreviations": [
      "B",
      "FM",
      "MZ1R"
    ]
  },
  {
    "load_case_id": "LC3_ B_M1R_MZ1R_TWA45_TWS19_RM22_20240410",
    "awa_range_id": "upwind",
    "aws_range_id": 1,
    "sail_abbreviations": [
      "B",
      "M1R",
      "MZ1R"
    ]
  },
  {
    "load_case_id": "LC3_ B_M1R_MZ1R_TWA45_TWS19_RM22_20240410",
    "awa_range_id": "upwind",
    "aws_range_id": 2,
    "sail_abbreviations": [
      "B",
      "M1R",
      "MZ1R"
    ]
  },
  {
    "load_case_id": "LC3_ B_M1R_MZ1R_TWA45_TWS19_RM22_20240410",
    "awa_range_id": "upwind",
    "aws_range_id": 3,
    "sail_abbreviations": [
      "B",
      "M1R",
      "MZ1R"
    ]
  },
  {
    "load_case_id": "LC3_ B_M1R_MZ1R_TWA45_TWS19_RM22_20240410",
    "awa_range_id": "upwind",
    "aws_range_id": 4,
    "sail_abbreviations": [
      "B",
      "M1R",
      "MZ1R"
    ]
  },
  {
    "load_case_id": "LC3_ B_M1R_MZ1R_TWA45_TWS19_RM22_20240410",
    "awa_range_id": "upwind",
    "aws_range_id": 5,
    "sail_abbreviations": [
      "B",
      "M1R",
      "MZ1R"
    ]
  },
  {
    "load_case_id": "LC3_ B_M1R_MZ1R_TWA45_TWS19_RM22_20240410",
    "awa_range_id": "upwind",
    "aws_range_id": 6,
    "sail_abbreviations": [
      "B",
      "M1R",
      "MZ1R"
    ]
  },
  {
    "load_case_id": "LC3_ B_M1R_MZ1R_TWA45_TWS19_RM22_20240410",
    "awa_range_id": "upwind",
    "aws_range_id": 7,
    "sail_abbreviations": [
      "B",
      "M1R",
      "MZ1R"
    ]
  },
  {
    "load_case_id": "LC4_ B_M1R_MZ2R_TWA45_TWS22_RM20_20240410",
    "awa_range_id": "upwind",
    "aws_range_id": 1,
    "sail_abbreviations": [
      "B",
      "M1R",
      "MZ2R"
    ]
  },
  {
    "load_case_id": "LC4_ B_M1R_MZ2R_TWA45_TWS22_RM20_20240410",
    "awa_range_id": "upwind",
    "aws_range_id": 2,
    "sail_abbreviations": [
      "B",
      "M1R",
      "MZ2R"
    ]
  },
  {
    "load_case_id": "LC4_ B_M1R_MZ2R_TWA45_TWS22_RM20_20240410",
    "awa_range_id": "upwind",
    "aws_range_id": 3,
    "sail_abbreviations": [
      "B",
      "M1R",
      "MZ2R"
    ]
  },
  {
    "load_case_id": "LC4_ B_M1R_MZ2R_TWA45_TWS22_RM20_20240410",
    "awa_range_id": "upwind",
    "aws_range_id": 4,
    "sail_abbreviations": [
      "B",
      "M1R",
      "MZ2R"
    ]
  },
  {
    "load_case_id": "LC4_ B_M1R_MZ2R_TWA45_TWS22_RM20_20240410",
    "awa_range_id": "upwind",
    "aws_range_id": 5,
    "sail_abbreviations": [
      "B",
      "M1R",
      "MZ2R"
    ]
  },
  {
    "load_case_id": "LC4_ B_M1R_MZ2R_TWA45_TWS22_RM20_20240410",
    "awa_range_id": "upwind",
    "aws_range_id": 6,
    "sail_abbreviations": [
      "B",
      "M1R",
      "MZ2R"
    ]
  },
  {
    "load_case_id": "LC4_ B_M1R_MZ2R_TWA45_TWS22_RM20_20240410",
    "awa_range_id": "upwind",
    "aws_range_id": 7,
    "sail_abbreviations": [
      "B",
      "M1R",
      "MZ2R"
    ]
  },
  {
    "load_case_id": "LC20_ MH0_FM_FMZ_ TWA70_TWS12_RM22_20240411",
    "awa_range_id": "upwind",
    "aws_range_id": 1,
    "sail_abbreviations": [
      "C0",
      "FM",
      "FMZ"
    ]
  },
  {
    "load_case_id": "LC20_ MH0_FM_FMZ_ TWA70_TWS12_RM22_20240411",
    "awa_range_id": "upwind",
    "aws_range_id": 2,
    "sail_abbreviations": [
      "C0",
      "FM",
      "FMZ"
    ]
  },
  {
    "load_case_id": "LC20_ MH0_FM_FMZ_ TWA70_TWS12_RM22_20240411",
    "awa_range_id": "upwind",
    "aws_range_id": 3,
    "sail_abbreviations": [
      "C0",
      "FM",
      "FMZ"
    ]
  },
  {
    "load_case_id": "LC20_ MH0_FM_FMZ_ TWA70_TWS12_RM22_20240411",
    "awa_range_id": "upwind",
    "aws_range_id": 4,
    "sail_abbreviations": [
      "C0",
      "FM",
      "FMZ"
    ]
  },
  {
    "load_case_id": "LC20_ MH0_FM_FMZ_ TWA70_TWS12_RM22_20240411",
    "awa_range_id": "upwind",
    "aws_range_id": 5,
    "sail_abbreviations": [
      "C0",
      "FM",
      "FMZ"
    ]
  },
  {
    "load_case_id": "LC20_ MH0_FM_FMZ_ TWA70_TWS12_RM22_20240411",
    "awa_range_id": "upwind",
    "aws_range_id": 6,
    "sail_abbreviations": [
      "C0",
      "FM",
      "FMZ"
    ]
  },
  {
    "load_case_id": "LC20_ MH0_FM_FMZ_ TWA70_TWS12_RM22_20240411",
    "awa_range_id": "upwind",
    "aws_range_id": 7,
    "sail_abbreviations": [
      "C0",
      "FM",
      "FMZ"
    ]
  },
  {
    "load_case_id": "LC53_FM_FMZ_TWA120_TWS20_RM20_PV_20240419",
    "awa_range_id": "upwind",
    "aws_range_id": 1,
    "sail_abbreviations": [
      "FM",
      "FMZ"
    ]
  },
  {
    "load_case_id": "LC53_FM_FMZ_TWA120_TWS20_RM20_PV_20240419",
    "awa_range_id": "upwind",
    "aws_range_id": 2,
    "sail_abbreviations": [
      "FM",
      "FMZ"
    ]
  },
  {
    "load_case_id": "LC53_FM_FMZ_TWA120_TWS20_RM20_PV_20240419",
    "awa_range_id": "upwind",
    "aws_range_id": 3,
    "sail_abbreviations": [
      "FM",
      "FMZ"
    ]
  },
  {
    "load_case_id": "LC53_FM_FMZ_TWA120_TWS20_RM20_PV_20240419",
    "awa_range_id": "upwind",
    "aws_range_id": 4,
    "sail_abbreviations": [
      "FM",
      "FMZ"
    ]
  },
  {
    "load_case_id": "LC53_FM_FMZ_TWA120_TWS20_RM20_PV_20240419",
    "awa_range_id": "upwind",
    "aws_range_id": 5,
    "sail_abbreviations": [
      "FM",
      "FMZ"
    ]
  },
  {
    "load_case_id": "LC53_FM_FMZ_TWA120_TWS20_RM20_PV_20240419",
    "awa_range_id": "upwind",
    "aws_range_id": 6,
    "sail_abbreviations": [
      "FM",
      "FMZ"
    ]
  },
  {
    "load_case_id": "LC53_FM_FMZ_TWA120_TWS20_RM20_PV_20240419",
    "awa_range_id": "upwind",
    "aws_range_id": 7,
    "sail_abbreviations": [
      "FM",
      "FMZ"
    ]
  },
  {
    "load_case_id": "LC5-R_ SS_M1R_MZ1R_TWA110_TWS25_RM20_20240418",
    "awa_range_id": "upwind",
    "aws_range_id": 1,
    "sail_abbreviations": [
      "M1R",
      "MZ1R",
      "SS"
    ]
  },
  {
    "load_case_id": "LC5-R_ SS_M1R_MZ1R_TWA110_TWS25_RM20_20240418",
    "awa_range_id": "upwind",
    "aws_range_id": 2,
    "sail_abbreviations": [
      "M1R",
      "MZ1R",
      "SS"
    ]
  },
  {
    "load_case_id": "LC5-R_ SS_M1R_MZ1R_TWA110_TWS25_RM20_20240418",
    "awa_range_id": "upwind",
    "aws_range_id": 3,
    "sail_abbreviations": [
      "M1R",
      "MZ1R",
      "SS"
    ]
  },
  {
    "load_case_id": "LC5-R_ SS_M1R_MZ1R_TWA110_TWS25_RM20_20240418",
    "awa_range_id": "upwind",
    "aws_range_id": 4,
    "sail_abbreviations": [
      "M1R",
      "MZ1R",
      "SS"
    ]
  },
  {
    "load_case_id": "LC5-R_ SS_M1R_MZ1R_TWA110_TWS25_RM20_20240418",
    "awa_range_id": "upwind",
    "aws_range_id": 5,
    "sail_abbreviations": [
      "M1R",
      "MZ1R",
      "SS"
    ]
  },
  {
    "load_case_id": "LC5-R_ SS_M1R_MZ1R_TWA110_TWS25_RM20_20240418",
    "awa_range_id": "upwind",
    "aws_range_id": 6,
    "sail_abbreviations": [
      "M1R",
      "MZ1R",
      "SS"
    ]
  },
  {
    "load_case_id": "LC5-R_ SS_M1R_MZ1R_TWA110_TWS25_RM20_20240418",
    "awa_range_id": "upwind",
    "aws_range_id": 7,
    "sail_abbreviations": [
      "M1R",
      "MZ1R",
      "SS"
    ]
  },
  {
    "load_case_id": "LC6_ SS_M1R_MZ2R_TWA45_TWS24_RM20_20240410",
    "awa_range_id": "upwind",
    "aws_range_id": 1,
    "sail_abbreviations": [
      "M1R",
      "MZ2R",
      "SS"
    ]
  },
  {
    "load_case_id": "LC6_ SS_M1R_MZ2R_TWA45_TWS24_RM20_20240410",
    "awa_range_id": "upwind",
    "aws_range_id": 2,
    "sail_abbreviations": [
      "M1R",
      "MZ2R",
      "SS"
    ]
  },
  {
    "load_case_id": "LC6_ SS_M1R_MZ2R_TWA45_TWS24_RM20_20240410",
    "awa_range_id": "upwind",
    "aws_range_id": 3,
    "sail_abbreviations": [
      "M1R",
      "MZ2R",
      "SS"
    ]
  },
  {
    "load_case_id": "LC6_ SS_M1R_MZ2R_TWA45_TWS24_RM20_20240410",
    "awa_range_id": "upwind",
    "aws_range_id": 4,
    "sail_abbreviations": [
      "M1R",
      "MZ2R",
      "SS"
    ]
  },
  {
    "load_case_id": "LC6_ SS_M1R_MZ2R_TWA45_TWS24_RM20_20240410",
    "awa_range_id": "upwind",
    "aws_range_id": 5,
    "sail_abbreviations": [
      "M1R",
      "MZ2R",
      "SS"
    ]
  },
  {
    "load_case_id": "LC6-R_ SS_M1R_MZ2R_TWA90_TWS25_RM20_20240508",
    "awa_range_id": "upwind",
    "aws_range_id": 6,
    "sail_abbreviations": [
      "M1R",
      "MZ2R",
      "SS"
    ]
  },
  {
    "load_case_id": "LC6-R_ SS_M1R_MZ2R_TWA90_TWS25_RM20_20240508",
    "awa_range_id": "upwind",
    "aws_range_id": 7,
    "sail_abbreviations": [
      "M1R",
      "MZ2R",
      "SS"
    ]
  },
  {
    "load_case_id": "LC11_ SS_M1R_TWA50_TWS24_RM18_20240410",
    "awa_range_id": "upwind",
    "aws_range_id": 1,
    "sail_abbreviations": [
      "M1R",
      "SS"
    ]
  },
  {
    "load_case_id": "LC11_ SS_M1R_TWA50_TWS24_RM18_20240410",
    "awa_range_id": "upwind",
    "aws_range_id": 2,
    "sail_abbreviations": [
      "M1R",
      "SS"
    ]
  },
  {
    "load_case_id": "LC11_ SS_M1R_TWA50_TWS24_RM18_20240410",
    "awa_range_id": "upwind",
    "aws_range_id": 3,
    "sail_abbreviations": [
      "M1R",
      "SS"
    ]
  },
  {
    "load_case_id": "LC11_ SS_M1R_TWA50_TWS24_RM18_20240410",
    "awa_range_id": "upwind",
    "aws_range_id": 4,
    "sail_abbreviations": [
      "M1R",
      "SS"
    ]
  },
  {
    "load_case_id": "LC11_ SS_M1R_TWA50_TWS24_RM18_20240410",
    "awa_range_id": "upwind",
    "aws_range_id": 5,
    "sail_abbreviations": [
      "M1R",
      "SS"
    ]
  },
  {
    "load_case_id": "LC11_ SS_M1R_TWA50_TWS24_RM18_20240410",
    "awa_range_id": "upwind",
    "aws_range_id": 6,
    "sail_abbreviations": [
      "M1R",
      "SS"
    ]
  },
  {
    "load_case_id": "LC11_ SS_M1R_TWA50_TWS24_RM18_20240410",
    "awa_range_id": "upwind",
    "aws_range_id": 7,
    "sail_abbreviations": [
      "M1R",
      "SS"
    ]
  },
  {
    "load_case_id": "LC7_ SS_M2R_MZ2R_TWA45_TWS26_RM20_20240410",
    "awa_range_id": "upwind",
    "aws_range_id": 1,
    "sail_abbreviations": [
      "M2R",
      "MZ2R",
      "SS"
    ]
  },
  {
    "load_case_id": "LC7_ SS_M2R_MZ2R_TWA45_TWS26_RM20_20240410",
    "awa_range_id": "upwind",
    "aws_range_id": 2,
    "sail_abbreviations": [
      "M2R",
      "MZ2R",
      "SS"
    ]
  },
  {
    "load_case_id": "LC7_ SS_M2R_MZ2R_TWA45_TWS26_RM20_20240410",
    "awa_range_id": "upwind",
    "aws_range_id": 3,
    "sail_abbreviations": [
      "M2R",
      "MZ2R",
      "SS"
    ]
  },
  {
    "load_case_id": "LC7_ SS_M2R_MZ2R_TWA45_TWS26_RM20_20240410",
    "awa_range_id": "upwind",
    "aws_range_id": 4,
    "sail_abbreviations": [
      "M2R",
      "MZ2R",
      "SS"
    ]
  },
  {
    "load_case_id": "LC7_ SS_M2R_MZ2R_TWA45_TWS26_RM20_20240410",
    "awa_range_id": "upwind",
    "aws_range_id": 5,
    "sail_abbreviations": [
      "M2R",
      "MZ2R",
      "SS"
    ]
  },
  {
    "load_case_id": "LC7-R_ SS_M2R_MZ2R_TWA90_TWS28_RM20_20240418",
    "awa_range_id": "upwind",
    "aws_range_id": 6,
    "sail_abbreviations": [
      "M2R",
      "MZ2R",
      "SS"
    ]
  },
  {
    "load_case_id": "LC7-R_ SS_M2R_MZ2R_TWA90_TWS28_RM20_20240418",
    "awa_range_id": "upwind",
    "aws_range_id": 7,
    "sail_abbreviations": [
      "M2R",
      "MZ2R",
      "SS"
    ]
  },
  {
    "load_case_id": "LC12_ SJ_M2R_TWA52_TWS30_RM15_20240412",
    "awa_range_id": "upwind",
    "aws_range_id": 1,
    "sail_abbreviations": [
      "M2R",
      "SJ"
    ]
  },
  {
    "load_case_id": "LC12_ SJ_M2R_TWA52_TWS30_RM15_20240412",
    "awa_range_id": "upwind",
    "aws_range_id": 2,
    "sail_abbreviations": [
      "M2R",
      "SJ"
    ]
  },
  {
    "load_case_id": "LC12_ SJ_M2R_TWA52_TWS30_RM15_20240412",
    "awa_range_id": "upwind",
    "aws_range_id": 3,
    "sail_abbreviations": [
      "M2R",
      "SJ"
    ]
  },
  {
    "load_case_id": "LC12_ SJ_M2R_TWA52_TWS30_RM15_20240412",
    "awa_range_id": "upwind",
    "aws_range_id": 4,
    "sail_abbreviations": [
      "M2R",
      "SJ"
    ]
  },
  {
    "load_case_id": "LC12_ SJ_M2R_TWA52_TWS30_RM15_20240412",
    "awa_range_id": "upwind",
    "aws_range_id": 5,
    "sail_abbreviations": [
      "M2R",
      "SJ"
    ]
  },
  {
    "load_case_id": "LC12_ SJ_M2R_TWA52_TWS30_RM15_20240412",
    "awa_range_id": "upwind",
    "aws_range_id": 6,
    "sail_abbreviations": [
      "M2R",
      "SJ"
    ]
  },
  {
    "load_case_id": "LC12_ SJ_M2R_TWA52_TWS30_RM15_20240412",
    "awa_range_id": "upwind",
    "aws_range_id": 7,
    "sail_abbreviations": [
      "M2R",
      "SJ"
    ]
  },
  {
    "load_case_id": "LC8_ SS_M2R_TWA50_TWS27_RM15_20240410",
    "awa_range_id": "upwind",
    "aws_range_id": 1,
    "sail_abbreviations": [
      "M2R",
      "SS"
    ]
  },
  {
    "load_case_id": "LC8_ SS_M2R_TWA50_TWS27_RM15_20240410",
    "awa_range_id": "upwind",
    "aws_range_id": 2,
    "sail_abbreviations": [
      "M2R",
      "SS"
    ]
  },
  {
    "load_case_id": "LC8_ SS_M2R_TWA50_TWS27_RM15_20240410",
    "awa_range_id": "upwind",
    "aws_range_id": 3,
    "sail_abbreviations": [
      "M2R",
      "SS"
    ]
  },
  {
    "load_case_id": "LC8_ SS_M2R_TWA50_TWS27_RM15_20240410",
    "awa_range_id": "upwind",
    "aws_range_id": 4,
    "sail_abbreviations": [
      "M2R",
      "SS"
    ]
  },
  {
    "load_case_id": "LC8_ SS_M2R_TWA50_TWS27_RM15_20240410",
    "awa_range_id": "upwind",
    "aws_range_id": 5,
    "sail_abbreviations": [
      "M2R",
      "SS"
    ]
  },
  {
    "load_case_id": "LC8_ SS_M2R_TWA50_TWS27_RM15_20240410",
    "awa_range_id": "upwind",
    "aws_range_id": 6,
    "sail_abbreviations": [
      "M2R",
      "SS"
    ]
  },
  {
    "load_case_id": "LC8_ SS_M2R_TWA50_TWS27_RM15_20240410",
    "awa_range_id": "upwind",
    "aws_range_id": 7,
    "sail_abbreviations": [
      "M2R",
      "SS"
    ]
  },
  {
    "load_case_id": "LC65-2_M3R_TWA70_TWS40_RM12_20240412",
    "awa_range_id": "upwind",
    "aws_range_id": 1,
    "sail_abbreviations": [
      "M3R"
    ]
  },
  {
    "load_case_id": "LC65-2_M3R_TWA70_TWS40_RM12_20240412",
    "awa_range_id": "upwind",
    "aws_range_id": 2,
    "sail_abbreviations": [
      "M3R"
    ]
  },
  {
    "load_case_id": "LC65-2_M3R_TWA70_TWS40_RM12_20240412",
    "awa_range_id": "upwind",
    "aws_range_id": 3,
    "sail_abbreviations": [
      "M3R"
    ]
  },
  {
    "load_case_id": "LC65-2_M3R_TWA70_TWS40_RM12_20240412",
    "awa_range_id": "upwind",
    "aws_range_id": 4,
    "sail_abbreviations": [
      "M3R"
    ]
  },
  {
    "load_case_id": "LC65-2_M3R_TWA70_TWS40_RM12_20240412",
    "awa_range_id": "upwind",
    "aws_range_id": 5,
    "sail_abbreviations": [
      "M3R"
    ]
  },
  {
    "load_case_id": "LC65-2_M3R_TWA70_TWS40_RM12_20240412",
    "awa_range_id": "upwind",
    "aws_range_id": 6,
    "sail_abbreviations": [
      "M3R"
    ]
  },
  {
    "load_case_id": "LC65-2_M3R_TWA70_TWS40_RM12_20240412",
    "awa_range_id": "upwind",
    "aws_range_id": 7,
    "sail_abbreviations": [
      "M3R"
    ]
  },
  {
    "load_case_id": "LC9_ SJ_M3R_TWA55_TWS35_RM12_20240412",
    "awa_range_id": "upwind",
    "aws_range_id": 1,
    "sail_abbreviations": [
      "M3R",
      "SJ"
    ]
  },
  {
    "load_case_id": "LC9_ SJ_M3R_TWA55_TWS35_RM12_20240412",
    "awa_range_id": "upwind",
    "aws_range_id": 2,
    "sail_abbreviations": [
      "M3R",
      "SJ"
    ]
  },
  {
    "load_case_id": "LC9_ SJ_M3R_TWA55_TWS35_RM12_20240412",
    "awa_range_id": "upwind",
    "aws_range_id": 3,
    "sail_abbreviations": [
      "M3R",
      "SJ"
    ]
  },
  {
    "load_case_id": "LC9_ SJ_M3R_TWA55_TWS35_RM12_20240412",
    "awa_range_id": "upwind",
    "aws_range_id": 4,
    "sail_abbreviations": [
      "M3R",
      "SJ"
    ]
  },
  {
    "load_case_id": "LC9_ SJ_M3R_TWA55_TWS35_RM12_20240412",
    "awa_range_id": "upwind",
    "aws_range_id": 5,
    "sail_abbreviations": [
      "M3R",
      "SJ"
    ]
  },
  {
    "load_case_id": "LC9_ SJ_M3R_TWA55_TWS35_RM12_20240412",
    "awa_range_id": "upwind",
    "aws_range_id": 6,
    "sail_abbreviations": [
      "M3R",
      "SJ"
    ]
  },
  {
    "load_case_id": "LC9_ SJ_M3R_TWA55_TWS35_RM12_20240412",
    "awa_range_id": "upwind",
    "aws_range_id": 7,
    "sail_abbreviations": [
      "M3R",
      "SJ"
    ]
  },
  {
    "load_case_id": "LC9-R_ SJ_M3R_TWA90_TWS35_RM12_20240418",
    "awa_range_id": "reaching",
    "aws_range_id": 1,
    "sail_abbreviations": [
      "M3R",
      "SJ"
    ]
  },
  {
    "load_case_id": "LC9-R_ SJ_M3R_TWA90_TWS35_RM12_20240418",
    "awa_range_id": "reaching",
    "aws_range_id": 2,
    "sail_abbreviations": [
      "M3R",
      "SJ"
    ]
  },
  {
    "load_case_id": "LC9-R_ SJ_M3R_TWA90_TWS35_RM12_20240418",
    "awa_range_id": "reaching",
    "aws_range_id": 3,
    "sail_abbreviations": [
      "M3R",
      "SJ"
    ]
  },
  {
    "load_case_id": "LC9-R_ SJ_M3R_TWA90_TWS35_RM12_20240418",
    "awa_range_id": "reaching",
    "aws_range_id": 4,
    "sail_abbreviations": [
      "M3R",
      "SJ"
    ]
  },
  {
    "load_case_id": "LC9-R_ SJ_M3R_TWA90_TWS35_RM12_20240418",
    "awa_range_id": "reaching",
    "aws_range_id": 5,
    "sail_abbreviations": [
      "M3R",
      "SJ"
    ]
  },
  {
    "load_case_id": "LC9-R_ SJ_M3R_TWA90_TWS35_RM12_20240418",
    "awa_range_id": "reaching",
    "aws_range_id": 6,
    "sail_abbreviations": [
      "M3R",
      "SJ"
    ]
  },
  {
    "load_case_id": "LC9-R_ SJ_M3R_TWA90_TWS35_RM12_20240418",
    "awa_range_id": "reaching",
    "aws_range_id": 7,
    "sail_abbreviations": [
      "M3R",
      "SJ"
    ]
  },
  {
    "load_case_id": "LC10_ SJ_TWA60_TWS45_RM10_20240419",
    "awa_range_id": "upwind",
    "aws_range_id": 1,
    "sail_abbreviations": [
      "SJ"
    ]
  },
  {
    "load_case_id": "LC10_ SJ_TWA60_TWS45_RM10_20240419",
    "awa_range_id": "upwind",
    "aws_range_id": 2,
    "sail_abbreviations": [
      "SJ"
    ]
  },
  {
    "load_case_id": "LC10_ SJ_TWA60_TWS45_RM10_20240419",
    "awa_range_id": "upwind",
    "aws_range_id": 3,
    "sail_abbreviations": [
      "SJ"
    ]
  },
  {
    "load_case_id": "LC10_ SJ_TWA60_TWS45_RM10_20240419",
    "awa_range_id": "upwind",
    "aws_range_id": 4,
    "sail_abbreviations": [
      "SJ"
    ]
  },
  {
    "load_case_id": "LC10_ SJ_TWA60_TWS45_RM10_20240419",
    "awa_range_id": "upwind",
    "aws_range_id": 5,
    "sail_abbreviations": [
      "SJ"
    ]
  },
  {
    "load_case_id": "LC10_ SJ_TWA60_TWS45_RM10_20240419",
    "awa_range_id": "upwind",
    "aws_range_id": 6,
    "sail_abbreviations": [
      "SJ"
    ]
  },
  {
    "load_case_id": "LC10_ SJ_TWA60_TWS45_RM10_20240419",
    "awa_range_id": "upwind",
    "aws_range_id": 7,
    "sail_abbreviations": [
      "SJ"
    ]
  }
]$$::jsonb) AS t(
        load_case_id TEXT,
        awa_range_id TEXT,
        aws_range_id INT,
        sail_abbreviations TEXT[]
    )
),
resolved_mappings AS (
    SELECT
        payload.load_case_id,
        payload.awa_range_id,
        payload.aws_range_id,
        (
            SELECT ssc.id
            FROM loads.sail_sets_combined AS ssc
            WHERE COALESCE(ssc.sails, '{}'::TEXT[]) = COALESCE(
                (
                    SELECT ARRAY_AGG(s.id ORDER BY s.id)
                    FROM loads.sails AS s
                    WHERE s.abbreviation = ANY(payload.sail_abbreviations)
                ),
                '{}'::TEXT[]
            )
            LIMIT 1
        ) AS sail_set_id
    FROM mapping_payload AS payload
)
INSERT INTO loads.load_case_mappings (
    load_case_id,
    awa_range_id,
    aws_range_id,
    sail_set_id
)
SELECT
    load_case_id,
    awa_range_id,
    aws_range_id,
    sail_set_id
FROM resolved_mappings
WHERE sail_set_id IS NOT NULL
ON CONFLICT (awa_range_id, aws_range_id, sail_set_id) DO UPDATE
SET
    load_case_id = EXCLUDED.load_case_id;

COMMIT;
