-- Generated by src/sailpack/export_seed.py
-- Uses jsonb_to_recordset and resolves sail_set_id from sail abbreviations.

BEGIN;

WITH load_case_payload AS (
    SELECT *
    FROM jsonb_to_recordset($$[
  {
    "id": "LC1-2_ B_FM_FMZ_TWA45_TWS14_RM22_20250306",
    "name": "LC1-2_ B_FM_FMZ_TWA45_TWS14_RM22_20250306",
    "awa": 42.8,
    "aws": 14.0,
    "sail_abbreviations": [
      "B",
      "FM",
      "FMZ"
    ]
  },
  {
    "id": "LC7-R_ SS_M2R_MZ2R_TWA90_TWS28_RM20_20240418",
    "name": "LC7-R_ SS_M2R_MZ2R_TWA90_TWS28_RM20_20240418",
    "awa": 69.3,
    "aws": 28.0,
    "sail_abbreviations": [
      "SS",
      "M2R",
      "MZ2R"
    ]
  },
  {
    "id": "LC35_ B_FM_FMZ_MZSS_TWA115_TWS26_RMMax_20240411",
    "name": "LC35_ B_FM_FMZ_MZSS_TWA115_TWS26_RMMax_20240411",
    "awa": 84.6,
    "aws": 26.0,
    "sail_abbreviations": [
      "B",
      "FM",
      "FMZ",
      "MZSS"
    ]
  },
  {
    "id": "FM B Rchng",
    "name": "FM B Rchng",
    "awa": 90.0,
    "aws": 22.0,
    "sail_abbreviations": [
      "FM",
      "B"
    ]
  },
  {
    "id": "LC20_ MH0_FM_FMZ_ TWA110_TWS12_RM15_NoRunner_20240630",
    "name": "LC20_ MH0_FM_FMZ_ TWA110_TWS12_RM15_NoRunner_20240630",
    "awa": 84.1,
    "aws": 12.0,
    "sail_abbreviations": [
      "FM",
      "FMZ"
    ]
  }
]$$::jsonb) AS t(
        id TEXT,
        name TEXT,
        awa NUMERIC,
        aws NUMERIC,
        sail_abbreviations TEXT[]
    )
),
resolved_load_cases AS (
    SELECT
        payload.id,
        payload.name,
        payload.awa,
        payload.aws,
        (
            SELECT ssc.id
            FROM loads.sail_sets_combined AS ssc
            WHERE COALESCE(ssc.sails, '{}'::TEXT[]) = COALESCE(
                (
                    SELECT ARRAY_AGG(s.id ORDER BY s.id)
                    FROM loads.sails AS s
                    WHERE s.abbreviation = ANY(payload.sail_abbreviations)
                ),
                '{}'::TEXT[]
            )
            LIMIT 1
        ) AS sail_set_id
    FROM load_case_payload AS payload
),
upsert_load_cases AS (
    INSERT INTO loads.load_cases (id, name, awa, aws, sail_set_id)
    SELECT
        id,
        name,
        awa,
        aws,
        sail_set_id
    FROM resolved_load_cases
    ON CONFLICT (id) DO UPDATE
    SET
        name = EXCLUDED.name,
        awa = EXCLUDED.awa,
        aws = EXCLUDED.aws,
        sail_set_id = EXCLUDED.sail_set_id
    RETURNING id
),
reference_payload AS (
    SELECT *
    FROM jsonb_to_recordset($$[
  {
    "load_case_id": "LC1-2_ B_FM_FMZ_TWA45_TWS14_RM22_20250306",
    "variable_key": "mizzen-vang-relative-position",
    "target": 0.02,
    "alarm_low": null,
    "warning_low": null,
    "warning_high": null,
    "alarm_high": null
  },
  {
    "load_case_id": "LC1-2_ B_FM_FMZ_TWA45_TWS14_RM22_20250306",
    "variable_key": "mizzen-checkstay-deflector-relative-position",
    "target": -0.75,
    "alarm_low": null,
    "warning_low": null,
    "warning_high": null,
    "alarm_high": null
  },
  {
    "load_case_id": "LC1-2_ B_FM_FMZ_TWA45_TWS14_RM22_20250306",
    "variable_key": "main-traveller-relative-position",
    "target": 0.5,
    "alarm_low": null,
    "warning_low": null,
    "warning_high": null,
    "alarm_high": null
  },
  {
    "load_case_id": "LC1-2_ B_FM_FMZ_TWA45_TWS14_RM22_20250306",
    "variable_key": "main-checkstay-deflector-relative-position",
    "target": -0.75,
    "alarm_low": null,
    "warning_low": null,
    "warning_high": null,
    "alarm_high": null
  },
  {
    "load_case_id": "LC1-2_ B_FM_FMZ_TWA45_TWS14_RM22_20250306",
    "variable_key": "main-vang-relative-position",
    "target": 100.0,
    "alarm_low": null,
    "warning_low": null,
    "warning_high": null,
    "alarm_high": null
  },
  {
    "load_case_id": "LC1-2_ B_FM_FMZ_TWA45_TWS14_RM22_20250306",
    "variable_key": "blade-tweaker-relative-position",
    "target": -0.15,
    "alarm_low": null,
    "warning_low": null,
    "warning_high": null,
    "alarm_high": null
  },
  {
    "load_case_id": "LC1-2_ B_FM_FMZ_TWA45_TWS14_RM22_20250306",
    "variable_key": "main-outhaul-relative-position",
    "target": -0.05,
    "alarm_low": null,
    "warning_low": null,
    "warning_high": null,
    "alarm_high": null
  },
  {
    "load_case_id": "LC1-2_ B_FM_FMZ_TWA45_TWS14_RM22_20250306",
    "variable_key": "main-cunningham-stroke",
    "target": 25000.0,
    "alarm_low": null,
    "warning_low": null,
    "warning_high": null,
    "alarm_high": null
  },
  {
    "load_case_id": "LC1-2_ B_FM_FMZ_TWA45_TWS14_RM22_20250306",
    "variable_key": "mizzen-outhaul-relative-position",
    "target": 0.01,
    "alarm_low": null,
    "warning_low": null,
    "warning_high": null,
    "alarm_high": null
  },
  {
    "load_case_id": "LC1-2_ B_FM_FMZ_TWA45_TWS14_RM22_20250306",
    "variable_key": "mizzen-cunningham-stroke",
    "target": 15000.0,
    "alarm_low": null,
    "warning_low": null,
    "warning_high": null,
    "alarm_high": null
  },
  {
    "load_case_id": "LC7-R_ SS_M2R_MZ2R_TWA90_TWS28_RM20_20240418",
    "variable_key": "mizzen-vang-relative-position",
    "target": 0.085,
    "alarm_low": null,
    "warning_low": null,
    "warning_high": null,
    "alarm_high": null
  },
  {
    "load_case_id": "LC7-R_ SS_M2R_MZ2R_TWA90_TWS28_RM20_20240418",
    "variable_key": "mizzen-checkstay-deflector-relative-position",
    "target": -0.3,
    "alarm_low": null,
    "warning_low": null,
    "warning_high": null,
    "alarm_high": null
  },
  {
    "load_case_id": "LC7-R_ SS_M2R_MZ2R_TWA90_TWS28_RM20_20240418",
    "variable_key": "main-traveller-relative-position",
    "target": 2.5,
    "alarm_low": null,
    "warning_low": null,
    "warning_high": null,
    "alarm_high": null
  },
  {
    "load_case_id": "LC7-R_ SS_M2R_MZ2R_TWA90_TWS28_RM20_20240418",
    "variable_key": "main-checkstay-deflector-relative-position",
    "target": -0.5,
    "alarm_low": null,
    "warning_low": null,
    "warning_high": null,
    "alarm_high": null
  },
  {
    "load_case_id": "LC7-R_ SS_M2R_MZ2R_TWA90_TWS28_RM20_20240418",
    "variable_key": "main-vang-relative-position",
    "target": 0.055,
    "alarm_low": null,
    "warning_low": null,
    "warning_high": null,
    "alarm_high": null
  },
  {
    "load_case_id": "LC7-R_ SS_M2R_MZ2R_TWA90_TWS28_RM20_20240418",
    "variable_key": "staysail-stay-adjuster-relative-position",
    "target": -0.1,
    "alarm_low": null,
    "warning_low": null,
    "warning_high": null,
    "alarm_high": null
  },
  {
    "load_case_id": "LC35_ B_FM_FMZ_MZSS_TWA115_TWS26_RMMax_20240411",
    "variable_key": "mizzen-vang-relative-position",
    "target": 0.03,
    "alarm_low": null,
    "warning_low": null,
    "warning_high": null,
    "alarm_high": null
  },
  {
    "load_case_id": "LC35_ B_FM_FMZ_MZSS_TWA115_TWS26_RMMax_20240411",
    "variable_key": "mizzen-checkstay-deflector-relative-position",
    "target": 2500.0,
    "alarm_low": null,
    "warning_low": null,
    "warning_high": null,
    "alarm_high": null
  },
  {
    "load_case_id": "LC35_ B_FM_FMZ_MZSS_TWA115_TWS26_RMMax_20240411",
    "variable_key": "main-traveller-relative-position",
    "target": 2.5,
    "alarm_low": null,
    "warning_low": null,
    "warning_high": null,
    "alarm_high": null
  },
  {
    "load_case_id": "LC35_ B_FM_FMZ_MZSS_TWA115_TWS26_RMMax_20240411",
    "variable_key": "main-vang-relative-position",
    "target": 0.035,
    "alarm_low": null,
    "warning_low": null,
    "warning_high": null,
    "alarm_high": null
  },
  {
    "load_case_id": "LC35_ B_FM_FMZ_MZSS_TWA115_TWS26_RMMax_20240411",
    "variable_key": "blade-tweaker-relative-position",
    "target": 0.2,
    "alarm_low": null,
    "warning_low": null,
    "warning_high": null,
    "alarm_high": null
  },
  {
    "load_case_id": "LC35_ B_FM_FMZ_MZSS_TWA115_TWS26_RMMax_20240411",
    "variable_key": "main-outhaul-relative-position",
    "target": -0.045,
    "alarm_low": null,
    "warning_low": null,
    "warning_high": null,
    "alarm_high": null
  },
  {
    "load_case_id": "LC35_ B_FM_FMZ_MZSS_TWA115_TWS26_RMMax_20240411",
    "variable_key": "main-cunningham-stroke",
    "target": 17500.0,
    "alarm_low": null,
    "warning_low": null,
    "warning_high": null,
    "alarm_high": null
  },
  {
    "load_case_id": "LC35_ B_FM_FMZ_MZSS_TWA115_TWS26_RMMax_20240411",
    "variable_key": "mizzen-outhaul-relative-position",
    "target": -0.01,
    "alarm_low": null,
    "warning_low": null,
    "warning_high": null,
    "alarm_high": null
  },
  {
    "load_case_id": "LC35_ B_FM_FMZ_MZSS_TWA115_TWS26_RMMax_20240411",
    "variable_key": "mizzen-cunningham-stroke",
    "target": 10000.0,
    "alarm_low": null,
    "warning_low": null,
    "warning_high": null,
    "alarm_high": null
  },
  {
    "load_case_id": "LC35_ B_FM_FMZ_MZSS_TWA115_TWS26_RMMax_20240411",
    "variable_key": "mizzen-headsail-tack-adjuster-relative-position",
    "target": -0.1,
    "alarm_low": null,
    "warning_low": null,
    "warning_high": null,
    "alarm_high": null
  },
  {
    "load_case_id": "FM B Rchng",
    "variable_key": "main-traveller-relative-position",
    "target": 2.85,
    "alarm_low": null,
    "warning_low": null,
    "warning_high": null,
    "alarm_high": null
  },
  {
    "load_case_id": "FM B Rchng",
    "variable_key": "main-checkstay-deflector-relative-position",
    "target": -0.75,
    "alarm_low": null,
    "warning_low": null,
    "warning_high": null,
    "alarm_high": null
  },
  {
    "load_case_id": "FM B Rchng",
    "variable_key": "mizzen-checkstay-deflector-relative-position",
    "target": -0.75,
    "alarm_low": null,
    "warning_low": null,
    "warning_high": null,
    "alarm_high": null
  },
  {
    "load_case_id": "FM B Rchng",
    "variable_key": "main-vang-relative-position",
    "target": 100.0,
    "alarm_low": null,
    "warning_low": null,
    "warning_high": null,
    "alarm_high": null
  },
  {
    "load_case_id": "FM B Rchng",
    "variable_key": "main-outhaul-relative-position",
    "target": -0.05,
    "alarm_low": null,
    "warning_low": null,
    "warning_high": null,
    "alarm_high": null
  },
  {
    "load_case_id": "FM B Rchng",
    "variable_key": "blade-tweaker-relative-position",
    "target": -0.15,
    "alarm_low": null,
    "warning_low": null,
    "warning_high": null,
    "alarm_high": null
  },
  {
    "load_case_id": "FM B Rchng",
    "variable_key": "main-cunningham-stroke",
    "target": 50000.0,
    "alarm_low": null,
    "warning_low": null,
    "warning_high": null,
    "alarm_high": null
  },
  {
    "load_case_id": "LC20_ MH0_FM_FMZ_ TWA110_TWS12_RM15_NoRunner_20240630",
    "variable_key": "mizzen-vang-relative-position",
    "target": 0.015,
    "alarm_low": null,
    "warning_low": null,
    "warning_high": null,
    "alarm_high": null
  },
  {
    "load_case_id": "LC20_ MH0_FM_FMZ_ TWA110_TWS12_RM15_NoRunner_20240630",
    "variable_key": "mizzen-checkstay-deflector-relative-position",
    "target": -0.5,
    "alarm_low": null,
    "warning_low": null,
    "warning_high": null,
    "alarm_high": null
  },
  {
    "load_case_id": "LC20_ MH0_FM_FMZ_ TWA110_TWS12_RM15_NoRunner_20240630",
    "variable_key": "main-traveller-relative-position",
    "target": 2.0,
    "alarm_low": null,
    "warning_low": null,
    "warning_high": null,
    "alarm_high": null
  },
  {
    "load_case_id": "LC20_ MH0_FM_FMZ_ TWA110_TWS12_RM15_NoRunner_20240630",
    "variable_key": "main-checkstay-deflector-relative-position",
    "target": -0.75,
    "alarm_low": null,
    "warning_low": null,
    "warning_high": null,
    "alarm_high": null
  },
  {
    "load_case_id": "LC20_ MH0_FM_FMZ_ TWA110_TWS12_RM15_NoRunner_20240630",
    "variable_key": "main-vang-relative-position",
    "target": 550000.0,
    "alarm_low": null,
    "warning_low": null,
    "warning_high": null,
    "alarm_high": null
  },
  {
    "load_case_id": "LC20_ MH0_FM_FMZ_ TWA110_TWS12_RM15_NoRunner_20240630",
    "variable_key": "main-outhaul-relative-position",
    "target": -0.065,
    "alarm_low": null,
    "warning_low": null,
    "warning_high": null,
    "alarm_high": null
  },
  {
    "load_case_id": "LC20_ MH0_FM_FMZ_ TWA110_TWS12_RM15_NoRunner_20240630",
    "variable_key": "main-cunningham-stroke",
    "target": 20000.0,
    "alarm_low": null,
    "warning_low": null,
    "warning_high": null,
    "alarm_high": null
  },
  {
    "load_case_id": "LC20_ MH0_FM_FMZ_ TWA110_TWS12_RM15_NoRunner_20240630",
    "variable_key": "mizzen-outhaul-relative-position",
    "target": -0.03,
    "alarm_low": null,
    "warning_low": null,
    "warning_high": null,
    "alarm_high": null
  },
  {
    "load_case_id": "LC20_ MH0_FM_FMZ_ TWA110_TWS12_RM15_NoRunner_20240630",
    "variable_key": "mizzen-cunningham-stroke",
    "target": 15000.0,
    "alarm_low": null,
    "warning_low": null,
    "warning_high": null,
    "alarm_high": null
  },
  {
    "load_case_id": "LC20_ MH0_FM_FMZ_ TWA110_TWS12_RM15_NoRunner_20240630",
    "variable_key": "code-zero-tack-relative-position",
    "target": 0.05,
    "alarm_low": null,
    "warning_low": null,
    "warning_high": null,
    "alarm_high": null
  },
  {
    "load_case_id": "LC1-2_ B_FM_FMZ_TWA45_TWS14_RM22_20250306",
    "variable_key": "fiber-optic-mizzen-v1-sb",
    "target": 10.008208715514472,
    "alarm_low": null,
    "warning_low": null,
    "warning_high": null,
    "alarm_high": null
  },
  {
    "load_case_id": "LC1-2_ B_FM_FMZ_TWA45_TWS14_RM22_20250306",
    "variable_key": "fiber-optic-mizzen-v1-ps",
    "target": 34.66535463180597,
    "alarm_low": null,
    "warning_low": null,
    "warning_high": null,
    "alarm_high": null
  },
  {
    "load_case_id": "LC1-2_ B_FM_FMZ_TWA45_TWS14_RM22_20250306",
    "variable_key": "fiber-optic-mizzen-d1-sb",
    "target": 0.37464373664809086,
    "alarm_low": null,
    "warning_low": null,
    "warning_high": null,
    "alarm_high": null
  },
  {
    "load_case_id": "LC1-2_ B_FM_FMZ_TWA45_TWS14_RM22_20250306",
    "variable_key": "fiber-optic-mizzen-d1-ps",
    "target": 13.741593714469264,
    "alarm_low": null,
    "warning_low": null,
    "warning_high": null,
    "alarm_high": null
  },
  {
    "load_case_id": "LC1-2_ B_FM_FMZ_TWA45_TWS14_RM22_20250306",
    "variable_key": "fiber-optic-mizzen-forestay",
    "target": 25.750893526331623,
    "alarm_low": null,
    "warning_low": null,
    "warning_high": null,
    "alarm_high": null
  },
  {
    "load_case_id": "LC1-2_ B_FM_FMZ_TWA45_TWS14_RM22_20250306",
    "variable_key": "fiber-optic-main-v1-sb",
    "target": 13.66644062957279,
    "alarm_low": null,
    "warning_low": null,
    "warning_high": null,
    "alarm_high": null
  },
  {
    "load_case_id": "LC1-2_ B_FM_FMZ_TWA45_TWS14_RM22_20250306",
    "variable_key": "fiber-optic-main-v1-ps",
    "target": 64.16798804892599,
    "alarm_low": null,
    "warning_low": null,
    "warning_high": null,
    "alarm_high": null
  },
  {
    "load_case_id": "LC1-2_ B_FM_FMZ_TWA45_TWS14_RM22_20250306",
    "variable_key": "fiber-optic-main-d1-sb",
    "target": 2.064721388037709,
    "alarm_low": null,
    "warning_low": null,
    "warning_high": null,
    "alarm_high": null
  },
  {
    "load_case_id": "LC1-2_ B_FM_FMZ_TWA45_TWS14_RM22_20250306",
    "variable_key": "fiber-optic-main-d1-ps",
    "target": 25.280498437284905,
    "alarm_low": null,
    "warning_low": null,
    "warning_high": null,
    "alarm_high": null
  },
  {
    "load_case_id": "LC1-2_ B_FM_FMZ_TWA45_TWS14_RM22_20250306",
    "variable_key": "mizzen-runner-load",
    "target": 1.1435097612334488,
    "alarm_low": null,
    "warning_low": null,
    "warning_high": null,
    "alarm_high": null
  },
  {
    "load_case_id": "LC1-2_ B_FM_FMZ_TWA45_TWS14_RM22_20250306",
    "variable_key": "mizzen-checkstay-load",
    "target": 1.2799477905298955,
    "alarm_low": null,
    "warning_low": null,
    "warning_high": null,
    "alarm_high": null
  },
  {
    "load_case_id": "LC1-2_ B_FM_FMZ_TWA45_TWS14_RM22_20250306",
    "variable_key": "mizzen-vang-load",
    "target": 0.005200552686187434,
    "alarm_low": null,
    "warning_low": null,
    "warning_high": null,
    "alarm_high": null
  },
  {
    "load_case_id": "LC1-2_ B_FM_FMZ_TWA45_TWS14_RM22_20250306",
    "variable_key": "mizzen-checkstay-deflector-load",
    "target": 0.23759387762385728,
    "alarm_low": null,
    "warning_low": null,
    "warning_high": null,
    "alarm_high": null
  },
  {
    "load_case_id": "LC1-2_ B_FM_FMZ_TWA45_TWS14_RM22_20250306",
    "variable_key": "mizzen-preventer-load",
    "target": 0.0,
    "alarm_low": null,
    "warning_low": null,
    "warning_high": null,
    "alarm_high": null
  },
  {
    "load_case_id": "LC1-2_ B_FM_FMZ_TWA45_TWS14_RM22_20250306",
    "variable_key": "mizzen-sheet-load",
    "target": 6.3680257784258645,
    "alarm_low": null,
    "warning_low": null,
    "warning_high": null,
    "alarm_high": null
  },
  {
    "load_case_id": "LC1-2_ B_FM_FMZ_TWA45_TWS14_RM22_20250306",
    "variable_key": "main-checkstay-load",
    "target": 0.85054529324489,
    "alarm_low": null,
    "warning_low": null,
    "warning_high": null,
    "alarm_high": null
  },
  {
    "load_case_id": "LC1-2_ B_FM_FMZ_TWA45_TWS14_RM22_20250306",
    "variable_key": "main-runner-load",
    "target": 17.70247740053943,
    "alarm_low": null,
    "warning_low": null,
    "warning_high": null,
    "alarm_high": null
  },
  {
    "load_case_id": "LC1-2_ B_FM_FMZ_TWA45_TWS14_RM22_20250306",
    "variable_key": "main-checkstay-deflector-load",
    "target": 0.07668265921594021,
    "alarm_low": null,
    "warning_low": null,
    "warning_high": null,
    "alarm_high": null
  },
  {
    "load_case_id": "LC1-2_ B_FM_FMZ_TWA45_TWS14_RM22_20250306",
    "variable_key": "main-vang-load",
    "target": 0.010197162129779282,
    "alarm_low": null,
    "warning_low": null,
    "warning_high": null,
    "alarm_high": null
  },
  {
    "load_case_id": "LC1-2_ B_FM_FMZ_TWA45_TWS14_RM22_20250306",
    "variable_key": "main-preventer-load",
    "target": 0.0,
    "alarm_low": null,
    "warning_low": null,
    "warning_high": null,
    "alarm_high": null
  },
  {
    "load_case_id": "LC1-2_ B_FM_FMZ_TWA45_TWS14_RM22_20250306",
    "variable_key": "blade-tweaker-load",
    "target": 4.103440012644481,
    "alarm_low": null,
    "warning_low": null,
    "warning_high": null,
    "alarm_high": null
  },
  {
    "load_case_id": "LC1-2_ B_FM_FMZ_TWA45_TWS14_RM22_20250306",
    "variable_key": "main-sheet-load",
    "target": 8.931490366231078,
    "alarm_low": null,
    "warning_low": null,
    "warning_high": null,
    "alarm_high": null
  },
  {
    "load_case_id": "LC1-2_ B_FM_FMZ_TWA45_TWS14_RM22_20250306",
    "variable_key": "main-halyard-load",
    "target": 19.3440165601913,
    "alarm_low": null,
    "warning_low": null,
    "warning_high": null,
    "alarm_high": null
  },
  {
    "load_case_id": "LC1-2_ B_FM_FMZ_TWA45_TWS14_RM22_20250306",
    "variable_key": "main-outhaul-load",
    "target": 8.188831048319253,
    "alarm_low": null,
    "warning_low": null,
    "warning_high": null,
    "alarm_high": null
  },
  {
    "load_case_id": "LC1-2_ B_FM_FMZ_TWA45_TWS14_RM22_20250306",
    "variable_key": "main-cunningham-load",
    "target": 2.5492905324448207,
    "alarm_low": null,
    "warning_low": null,
    "warning_high": null,
    "alarm_high": null
  },
  {
    "load_case_id": "LC1-2_ B_FM_FMZ_TWA45_TWS14_RM22_20250306",
    "variable_key": "mizzen-halyard-load",
    "target": 13.937277255739728,
    "alarm_low": null,
    "warning_low": null,
    "warning_high": null,
    "alarm_high": null
  },
  {
    "load_case_id": "LC1-2_ B_FM_FMZ_TWA45_TWS14_RM22_20250306",
    "variable_key": "mizzen-outhaul-load",
    "target": 5.720098096699688,
    "alarm_low": null,
    "warning_low": null,
    "warning_high": null,
    "alarm_high": null
  },
  {
    "load_case_id": "LC1-2_ B_FM_FMZ_TWA45_TWS14_RM22_20250306",
    "variable_key": "mizzen-cunningham-load",
    "target": 1.5295743194668925,
    "alarm_low": null,
    "warning_low": null,
    "warning_high": null,
    "alarm_high": null
  },
  {
    "load_case_id": "LC1-2_ B_FM_FMZ_TWA45_TWS14_RM22_20250306",
    "variable_key": "blade-sheet-feeder-load",
    "target": 8.941381613496963,
    "alarm_low": null,
    "warning_low": null,
    "warning_high": null,
    "alarm_high": null
  },
  {
    "load_case_id": "LC1-2_ B_FM_FMZ_TWA45_TWS14_RM22_20250306",
    "variable_key": "primary-winch-load",
    "target": 0.0,
    "alarm_low": null,
    "warning_low": null,
    "warning_high": null,
    "alarm_high": null
  },
  {
    "load_case_id": "LC1-2_ B_FM_FMZ_TWA45_TWS14_RM22_20250306",
    "variable_key": "headsail-locks-lock-Jib",
    "target": 189305.0,
    "alarm_low": null,
    "warning_low": null,
    "warning_high": null,
    "alarm_high": null
  },
  {
    "load_case_id": "LC1-2_ B_FM_FMZ_TWA45_TWS14_RM22_20250306",
    "variable_key": "blade-cunningham-load",
    "target": 15.67385396644114,
    "alarm_low": null,
    "warning_low": null,
    "warning_high": null,
    "alarm_high": null
  },
  {
    "load_case_id": "LC1-2_ B_FM_FMZ_TWA45_TWS14_RM22_20250306",
    "variable_key": "main-headstay-combined-load",
    "target": 15.67385396644114,
    "alarm_low": null,
    "warning_low": null,
    "warning_high": null,
    "alarm_high": null
  },
  {
    "load_case_id": "LC1-2_ B_FM_FMZ_TWA45_TWS14_RM22_20250306",
    "variable_key": "blade-adjuster-load",
    "target": 27.456776779022398,
    "alarm_low": null,
    "warning_low": null,
    "warning_high": null,
    "alarm_high": null
  },
  {
    "load_case_id": "LC7-R_ SS_M2R_MZ2R_TWA90_TWS28_RM20_20240418",
    "variable_key": "fiber-optic-mizzen-v1-sb",
    "target": 14.02130187168911,
    "alarm_low": null,
    "warning_low": null,
    "warning_high": null,
    "alarm_high": null
  },
  {
    "load_case_id": "LC7-R_ SS_M2R_MZ2R_TWA90_TWS28_RM20_20240418",
    "variable_key": "fiber-optic-mizzen-v1-ps",
    "target": 29.692504575976507,
    "alarm_low": null,
    "warning_low": null,
    "warning_high": null,
    "alarm_high": null
  },
  {
    "load_case_id": "LC7-R_ SS_M2R_MZ2R_TWA90_TWS28_RM20_20240418",
    "variable_key": "fiber-optic-mizzen-d1-sb",
    "target": 0.0,
    "alarm_low": null,
    "warning_low": null,
    "warning_high": null,
    "alarm_high": null
  },
  {
    "load_case_id": "LC7-R_ SS_M2R_MZ2R_TWA90_TWS28_RM20_20240418",
    "variable_key": "fiber-optic-mizzen-d1-ps",
    "target": 15.709340090652772,
    "alarm_low": null,
    "warning_low": null,
    "warning_high": null,
    "alarm_high": null
  },
  {
    "load_case_id": "LC7-R_ SS_M2R_MZ2R_TWA90_TWS28_RM20_20240418",
    "variable_key": "fiber-optic-mizzen-forestay",
    "target": 25.566018976918723,
    "alarm_low": null,
    "warning_low": null,
    "warning_high": null,
    "alarm_high": null
  },
  {
    "load_case_id": "LC7-R_ SS_M2R_MZ2R_TWA90_TWS28_RM20_20240418",
    "variable_key": "fiber-optic-main-v1-sb",
    "target": 23.468666670065723,
    "alarm_low": null,
    "warning_low": null,
    "warning_high": null,
    "alarm_high": null
  },
  {
    "load_case_id": "LC7-R_ SS_M2R_MZ2R_TWA90_TWS28_RM20_20240418",
    "variable_key": "fiber-optic-main-v1-ps",
    "target": 68.21819887525302,
    "alarm_low": null,
    "warning_low": null,
    "warning_high": null,
    "alarm_high": null
  },
  {
    "load_case_id": "LC7-R_ SS_M2R_MZ2R_TWA90_TWS28_RM20_20240418",
    "variable_key": "fiber-optic-main-d1-sb",
    "target": 4.934304782978897,
    "alarm_low": null,
    "warning_low": null,
    "warning_high": null,
    "alarm_high": null
  },
  {
    "load_case_id": "LC7-R_ SS_M2R_MZ2R_TWA90_TWS28_RM20_20240418",
    "variable_key": "fiber-optic-main-d1-ps",
    "target": 34.47782882023933,
    "alarm_low": null,
    "warning_low": null,
    "warning_high": null,
    "alarm_high": null
  },
  {
    "load_case_id": "LC7-R_ SS_M2R_MZ2R_TWA90_TWS28_RM20_20240418",
    "variable_key": "blade-adjuster-load",
    "target": 12.740844223052726,
    "alarm_low": null,
    "warning_low": null,
    "warning_high": null,
    "alarm_high": null
  },
  {
    "load_case_id": "LC7-R_ SS_M2R_MZ2R_TWA90_TWS28_RM20_20240418",
    "variable_key": "main-headstay-combined-load",
    "target": 12.740844223052726,
    "alarm_low": null,
    "warning_low": null,
    "warning_high": null,
    "alarm_high": null
  },
  {
    "load_case_id": "LC7-R_ SS_M2R_MZ2R_TWA90_TWS28_RM20_20240418",
    "variable_key": "mizzen-runner-load",
    "target": 8.951782718869339,
    "alarm_low": null,
    "warning_low": null,
    "warning_high": null,
    "alarm_high": null
  },
  {
    "load_case_id": "LC7-R_ SS_M2R_MZ2R_TWA90_TWS28_RM20_20240418",
    "variable_key": "mizzen-checkstay-load",
    "target": 1.5472154099514106,
    "alarm_low": null,
    "warning_low": null,
    "warning_high": null,
    "alarm_high": null
  },
  {
    "load_case_id": "LC7-R_ SS_M2R_MZ2R_TWA90_TWS28_RM20_20240418",
    "variable_key": "mizzen-vang-load",
    "target": 17.507303717375454,
    "alarm_low": null,
    "warning_low": null,
    "warning_high": null,
    "alarm_high": null
  },
  {
    "load_case_id": "LC7-R_ SS_M2R_MZ2R_TWA90_TWS28_RM20_20240418",
    "variable_key": "mizzen-checkstay-deflector-load",
    "target": 0.20679844799192384,
    "alarm_low": null,
    "warning_low": null,
    "warning_high": null,
    "alarm_high": null
  },
  {
    "load_case_id": "LC7-R_ SS_M2R_MZ2R_TWA90_TWS28_RM20_20240418",
    "variable_key": "mizzen-preventer-load",
    "target": 3.3805631892644277,
    "alarm_low": null,
    "warning_low": null,
    "warning_high": null,
    "alarm_high": null
  },
  {
    "load_case_id": "LC7-R_ SS_M2R_MZ2R_TWA90_TWS28_RM20_20240418",
    "variable_key": "mizzen-sheet-load",
    "target": 1.692219055436872,
    "alarm_low": null,
    "warning_low": null,
    "warning_high": null,
    "alarm_high": null
  },
  {
    "load_case_id": "LC7-R_ SS_M2R_MZ2R_TWA90_TWS28_RM20_20240418",
    "variable_key": "main-checkstay-load",
    "target": 4.319415906553206,
    "alarm_low": null,
    "warning_low": null,
    "warning_high": null,
    "alarm_high": null
  },
  {
    "load_case_id": "LC7-R_ SS_M2R_MZ2R_TWA90_TWS28_RM20_20240418",
    "variable_key": "main-runner-load",
    "target": 14.438365802797081,
    "alarm_low": null,
    "warning_low": null,
    "warning_high": null,
    "alarm_high": null
  },
  {
    "load_case_id": "LC7-R_ SS_M2R_MZ2R_TWA90_TWS28_RM20_20240418",
    "variable_key": "main-checkstay-deflector-load",
    "target": 0.21281477364849363,
    "alarm_low": null,
    "warning_low": null,
    "warning_high": null,
    "alarm_high": null
  },
  {
    "load_case_id": "LC7-R_ SS_M2R_MZ2R_TWA90_TWS28_RM20_20240418",
    "variable_key": "main-vang-load",
    "target": 0.06342634844722714,
    "alarm_low": null,
    "warning_low": null,
    "warning_high": null,
    "alarm_high": null
  },
  {
    "load_case_id": "LC7-R_ SS_M2R_MZ2R_TWA90_TWS28_RM20_20240418",
    "variable_key": "main-preventer-load",
    "target": 8.441108839409992,
    "alarm_low": null,
    "warning_low": null,
    "warning_high": null,
    "alarm_high": null
  },
  {
    "load_case_id": "LC7-R_ SS_M2R_MZ2R_TWA90_TWS28_RM20_20240418",
    "variable_key": "main-sheet-load",
    "target": 4.394670963070977,
    "alarm_low": null,
    "warning_low": null,
    "warning_high": null,
    "alarm_high": null
  },
  {
    "load_case_id": "LC7-R_ SS_M2R_MZ2R_TWA90_TWS28_RM20_20240418",
    "variable_key": "main-halyard-lock-2",
    "target": 151468.0,
    "alarm_low": null,
    "warning_low": null,
    "warning_high": null,
    "alarm_high": null
  },
  {
    "load_case_id": "LC7-R_ SS_M2R_MZ2R_TWA90_TWS28_RM20_20240418",
    "variable_key": "mizzen-halyard-lock-2",
    "target": 102712.0,
    "alarm_low": null,
    "warning_low": null,
    "warning_high": null,
    "alarm_high": null
  },
  {
    "load_case_id": "LC7-R_ SS_M2R_MZ2R_TWA90_TWS28_RM20_20240418",
    "variable_key": "mizzen-halyard-boom-lock-2",
    "target": 125889.0,
    "alarm_low": null,
    "warning_low": null,
    "warning_high": null,
    "alarm_high": null
  },
  {
    "load_case_id": "LC7-R_ SS_M2R_MZ2R_TWA90_TWS28_RM20_20240418",
    "variable_key": "headsail-locks-lock-staysail",
    "target": 326598.0,
    "alarm_low": null,
    "warning_low": null,
    "warning_high": null,
    "alarm_high": null
  },
  {
    "load_case_id": "LC7-R_ SS_M2R_MZ2R_TWA90_TWS28_RM20_20240418",
    "variable_key": "staysail-sheet-feeder-load",
    "target": 0.10197162129779283,
    "alarm_low": null,
    "warning_low": null,
    "warning_high": null,
    "alarm_high": null
  },
  {
    "load_case_id": "LC7-R_ SS_M2R_MZ2R_TWA90_TWS28_RM20_20240418",
    "variable_key": "staysail-stay-adjuster-load",
    "target": 29.41932260251972,
    "alarm_low": null,
    "warning_low": null,
    "warning_high": null,
    "alarm_high": null
  },
  {
    "load_case_id": "LC35_ B_FM_FMZ_MZSS_TWA115_TWS26_RMMax_20240411",
    "variable_key": "fiber-optic-mizzen-v1-sb",
    "target": 1.5365083897151424,
    "alarm_low": null,
    "warning_low": null,
    "warning_high": null,
    "alarm_high": null
  },
  {
    "load_case_id": "LC35_ B_FM_FMZ_MZSS_TWA115_TWS26_RMMax_20240411",
    "variable_key": "fiber-optic-mizzen-v1-ps",
    "target": 53.87170950324525,
    "alarm_low": null,
    "warning_low": null,
    "warning_high": null,
    "alarm_high": null
  },
  {
    "load_case_id": "LC35_ B_FM_FMZ_MZSS_TWA115_TWS26_RMMax_20240411",
    "variable_key": "fiber-optic-mizzen-d1-sb",
    "target": 0.733379900373726,
    "alarm_low": null,
    "warning_low": null,
    "warning_high": null,
    "alarm_high": null
  },
  {
    "load_case_id": "LC35_ B_FM_FMZ_MZSS_TWA115_TWS26_RMMax_20240411",
    "variable_key": "fiber-optic-mizzen-d1-ps",
    "target": 19.517368316397548,
    "alarm_low": null,
    "warning_low": null,
    "warning_high": null,
    "alarm_high": null
  },
  {
    "load_case_id": "LC35_ B_FM_FMZ_MZSS_TWA115_TWS26_RMMax_20240411",
    "variable_key": "fiber-optic-mizzen-forestay",
    "target": 0.021414040472536495,
    "alarm_low": null,
    "warning_low": null,
    "warning_high": null,
    "alarm_high": null
  },
  {
    "load_case_id": "LC35_ B_FM_FMZ_MZSS_TWA115_TWS26_RMMax_20240411",
    "variable_key": "fiber-optic-main-v1-sb",
    "target": 7.204804902795552,
    "alarm_low": null,
    "warning_low": null,
    "warning_high": null,
    "alarm_high": null
  },
  {
    "load_case_id": "LC35_ B_FM_FMZ_MZSS_TWA115_TWS26_RMMax_20240411",
    "variable_key": "fiber-optic-main-v1-ps",
    "target": 77.9855506212621,
    "alarm_low": null,
    "warning_low": null,
    "warning_high": null,
    "alarm_high": null
  },
  {
    "load_case_id": "LC35_ B_FM_FMZ_MZSS_TWA115_TWS26_RMMax_20240411",
    "variable_key": "fiber-optic-main-d1-sb",
    "target": 1.011558483274105,
    "alarm_low": null,
    "warning_low": null,
    "warning_high": null,
    "alarm_high": null
  },
  {
    "load_case_id": "LC35_ B_FM_FMZ_MZSS_TWA115_TWS26_RMMax_20240411",
    "variable_key": "fiber-optic-main-d1-ps",
    "target": 32.468885909051515,
    "alarm_low": null,
    "warning_low": null,
    "warning_high": null,
    "alarm_high": null
  },
  {
    "load_case_id": "LC35_ B_FM_FMZ_MZSS_TWA115_TWS26_RMMax_20240411",
    "variable_key": "mizzen-runner-load",
    "target": 14.32986799773623,
    "alarm_low": null,
    "warning_low": null,
    "warning_high": null,
    "alarm_high": null
  },
  {
    "load_case_id": "LC35_ B_FM_FMZ_MZSS_TWA115_TWS26_RMMax_20240411",
    "variable_key": "mizzen-checkstay-load",
    "target": 1.6682557244318907,
    "alarm_low": null,
    "warning_low": null,
    "warning_high": null,
    "alarm_high": null
  },
  {
    "load_case_id": "LC35_ B_FM_FMZ_MZSS_TWA115_TWS26_RMMax_20240411",
    "variable_key": "mizzen-vang-load",
    "target": 6.989848725099805,
    "alarm_low": null,
    "warning_low": null,
    "warning_high": null,
    "alarm_high": null
  },
  {
    "load_case_id": "LC35_ B_FM_FMZ_MZSS_TWA115_TWS26_RMMax_20240411",
    "variable_key": "mizzen-checkstay-deflector-load",
    "target": 0.25492905324448206,
    "alarm_low": null,
    "warning_low": null,
    "warning_high": null,
    "alarm_high": null
  },
  {
    "load_case_id": "LC35_ B_FM_FMZ_MZSS_TWA115_TWS26_RMMax_20240411",
    "variable_key": "mizzen-preventer-load",
    "target": 4.715881570159025,
    "alarm_low": null,
    "warning_low": null,
    "warning_high": null,
    "alarm_high": null
  },
  {
    "load_case_id": "LC35_ B_FM_FMZ_MZSS_TWA115_TWS26_RMMax_20240411",
    "variable_key": "mizzen-sheet-load",
    "target": 3.233927997838202,
    "alarm_low": null,
    "warning_low": null,
    "warning_high": null,
    "alarm_high": null
  },
  {
    "load_case_id": "LC35_ B_FM_FMZ_MZSS_TWA115_TWS26_RMMax_20240411",
    "variable_key": "main-checkstay-load",
    "target": 2.937496494725518,
    "alarm_low": null,
    "warning_low": null,
    "warning_high": null,
    "alarm_high": null
  },
  {
    "load_case_id": "LC35_ B_FM_FMZ_MZSS_TWA115_TWS26_RMMax_20240411",
    "variable_key": "main-runner-load",
    "target": 27.69600220258702,
    "alarm_low": null,
    "warning_low": null,
    "warning_high": null,
    "alarm_high": null
  },
  {
    "load_case_id": "LC35_ B_FM_FMZ_MZSS_TWA115_TWS26_RMMax_20240411",
    "variable_key": "main-checkstay-deflector-load",
    "target": 0.0,
    "alarm_low": null,
    "warning_low": null,
    "warning_high": null,
    "alarm_high": null
  },
  {
    "load_case_id": "LC35_ B_FM_FMZ_MZSS_TWA115_TWS26_RMMax_20240411",
    "variable_key": "main-vang-load",
    "target": 3.6618009208037403,
    "alarm_low": null,
    "warning_low": null,
    "warning_high": null,
    "alarm_high": null
  },
  {
    "load_case_id": "LC35_ B_FM_FMZ_MZSS_TWA115_TWS26_RMMax_20240411",
    "variable_key": "main-preventer-load",
    "target": 9.653347473398153,
    "alarm_low": null,
    "warning_low": null,
    "warning_high": null,
    "alarm_high": null
  },
  {
    "load_case_id": "LC35_ B_FM_FMZ_MZSS_TWA115_TWS26_RMMax_20240411",
    "variable_key": "blade-tweaker-load",
    "target": 0.04415371202194429,
    "alarm_low": null,
    "warning_low": null,
    "warning_high": null,
    "alarm_high": null
  },
  {
    "load_case_id": "LC35_ B_FM_FMZ_MZSS_TWA115_TWS26_RMMax_20240411",
    "variable_key": "main-sheet-load",
    "target": 4.444535085885598,
    "alarm_low": null,
    "warning_low": null,
    "warning_high": null,
    "alarm_high": null
  },
  {
    "load_case_id": "LC35_ B_FM_FMZ_MZSS_TWA115_TWS26_RMMax_20240411",
    "variable_key": "main-halyard-load",
    "target": 17.05893449852906,
    "alarm_low": null,
    "warning_low": null,
    "warning_high": null,
    "alarm_high": null
  },
  {
    "load_case_id": "LC35_ B_FM_FMZ_MZSS_TWA115_TWS26_RMMax_20240411",
    "variable_key": "main-outhaul-load",
    "target": 7.376525113061035,
    "alarm_low": null,
    "warning_low": null,
    "warning_high": null,
    "alarm_high": null
  },
  {
    "load_case_id": "LC35_ B_FM_FMZ_MZSS_TWA115_TWS26_RMMax_20240411",
    "variable_key": "main-cunningham-load",
    "target": 1.7845033727113744,
    "alarm_low": null,
    "warning_low": null,
    "warning_high": null,
    "alarm_high": null
  },
  {
    "load_case_id": "LC35_ B_FM_FMZ_MZSS_TWA115_TWS26_RMMax_20240411",
    "variable_key": "mizzen-halyard-load",
    "target": 6.804770232444311,
    "alarm_low": null,
    "warning_low": null,
    "warning_high": null,
    "alarm_high": null
  },
  {
    "load_case_id": "LC35_ B_FM_FMZ_MZSS_TWA115_TWS26_RMMax_20240411",
    "variable_key": "mizzen-outhaul-load",
    "target": 4.154017936808186,
    "alarm_low": null,
    "warning_low": null,
    "warning_high": null,
    "alarm_high": null
  },
  {
    "load_case_id": "LC35_ B_FM_FMZ_MZSS_TWA115_TWS26_RMMax_20240411",
    "variable_key": "mizzen-cunningham-load",
    "target": 1.0197162129779282,
    "alarm_low": null,
    "warning_low": null,
    "warning_high": null,
    "alarm_high": null
  },
  {
    "load_case_id": "LC35_ B_FM_FMZ_MZSS_TWA115_TWS26_RMMax_20240411",
    "variable_key": "blade-sheet-feeder-load",
    "target": 0.10197162129779283,
    "alarm_low": null,
    "warning_low": null,
    "warning_high": null,
    "alarm_high": null
  },
  {
    "load_case_id": "LC35_ B_FM_FMZ_MZSS_TWA115_TWS26_RMMax_20240411",
    "variable_key": "primary-winch-load",
    "target": 10.59321990689991,
    "alarm_low": null,
    "warning_low": null,
    "warning_high": null,
    "alarm_high": null
  },
  {
    "load_case_id": "LC35_ B_FM_FMZ_MZSS_TWA115_TWS26_RMMax_20240411",
    "variable_key": "headsail-locks-lock-Jib",
    "target": 238965.0,
    "alarm_low": null,
    "warning_low": null,
    "warning_high": null,
    "alarm_high": null
  },
  {
    "load_case_id": "LC35_ B_FM_FMZ_MZSS_TWA115_TWS26_RMMax_20240411",
    "variable_key": "blade-cunningham-load",
    "target": 18.938067535804787,
    "alarm_low": null,
    "warning_low": null,
    "warning_high": null,
    "alarm_high": null
  },
  {
    "load_case_id": "LC35_ B_FM_FMZ_MZSS_TWA115_TWS26_RMMax_20240411",
    "variable_key": "main-headstay-combined-load",
    "target": 18.938067535804787,
    "alarm_low": null,
    "warning_low": null,
    "warning_high": null,
    "alarm_high": null
  },
  {
    "load_case_id": "LC35_ B_FM_FMZ_MZSS_TWA115_TWS26_RMMax_20240411",
    "variable_key": "mizzen-headsail-locks-lock",
    "target": 236018.0,
    "alarm_low": null,
    "warning_low": null,
    "warning_high": null,
    "alarm_high": null
  },
  {
    "load_case_id": "LC35_ B_FM_FMZ_MZSS_TWA115_TWS26_RMMax_20240411",
    "variable_key": "mizzen-headsail-tack-adjuster-load",
    "target": 21.15146354769468,
    "alarm_low": null,
    "warning_low": null,
    "warning_high": null,
    "alarm_high": null
  },
  {
    "load_case_id": "LC35_ B_FM_FMZ_MZSS_TWA115_TWS26_RMMax_20240411",
    "variable_key": "blade-adjuster-load",
    "target": 23.089638153701827,
    "alarm_low": null,
    "warning_low": null,
    "warning_high": null,
    "alarm_high": null
  },
  {
    "load_case_id": "FM B Rchng",
    "variable_key": "fiber-optic-main-v1-sb",
    "target": 0.0,
    "alarm_low": null,
    "warning_low": null,
    "warning_high": null,
    "alarm_high": null
  },
  {
    "load_case_id": "FM B Rchng",
    "variable_key": "fiber-optic-main-v1-ps",
    "target": 72.93550804811021,
    "alarm_low": null,
    "warning_low": null,
    "warning_high": null,
    "alarm_high": null
  },
  {
    "load_case_id": "FM B Rchng",
    "variable_key": "fiber-optic-main-d1-sb",
    "target": 0.0,
    "alarm_low": null,
    "warning_low": null,
    "warning_high": null,
    "alarm_high": null
  },
  {
    "load_case_id": "FM B Rchng",
    "variable_key": "fiber-optic-main-d1-ps",
    "target": 33.1298659583038,
    "alarm_low": null,
    "warning_low": null,
    "warning_high": null,
    "alarm_high": null
  },
  {
    "load_case_id": "FM B Rchng",
    "variable_key": "fiber-optic-mizzen-v1-sb",
    "target": 18.574538705878155,
    "alarm_low": null,
    "warning_low": null,
    "warning_high": null,
    "alarm_high": null
  },
  {
    "load_case_id": "FM B Rchng",
    "variable_key": "fiber-optic-mizzen-v1-ps",
    "target": 21.763293275481434,
    "alarm_low": null,
    "warning_low": null,
    "warning_high": null,
    "alarm_high": null
  },
  {
    "load_case_id": "FM B Rchng",
    "variable_key": "fiber-optic-mizzen-d1-sb",
    "target": 7.623806294708183,
    "alarm_low": null,
    "warning_low": null,
    "warning_high": null,
    "alarm_high": null
  },
  {
    "load_case_id": "FM B Rchng",
    "variable_key": "fiber-optic-mizzen-d1-ps",
    "target": 11.344852727485941,
    "alarm_low": null,
    "warning_low": null,
    "warning_high": null,
    "alarm_high": null
  },
  {
    "load_case_id": "FM B Rchng",
    "variable_key": "fiber-optic-mizzen-forestay",
    "target": 19.199930659297518,
    "alarm_low": null,
    "warning_low": null,
    "warning_high": null,
    "alarm_high": null
  },
  {
    "load_case_id": "FM B Rchng",
    "variable_key": "main-runner-load",
    "target": 26.94906007658069,
    "alarm_low": null,
    "warning_low": null,
    "warning_high": null,
    "alarm_high": null
  },
  {
    "load_case_id": "FM B Rchng",
    "variable_key": "main-checkstay-load",
    "target": 3.6208083290420277,
    "alarm_low": null,
    "warning_low": null,
    "warning_high": null,
    "alarm_high": null
  },
  {
    "load_case_id": "FM B Rchng",
    "variable_key": "main-checkstay-deflector-load",
    "target": 0.2803199869476325,
    "alarm_low": null,
    "warning_low": null,
    "warning_high": null,
    "alarm_high": null
  },
  {
    "load_case_id": "FM B Rchng",
    "variable_key": "mizzen-runner-load",
    "target": 5.244196540102889,
    "alarm_low": null,
    "warning_low": null,
    "warning_high": null,
    "alarm_high": null
  },
  {
    "load_case_id": "FM B Rchng",
    "variable_key": "mizzen-checkstay-load",
    "target": 1.9973181463598682,
    "alarm_low": null,
    "warning_low": null,
    "warning_high": null,
    "alarm_high": null
  },
  {
    "load_case_id": "FM B Rchng",
    "variable_key": "mizzen-checkstay-deflector-load",
    "target": 0.33742409487439645,
    "alarm_low": null,
    "warning_low": null,
    "warning_high": null,
    "alarm_high": null
  },
  {
    "load_case_id": "FM B Rchng",
    "variable_key": "main-sheet-load",
    "target": 9.713714673206447,
    "alarm_low": null,
    "warning_low": null,
    "warning_high": null,
    "alarm_high": null
  },
  {
    "load_case_id": "FM B Rchng",
    "variable_key": "main-vang-load",
    "target": 0.010197162129779282,
    "alarm_low": null,
    "warning_low": null,
    "warning_high": null,
    "alarm_high": null
  },
  {
    "load_case_id": "FM B Rchng",
    "variable_key": "main-outhaul-load",
    "target": 14.167019318523655,
    "alarm_low": null,
    "warning_low": null,
    "warning_high": null,
    "alarm_high": null
  },
  {
    "load_case_id": "FM B Rchng",
    "variable_key": "mizzen-sheet-load",
    "target": 0.5850111913854374,
    "alarm_low": null,
    "warning_low": null,
    "warning_high": null,
    "alarm_high": null
  },
  {
    "load_case_id": "FM B Rchng",
    "variable_key": "mizzen-vang-load",
    "target": 0.00020394324259558565,
    "alarm_low": null,
    "warning_low": null,
    "warning_high": null,
    "alarm_high": null
  },
  {
    "load_case_id": "FM B Rchng",
    "variable_key": "blade-tweaker-load",
    "target": 0.006730127005654327,
    "alarm_low": null,
    "warning_low": null,
    "warning_high": null,
    "alarm_high": null
  },
  {
    "load_case_id": "FM B Rchng",
    "variable_key": "main-halyard-load",
    "target": 24.325024345724586,
    "alarm_low": null,
    "warning_low": null,
    "warning_high": null,
    "alarm_high": null
  },
  {
    "load_case_id": "FM B Rchng",
    "variable_key": "main-cunningham-load",
    "target": 5.0985810648896415,
    "alarm_low": null,
    "warning_low": null,
    "warning_high": null,
    "alarm_high": null
  },
  {
    "load_case_id": "FM B Rchng",
    "variable_key": "blade-sheet-feeder-load",
    "target": 0.010197162129779282,
    "alarm_low": null,
    "warning_low": null,
    "warning_high": null,
    "alarm_high": null
  },
  {
    "load_case_id": "FM B Rchng",
    "variable_key": "primary-winch-load",
    "target": 11.316096730279963,
    "alarm_low": null,
    "warning_low": null,
    "warning_high": null,
    "alarm_high": null
  },
  {
    "load_case_id": "FM B Rchng",
    "variable_key": "headsail-locks-lock-Jib",
    "target": 250679.0,
    "alarm_low": null,
    "warning_low": null,
    "warning_high": null,
    "alarm_high": null
  },
  {
    "load_case_id": "FM B Rchng",
    "variable_key": "blade-cunningham-load",
    "target": 20.30550697740819,
    "alarm_low": null,
    "warning_low": null,
    "warning_high": null,
    "alarm_high": null
  },
  {
    "load_case_id": "FM B Rchng",
    "variable_key": "main-headstay-combined-load",
    "target": 20.30550697740819,
    "alarm_low": null,
    "warning_low": null,
    "warning_high": null,
    "alarm_high": null
  },
  {
    "load_case_id": "FM B Rchng",
    "variable_key": "blade-adjuster-load",
    "target": 23.19538272498764,
    "alarm_low": null,
    "warning_low": null,
    "warning_high": null,
    "alarm_high": null
  },
  {
    "load_case_id": "LC20_ MH0_FM_FMZ_ TWA110_TWS12_RM15_NoRunner_20240630",
    "variable_key": "fiber-optic-mizzen-v1-sb",
    "target": 18.931235437177833,
    "alarm_low": null,
    "warning_low": null,
    "warning_high": null,
    "alarm_high": null
  },
  {
    "load_case_id": "LC20_ MH0_FM_FMZ_ TWA110_TWS12_RM15_NoRunner_20240630",
    "variable_key": "fiber-optic-mizzen-v1-ps",
    "target": 29.837712164704563,
    "alarm_low": null,
    "warning_low": null,
    "warning_high": null,
    "alarm_high": null
  },
  {
    "load_case_id": "LC20_ MH0_FM_FMZ_ TWA110_TWS12_RM15_NoRunner_20240630",
    "variable_key": "fiber-optic-mizzen-d1-sb",
    "target": 6.9471226157760295,
    "alarm_low": null,
    "warning_low": null,
    "warning_high": null,
    "alarm_high": null
  },
  {
    "load_case_id": "LC20_ MH0_FM_FMZ_ TWA110_TWS12_RM15_NoRunner_20240630",
    "variable_key": "fiber-optic-mizzen-d1-ps",
    "target": 11.185471083397491,
    "alarm_low": null,
    "warning_low": null,
    "warning_high": null,
    "alarm_high": null
  },
  {
    "load_case_id": "LC20_ MH0_FM_FMZ_ TWA110_TWS12_RM15_NoRunner_20240630",
    "variable_key": "fiber-optic-mizzen-forestay",
    "target": 21.442694498121174,
    "alarm_low": null,
    "warning_low": null,
    "warning_high": null,
    "alarm_high": null
  },
  {
    "load_case_id": "LC20_ MH0_FM_FMZ_ TWA110_TWS12_RM15_NoRunner_20240630",
    "variable_key": "fiber-optic-main-v1-sb",
    "target": 35.601963973426194,
    "alarm_low": null,
    "warning_low": null,
    "warning_high": null,
    "alarm_high": null
  },
  {
    "load_case_id": "LC20_ MH0_FM_FMZ_ TWA110_TWS12_RM15_NoRunner_20240630",
    "variable_key": "fiber-optic-main-v1-ps",
    "target": 104.52182957482933,
    "alarm_low": null,
    "warning_low": null,
    "warning_high": null,
    "alarm_high": null
  },
  {
    "load_case_id": "LC20_ MH0_FM_FMZ_ TWA110_TWS12_RM15_NoRunner_20240630",
    "variable_key": "fiber-optic-main-d1-sb",
    "target": 14.544926147053276,
    "alarm_low": null,
    "warning_low": null,
    "warning_high": null,
    "alarm_high": null
  },
  {
    "load_case_id": "LC20_ MH0_FM_FMZ_ TWA110_TWS12_RM15_NoRunner_20240630",
    "variable_key": "fiber-optic-main-d1-ps",
    "target": 37.18884634406245,
    "alarm_low": null,
    "warning_low": null,
    "warning_high": null,
    "alarm_high": null
  },
  {
    "load_case_id": "LC20_ MH0_FM_FMZ_ TWA110_TWS12_RM15_NoRunner_20240630",
    "variable_key": "blade-adjuster-load",
    "target": 0.0,
    "alarm_low": null,
    "warning_low": null,
    "warning_high": null,
    "alarm_high": null
  },
  {
    "load_case_id": "LC20_ MH0_FM_FMZ_ TWA110_TWS12_RM15_NoRunner_20240630",
    "variable_key": "main-headstay-combined-load",
    "target": 0.0,
    "alarm_low": null,
    "warning_low": null,
    "warning_high": null,
    "alarm_high": null
  },
  {
    "load_case_id": "LC20_ MH0_FM_FMZ_ TWA110_TWS12_RM15_NoRunner_20240630",
    "variable_key": "mizzen-runner-load",
    "target": 4.538654892343461,
    "alarm_low": null,
    "warning_low": null,
    "warning_high": null,
    "alarm_high": null
  },
  {
    "load_case_id": "LC20_ MH0_FM_FMZ_ TWA110_TWS12_RM15_NoRunner_20240630",
    "variable_key": "mizzen-checkstay-load",
    "target": 3.4489861471552468,
    "alarm_low": null,
    "warning_low": null,
    "warning_high": null,
    "alarm_high": null
  },
  {
    "load_case_id": "LC20_ MH0_FM_FMZ_ TWA110_TWS12_RM15_NoRunner_20240630",
    "variable_key": "mizzen-vang-load",
    "target": 12.700667404261395,
    "alarm_low": null,
    "warning_low": null,
    "warning_high": null,
    "alarm_high": null
  },
  {
    "load_case_id": "LC20_ MH0_FM_FMZ_ TWA110_TWS12_RM15_NoRunner_20240630",
    "variable_key": "mizzen-checkstay-deflector-load",
    "target": 0.5201572402400412,
    "alarm_low": null,
    "warning_low": null,
    "warning_high": null,
    "alarm_high": null
  },
  {
    "load_case_id": "LC20_ MH0_FM_FMZ_ TWA110_TWS12_RM15_NoRunner_20240630",
    "variable_key": "mizzen-preventer-load",
    "target": 1.6279769340192625,
    "alarm_low": null,
    "warning_low": null,
    "warning_high": null,
    "alarm_high": null
  },
  {
    "load_case_id": "LC20_ MH0_FM_FMZ_ TWA110_TWS12_RM15_NoRunner_20240630",
    "variable_key": "mizzen-sheet-load",
    "target": 0.17294386972105663,
    "alarm_low": null,
    "warning_low": null,
    "warning_high": null,
    "alarm_high": null
  },
  {
    "load_case_id": "LC20_ MH0_FM_FMZ_ TWA110_TWS12_RM15_NoRunner_20240630",
    "variable_key": "main-checkstay-load",
    "target": 0.0,
    "alarm_low": null,
    "warning_low": null,
    "warning_high": null,
    "alarm_high": null
  },
  {
    "load_case_id": "LC20_ MH0_FM_FMZ_ TWA110_TWS12_RM15_NoRunner_20240630",
    "variable_key": "main-runner-load",
    "target": 0.0,
    "alarm_low": null,
    "warning_low": null,
    "warning_high": null,
    "alarm_high": null
  },
  {
    "load_case_id": "LC20_ MH0_FM_FMZ_ TWA110_TWS12_RM15_NoRunner_20240630",
    "variable_key": "main-checkstay-deflector-load",
    "target": 0.0,
    "alarm_low": null,
    "warning_low": null,
    "warning_high": null,
    "alarm_high": null
  },
  {
    "load_case_id": "LC20_ MH0_FM_FMZ_ TWA110_TWS12_RM15_NoRunner_20240630",
    "variable_key": "main-vang-load",
    "target": 56.084391713786054,
    "alarm_low": null,
    "warning_low": null,
    "warning_high": null,
    "alarm_high": null
  },
  {
    "load_case_id": "LC20_ MH0_FM_FMZ_ TWA110_TWS12_RM15_NoRunner_20240630",
    "variable_key": "main-preventer-load",
    "target": 0.010197162129779282,
    "alarm_low": null,
    "warning_low": null,
    "warning_high": null,
    "alarm_high": null
  },
  {
    "load_case_id": "LC20_ MH0_FM_FMZ_ TWA110_TWS12_RM15_NoRunner_20240630",
    "variable_key": "main-sheet-load",
    "target": 1.010028908954638,
    "alarm_low": null,
    "warning_low": null,
    "warning_high": null,
    "alarm_high": null
  },
  {
    "load_case_id": "LC20_ MH0_FM_FMZ_ TWA110_TWS12_RM15_NoRunner_20240630",
    "variable_key": "main-halyard-load",
    "target": 11.16426098616755,
    "alarm_low": null,
    "warning_low": null,
    "warning_high": null,
    "alarm_high": null
  },
  {
    "load_case_id": "LC20_ MH0_FM_FMZ_ TWA110_TWS12_RM15_NoRunner_20240630",
    "variable_key": "main-outhaul-load",
    "target": 4.791340569919392,
    "alarm_low": null,
    "warning_low": null,
    "warning_high": null,
    "alarm_high": null
  },
  {
    "load_case_id": "LC20_ MH0_FM_FMZ_ TWA110_TWS12_RM15_NoRunner_20240630",
    "variable_key": "main-cunningham-load",
    "target": 2.0394324259558565,
    "alarm_low": null,
    "warning_low": null,
    "warning_high": null,
    "alarm_high": null
  },
  {
    "load_case_id": "LC20_ MH0_FM_FMZ_ TWA110_TWS12_RM15_NoRunner_20240630",
    "variable_key": "mizzen-halyard-load",
    "target": 5.873463415131569,
    "alarm_low": null,
    "warning_low": null,
    "warning_high": null,
    "alarm_high": null
  },
  {
    "load_case_id": "LC20_ MH0_FM_FMZ_ TWA110_TWS12_RM15_NoRunner_20240630",
    "variable_key": "mizzen-outhaul-load",
    "target": 5.187602290282615,
    "alarm_low": null,
    "warning_low": null,
    "warning_high": null,
    "alarm_high": null
  },
  {
    "load_case_id": "LC20_ MH0_FM_FMZ_ TWA110_TWS12_RM15_NoRunner_20240630",
    "variable_key": "mizzen-cunningham-load",
    "target": 1.5295743194668925,
    "alarm_low": null,
    "warning_low": null,
    "warning_high": null,
    "alarm_high": null
  },
  {
    "load_case_id": "LC20_ MH0_FM_FMZ_ TWA110_TWS12_RM15_NoRunner_20240630",
    "variable_key": "primary-winch-load",
    "target": 6.520371380644767,
    "alarm_low": null,
    "warning_low": null,
    "warning_high": null,
    "alarm_high": null
  },
  {
    "load_case_id": "LC20_ MH0_FM_FMZ_ TWA110_TWS12_RM15_NoRunner_20240630",
    "variable_key": "code-zero-tack-load",
    "target": 12.67874350568237,
    "alarm_low": null,
    "warning_low": null,
    "warning_high": null,
    "alarm_high": null
  }
]$$::jsonb) AS t(
        load_case_id TEXT,
        variable_key TEXT,
        target NUMERIC,
        alarm_low NUMERIC,
        warning_low NUMERIC,
        warning_high NUMERIC,
        alarm_high NUMERIC
    )
)
INSERT INTO loads.reference_values (
    load_case_id,
    variable_key,
    alarm_low,
    warning_low,
    target,
    warning_high,
    alarm_high
)
SELECT
    payload.load_case_id,
    payload.variable_key,
    payload.alarm_low,
    payload.warning_low,
    payload.target,
    payload.warning_high,
    payload.alarm_high
FROM reference_payload AS payload
JOIN upsert_load_cases AS load_case
    ON load_case.id = payload.load_case_id
ON CONFLICT (load_case_id, variable_key) DO UPDATE
SET
    alarm_low = EXCLUDED.alarm_low,
    warning_low = EXCLUDED.warning_low,
    target = EXCLUDED.target,
    warning_high = EXCLUDED.warning_high,
    alarm_high = EXCLUDED.alarm_high;

COMMIT;
