apiVersion: v1
kind: Service
metadata:
  namespace: {{ .Release.Namespace }}
  name: {{ include "zero-prop-test.name" . }}
  labels:
    {{- include "..labels" . | nindent 4 }}
    {{- with .Values.service.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  annotations:
    {{- with .Values.service.annotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  type: LoadBalancer
  externalIPs:
    - {{ .Values.twincat.externalIp }}
  ports:
    - port: 48898
      targetPort: 48898
      protocol: TCP
      name: ads
    - port: 30000
      targetPort: 30000
      protocol: TCP
      name: ads
  selector:
    {{- include "zero-prop-test.selectorLabels" . | nindent 4 }}
