from pathlib import Path

from pydantic import TypeAdapter

from zero_data.io_list.atpx_meta import read_senders, slugify
from zero_data.io_list.types import IOResult

_SENDERS_PATH = Path("io_lists/atpx/atpx_senders.json")
# Our additions (senders A+T's UI defines but omits), merged over the base file.
_EXTRA_PATH = Path("io_lists/atpx/atpx_extra.json")


class AtpxVectorGenerator:
    def __init__(self, vector_path: Path):
        self._vector_path = vector_path / "processing/atpx_0_consts.vrl"

    def generate(self, io_result: IOResult):
        """Write the VRL constants (atpx_0_consts.vrl) mapping field and sender
        ids to slugified names, consumed by processing/atpx_1_parse.vrl."""
        senders = {
            **read_senders(_SENDERS_PATH),
            **read_senders(_EXTRA_PATH),
        }
        fields_mapping = {
            str(row["id"]): row["key"]
            for row in io_result.io_list.sort("id").iter_rows(named=True)
        }
        senders_mapping = {
            str(sender_id): slugify(name) for sender_id, name in sorted(senders.items())
        }

        fields_adapter = TypeAdapter(dict[str, str])
        senders_adapter = TypeAdapter(dict[str, str])

        fields_json = str(fields_adapter.dump_json(fields_mapping, indent=2), "utf-8")
        senders_json = str(
            senders_adapter.dump_json(senders_mapping, indent=2), "utf-8"
        )
        self._vector_path.write_text(
            "# This file is auto-generated by zero-data\n"
            f"atpx_fields = {fields_json}\n\n"
            f"atpx_senders = {senders_json}\n"
        )
