from pathlib import Path

from zero_data.io_list.types import IOTopic
from zero_data.utils import detect_same_format


class MarpowerVectorGenerator:
    def __init__(self, vector_path: Path):
        self._vector_path = vector_path / "marpower/0_consts.vrl"

    def generate(self, topics: list[IOTopic]):
        """Generate the VRL file for the given topics."""
        _, squashed, _ = detect_same_format(topics)
        with open(self._vector_path, "w") as f:
            f.writelines(
                (
                    "# This file is auto-generated by zero-data\n",
                    "grouped_topics = [\n",
                    ",\n".join(
                        f'  "{topic.topic.removesuffix("#")}"' for topic in squashed
                    ),
                    "\n]\n",
                )
            )
