import logging
from pathlib import Path

from pydantic import BaseModel, TypeAdapter

from zero_data.io_list.managed_topics import extract_managed_topics
from zero_data.io_list.types import IOResult
from zero_data.io_list.utils import detect_same_format

EXTRA_GROUPED_TOPICS = [
    # "marpower/450000-main-power-storage/system-05/",
    # "marpower/450000-main-power-storage/system-5/",
    # "marpower/500000-thrs/vlv/",
    "marpower/450000-dc-distribution/350v-conv/",
    "marpower/450000-dc-distribution/conv/",
    "marpower/450000-dc-distribution/dc-switch/",
    "marpower/450000-dc-distribution/esi/",
    "marpower/450000-dc-distribution/pwr/",
    "marpower/450000-24vdc-system/",
    "marpower/450000-dynamic-conv-ps/",
    "marpower/450000-dynamic-conv-sb/",
    "termodinamica/ac/",
    "power-tags/",
]


logger = logging.getLogger(__name__)


class ManagedTopicMapping(BaseModel):
    table: str
    yard_tag: str | None
    technical_name: str


class MarpowerVectorGenerator:
    def __init__(self, vector_path: Path):
        self._vector_path = vector_path / "processing/process_0_consts.vrl"

    def generate(self, io_result: IOResult):
        """Generate the VRL file for the given topics."""
        topics = io_result.topics
        managed_topics, invalid_managed_topics, other_topics = extract_managed_topics(
            topics
        )
        for topic in invalid_managed_topics:
            logger.warning(f"Invalid managed topic: {topic.topic}")

        mapping = {
            managed_topic.topic.topic: ManagedTopicMapping(
                table=f"marpower__{managed_topic.system_name}__{managed_topic.component}",
                yard_tag=(
                    managed_topic.topic.yard_tag.strip()
                    if managed_topic.topic.yard_tag is not None
                    else None
                ),
                technical_name=managed_topic.technical_name,
            )
            for managed_topic in sorted(managed_topics, key=lambda t: t.topic.topic)
        }
        mapping_adapter = TypeAdapter(dict[str, ManagedTopicMapping])

        _, squashed, _ = detect_same_format(other_topics + invalid_managed_topics)
        grouped_topics = set(
            [topic.topic.removesuffix("#").replace("//", "/") for topic in squashed]
        )
        without_extra_topics = [
            topic
            for topic in grouped_topics
            if not any(
                extra for extra in EXTRA_GROUPED_TOPICS if extra.startswith(topic)
            )
        ]
        all_grouped_topic = sorted(without_extra_topics + EXTRA_GROUPED_TOPICS)
        with open(self._vector_path, "w") as f:
            f.writelines(
                (
                    "# This file is auto-generated by zero-data\n",
                    "grouped_topics = [\n",
                    ",\n".join(f'  "{topic}"' for topic in all_grouped_topic),
                    "\n]\n\n",
                )
                + (
                    f"managed_tables = {str(mapping_adapter.dump_json(mapping, indent=2), 'utf-8')}\n",
                )
            )
