{{ config(materialized='table_with_connector') }}
CREATE TABLE {{ this }} (
	TIMESTAMP	TIMESTAMP,
	SEA_WATER_COOL_PMP1_REMOTE	BOOLEAN,
	SEA_WATER_COOL_PMP1_RUNNING	BOOLEAN,
	SEA_WATER_COOL_PMP1_START_STOP	BOOLEAN,
	SEA_WATER_COOL_PMP2_REMOTE	BOOLEAN,
	SEA_WATER_COOL_PMP2_RUNNING	BOOLEAN,
	SEA_WATER_COOL_PMP2_START_STOP	BOOLEAN,
)
{{ mqtt_with('marpower/380000_seawater') }}
