{{ config(materialized='table_with_connector') }}
CREATE TABLE {{ this }} (
	TIMESTAMP	TIMESTAMP,
	BURGLAR_ALARM_206U01	BOOLEAN,
	BURGLAR_ALARM_206U02	BOOLEAN,
	BURGLAR_ALARM_206U03	BOOLEAN,
	BURGLAR_ALARM_206U04	BOOLEAN,
	BURGLAR_ALARM_206U05	BOOLEAN,
	BURGLAR_ALARM_206U06	BOOLEAN,
	BURGLAR_ALRM_SYSTEM_ON_OFF	BOOLEAN,
)
{{ mqtt_with('marpower/450000_burglar') }}
