{{ config(materialized='table_with_connector') }}
CREATE TABLE {{ this }} (
	TIMESTAMP	TIMESTAMP,
	DECK_CRANE_GEN_ALARM	BOOLEAN,
	GUEST_TENDER_HATCH_CL_LOCK	BOOLEAN,
	MOB_TENDER_HATCH_CL_LOCK	BOOLEAN,
	PASS_HATCH_CL_LOCK	BOOLEAN,
	SBL_COMMON_ALARM	BOOLEAN,
	SBL_SB_CLOSED_LOCKED	BOOLEAN,
)
{{ mqtt_with('marpower/750000_deck_equip') }}
