<script setup lang="ts">
import { MimicComponentType } from "@/modules/thrapp/types";
import { ComponentOrientation } from "../../../components";
import { MANUAL_VALVE_WIDTH, ManualValveType } from "../../../components/manual-valve";
import { ManualValveInstance } from "../../../instances";
import TagLabelInstance from "../../../instances/TagLabelInstance.vue";
import { DHW_MIMIC_DATA } from "../data";

const manualValves = DHW_MIMIC_DATA[MimicComponentType.ManualValve];
</script>

<template>
  <g>
    <ManualValveInstance
      x="178.550048828125"
      y="279.2099609375"
      v-bind="manualValves['1174-02']"
      :type="ManualValveType.Switch"
      :orientation="ComponentOrientation.Right"
    >
      <TagLabelInstance
        x="211"
        y="283"
        :tag-id="manualValves['1174-02'].tooltip?.yardTag"
      />
    </ManualValveInstance>
    <ManualValveInstance
      x="58"
      y="495"
      v-bind="manualValves['1069-17']"
      :type="ManualValveType.Switch"
      :orientation="ComponentOrientation.Left"
    >
      <TagLabelInstance
        x="91"
        y="498"
        :tag-id="manualValves['1069-17'].tooltip?.yardTag"
      />
    </ManualValveInstance>
    <ManualValveInstance
      x="360.5"
      y="358.2099609375"
      v-bind="manualValves['1169-01']"
      :type="ManualValveType.Switch"
      :orientation="ComponentOrientation.Right"
    >
      <TagLabelInstance
        x="389"
        y="363"
        :tag-id="manualValves['1169-01'].tooltip?.yardTag"
      />
    </ManualValveInstance>
    <ManualValveInstance
      x="805"
      y="636.5"
      v-bind="manualValves['1169-02']"
      :type="ManualValveType.Switch"
      :orientation="ComponentOrientation.Up"
    >
      <TagLabelInstance
        :target-x="805"
        :target-width="MANUAL_VALVE_WIDTH"
        y="625"
        :tag-id="manualValves['1169-02'].tooltip?.yardTag"
      />
    </ManualValveInstance>
    <ManualValveInstance
      x="323"
      y="358.2099609375"
      v-bind="manualValves['1169-03']"
      :type="ManualValveType.Switch"
      :orientation="ComponentOrientation.Right"
    >
      <TagLabelInstance
        x="295"
        y="363"
        :tag-id="manualValves['1169-03'].tooltip?.yardTag"
      />
    </ManualValveInstance>
    <ManualValveInstance
      x="180"
      y="378.2099609375"
      v-bind="manualValves['1174-01']"
      :type="ManualValveType.Switch"
      :orientation="ComponentOrientation.Right"
    >
      <TagLabelInstance
        x="211"
        y="382"
        :tag-id="manualValves['1174-01'].tooltip?.yardTag"
      />
    </ManualValveInstance>
    <ManualValveInstance
      x="27.5"
      y="537.2099609375"
      v-bind="manualValves['1069-18']"
      :type="ManualValveType.Switch"
      :orientation="ComponentOrientation.Right"
    >
      <TagLabelInstance
        x="60"
        y="541"
        :tag-id="manualValves['1069-18'].tooltip?.yardTag"
      />
    </ManualValveInstance>
    <ManualValveInstance
      x="117.5"
      y="588"
      v-bind="manualValves['1069-10']"
      :type="ManualValveType.Switch"
      :orientation="ComponentOrientation.Right"
    >
      <TagLabelInstance
        x="79"
        y="590"
        :tag-id="manualValves['1069-10'].tooltip?.yardTag"
      />
    </ManualValveInstance>
    <ManualValveInstance
      x="734"
      y="350.7099609375"
      v-bind="manualValves['1168-06']"
      :type="ManualValveType.Switch"
      :orientation="ComponentOrientation.Up"
    >
      <TagLabelInstance
        :target-x="734"
        :target-width="MANUAL_VALVE_WIDTH"
        y="341"
        :tag-id="manualValves['1168-06'].tooltip?.yardTag"
      />
    </ManualValveInstance>
    <ManualValveInstance
      x="844"
      y="474.7099609375"
      v-bind="manualValves['1168-05']"
      :type="ManualValveType.Switch"
      :orientation="ComponentOrientation.Up"
    >
      <TagLabelInstance
        :target-x="844"
        :target-width="MANUAL_VALVE_WIDTH"
        y="464"
        :tag-id="manualValves['1168-05'].tooltip?.yardTag"
      />
    </ManualValveInstance>
    <ManualValveInstance
      x="614"
      y="473.2099609375"
      v-bind="manualValves['1168-04']"
      :type="ManualValveType.Switch"
      :orientation="ComponentOrientation.Up"
    >
      <TagLabelInstance
        :target-x="614"
        :target-width="MANUAL_VALVE_WIDTH"
        y="463"
        :tag-id="manualValves['1168-04'].tooltip?.yardTag"
      />
    </ManualValveInstance>
  </g>
</template>
