<script setup lang="ts">
import { ComponentOrientation } from "../../../components";
import { MANUAL_VALVE_WIDTH, ManualValveType } from "../../../components/manual-valve";
import { ManualValveInstance } from "../../../instances";
import TagLabelInstance from "../../../instances/TagLabelInstance.vue";
import { DC_MANUAL_VALVE_DATA } from "../data";

const manualValves = DC_MANUAL_VALVE_DATA.ManualValve;
</script>

<template>
  <ManualValveInstance
    x="292"
    y="260"
    :type="ManualValveType.Switch"
    :orientation="ComponentOrientation.Left"
    v-bind="manualValves['1168-27']"
  >
    <TagLabelInstance
      x="326"
      y="261.1458"
      :tag-id="manualValves['1168-27'].tooltip?.yardTag"
    />
  </ManualValveInstance>
  <ManualValveInstance
    x="276"
    y="420"
    :type="ManualValveType.Switch"
    :orientation="ComponentOrientation.Left"
    v-bind="manualValves['1168-28']"
  >
    <TagLabelInstance
      x="233"
      y="430.1458"
      :tag-id="manualValves['1168-28'].tooltip?.yardTag"
    />
  </ManualValveInstance>
  <ManualValveInstance
    x="292"
    y="505"
    :type="ManualValveType.Switch"
    :orientation="ComponentOrientation.Left"
    v-bind="manualValves['1168-29']"
  >
    <TagLabelInstance
      x="325"
      y="505"
      :tag-id="manualValves['1168-29'].tooltip?.yardTag"
    />
  </ManualValveInstance>

  <ManualValveInstance
    x="413"
    y="179.1458"
    :type="ManualValveType.Switch"
    :orientation="ComponentOrientation.Up"
    v-bind="manualValves['1168-15']"
  >
    <TagLabelInstance
      :target-x="413"
      :target-width="MANUAL_VALVE_WIDTH"
      y="210.1458"
      :tag-id="manualValves['1168-15'].tooltip?.yardTag"
    />
  </ManualValveInstance>
  <ManualValveInstance
    x="517"
    y="179.1458"
    :type="ManualValveType.Switch"
    :orientation="ComponentOrientation.Up"
    v-bind="manualValves['1168-16']"
  >
    <TagLabelInstance
      :target-x="517"
      :target-width="MANUAL_VALVE_WIDTH"
      y="210.1458"
      :tag-id="manualValves['1168-16'].tooltip?.yardTag"
    />
  </ManualValveInstance>
  <ManualValveInstance
    x="413"
    y="393.1458"
    :type="ManualValveType.Switch"
    :orientation="ComponentOrientation.Up"
    v-bind="manualValves['1169-17']"
  >
    <TagLabelInstance
      :target-x="413"
      :target-width="MANUAL_VALVE_WIDTH"
      y="423.1458"
      :tag-id="manualValves['1169-17'].tooltip?.yardTag"
    />
  </ManualValveInstance>
  <ManualValveInstance
    x="517"
    y="393.1458"
    :type="ManualValveType.Switch"
    :orientation="ComponentOrientation.Up"
    v-bind="manualValves['1069-18']"
  >
    <TagLabelInstance
      :target-x="517"
      :target-width="MANUAL_VALVE_WIDTH"
      y="423.1458"
      :tag-id="manualValves['1069-18'].tooltip?.yardTag"
    />
  </ManualValveInstance>
  <ManualValveInstance
    x="413"
    y="623.1458"
    :type="ManualValveType.Switch"
    :orientation="ComponentOrientation.Up"
    v-bind="manualValves['1067-08']"
  >
    <TagLabelInstance
      :target-x="413"
      :target-width="MANUAL_VALVE_WIDTH"
      y="655.1458"
      :tag-id="manualValves['1067-08'].tooltip?.yardTag"
    />
  </ManualValveInstance>
  <ManualValveInstance
    x="517"
    y="623.1458"
    :type="ManualValveType.Switch"
    :orientation="ComponentOrientation.Up"
    v-bind="manualValves['1067-07']"
  >
    <TagLabelInstance
      :target-x="517"
      :target-width="MANUAL_VALVE_WIDTH"
      y="655.1458"
      :tag-id="manualValves['1067-07'].tooltip?.yardTag"
    />
  </ManualValveInstance>

  <ManualValveInstance
    x="846.1406"
    y="483.9006"
    :type="ManualValveType.Switch"
    :orientation="ComponentOrientation.Up"
    v-bind="manualValves['1172-05']"
  >
    <TagLabelInstance
      :target-x="846.1406"
      :target-width="MANUAL_VALVE_WIDTH"
      y="512.9006"
      :tag-id="manualValves['1172-05'].tooltip?.yardTag"
    />
  </ManualValveInstance>
  <ManualValveInstance
    x="951.1406"
    y="483.9006"
    :type="ManualValveType.Switch"
    :orientation="ComponentOrientation.Up"
    v-bind="manualValves['1172-06']"
  >
    <TagLabelInstance
      :target-x="951.1406"
      :target-width="MANUAL_VALVE_WIDTH"
      y="515.9006"
      :tag-id="manualValves['1172-06'].tooltip?.yardTag"
    />
  </ManualValveInstance>
  <ManualValveInstance
    x="1202.1406"
    y="393.1458"
    :type="ManualValveType.Switch"
    :orientation="ComponentOrientation.Up"
    v-bind="manualValves['1170-04']"
  >
    <TagLabelInstance
      :target-x="1202.1406"
      :target-width="MANUAL_VALVE_WIDTH"
      y="424.1458"
      :tag-id="manualValves['1170-04'].tooltip?.yardTag"
    />
  </ManualValveInstance>
  <ManualValveInstance
    x="1202.1406"
    y="298.1458"
    :type="ManualValveType.Switch"
    :orientation="ComponentOrientation.Up"
    v-bind="manualValves['1170-03']"
  >
    <TagLabelInstance
      :target-x="1202.1406"
      :target-width="MANUAL_VALVE_WIDTH"
      y="283.1458"
      :tag-id="manualValves['1170-03'].tooltip?.yardTag"
    />
  </ManualValveInstance>

  <ManualValveInstance
    x="1172.1406"
    y="627.6458"
    :type="ManualValveType.Switch"
    :orientation="ComponentOrientation.Up"
    v-bind="manualValves['1167-13']"
  >
    <TagLabelInstance
      x="1208.1406"
      y="588.1458"
      :tag-id="manualValves['1167-13'].tooltip?.yardTag"
    />
  </ManualValveInstance>
  <ManualValveInstance
    x="1172.1406"
    y="585.1458"
    :type="ManualValveType.Switch"
    :orientation="ComponentOrientation.Up"
    v-bind="manualValves['1068-22']"
  >
    <TagLabelInstance
      x="1121.1406"
      y="630.1458"
      :tag-id="manualValves['1068-22'].tooltip?.yardTag"
    />
  </ManualValveInstance>
</template>
