apiVersion: v1
kind: Service
metadata:
  name: {{ include "..fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "..labels" . | nindent 4 }}
    {{- with .Values.api.service.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  annotations:
    {{- with .Values.api.service.annotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  type: ClusterIP
  ports:
    - port: 5101
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "..selectorLabels" . | nindent 4 }}
    app.kubernetes.io/part-of: loads-app
    app.kubernetes.io/component: api
