import asyncio
import json
import logging
from typing import Any, Literal

from faststream import FastStream
from faststream.mqtt import MQTTBroker
from faststream.specification import AsyncAPI
from pydantic import BaseModel
from pydantic_settings import (
    BaseSettings,
    CliApp,
    CliMutuallyExclusiveGroup,
    CliSubCommand,
    SettingsConfigDict,
)
from zero_modbus_bridge.io import ModbusTopic
from zero_modbus_bridge.reader import ModbusReader
from zero_modbus_bridge.settings import ModbusSettings, MqttSettings

from zero_hull_temperature.addresses import (
    HULL_TEMPERATURE_TOPIC,
    PATH,
    TOPIC,
    create_publisher,
)
from zero_hull_temperature.bridge_relay import RelaySwitchingBridge
from zero_hull_temperature.stub import Stub

logging.basicConfig(
    level=logging.INFO, format="%(asctime)s | %(levelname)-8s | %(message)s"
)


class MqttSend(CliMutuallyExclusiveGroup):
    mqtt: MqttSettings | None = None
    skip_mqtt: Literal[True] | None = None


class ReadWithMqttCmd(ModbusSettings, MqttSettings):
    activate_topic: str = TOPIC
    activate_json_path: str = PATH

    async def cli_cmd(self) -> None:
        async with self.make_broker() as broker:
            bridge = RelaySwitchingBridge.from_settings(
                self,
                broker,
                self.activate_topic,
                self.activate_json_path,
            )
            await bridge.run_once()
        print("Read complete — temperatures published to MQTT")


class ReadSkipMqttCmd(ModbusSettings):
    async def cli_cmd(self) -> None:
        modbus = self.modbus_client()
        topics: list[ModbusTopic] = [HULL_TEMPERATURE_TOPIC]
        reader = ModbusReader(modbus, topics)
        modbus.open()
        try:
            for topic, payload in reader.read_all():
                print(f"{topic}: {payload.model_dump(mode='json')}")
        finally:
            modbus.close()


class StubCmd(ModbusSettings, MqttSettings):
    temperature: float = 20
    seconds: int = -1

    async def cli_cmd(self) -> None:
        async with Stub.from_settings(
            self, self, TOPIC, PATH, self.temperature
        ) as stub:
            print("Running stub...")
            task = asyncio.create_task(await stub.run())
            if self.seconds == -1:
                await task
            else:
                await asyncio.sleep(self.seconds)
                task.cancel()


class TuiCmd(ModbusSettings):
    temperature: float = 20

    def cli_cmd(self) -> None:
        from zero_modbus_bridge.tui import (
            run_tui,
        )  # heavy TUI-only dep, import on demand

        run_tui(
            [([HULL_TEMPERATURE_TOPIC], self.modbus_port)],
            bind_host=self.modbus_host,
            float_default=self.temperature,
        )


class RunCmd(ModbusSettings, MqttSettings):
    activate_topic: str = TOPIC
    activate_json_path: str = PATH

    async def cli_cmd(self) -> None:
        broker = self.make_broker()
        bridge = RelaySwitchingBridge.from_settings(
            self,
            broker,
            self.activate_topic,
            self.activate_json_path,
        )
        app = FastStream(broker)
        app.after_startup(bridge.run)
        await app.run()


class SchemaCmd(BaseModel):
    async def cli_cmd(self) -> None:
        from zero_hull_temperature.addresses import HullTemperature

        print(HullTemperature.model_json_schema())


class AsyncApiCmd(BaseSettings):
    title: str = "Hull Temperature"
    version: str = "1.0.0"

    def cli_cmd(self) -> None:
        print(json.dumps(build_asyncapi(self.title, self.version), indent=2))


def build_asyncapi(
    title: str = "Hull Temperature", version: str = "1.0.0"
) -> dict[str, Any]:
    """AsyncAPI 3.0 document generated by FastStream.

    Built from the same publisher the runtime bridge registers (see
    ``addresses.create_publisher``), so spec and runtime cannot drift.
    """
    broker = MQTTBroker("localhost:1883")
    create_publisher(broker)
    factory = AsyncAPI(broker, title=title, version=version)
    return factory.to_specification().to_jsonable()


class ZeroHullTemperature(BaseSettings, cli_kebab_case=True):
    model_config = SettingsConfigDict(
        cli_implicit_flags=True,
        cli_ignore_unknown_args=True,
    )

    read_with_mqtt: CliSubCommand[ReadWithMqttCmd]
    read_skip_mqtt: CliSubCommand[ReadSkipMqttCmd]
    stub: CliSubCommand[StubCmd]
    tui: CliSubCommand[TuiCmd]
    run: CliSubCommand[RunCmd]
    print_schema: CliSubCommand[SchemaCmd]
    print_asyncapi: CliSubCommand[AsyncApiCmd]

    def cli_cmd(self) -> None:
        try:
            CliApp.run_subcommand(self)
        except KeyboardInterrupt:
            pass
