blueprint:
  name: Dual Button Light Control
  description: Control light brightness using up and down buttons of a Rocker Button
  domain: automation
  input:
    button_up_section:
      name: Button Up
      icon: mdi:gesture-tap-button
      description: These options control the behavior of the first button
      input:
        button_up:
          name: Button
          description: Up button
          selector:
            entity:
              domain: [binary_sensor, input_boolean, input_button]
        button_up_short_press:
          name: Short Press
          description: When the up button is pressed and released quickly
          default: "script.light_toggle"
          selector:
            select:
              mode: dropdown
              options:
                - label: "Toggle"
                  value: "script.light_toggle"
                - label: "Turn On"
                  value: "script.light_turn_on"
                - label: "Turn Off"
                  value: "script.light_turn_off"
        button_up_hold:
          name: Press & Hold
          description: When the up button is held down
          default: script.light_dim_up
          selector:
            select:
              mode: dropdown
              options:
                - label: "Dim Up"
                  value: "script.light_dim_up"
                - label: "Dim Down"
                  value: "script.light_dim_down"
                - label: "Smart Dim (up/down)"
                  value: "script.light_smart_dim"

    button_down_section:
      name: Button Down
      collapsed: true
      icon: mdi:gesture-tap-button
      description: These options control the behavior of the second button
      input:
        button_down:
          name: Button
          description: Down button
          selector:
            entity:
              domain: [binary_sensor, input_boolean, input_button]
        button_down_short_press:
          name: Short Press
          description: When the down button is pressed and released quickly
          default: "script.light_toggle"
          selector:
            select:
              mode: dropdown
              options:
                - label: "Toggle"
                  value: "script.light_toggle"
                - label: "Turn On"
                  value: "script.light_turn_on"
                - label: "Turn Off"
                  value: "script.light_turn_off"
        button_down_hold:
          name: Press & Hold
          description: When the down button is held down
          default: script.light_dim_down
          selector:
            select:
              mode: dropdown
              options:
                - label: "Dim Up"
                  value: "script.light_dim_up"
                - label: "Dim Down"
                  value: "script.light_dim_down"
                - label: "Smart Dim (up/down)"
                  value: "script.light_smart_dim"
    dimming:
      name: Dimming
      icon: mdi:brightness-6
      description: These options control the dimming behavior of the buttons
      input:
        light_label:
          name: Light Label
          description: Label to select light outputs
          selector:
            label:
        dim_level:
          name: Dim Level
          description: Helper to store dim level
          selector:
            entity:
              domain: input_number
        min_level:
          name: Minimum Level
          description: Minimum dim level
          default: 1
          selector:
            number:
              min: 1
              max: 100
              step: 1
        max_level:
          name: Maximum Level
          description: Maximum dim level
          default: 100
          selector:
            number:
              min: 0
              max: 100
              step: 1
        reverse_delay:
          name: Reverse Delay (for Smart Dim)
          description: Delay in seconds before reversing dim direction when hitting a boundary
          default: 5
          selector:
            number:
              min: 0
              max: 10
              step: 1

    night_mode_section:
      name: Night Mode (optional)
      icon: mdi:lightbulb-on-outline
      collapsed: true
      description: These options control the behavior of the light when night mode is active
      input:
        night_mode:
          default: []
          name: Night Mode
          description: Select a toggle to determine if night mode is active. If night mode is active, this light will be turned off.
          selector:
            entity:
              domain: [binary_sensor, input_boolean]
        enable_night_controls:
          default: true
          name: Enable Night Controls
          description: Enable light control when in night mode. If this option is disabled, the buttons do not control the light when night mode is active.
          selector:
            boolean:

mode: parallel

variables:
  dim_level: !input dim_level
  light_label: !input light_label
  night_mode: !input night_mode
  enable_night_controls: !input enable_night_controls

trigger_variables:
  scripts:
    "short_press:button_up": !input button_up_short_press
    "short_press:button_down": !input button_down_short_press
    "hold:button_up": !input button_up_hold
    "hold:button_down": !input button_down_hold

triggers:
  - id: "short_press:button_up"
    trigger: state
    entity_id: !input button_up
    to: "on"
  - id: "hold:button_up"
    trigger: state
    entity_id: !input button_up
    to: "on"
    for:
      milliseconds: 500
  - id: "short_press:button_down"
    trigger: state
    entity_id: !input button_down
    to: "on"
  - id: "hold:button_down"
    trigger: state
    entity_id: !input button_down
    to: "on"
    for:
      milliseconds: 500
  - id: dim_set
    trigger: state
    entity_id: !input dim_level
  - id: night_mode_changed
    trigger: state
    entity_id: !input night_mode

actions:
  - choose:
      - conditions:
          - alias: Short press
            condition: template
            value_template: "{{ trigger.id.startswith('short_press') and (enable_night_controls or (not night_mode) or is_state(night_mode, 'off')) }}"
        sequence:
          - delay:
              milliseconds: 300.0
          - if:
              - alias: Button no longer pressed
                condition: template
                value_template: "{{ is_state(trigger.entity_id, 'off') }}"
            then:
              - alias: Execute short press behavior
                action: "{{ scripts.get(trigger.id) }}"
                data:
                  dim_level: !input dim_level
                  button: "{{ trigger.entity_id }}"
                  min_level: !input min_level
                  max_level: !input max_level
      - conditions:
          - alias: Hold
            condition: template
            value_template: "{{ trigger.id.startswith('hold') and (enable_night_controls or (not night_mode) or is_state(night_mode, 'off')) }}"
        sequence:
          - alias: Repeat behaviour while button is held
            action: "{{ scripts.get(trigger.id) }}"
            data:
              dim_level: !input dim_level
              button: "{{ trigger.entity_id }}"
              min_level: !input min_level
              max_level: !input max_level
              reverse_delay: !input reverse_delay
      - conditions:
          - alias: Night mode changed
            condition: trigger
            id: night_mode_changed
        sequence:
          - if:
              - condition: template
                value_template: "{{ is_state(night_mode, 'on') }}"
            then:
              - action: script.light_turn_off
                data:
                  dim_level: !input dim_level
            else:
              - action: script.light_turn_on
                data:
                  dim_level: !input dim_level
                  min_level: !input min_level
      - conditions:
          - alias: Dim level changed
            condition: trigger
            id: dim_set
        sequence:
          - action: script.light_set_dim
            data:
              dim_level: "{{ states(dim_level) | int }}"
              light_label: !input light_label
