blueprint:
  name: Red/night lights
  description: Turn on red lights when night mode is active, and turn them off when night mode is inactive. Optionally, turn off white lights when night mode is active, and turn them on when night mode is inactive.
  domain: automation
  input:
    lights_section:
      name: Lights
      icon: mdi:lightbulb-on-outline
      description: The lights that need to be controlled
      input:
        red_lights:
          name: Red Lights
          description: Red Lights to turn on when night mode is active, and turn off when night mode is inactive
          selector:
            target:
              entity:
                - domain: light
        white_lights:
          name: White Lights
          description: White Lights to turn off when night mode is active, and turn on when night mode is inactive
          selector:
            entity:
              domain: input_number
              multiple: true
        night_mode:
          default: []
          name: Night Mode
          description: Select a toggle to determine if night mode is active.gfp
          
          selector:
            entity:
              domain: [binary_sensor, input_boolean]

mode: parallel

variables:
  night_mode: !input night_mode

triggers:
  - id: night_mode_changed
    trigger: state
    entity_id: !input night_mode

actions:
  - if:
      - condition: template
        value_template: "{{ is_state(night_mode, 'on') }}"
    then:
      - alias: Turn on all red lights
        action: light.turn_on
        data:
          brightness_pct: 100
        target: !input red_lights
      - repeat:
          for_each: !input white_lights
          sequence:
            - alias: Turn off all white lights
              action: script.light_turn_off
              data:
                dim_level: "{{ repeat.item }}"
    else:
      - alias: Turn off all red lights
        action: light.turn_off
        target: !input red_lights
      - repeat:
          for_each: !input white_lights
          sequence:
            - alias: Turn on all white lights
              action: script.light_turn_on
              data:
                dim_level: "{{ repeat.item }}"
