apiVersion: 1
datasources:
  - jsonData:
      connMaxLifetime: 14400
      database: dev
      maxIdleConns: 100
      maxIdleConnsAuto: true
      maxOpenConns: 100
      postgresVersion: 1500
      sslmode: disable
      timescaledb: false
    name: Risingwave
    type: postgres
    url: risingwave:4566
    user: root
