{{- if ne (.Values.command | default "serve") "listen" }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "zero-mqtt-graphql.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "zero-mqtt-graphql.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.listenPort }}
      targetPort: {{ .Values.listenPort }}
      protocol: TCP
      name: http
  selector:
    {{- include "zero-mqtt-graphql.selectorLabels" . | nindent 6 }}
{{- end }}
