# This will set the replicaset count more information can be found here: https://kubernetes.io/docs/concepts/workloads/controllers/replicaset/
replicaCount:
  backend: 1

# This sets the container image more information can be found here: https://kubernetes.io/docs/concepts/containers/images/
image:
  repository: europe-west1-docker.pkg.dev/common-449414/common/zero-domestic-control
  # This sets the pull policy for images.
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: ""

# Required: MQTT host
mqtt:
  host:
  port:

# Required: Risingwave URL
risingwave:
  url:

# Required: PostgresQL configuration
postgresql:
  host:
  port:
  user:
  db:
  password:
  existingSecret:
  existingSecretPasswordKey:

# Required: Hasura configuration
hasura:
  secret:
  existingSecret:
  existingSecretJwtKey:

stub:
  enabled: false
  host: domestic-control-stub.zero.svc.cluster.local
  port: 502

# Required: Home Assistant configuration
homeAssistant:
  url:
  websocketUrl:
  token:
  existingSecret:
  existingSecretTokenKey:

# This is for the secrets for pulling an image from a private repository more information can be found here: https://kubernetes.io/docs/tasks/configure-pod-container/pull-image-private-registry/
imagePullSecrets:
  - name:

# This is to override the chart name.
nameOverride: ""
fullnameOverride: ""

# This is for setting Kubernetes Annotations to a Pod.
# For more information checkout: https://kubernetes.io/docs/concepts/overview/working-with-objects/annotations/
podAnnotations: {}
# This is for setting Kubernetes Labels to a Pod.
# For more information checkout: https://kubernetes.io/docs/concepts/overview/working-with-objects/labels/
podLabels: {}

# This is for setting up a service more information can be found here: https://kubernetes.io/docs/concepts/services-networking/service/
service:
  backend:
    # This sets the service type more information can be found here: https://kubernetes.io/docs/concepts/services-networking/service/#publishing-services-service-types
    type: ClusterIP
    # This sets the ports more information can be found here: https://kubernetes.io/docs/concepts/services-networking/service/#field-spec-ports
    port: 80
  control:
    # This sets the service type more information can be found here: https://kubernetes.io/docs/concepts/services-networking/service/#publishing-services-service-types
    type: ClusterIP
    # This sets the ports more information can be found here: https://kubernetes.io/docs/concepts/services-networking/service/#field-spec-ports
    port: 80

# Resources are left to user
resources:
  backend: {}

  control: {}
