{
 "title": "Electrical energy",
 "time": { "from": "now-12h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "datasource", "query": "info8fcc-greptimedb-datasource" }
  ]
 },
 "panels": [
  {
   "title": "Electrical flow",
   "type": "canvas",
   "gridPos": { "h": 12, "w": 11, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "targets": [
    {
     "dataset": "dev",
     "rawSql": "SELECT\r\n  time,\r\n  MAX(CASE WHEN main_group = 'Domestic' THEN power_value ELSE 0 END)  AS domestic,\r\n  MAX(CASE WHEN main_group = 'HVAC' THEN power_value ELSE 0 END)      AS hvac,\r\n  MAX(CASE WHEN main_group = 'Technical' THEN power_value ELSE 0 END) AS technical,\r\n  NULL                                                                AS propulsion,\r\n  NULL                                                                AS solar,\r\n  NULL                                                                AS shore_power,\r\n  NULL                                                                AS hydro\r\n  FROM (\r\n  SELECT\r\n    MAX(time) AS time,\r\n    main_group,\r\n    AVG(power_value) AS power_value\r\n  FROM (\r\n    SELECT\r\n      time,\r\n      main_group,\r\n      SUM(power) AS power_value\r\n    FROM views.gld_electrical_power_consumption_per_minute\r\n    WHERE time >= date_sub($__toTime, '5 minutes'::INTERVAL) AND time < $__toTime\r\n    GROUP BY\r\n      time,\r\n      main_group\r\n  )\r\n  GROUP BY main_group\r\n)\r\nGROUP BY time"
    },
    {
     "rawSql": "SELECT\r\n  MAX(time) AS time,\r\n  SUM(avg_energy_per_pack) AS energy,\r\n  AVG(avg_soc_per_pack) AS soc,\r\n  SUM(avg_charging_power_per_pack) AS charging_power,\r\n  SUM(avg_discharging_power_per_pack) AS discharging_power\r\nFROM (\r\n  SELECT\r\n    MAX(time) AS time,\r\n    topic,\r\n    AVG(avg_energy) AS avg_energy_per_pack,\r\n    AVG(avg_soc) AS avg_soc_per_pack,\r\n    CASE WHEN MAX(is_charging) THEN AVG(ABS(avg_battery_power)) ELSE 0 END AS avg_charging_power_per_pack,\r\n    CASE WHEN MAX(is_discharging) THEN AVG(avg_battery_power) ELSE 0 END AS avg_discharging_power_per_pack,\r\n  FROM views.gld_batteries_per_minute\r\n  WHERE time >= date_sub($__toTime, '5 minutes'::INTERVAL) AND time < $__toTime\r\n  GROUP BY topic\r\n)"
    }
   ]
  },
  {
   "title": "Electrical energy consumption",
   "type": "marcusolsson-treemap-panel",
   "description": "Energy consumption per group and subgroup",
   "gridPos": { "h": 12, "w": 13, "x": 11, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "watth" } },
   "targets": [
    {
     "dataset": "dev",
     "rawSql": "SELECT\r\n\tmain_group AS group_name,\r\n\tsub_group AS sub_group_name,\r\n\tSUM(energy) AS energy,\r\n  SUM(SUM(energy)) OVER (PARTITION BY main_group) AS group_energy\r\nFROM (\r\n\tSELECT\r\n    date_trunc('hour', time) AS hour,\r\n\t\tmain_group,\r\n\t\tsub_group,\r\n\t\tSUM(power) / 60 AS energy\r\n\tFROM views.gld_electrical_power_consumption_per_minute\r\n\tWHERE main_group IN ('Domestic', 'HVAC', 'Technical', 'Propulsion')\r\n\tAND $__timeFilter(time)\r\n\tGROUP BY hour, main_group, sub_group\r\n)\r\nGROUP BY main_group, sub_group"
    }
   ]
  },
  {
   "title": "Electrical energy production and consumption",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "watth" } },
   "targets": [
    {
     "rawSql": "SELECT\r\n  hour AS time,\r\n\t-- Producers\r\n  SUM(CASE WHEN group_name = 'Solar' THEN energy ELSE 0 END)           AS solar,\r\n  SUM(CASE WHEN group_name = 'Shore' THEN energy ELSE 0 END)           AS shore,\r\n  SUM(CASE WHEN group_name = 'Hydrogeneration' THEN energy ELSE 0 END) AS hydrogeneration,\r\n\t-- Consumers\r\n  SUM(CASE WHEN group_name = 'Domestic' THEN -energy ELSE 0 END)       AS domestic,\r\n  SUM(CASE WHEN group_name = 'Technical' THEN -energy ELSE 0 END)      AS technical,\r\n  SUM(CASE WHEN group_name = 'HVAC' THEN -energy ELSE 0 END)           AS hvac,\r\n  SUM(CASE WHEN group_name = 'Propulsion' THEN -energy ELSE 0 END)     AS propulsion\r\nFROM (\r\n\tSELECT\r\n\t\tdate_trunc('hour', time) AS hour,\r\n\t\tmain_group               AS group_name,\r\n\t\tsub_group                AS sub_group_name,\r\n\t\tSUM(power) / 60          AS energy\r\n\tFROM views.gld_electrical_power_consumption_per_minute\r\n\tWHERE $__timeFilter(time)\r\n\tGROUP BY hour, main_group, sub_group\r\n)\r\nGROUP BY hour\r\nORDER BY hour"
    }
   ]
  }
 ]
}