{
 "title": "Historical energy",
 "time": { "from": "now-29d/d", "to": "now/d" },
 "refresh": "15m",
 "templating": {
  "list": [
   { "name": "datasource", "query": "grafana-postgresql-datasource" },
   { "name": "min_soc", "label": "Minimal State of Charge (%)", "query": "5,10,15,20,25,30" },
   {
    "name": "start_date",
    "label": "Start date",
    "query": "SELECT to_char(hour, 'MM_DD Mon YYYY') AS day \nFROM energy.electrical_soc_hourly\nWHERE hour > now() - INTERVAL '15 days'\nGROUP BY day\nORDER BY day DESC"
   },
   {
    "name": "daily_consumption",
    "label": "Daily consumption (kWh)",
    "query": "SELECT\n  ARG_MAX(avg_daily_consumption,\n  avg_daily_consumption_timestamp)\nFROM energy.energy_metrics"
   },
   { "name": "max_soc", "label": "Max state of charge", "query": "300" }
  ]
 },
 "panels": [
  {
   "title": "State of charge (SoC)",
   "type": "timeseries",
   "description": "Battery state of charge and daily net consumption/production",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "dataset": "dev",
     "rawSql": "SELECT\r\n\tDAY,\r\n\tAVG(total_soc) * 100 / $max_soc AS soc\r\nFROM (\r\n\tSELECT\r\n\t\tdate_trunc('day', HOUR AT TIME ZONE 'Etc/Universal') AS day,\r\n\t\tSUM(soc) AS total_soc\r\n\tFROM energy.electrical_soc_hourly\r\n\tGROUP BY hour\r\n)\r\nGROUP BY DAY\r\nORDER BY day"
    },
    {
     "dataset": "dev",
     "rawSql": "SELECT *\r\nFROM (\r\n  WITH\r\n  start_value AS (\r\n    SELECT\r\n      day AS start_day,\r\n      AVG(total_soc) as start_soc\r\n    FROM (\r\n      SELECT\r\n        date_trunc('day', hour) AS day,\r\n        SUM(soc) AS total_soc\r\n      FROM energy.electrical_soc_hourly\r\n      WHERE hour BETWEEN to_date('$start_date', 'DD Mon YYYY') AND to_date('$start_date', 'DD Mon YYYY') + TIME '23:59'\r\n      GROUP BY hour\r\n    )\r\n    GROUP BY day\r\n  ),\r\n  future AS (\r\n    SELECT\r\n      (start_day + n * INTERVAL '1 day')::date AS day,\r\n      start_soc - $daily_consumption * n AS soc\r\n    FROM start_value\r\n    CROSS JOIN generate_series(0, 30) AS n\r\n  )\r\n  SELECT\r\n    day AS time,\r\n    soc * 100 / $max_soc AS soc_prediction\r\n  FROM future\r\n)\r\nORDER BY time"
    },
    {
     "dataset": "dev",
     "rawSql": "WITH\r\n  start_point AS (\r\n    SELECT\r\n      day::date AS start_day,\r\n      AVG(total_soc) as start_soc\r\n    FROM (\r\n      SELECT\r\n        date_trunc('day', hour) AS day,\r\n        SUM(soc) AS total_soc\r\n      FROM energy.electrical_soc_hourly\r\n      WHERE hour BETWEEN to_date('$start_date', 'DD Mon YYYY') AND to_date('$start_date', 'DD Mon YYYY') + TIME '23:59'\r\n      GROUP BY hour\r\n    )\r\n    GROUP BY day\r\n  ),\r\n  end_point AS (\r\n    SELECT\r\n      day::date AS end_day,\r\n      AVG(total_soc) as end_soc\r\n    FROM (\r\n      SELECT\r\n        date_trunc('day', hour) AS day,\r\n        SUM(soc) AS total_soc\r\n      FROM energy.electrical_soc_hourly\r\n      WHERE hour >= (SELECT date_trunc('day', MAX(hour)) FROM energy.electrical_soc_hourly)\r\n      GROUP BY hour\r\n    )\r\n    GROUP BY day\r\n  ),\r\n  consumption_values AS (\r\n    SELECT \r\n      s.start_day AS start_date,\r\n      e.end_day AS end_date,\r\n      s.start_soc AS start_value,\r\n      (e.end_soc - s.start_soc) / GREATEST(1, (e.end_day - s.start_day)) AS daily_consumption\r\n    FROM start_point s\r\n    CROSS JOIN end_point e\r\n  )\r\nSELECT\r\n  (start_date + n * INTERVAL '1 day')::date AS day,\r\n  CASE WHEN start_date = end_date\r\n    THEN NULL\r\n    ELSE (start_value + n * daily_consumption) * 100 / $max_soc\r\n  END AS soc_calculated\r\nFROM consumption_values\r\nCROSS JOIN generate_series(0, 30) AS n\r\n"
    },
    {
     "dataset": "dev",
     "rawSql": "WITH start_date AS (\r\n  SELECT to_timestamp($__from / 1000)::date AS start\r\n)\r\nSELECT\r\n  (start + n * INTERVAL '1 day')::date AS day,\r\n  $min_soc AS soc_threshold\r\nFROM start_date\r\nCROSS JOIN generate_series(0, 100) AS n"
    },
    {
     "dataset": "dev",
     "rawSql": "SELECT\r\n  date_trunc('day',  hour) DAY,\r\n  CASE WHEN SUM(-energy_wh) > 0 THEN SUM(-energy_wh)\r\n  ELSE NULL END AS daily_consumption,\r\n  CASE WHEN SUM(energy_wh) > 0 THEN SUM(energy_wh)\r\n  ELSE NULL END AS daily_production\r\nFROM energy.electrical_hourly\r\nGROUP BY DAY\r\nORDER BY DAY desc"
    }
   ]
  },
  {
   "title": "Total electrical energy consumption and production",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 12, "x": 0, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "watth" } },
   "targets": [
    {
     "dataset": "dev",
     "rawSql": "SELECT\r\n\tdate_trunc('day', hour) AS day,\r\n\t-- Producers\r\n\tSUM(CASE WHEN group_name = 'Hydrogeneration' THEN energy_wh ELSE 0 END) AS hydrogeneration,\r\n\tSUM(CASE WHEN group_name = 'Solar' THEN energy_wh ELSE 0 END) AS solar,\r\n\tSUM(CASE WHEN group_name = 'Shore' THEN energy_wh ELSE 0 END) AS shore,\r\n\t-- Consumers\r\n\tSUM(CASE WHEN group_name = 'Domestic' THEN -energy_wh ELSE 0 END) AS domestic,\r\n\tSUM(CASE WHEN group_name = 'HVAC' THEN -energy_wh ELSE 0 END) AS hvac,\r\n\tSUM(CASE WHEN group_name = 'Technical' THEN -energy_wh ELSE 0 END) AS technical,\r\n\tSUM(CASE WHEN group_name = 'Propulsion' THEN -energy_wh ELSE 0 END) AS propulsion\r\nFROM energy.electrical_hourly\r\nGROUP BY day"
    }
   ]
  },
  {
   "title": "Total electrical energy consumption",
   "type": "marcusolsson-treemap-panel",
   "description": "Total energy consumption per group and sub group",
   "gridPos": { "h": 13, "w": 12, "x": 12, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "watth" } },
   "targets": [
    {
     "dataset": "dev",
     "rawSql": "SELECT\r\n\tgroup_name,\r\n\tsub_group_name,\r\n  SUM(SUM(energy)) OVER (PARTITION BY group_name) AS group_energy,\r\n\tSUM(energy) AS sub_group_energy\r\nFROM (\r\n\tSELECT\r\n\t\tgroup_name,\r\n\t\tsub_group_name,\r\n\t\tSUM(energy_wh) AS energy\r\n\tFROM energy.electrical_hourly\r\n\tWHERE group_name IN ('Domestic', 'HVAC', 'Technical', 'Propulsion')\r\n\tAND $__timeFilter(hour)\r\n\tGROUP BY topic, group_name, sub_group_name\r\n)\r\nGROUP BY group_name, sub_group_name\r\n"
    }
   ]
  }
 ]
}