# Per https://chatgpt.com/share/68878e3e-7eb8-8006-9142-92fbd124b502
from dataclasses import dataclass
from itertools import chain

AC_ADRESSES = {
    "01": [
        {
            "register_name": "REG_SPLIT_01_READ_PWR ",
            "address": 200,
            "description": "Unit Power On/Off 0=OFF 1=ON",
            "reg_split": "01",
            "variable_name": "PWR",
            "type": "ac",
        },
        {
            "register_name": "REG_SPLIT_01_READ_SP_ROOM ",
            "address": 201,
            "description": 'Unit SetPoint: (hundredths of degrees Celsius) es: 2350 = 23.50 \u00b0C -> Range: 18..30\u00b0C"',
            "reg_split": "01",
            "variable_name": "SP_ROOM",
            "type": "ac",
        },
        {
            "register_name": "REG_SPLIT_01_READ_FAN_SPEED ",
            "address": 202,
            "description": "Unit Fan Speed (with Syxthsense): 1=Vel.Night; 2=Vel.1; 3=Vel.2; 4=Vel.3; 5=Vel.4; 7=Vel.5; 8=Vel.6; 9=Vel.Auto Unit Fan Speed (in other case): 1=Vel.Night; 2=Vel.1; 3=Vel.2; 4=Vel.3; 5=Vel.4; 6=Vel.5; 7=Vel.6; 8=Vel.7; 9=Vel.Auto",
            "reg_split": "01",
            "variable_name": "FAN_SPEED",
            "type": "ac",
        },
        {
            "register_name": "REG_SPLIT_01_READ_AIR_IN ",
            "address": 203,
            "description": "Unit Input Air Temperature: (hundredths of degrees Celsius) es: 2350 = 23.50 \u00b0C",
            "reg_split": "01",
            "variable_name": "AIR_IN",
            "type": "ac",
        },
        {
            "register_name": "REG_SPLIT_01_READ_STATUS ",
            "address": 204,
            "description": "Diagnostic Split Comunication Status: Bit 0=Unit not connected on the bus; Bit 1=Unit connected on the bus; Bit 2=Unit connected on the bus but offline; Bit 3=Unit in error.",
            "reg_split": "01",
            "variable_name": "STATUS",
            "type": "ac",
        },
        {
            "register_name": "REG_SPLIT_01_AHU_MODE ",
            "address": 205,
            "description": "AHU State 16 = Ventilation 32=Automatic ",
            "reg_split": "01",
            "variable_name": None,
            "type": "ac",
        },
        {
            "register_name": "REG_SPLIT_01_READ_HEATER_PWR ",
            "address": 206,
            "description": "Heater State 0 = OFF; 1 = ON ",
            "reg_split": "01",
            "variable_name": "HEATER_PWR",
            "type": "ac",
        },
        {
            "register_name": "REG_SPLIT_01_READ_HUMI ",
            "address": 207,
            "description": "Humidity 0..100% ",
            "reg_split": "01",
            "variable_name": "HUMI",
            "type": "ac",
        },
    ],
    "02": [
        {
            "register_name": "REG_SPLIT_02_READ_PWR ",
            "address": 210,
            "description": "Unit Power On/Off 0=OFF 1=ON",
            "reg_split": "02",
            "variable_name": "PWR",
            "type": "ac",
        },
        {
            "register_name": "REG_SPLIT_02_READ_SP_ROOM ",
            "address": 211,
            "description": 'Unit SetPoint: (hundredths of degrees Celsius) es: 2350 = 23.50 \u00b0C -> Range: 18..30\u00b0C"',
            "reg_split": "02",
            "variable_name": "SP_ROOM",
            "type": "ac",
        },
        {
            "register_name": "REG_SPLIT_02_READ_FAN_SPEED ",
            "address": 212,
            "description": "Unit Fan Speed: 1=Vel.Night; 2=Vel.1; 3=Vel.2; 4=Vel.3; 5=Vel.4; 7=Vel.5; 8=Vel.6; 9=Vel.Auto",
            "reg_split": "02",
            "variable_name": "FAN_SPEED",
            "type": "ac",
        },
        {
            "register_name": "REG_SPLIT_02_READ_AIR_IN ",
            "address": 213,
            "description": "Unit Input Air Temperature: (hundredths of degrees Celsius) es: 2350 = 23.50 \u00b0C",
            "reg_split": "02",
            "variable_name": "AIR_IN",
            "type": "ac",
        },
        {
            "register_name": "REG_SPLIT_02_READ_STATUS ",
            "address": 214,
            "description": "Diagnostic Split Comunication Status: Bit 0=Unit not connected on the bus; Bit 1=Unit connected on the bus; Bit 2=Unit connected on the bus but offline; Bit 3=Unit in error.",
            "reg_split": "02",
            "variable_name": "STATUS",
            "type": "ac",
        },
        {
            "register_name": "REG_SPLIT_02_AHU_MODE ",
            "address": 215,
            "description": "AHU State 16 = Ventilation 32=Automatic ",
            "reg_split": "02",
            "variable_name": None,
            "type": "ac",
        },
        {
            "register_name": "REG_SPLIT_02_READ_HEATER_PWR ",
            "address": 216,
            "description": "Heater State 0 = OFF; 1 = ON ",
            "reg_split": "02",
            "variable_name": "HEATER_PWR",
            "type": "ac",
        },
        {
            "register_name": "REG_SPLIT_02_READ_HUMI ",
            "address": 217,
            "description": "Humidity 0..100% ",
            "reg_split": "02",
            "variable_name": "HUMI",
            "type": "ac",
        },
    ],
    "03": [
        {
            "register_name": "REG_SPLIT_03_READ_PWR ",
            "address": 220,
            "description": "Unit Power On/Off 0=OFF 1=ON",
            "reg_split": "03",
            "variable_name": "PWR",
            "type": "ac",
        },
        {
            "register_name": "REG_SPLIT_03_READ_SP_ROOM ",
            "address": 221,
            "description": 'Unit SetPoint: (hundredths of degrees Celsius) es: 2350 = 23.50 \u00b0C -> Range: 18..30\u00b0C"',
            "reg_split": "03",
            "variable_name": "SP_ROOM",
            "type": "ac",
        },
        {
            "register_name": "REG_SPLIT_03_READ_FAN_SPEED ",
            "address": 222,
            "description": "Unit Fan Speed (with Syxthsense): 1=Vel.Night; 2=Vel.1; 3=Vel.2; 4=Vel.3; 5=Vel.4; 7=Vel.5; 8=Vel.6; 9=Vel.Auto Unit Fan Speed (in other case): 1=Vel.Night; 2=Vel.1; 3=Vel.2; 4=Vel.3; 5=Vel.4; 6=Vel.5; 7=Vel.6; 8=Vel.7; 9=Vel.Auto",
            "reg_split": "03",
            "variable_name": "FAN_SPEED",
            "type": "ac",
        },
        {
            "register_name": "REG_SPLIT_03_READ_AIR_IN ",
            "address": 223,
            "description": "Unit Input Air Temperature: (hundredths of degrees Celsius) es: 2350 = 23.50 \u00b0C",
            "reg_split": "03",
            "variable_name": "AIR_IN",
            "type": "ac",
        },
        {
            "register_name": "REG_SPLIT_03_READ_STATUS ",
            "address": 224,
            "description": "Diagnostic Split Comunication Status: Bit 0=Unit not connected on the bus; Bit 1=Unit connected on the bus; Bit 2=Unit connected on the bus but offline; Bit 3=Unit in error.",
            "reg_split": "03",
            "variable_name": "STATUS",
            "type": "ac",
        },
        {
            "register_name": "REG_SPLIT_03_AHU_MODE ",
            "address": 225,
            "description": "AHU State 16 = Ventilation 32=Automatic ",
            "reg_split": "03",
            "variable_name": None,
            "type": "ac",
        },
        {
            "register_name": "REG_SPLIT_03_READ_HEATER_PWR ",
            "address": 226,
            "description": "Heater State 0 = OFF; 1 = ON ",
            "reg_split": "03",
            "variable_name": "HEATER_PWR",
            "type": "ac",
        },
        {
            "register_name": "REG_SPLIT_03_READ_HUMI ",
            "address": 227,
            "description": "Humidity 0..100% ",
            "reg_split": "03",
            "variable_name": "HUMI",
            "type": "ac",
        },
    ],
    "04": [
        {
            "register_name": "REG_SPLIT_04_READ_PWR ",
            "address": 230,
            "description": "Unit Power On/Off 0=OFF 1=ON",
            "reg_split": "04",
            "variable_name": "PWR",
            "type": "ac",
        },
        {
            "register_name": "REG_SPLIT_04_READ_SP_ROOM ",
            "address": 231,
            "description": 'Unit SetPoint: (hundredths of degrees Celsius) es: 2350 = 23.50 \u00b0C -> Range: 18..30\u00b0C"',
            "reg_split": "04",
            "variable_name": "SP_ROOM",
            "type": "ac",
        },
        {
            "register_name": "REG_SPLIT_04_READ_FAN_SPEED ",
            "address": 232,
            "description": "Unit Fan Speed (with Syxthsense): 1=Vel.Night; 2=Vel.1; 3=Vel.2; 4=Vel.3; 5=Vel.4; 7=Vel.5; 8=Vel.6; 9=Vel.Auto Unit Fan Speed (in other case): 1=Vel.Night; 2=Vel.1; 3=Vel.2; 4=Vel.3; 5=Vel.4; 6=Vel.5; 7=Vel.6; 8=Vel.7; 9=Vel.Auto",
            "reg_split": "04",
            "variable_name": "FAN_SPEED",
            "type": "ac",
        },
        {
            "register_name": "REG_SPLIT_04_READ_AIR_IN ",
            "address": 233,
            "description": "Unit Input Air Temperature: (hundredths of degrees Celsius) es: 2350 = 23.50 \u00b0C",
            "reg_split": "04",
            "variable_name": "AIR_IN",
            "type": "ac",
        },
        {
            "register_name": "REG_SPLIT_04_READ_STATUS ",
            "address": 234,
            "description": "Diagnostic Split Comunication Status: Bit 0=Unit not connected on the bus; Bit 1=Unit connected on the bus; Bit 2=Unit connected on the bus but offline; Bit 3=Unit in error.",
            "reg_split": "04",
            "variable_name": "STATUS",
            "type": "ac",
        },
        {
            "register_name": "REG_SPLIT_04_AHU_MODE ",
            "address": 235,
            "description": "AHU State 16 = Ventilation 32=Automatic ",
            "reg_split": "04",
            "variable_name": None,
            "type": "ac",
        },
        {
            "register_name": "REG_SPLIT_04_READ_HEATER_PWR ",
            "address": 236,
            "description": "Heater State 0 = OFF; 1 = ON ",
            "reg_split": "04",
            "variable_name": "HEATER_PWR",
            "type": "ac",
        },
        {
            "register_name": "REG_SPLIT_04_READ_HUMI ",
            "address": 237,
            "description": "Humidity 0..100% ",
            "reg_split": "04",
            "variable_name": "HUMI",
            "type": "ac",
        },
    ],
    "05": [
        {
            "register_name": "REG_SPLIT_05_READ_PWR ",
            "address": 240,
            "description": "Unit Power On/Off 0=OFF 1=ON",
            "reg_split": "05",
            "variable_name": "PWR",
            "type": "ac",
        },
        {
            "register_name": "REG_SPLIT_05_READ_SP_ROOM ",
            "address": 241,
            "description": 'Unit SetPoint: (hundredths of degrees Celsius) es: 2350 = 23.50 \u00b0C -> Range: 18..30\u00b0C"',
            "reg_split": "05",
            "variable_name": "SP_ROOM",
            "type": "ac",
        },
        {
            "register_name": "REG_SPLIT_05_READ_FAN_SPEED ",
            "address": 242,
            "description": "Unit Fan Speed (with Syxthsense): 1=Vel.Night; 2=Vel.1; 3=Vel.2; 4=Vel.3; 5=Vel.4; 7=Vel.5; 8=Vel.6; 9=Vel.Auto Unit Fan Speed (in other case): 1=Vel.Night; 2=Vel.1; 3=Vel.2; 4=Vel.3; 5=Vel.4; 6=Vel.5; 7=Vel.6; 8=Vel.7; 9=Vel.Auto",
            "reg_split": "05",
            "variable_name": "FAN_SPEED",
            "type": "ac",
        },
        {
            "register_name": "REG_SPLIT_05_READ_AIR_IN ",
            "address": 243,
            "description": "Unit Input Air Temperature: (hundredths of degrees Celsius) es: 2350 = 23.50 \u00b0C",
            "reg_split": "05",
            "variable_name": "AIR_IN",
            "type": "ac",
        },
        {
            "register_name": "REG_SPLIT_05_READ_STATUS ",
            "address": 244,
            "description": "Diagnostic Split Comunication Status: Bit 0=Unit not connected on the bus; Bit 1=Unit connected on the bus; Bit 2=Unit connected on the bus but offline; Bit 3=Unit in error.",
            "reg_split": "05",
            "variable_name": "STATUS",
            "type": "ac",
        },
        {
            "register_name": "REG_SPLIT_05_AHU_MODE ",
            "address": 245,
            "description": "AHU State 16 = Ventilation 32=Automatic ",
            "reg_split": "05",
            "variable_name": None,
            "type": "ac",
        },
        {
            "register_name": "REG_SPLIT_05_READ_HEATER_PWR ",
            "address": 246,
            "description": "Heater State 0 = OFF; 1 = ON ",
            "reg_split": "05",
            "variable_name": "HEATER_PWR",
            "type": "ac",
        },
        {
            "register_name": "REG_SPLIT_05_READ_HUMI ",
            "address": 247,
            "description": "Humidity 0..100% ",
            "reg_split": "05",
            "variable_name": "HUMI",
            "type": "ac",
        },
    ],
    "06": [
        {
            "register_name": "REG_SPLIT_06_READ_PWR ",
            "address": 250,
            "description": "Unit Power On/Off 0=OFF 1=ON",
            "reg_split": "06",
            "variable_name": "PWR",
            "type": "ac",
        },
        {
            "register_name": "REG_SPLIT_06_READ_SP_ROOM ",
            "address": 251,
            "description": 'Unit SetPoint: (hundredths of degrees Celsius) es: 2350 = 23.50 \u00b0C -> Range: 18..30\u00b0C"',
            "reg_split": "06",
            "variable_name": "SP_ROOM",
            "type": "ac",
        },
        {
            "register_name": "REG_SPLIT_06_READ_FAN_SPEED ",
            "address": 252,
            "description": "Unit Fan Speed (with Syxthsense): 1=Vel.Night; 2=Vel.1; 3=Vel.2; 4=Vel.3; 5=Vel.4; 7=Vel.5; 8=Vel.6; 9=Vel.Auto Unit Fan Speed (in other case): 1=Vel.Night; 2=Vel.1; 3=Vel.2; 4=Vel.3; 5=Vel.4; 6=Vel.5; 7=Vel.6; 8=Vel.7; 9=Vel.Auto",
            "reg_split": "06",
            "variable_name": "FAN_SPEED",
            "type": "ac",
        },
        {
            "register_name": "REG_SPLIT_06_READ_AIR_IN ",
            "address": 253,
            "description": "Unit Input Air Temperature: (hundredths of degrees Celsius) es: 2350 = 23.50 \u00b0C",
            "reg_split": "06",
            "variable_name": "AIR_IN",
            "type": "ac",
        },
        {
            "register_name": "REG_SPLIT_06_READ_STATUS ",
            "address": 254,
            "description": "Diagnostic Split Comunication Status: Bit 0=Unit not connected on the bus; Bit 1=Unit connected on the bus; Bit 2=Unit connected on the bus but offline; Bit 3=Unit in error.",
            "reg_split": "06",
            "variable_name": "STATUS",
            "type": "ac",
        },
        {
            "register_name": "REG_SPLIT_06_AHU_MODE ",
            "address": 255,
            "description": "AHU State 16 = Ventilation 32=Automatic ",
            "reg_split": "06",
            "variable_name": None,
            "type": "ac",
        },
        {
            "register_name": "REG_SPLIT_06_READ_HEATER_PWR ",
            "address": 256,
            "description": "Heater State 0 = OFF; 1 = ON ",
            "reg_split": "06",
            "variable_name": "HEATER_PWR",
            "type": "ac",
        },
        {
            "register_name": "REG_SPLIT_06_READ_HUMI ",
            "address": 257,
            "description": "Humidity 0..100% ",
            "reg_split": "06",
            "variable_name": "HUMI",
            "type": "ac",
        },
    ],
    "07": [
        {
            "register_name": "REG_SPLIT_07_READ_PWR ",
            "address": 260,
            "description": "Unit Power On/Off 0=OFF 1=ON",
            "reg_split": "07",
            "variable_name": "PWR",
            "type": "ac",
        },
        {
            "register_name": "REG_SPLIT_07_READ_SP_ROOM ",
            "address": 261,
            "description": 'Unit SetPoint: (hundredths of degrees Celsius) es: 2350 = 23.50 \u00b0C -> Range: 18..30\u00b0C"',
            "reg_split": "07",
            "variable_name": "SP_ROOM",
            "type": "ac",
        },
        {
            "register_name": "REG_SPLIT_07_READ_FAN_SPEED ",
            "address": 262,
            "description": "Unit Fan Speed (with Syxthsense): 1=Vel.Night; 2=Vel.1; 3=Vel.2; 4=Vel.3; 5=Vel.4; 7=Vel.5; 8=Vel.6; 9=Vel.Auto Unit Fan Speed (in other case): 1=Vel.Night; 2=Vel.1; 3=Vel.2; 4=Vel.3; 5=Vel.4; 6=Vel.5; 7=Vel.6; 8=Vel.7; 9=Vel.Auto",
            "reg_split": "07",
            "variable_name": "FAN_SPEED",
            "type": "ac",
        },
        {
            "register_name": "REG_SPLIT_07_READ_AIR_IN ",
            "address": 263,
            "description": "Unit Input Air Temperature: (hundredths of degrees Celsius) es: 2350 = 23.50 \u00b0C",
            "reg_split": "07",
            "variable_name": "AIR_IN",
            "type": "ac",
        },
        {
            "register_name": "REG_SPLIT_07_READ_STATUS ",
            "address": 264,
            "description": "Diagnostic Split Comunication Status: Bit 0=Unit not connected on the bus; Bit 1=Unit connected on the bus; Bit 2=Unit connected on the bus but offline; Bit 3=Unit in error.",
            "reg_split": "07",
            "variable_name": "STATUS",
            "type": "ac",
        },
        {
            "register_name": "REG_SPLIT_07_AHU_MODE ",
            "address": 265,
            "description": "AHU State 16 = Ventilation 32=Automatic ",
            "reg_split": "07",
            "variable_name": None,
            "type": "ac",
        },
        {
            "register_name": "REG_SPLIT_07_READ_HEATER_PWR ",
            "address": 266,
            "description": "Heater State 0 = OFF; 1 = ON ",
            "reg_split": "07",
            "variable_name": "HEATER_PWR",
            "type": "ac",
        },
        {
            "register_name": "REG_SPLIT_07_READ_HUMI ",
            "address": 267,
            "description": "Humidity 0..100% ",
            "reg_split": "07",
            "variable_name": "HUMI",
            "type": "ac",
        },
    ],
    "08": [
        {
            "register_name": "REG_SPLIT_08_READ_PWR ",
            "address": 270,
            "description": "Unit Power On/Off 0=OFF 1=ON",
            "reg_split": "08",
            "variable_name": "PWR",
            "type": "ac",
        },
        {
            "register_name": "REG_SPLIT_08_READ_SP_ROOM ",
            "address": 271,
            "description": 'Unit SetPoint: (hundredths of degrees Celsius) es: 2350 = 23.50 \u00b0C -> Range: 18..30\u00b0C"',
            "reg_split": "08",
            "variable_name": "SP_ROOM",
            "type": "ac",
        },
        {
            "register_name": "REG_SPLIT_08_READ_FAN_SPEED ",
            "address": 272,
            "description": "Unit Fan Speed (with Syxthsense): 1=Vel.Night; 2=Vel.1; 3=Vel.2; 4=Vel.3; 5=Vel.4; 7=Vel.5; 8=Vel.6; 9=Vel.Auto Unit Fan Speed (in other case): 1=Vel.Night; 2=Vel.1; 3=Vel.2; 4=Vel.3; 5=Vel.4; 6=Vel.5; 7=Vel.6; 8=Vel.7; 9=Vel.Auto",
            "reg_split": "08",
            "variable_name": "FAN_SPEED",
            "type": "ac",
        },
        {
            "register_name": "REG_SPLIT_08_READ_AIR_IN ",
            "address": 273,
            "description": "Unit Input Air Temperature: (hundredths of degrees Celsius) es: 2350 = 23.50 \u00b0C",
            "reg_split": "08",
            "variable_name": "AIR_IN",
            "type": "ac",
        },
        {
            "register_name": "REG_SPLIT_08_READ_STATUS ",
            "address": 274,
            "description": "Diagnostic Split Comunication Status: Bit 0=Unit not connected on the bus; Bit 1=Unit connected on the bus; Bit 2=Unit connected on the bus but offline; Bit 3=Unit in error.",
            "reg_split": "08",
            "variable_name": "STATUS",
            "type": "ac",
        },
        {
            "register_name": "REG_SPLIT_08_AHU_MODE ",
            "address": 275,
            "description": "AHU State 16 = Ventilation 32=Automatic ",
            "reg_split": "08",
            "variable_name": None,
            "type": "ac",
        },
        {
            "register_name": "REG_SPLIT_08_READ_HEATER_PWR ",
            "address": 276,
            "description": "Heater State 0 = OFF; 1 = ON ",
            "reg_split": "08",
            "variable_name": "HEATER_PWR",
            "type": "ac",
        },
        {
            "register_name": "REG_SPLIT_08_READ_HUMI ",
            "address": 277,
            "description": "Humidity 0..100% ",
            "reg_split": "08",
            "variable_name": "HUMI",
            "type": "ac",
        },
    ],
    "09": [
        {
            "register_name": "REG_SPLIT_09_READ_PWR ",
            "address": 280,
            "description": "Unit Power On/Off 0=OFF 1=ON",
            "reg_split": "09",
            "variable_name": "PWR",
            "type": "ac",
        },
        {
            "register_name": "REG_SPLIT_09_READ_SP_ROOM ",
            "address": 281,
            "description": 'Unit SetPoint: (hundredths of degrees Celsius) es: 2350 = 23.50 \u00b0C -> Range: 18..30\u00b0C"',
            "reg_split": "09",
            "variable_name": "SP_ROOM",
            "type": "ac",
        },
        {
            "register_name": "REG_SPLIT_09_READ_FAN_SPEED ",
            "address": 282,
            "description": "Unit Fan Speed (with Syxthsense): 1=Vel.Night; 2=Vel.1; 3=Vel.2; 4=Vel.3; 5=Vel.4; 7=Vel.5; 8=Vel.6; 9=Vel.Auto Unit Fan Speed (in other case): 1=Vel.Night; 2=Vel.1; 3=Vel.2; 4=Vel.3; 5=Vel.4; 6=Vel.5; 7=Vel.6; 8=Vel.7; 9=Vel.Auto",
            "reg_split": "09",
            "variable_name": "FAN_SPEED",
            "type": "ac",
        },
        {
            "register_name": "REG_SPLIT_09_READ_AIR_IN ",
            "address": 283,
            "description": "Unit Input Air Temperature: (hundredths of degrees Celsius) es: 2350 = 23.50 \u00b0C",
            "reg_split": "09",
            "variable_name": "AIR_IN",
            "type": "ac",
        },
        {
            "register_name": "REG_SPLIT_09_READ_STATUS ",
            "address": 284,
            "description": "Diagnostic Split Comunication Status: Bit 0=Unit not connected on the bus; Bit 1=Unit connected on the bus; Bit 2=Unit connected on the bus but offline; Bit 3=Unit in error.",
            "reg_split": "09",
            "variable_name": "STATUS",
            "type": "ac",
        },
        {
            "register_name": "REG_SPLIT_09_AHU_MODE ",
            "address": 285,
            "description": "AHU State 16 = Ventilation 32=Automatic ",
            "reg_split": "09",
            "variable_name": None,
            "type": "ac",
        },
        {
            "register_name": "REG_SPLIT_09_READ_HEATER_PWR ",
            "address": 286,
            "description": "Heater State 0 = OFF; 1 = ON ",
            "reg_split": "09",
            "variable_name": "HEATER_PWR",
            "type": "ac",
        },
        {
            "register_name": "REG_SPLIT_09_READ_HUMI ",
            "address": 287,
            "description": "Humidity 0..100% ",
            "reg_split": "09",
            "variable_name": "HUMI",
            "type": "ac",
        },
    ],
    "10": [
        {
            "register_name": "REG_SPLIT_10_READ_PWR ",
            "address": 290,
            "description": "Unit Power On/Off 0=OFF 1=ON",
            "reg_split": "10",
            "variable_name": "PWR",
            "type": "ac",
        },
        {
            "register_name": "REG_SPLIT_10_READ_SP_ROOM ",
            "address": 291,
            "description": 'Unit SetPoint: (hundredths of degrees Celsius) es: 2350 = 23.50 \u00b0C -> Range: 18..30\u00b0C"',
            "reg_split": "10",
            "variable_name": "SP_ROOM",
            "type": "ac",
        },
        {
            "register_name": "REG_SPLIT_10_READ_FAN_SPEED ",
            "address": 292,
            "description": "Unit Fan Speed (with Syxthsense): 1=Vel.Night; 2=Vel.1; 3=Vel.2; 4=Vel.3; 5=Vel.4; 7=Vel.5; 8=Vel.6; 9=Vel.Auto Unit Fan Speed (in other case): 1=Vel.Night; 2=Vel.1; 3=Vel.2; 4=Vel.3; 5=Vel.4; 6=Vel.5; 7=Vel.6; 8=Vel.7; 9=Vel.Auto",
            "reg_split": "10",
            "variable_name": "FAN_SPEED",
            "type": "ac",
        },
        {
            "register_name": "REG_SPLIT_10_READ_AIR_IN ",
            "address": 293,
            "description": "Unit Input Air Temperature: (hundredths of degrees Celsius) es: 2350 = 23.50 \u00b0C",
            "reg_split": "10",
            "variable_name": "AIR_IN",
            "type": "ac",
        },
        {
            "register_name": "REG_SPLIT_10_READ_STATUS ",
            "address": 294,
            "description": "Diagnostic Split Comunication Status: Bit 0=Unit not connected on the bus; Bit 1=Unit connected on the bus; Bit 2=Unit connected on the bus but offline; Bit 3=Unit in error.",
            "reg_split": "10",
            "variable_name": "STATUS",
            "type": "ac",
        },
        {
            "register_name": "REG_SPLIT_10_AHU_MODE ",
            "address": 295,
            "description": "AHU State 16 = Ventilation 32=Automatic ",
            "reg_split": "10",
            "variable_name": None,
            "type": "ac",
        },
        {
            "register_name": "REG_SPLIT_10_READ_HEATER_PWR ",
            "address": 296,
            "description": "Heater State 0 = OFF; 1 = ON ",
            "reg_split": "10",
            "variable_name": "HEATER_PWR",
            "type": "ac",
        },
        {
            "register_name": "REG_SPLIT_10_READ_HUMI ",
            "address": 297,
            "description": "Humidity 0..100% ",
            "reg_split": "10",
            "variable_name": "HUMI",
            "type": "ac",
        },
    ],
    "11": [
        {
            "register_name": "REG_SPLIT_11_READ_PWR ",
            "address": 300,
            "description": "Unit Power On/Off 0=OFF 1=ON",
            "reg_split": "11",
            "variable_name": "PWR",
            "type": "ac",
        },
        {
            "register_name": "REG_SPLIT_11_READ_SP_ROOM ",
            "address": 301,
            "description": 'Unit SetPoint: (hundredths of degrees Celsius) es: 2350 = 23.50 \u00b0C -> Range: 18..30\u00b0C"',
            "reg_split": "11",
            "variable_name": "SP_ROOM",
            "type": "ac",
        },
        {
            "register_name": "REG_SPLIT_11_READ_FAN_SPEED ",
            "address": 302,
            "description": "Unit Fan Speed (with Syxthsense): 1=Vel.Night; 2=Vel.1; 3=Vel.2; 4=Vel.3; 5=Vel.4; 7=Vel.5; 8=Vel.6; 9=Vel.Auto Unit Fan Speed (in other case): 1=Vel.Night; 2=Vel.1; 3=Vel.2; 4=Vel.3; 5=Vel.4; 6=Vel.5; 7=Vel.6; 8=Vel.7; 9=Vel.Auto",
            "reg_split": "11",
            "variable_name": "FAN_SPEED",
            "type": "ac",
        },
        {
            "register_name": "REG_SPLIT_11_READ_AIR_IN ",
            "address": 303,
            "description": "Unit Input Air Temperature: (hundredths of degrees Celsius) es: 2350 = 23.50 \u00b0C",
            "reg_split": "11",
            "variable_name": "AIR_IN",
            "type": "ac",
        },
        {
            "register_name": "REG_SPLIT_11_READ_STATUS ",
            "address": 304,
            "description": "Diagnostic Split Comunication Status: Bit 0=Unit not connected on the bus; Bit 1=Unit connected on the bus; Bit 2=Unit connected on the bus but offline; Bit 3=Unit in error.",
            "reg_split": "11",
            "variable_name": "STATUS",
            "type": "ac",
        },
        {
            "register_name": "REG_SPLIT_11_AHU_MODE ",
            "address": 305,
            "description": "AHU State 16 = Ventilation 32=Automatic ",
            "reg_split": "11",
            "variable_name": None,
            "type": "ac",
        },
        {
            "register_name": "REG_SPLIT_11_READ_HEATER_PWR ",
            "address": 306,
            "description": "Heater State 0 = OFF; 1 = ON ",
            "reg_split": "11",
            "variable_name": "HEATER_PWR",
            "type": "ac",
        },
        {
            "register_name": "REG_SPLIT_11_READ_HUMI ",
            "address": 307,
            "description": "Humidity 0..100% ",
            "reg_split": "11",
            "variable_name": "HUMI",
            "type": "ac",
        },
    ],
    "12": [
        {
            "register_name": "REG_SPLIT_12_READ_PWR ",
            "address": 310,
            "description": "Unit Power On/Off 0=OFF 1=ON",
            "reg_split": "12",
            "variable_name": "PWR",
            "type": "ac",
        },
        {
            "register_name": "REG_SPLIT_12_READ_SP_ROOM ",
            "address": 311,
            "description": 'Unit SetPoint: (hundredths of degrees Celsius) es: 2350 = 23.50 \u00b0C -> Range: 18..30\u00b0C"',
            "reg_split": "12",
            "variable_name": "SP_ROOM",
            "type": "ac",
        },
        {
            "register_name": "REG_SPLIT_12_READ_FAN_SPEED ",
            "address": 312,
            "description": "Unit Fan Speed (with Syxthsense): 1=Vel.Night; 2=Vel.1; 3=Vel.2; 4=Vel.3; 5=Vel.4; 7=Vel.5; 8=Vel.6; 9=Vel.Auto Unit Fan Speed (in other case): 1=Vel.Night; 2=Vel.1; 3=Vel.2; 4=Vel.3; 5=Vel.4; 6=Vel.5; 7=Vel.6; 8=Vel.7; 9=Vel.Auto",
            "reg_split": "12",
            "variable_name": "FAN_SPEED",
            "type": "ac",
        },
        {
            "register_name": "REG_SPLIT_12_READ_AIR_IN ",
            "address": 313,
            "description": "Unit Input Air Temperature: (hundredths of degrees Celsius) es: 2350 = 23.50 \u00b0C",
            "reg_split": "12",
            "variable_name": "AIR_IN",
            "type": "ac",
        },
        {
            "register_name": "REG_SPLIT_12_READ_STATUS ",
            "address": 314,
            "description": "Diagnostic Split Comunication Status: Bit 0=Unit not connected on the bus; Bit 1=Unit connected on the bus; Bit 2=Unit connected on the bus but offline; Bit 3=Unit in error.",
            "reg_split": "12",
            "variable_name": "STATUS",
            "type": "ac",
        },
        {
            "register_name": "REG_SPLIT_12_AHU_MODE ",
            "address": 315,
            "description": "AHU State 16 = Ventilation 32=Automatic ",
            "reg_split": "12",
            "variable_name": None,
            "type": "ac",
        },
        {
            "register_name": "REG_SPLIT_12_READ_HEATER_PWR ",
            "address": 316,
            "description": "Heater State 0 = OFF; 1 = ON ",
            "reg_split": "12",
            "variable_name": "HEATER_PWR",
            "type": "ac",
        },
        {
            "register_name": "REG_SPLIT_12_READ_HUMI ",
            "address": 317,
            "description": "Humidity 0..100% ",
            "reg_split": "12",
            "variable_name": "HUMI",
            "type": "ac",
        },
    ],
    "13": [
        {
            "register_name": "REG_SPLIT_13_READ_PWR ",
            "address": 320,
            "description": "Unit Power On/Off 0=OFF 1=ON",
            "reg_split": "13",
            "variable_name": "PWR",
            "type": "ac",
        },
        {
            "register_name": "REG_SPLIT_13_READ_SP_ROOM ",
            "address": 321,
            "description": 'Unit SetPoint: (hundredths of degrees Celsius) es: 2350 = 23.50 \u00b0C -> Range: 18..30\u00b0C"',
            "reg_split": "13",
            "variable_name": "SP_ROOM",
            "type": "ac",
        },
        {
            "register_name": "REG_SPLIT_13_READ_FAN_SPEED ",
            "address": 322,
            "description": "Unit Fan Speed (with Syxthsense): 1=Vel.Night; 2=Vel.1; 3=Vel.2; 4=Vel.3; 5=Vel.4; 7=Vel.5; 8=Vel.6; 9=Vel.Auto Unit Fan Speed (in other case): 1=Vel.Night; 2=Vel.1; 3=Vel.2; 4=Vel.3; 5=Vel.4; 6=Vel.5; 7=Vel.6; 8=Vel.7; 9=Vel.Auto",
            "reg_split": "13",
            "variable_name": "FAN_SPEED",
            "type": "ac",
        },
        {
            "register_name": "REG_SPLIT_13_READ_AIR_IN ",
            "address": 323,
            "description": "Unit Input Air Temperature: (hundredths of degrees Celsius) es: 2350 = 23.50 \u00b0C",
            "reg_split": "13",
            "variable_name": "AIR_IN",
            "type": "ac",
        },
        {
            "register_name": "REG_SPLIT_13_READ_STATUS ",
            "address": 324,
            "description": "Diagnostic Split Comunication Status: Bit 0=Unit not connected on the bus; Bit 1=Unit connected on the bus; Bit 2=Unit connected on the bus but offline; Bit 3=Unit in error.",
            "reg_split": "13",
            "variable_name": "STATUS",
            "type": "ac",
        },
        {
            "register_name": "REG_SPLIT_13_AHU_MODE ",
            "address": 325,
            "description": "AHU State 16 = Ventilation 32=Automatic ",
            "reg_split": "13",
            "variable_name": None,
            "type": "ac",
        },
        {
            "register_name": "REG_SPLIT_13_READ_HEATER_PWR ",
            "address": 326,
            "description": "Heater State 0 = OFF; 1 = ON ",
            "reg_split": "13",
            "variable_name": "HEATER_PWR",
            "type": "ac",
        },
        {
            "register_name": "REG_SPLIT_13_READ_HUMI ",
            "address": 327,
            "description": "Humidity 0..100% ",
            "reg_split": "13",
            "variable_name": "HUMI",
            "type": "ac",
        },
    ],
    "14": [
        {
            "register_name": "REG_SPLIT_14_READ_PWR ",
            "address": 330,
            "description": "Unit Power On/Off 0=OFF 1=ON",
            "reg_split": "14",
            "variable_name": "PWR",
            "type": "ac",
        },
        {
            "register_name": "REG_SPLIT_14_READ_SP_ROOM ",
            "address": 331,
            "description": 'Unit SetPoint: (hundredths of degrees Celsius) es: 2350 = 23.50 \u00b0C -> Range: 18..30\u00b0C"',
            "reg_split": "14",
            "variable_name": "SP_ROOM",
            "type": "ac",
        },
        {
            "register_name": "REG_SPLIT_14_READ_FAN_SPEED ",
            "address": 332,
            "description": "Unit Fan Speed (with Syxthsense): 1=Vel.Night; 2=Vel.1; 3=Vel.2; 4=Vel.3; 5=Vel.4; 7=Vel.5; 8=Vel.6; 9=Vel.Auto Unit Fan Speed (in other case): 1=Vel.Night; 2=Vel.1; 3=Vel.2; 4=Vel.3; 5=Vel.4; 6=Vel.5; 7=Vel.6; 8=Vel.7; 9=Vel.Auto",
            "reg_split": "14",
            "variable_name": "FAN_SPEED",
            "type": "ac",
        },
        {
            "register_name": "REG_SPLIT_14_READ_AIR_IN ",
            "address": 333,
            "description": "Unit Input Air Temperature: (hundredths of degrees Celsius) es: 2350 = 23.50 \u00b0C",
            "reg_split": "14",
            "variable_name": "AIR_IN",
            "type": "ac",
        },
        {
            "register_name": "REG_SPLIT_14_READ_STATUS ",
            "address": 334,
            "description": "Diagnostic Split Comunication Status: Bit 0=Unit not connected on the bus; Bit 1=Unit connected on the bus; Bit 2=Unit connected on the bus but offline; Bit 3=Unit in error.",
            "reg_split": "14",
            "variable_name": "STATUS",
            "type": "ac",
        },
        {
            "register_name": "REG_SPLIT_14_AHU_MODE ",
            "address": 335,
            "description": "AHU State 16 = Ventilation 32=Automatic ",
            "reg_split": "14",
            "variable_name": None,
            "type": "ac",
        },
        {
            "register_name": "REG_SPLIT_14_READ_HEATER_PWR ",
            "address": 336,
            "description": "Heater State 0 = OFF; 1 = ON ",
            "reg_split": "14",
            "variable_name": "HEATER_PWR",
            "type": "ac",
        },
        {
            "register_name": "REG_SPLIT_14_READ_HUMI ",
            "address": 337,
            "description": "Humidity 0..100% ",
            "reg_split": "14",
            "variable_name": "HUMI",
            "type": "ac",
        },
    ],
    "15": [
        {
            "register_name": "REG_SPLIT_15_READ_PWR ",
            "address": 340,
            "description": "Unit Power On/Off 0=OFF 1=ON",
            "reg_split": "15",
            "variable_name": "PWR",
            "type": "ac",
        },
        {
            "register_name": "REG_SPLIT_15_READ_SP_ROOM ",
            "address": 341,
            "description": 'Unit SetPoint: (hundredths of degrees Celsius) es: 2350 = 23.50 \u00b0C -> Range: 18..30\u00b0C"',
            "reg_split": "15",
            "variable_name": "SP_ROOM",
            "type": "ac",
        },
        {
            "register_name": "REG_SPLIT_15_READ_FAN_SPEED ",
            "address": 342,
            "description": "Unit Fan Speed (with Syxthsense): 1=Vel.Night; 2=Vel.1; 3=Vel.2; 4=Vel.3; 5=Vel.4; 7=Vel.5; 8=Vel.6; 9=Vel.Auto Unit Fan Speed (in other case): 1=Vel.Night; 2=Vel.1; 3=Vel.2; 4=Vel.3; 5=Vel.4; 6=Vel.5; 7=Vel.6; 8=Vel.7; 9=Vel.Auto",
            "reg_split": "15",
            "variable_name": "FAN_SPEED",
            "type": "ac",
        },
        {
            "register_name": "REG_SPLIT_15_READ_AIR_IN ",
            "address": 343,
            "description": "Unit Input Air Temperature: (hundredths of degrees Celsius) es: 2350 = 23.50 \u00b0C",
            "reg_split": "15",
            "variable_name": "AIR_IN",
            "type": "ac",
        },
        {
            "register_name": "REG_SPLIT_15_READ_STATUS ",
            "address": 344,
            "description": "Diagnostic Split Comunication Status: Bit 0=Unit not connected on the bus; Bit 1=Unit connected on the bus; Bit 2=Unit connected on the bus but offline; Bit 3=Unit in error.",
            "reg_split": "15",
            "variable_name": "STATUS",
            "type": "ac",
        },
        {
            "register_name": "REG_SPLIT_15_AHU_MODE ",
            "address": 345,
            "description": "AHU State 16 = Ventilation 32=Automatic ",
            "reg_split": "15",
            "variable_name": None,
            "type": "ac",
        },
        {
            "register_name": "REG_SPLIT_15_READ_HEATER_PWR ",
            "address": 346,
            "description": "Heater State 0 = OFF; 1 = ON ",
            "reg_split": "15",
            "variable_name": "HEATER_PWR",
            "type": "ac",
        },
        {
            "register_name": "REG_SPLIT_15_READ_HUMI ",
            "address": 347,
            "description": "Humidity 0..100% ",
            "reg_split": "15",
            "variable_name": "HUMI",
            "type": "ac",
        },
    ],
    "16": [
        {
            "register_name": "REG_SPLIT_16_READ_PWR ",
            "address": 350,
            "description": "Unit Power On/Off 0=OFF 1=ON",
            "reg_split": "16",
            "variable_name": "PWR",
            "type": "ac",
        },
        {
            "register_name": "REG_SPLIT_16_READ_SP_ROOM ",
            "address": 351,
            "description": 'Unit SetPoint: (hundredths of degrees Celsius) es: 2350 = 23.50 \u00b0C -> Range: 18..30\u00b0C"',
            "reg_split": "16",
            "variable_name": "SP_ROOM",
            "type": "ac",
        },
        {
            "register_name": "REG_SPLIT_16_READ_FAN_SPEED ",
            "address": 352,
            "description": "Unit Fan Speed (with Syxthsense): 1=Vel.Night; 2=Vel.1; 3=Vel.2; 4=Vel.3; 5=Vel.4; 7=Vel.5; 8=Vel.6; 9=Vel.Auto Unit Fan Speed (in other case): 1=Vel.Night; 2=Vel.1; 3=Vel.2; 4=Vel.3; 5=Vel.4; 6=Vel.5; 7=Vel.6; 8=Vel.7; 9=Vel.Auto",
            "reg_split": "16",
            "variable_name": "FAN_SPEED",
            "type": "ac",
        },
        {
            "register_name": "REG_SPLIT_16_READ_AIR_IN ",
            "address": 353,
            "description": "Unit Input Air Temperature: (hundredths of degrees Celsius) es: 2350 = 23.50 \u00b0C",
            "reg_split": "16",
            "variable_name": "AIR_IN",
            "type": "ac",
        },
        {
            "register_name": "REG_SPLIT_16_READ_STATUS ",
            "address": 354,
            "description": "Diagnostic Split Comunication Status: Bit 0=Unit not connected on the bus; Bit 1=Unit connected on the bus; Bit 2=Unit connected on the bus but offline; Bit 3=Unit in error.",
            "reg_split": "16",
            "variable_name": "STATUS",
            "type": "ac",
        },
        {
            "register_name": "REG_SPLIT_16_AHU_MODE ",
            "address": 355,
            "description": "AHU State 16 = Ventilation 32=Automatic ",
            "reg_split": "16",
            "variable_name": None,
            "type": "ac",
        },
        {
            "register_name": "REG_SPLIT_16_READ_HEATER_PWR ",
            "address": 356,
            "description": "Heater State 0 = OFF; 1 = ON ",
            "reg_split": "16",
            "variable_name": "HEATER_PWR",
            "type": "ac",
        },
        {
            "register_name": "REG_SPLIT_16_READ_HUMI ",
            "address": 357,
            "description": "Humidity 0..100% ",
            "reg_split": "16",
            "variable_name": "HUMI",
            "type": "ac",
        },
    ],
    "17": [
        {
            "register_name": "REG_SPLIT_17_READ_PWR ",
            "address": 360,
            "description": "Unit Power On/Off 0=OFF 1=ON",
            "reg_split": "17",
            "variable_name": "PWR",
            "type": "ac",
        },
        {
            "register_name": "REG_SPLIT_17_READ_SP_ROOM ",
            "address": 361,
            "description": 'Unit SetPoint: (hundredths of degrees Celsius) es: 2350 = 23.50 \u00b0C -> Range: 18..30\u00b0C"',
            "reg_split": "17",
            "variable_name": "SP_ROOM",
            "type": "ac",
        },
        {
            "register_name": "REG_SPLIT_17_READ_FAN_SPEED ",
            "address": 362,
            "description": "Unit Fan Speed (with Syxthsense): 1=Vel.Night; 2=Vel.1; 3=Vel.2; 4=Vel.3; 5=Vel.4; 7=Vel.5; 8=Vel.6; 9=Vel.Auto Unit Fan Speed (in other case): 1=Vel.Night; 2=Vel.1; 3=Vel.2; 4=Vel.3; 5=Vel.4; 6=Vel.5; 7=Vel.6; 8=Vel.7; 9=Vel.Auto",
            "reg_split": "17",
            "variable_name": "FAN_SPEED",
            "type": "ac",
        },
        {
            "register_name": "REG_SPLIT_17_READ_AIR_IN ",
            "address": 363,
            "description": "Unit Input Air Temperature: (hundredths of degrees Celsius) es: 2350 = 23.50 \u00b0C",
            "reg_split": "17",
            "variable_name": "AIR_IN",
            "type": "ac",
        },
        {
            "register_name": "REG_SPLIT_17_READ_STATUS ",
            "address": 364,
            "description": "Diagnostic Split Comunication Status: Bit 0=Unit not connected on the bus; Bit 1=Unit connected on the bus; Bit 2=Unit connected on the bus but offline; Bit 3=Unit in error.",
            "reg_split": "17",
            "variable_name": "STATUS",
            "type": "ac",
        },
        {
            "register_name": "REG_SPLIT_17_AHU_MODE ",
            "address": 365,
            "description": "AHU State 16 = Ventilation 32=Automatic ",
            "reg_split": "17",
            "variable_name": None,
            "type": "ac",
        },
        {
            "register_name": "REG_SPLIT_17_READ_HEATER_PWR ",
            "address": 366,
            "description": "Heater State 0 = OFF; 1 = ON ",
            "reg_split": "17",
            "variable_name": "HEATER_PWR",
            "type": "ac",
        },
        {
            "register_name": "REG_SPLIT_17_READ_HUMI ",
            "address": 367,
            "description": "Humidity 0..100% ",
            "reg_split": "17",
            "variable_name": "HUMI",
            "type": "ac",
        },
    ],
    "18": [
        {
            "register_name": "REG_SPLIT_18_READ_PWR ",
            "address": 370,
            "description": "Unit Power On/Off 0=OFF 1=ON",
            "reg_split": "18",
            "variable_name": "PWR",
            "type": "ac",
        },
        {
            "register_name": "REG_SPLIT_18_READ_SP_ROOM ",
            "address": 371,
            "description": 'Unit SetPoint: (hundredths of degrees Celsius) es: 2350 = 23.50 \u00b0C -> Range: 18..30\u00b0C"',
            "reg_split": "18",
            "variable_name": "SP_ROOM",
            "type": "ac",
        },
        {
            "register_name": "REG_SPLIT_18_READ_FAN_SPEED ",
            "address": 372,
            "description": "Unit Fan Speed (with Syxthsense): 1=Vel.Night; 2=Vel.1; 3=Vel.2; 4=Vel.3; 5=Vel.4; 7=Vel.5; 8=Vel.6; 9=Vel.Auto Unit Fan Speed (in other case): 1=Vel.Night; 2=Vel.1; 3=Vel.2; 4=Vel.3; 5=Vel.4; 6=Vel.5; 7=Vel.6; 8=Vel.7; 9=Vel.Auto",
            "reg_split": "18",
            "variable_name": "FAN_SPEED",
            "type": "ac",
        },
        {
            "register_name": "REG_SPLIT_18_READ_AIR_IN ",
            "address": 373,
            "description": "Unit Input Air Temperature: (hundredths of degrees Celsius) es: 2350 = 23.50 \u00b0C",
            "reg_split": "18",
            "variable_name": "AIR_IN",
            "type": "ac",
        },
        {
            "register_name": "REG_SPLIT_18_READ_STATUS ",
            "address": 374,
            "description": "Diagnostic Split Comunication Status: Bit 0=Unit not connected on the bus; Bit 1=Unit connected on the bus; Bit 2=Unit connected on the bus but offline; Bit 3=Unit in error.",
            "reg_split": "18",
            "variable_name": "STATUS",
            "type": "ac",
        },
        {
            "register_name": "REG_SPLIT_18_AHU_MODE ",
            "address": 375,
            "description": "AHU State 16 = Ventilation 32=Automatic ",
            "reg_split": "18",
            "variable_name": None,
            "type": "ac",
        },
        {
            "register_name": "REG_SPLIT_18_READ_HEATER_PWR ",
            "address": 376,
            "description": "Heater State 0 = OFF; 1 = ON ",
            "reg_split": "18",
            "variable_name": "HEATER_PWR",
            "type": "ac",
        },
        {
            "register_name": "REG_SPLIT_18_READ_HUMI ",
            "address": 377,
            "description": "Humidity 0..100% ",
            "reg_split": "18",
            "variable_name": "HUMI",
            "type": "ac",
        },
    ],
    "19": [
        {
            "register_name": "REG_SPLIT_19_READ_PWR ",
            "address": 380,
            "description": "Unit Power On/Off 0=OFF 1=ON",
            "reg_split": "19",
            "variable_name": "PWR",
            "type": "ac",
        },
        {
            "register_name": "REG_SPLIT_19_READ_SP_ROOM ",
            "address": 381,
            "description": 'Unit SetPoint: (hundredths of degrees Celsius) es: 2350 = 23.50 \u00b0C -> Range: 18..30\u00b0C"',
            "reg_split": "19",
            "variable_name": "SP_ROOM",
            "type": "ac",
        },
        {
            "register_name": "REG_SPLIT_19_READ_FAN_SPEED ",
            "address": 382,
            "description": "Unit Fan Speed (with Syxthsense): 1=Vel.Night; 2=Vel.1; 3=Vel.2; 4=Vel.3; 5=Vel.4; 7=Vel.5; 8=Vel.6; 9=Vel.Auto Unit Fan Speed (in other case): 1=Vel.Night; 2=Vel.1; 3=Vel.2; 4=Vel.3; 5=Vel.4; 6=Vel.5; 7=Vel.6; 8=Vel.7; 9=Vel.Auto",
            "reg_split": "19",
            "variable_name": "FAN_SPEED",
            "type": "ac",
        },
        {
            "register_name": "REG_SPLIT_19_READ_AIR_IN ",
            "address": 383,
            "description": "Unit Input Air Temperature: (hundredths of degrees Celsius) es: 2350 = 23.50 \u00b0C",
            "reg_split": "19",
            "variable_name": "AIR_IN",
            "type": "ac",
        },
        {
            "register_name": "REG_SPLIT_19_READ_STATUS ",
            "address": 384,
            "description": "Diagnostic Split Comunication Status: Bit 0=Unit not connected on the bus; Bit 1=Unit connected on the bus; Bit 2=Unit connected on the bus but offline; Bit 3=Unit in error.",
            "reg_split": "19",
            "variable_name": "STATUS",
            "type": "ac",
        },
        {
            "register_name": "REG_SPLIT_19_AHU_MODE ",
            "address": 385,
            "description": "AHU State 16 = Ventilation 32=Automatic ",
            "reg_split": "19",
            "variable_name": None,
            "type": "ac",
        },
        {
            "register_name": "REG_SPLIT_19_READ_HEATER_PWR ",
            "address": 386,
            "description": "Heater State 0 = OFF; 1 = ON ",
            "reg_split": "19",
            "variable_name": "HEATER_PWR",
            "type": "ac",
        },
        {
            "register_name": "REG_SPLIT_19_READ_HUMI ",
            "address": 387,
            "description": "Humidity 0..100% ",
            "reg_split": "19",
            "variable_name": "HUMI",
            "type": "ac",
        },
    ],
    "20": [
        {
            "register_name": "REG_SPLIT_20_READ_PWR ",
            "address": 390,
            "description": "Unit Power On/Off 0=OFF 1=ON",
            "reg_split": "20",
            "variable_name": "PWR",
            "type": "ac",
        },
        {
            "register_name": "REG_SPLIT_20_READ_SP_ROOM ",
            "address": 391,
            "description": 'Unit SetPoint: (hundredths of degrees Celsius) es: 2350 = 23.50 \u00b0C -> Range: 18..30\u00b0C"',
            "reg_split": "20",
            "variable_name": "SP_ROOM",
            "type": "ac",
        },
        {
            "register_name": "REG_SPLIT_20_READ_FAN_SPEED ",
            "address": 392,
            "description": "Unit Fan Speed (with Syxthsense): 1=Vel.Night; 2=Vel.1; 3=Vel.2; 4=Vel.3; 5=Vel.4; 7=Vel.5; 8=Vel.6; 9=Vel.Auto Unit Fan Speed (in other case): 1=Vel.Night; 2=Vel.1; 3=Vel.2; 4=Vel.3; 5=Vel.4; 6=Vel.5; 7=Vel.6; 8=Vel.7; 9=Vel.Auto",
            "reg_split": "20",
            "variable_name": "FAN_SPEED",
            "type": "ac",
        },
        {
            "register_name": "REG_SPLIT_20_READ_AIR_IN ",
            "address": 393,
            "description": "Unit Input Air Temperature: (hundredths of degrees Celsius) es: 2350 = 23.50 \u00b0C",
            "reg_split": "20",
            "variable_name": "AIR_IN",
            "type": "ac",
        },
        {
            "register_name": "REG_SPLIT_20_READ_STATUS ",
            "address": 394,
            "description": "Diagnostic Split Comunication Status: Bit 0=Unit not connected on the bus; Bit 1=Unit connected on the bus; Bit 2=Unit connected on the bus but offline; Bit 3=Unit in error.",
            "reg_split": "20",
            "variable_name": "STATUS",
            "type": "ac",
        },
        {
            "register_name": "REG_SPLIT_20_AHU_MODE ",
            "address": 395,
            "description": "AHU State 16 = Ventilation 32=Automatic ",
            "reg_split": "20",
            "variable_name": None,
            "type": "ac",
        },
        {
            "register_name": "REG_SPLIT_20_READ_HEATER_PWR ",
            "address": 396,
            "description": "Heater State 0 = OFF; 1 = ON ",
            "reg_split": "20",
            "variable_name": "HEATER_PWR",
            "type": "ac",
        },
        {
            "register_name": "REG_SPLIT_20_READ_HUMI ",
            "address": 397,
            "description": "Humidity 0..100% ",
            "reg_split": "20",
            "variable_name": "HUMI",
            "type": "ac",
        },
    ],
    "21": [
        {
            "register_name": "REG_SPLIT_21_READ_PWR ",
            "address": 400,
            "description": "Unit Power On/Off 0=OFF 1=ON",
            "reg_split": "21",
            "variable_name": "PWR",
            "type": "ac",
        },
        {
            "register_name": "REG_SPLIT_21_READ_SP_ROOM ",
            "address": 401,
            "description": 'Unit SetPoint: (hundredths of degrees Celsius) es: 2350 = 23.50 \u00b0C -> Range: 18..30\u00b0C"',
            "reg_split": "21",
            "variable_name": "SP_ROOM",
            "type": "ac",
        },
        {
            "register_name": "REG_SPLIT_21_READ_FAN_SPEED ",
            "address": 402,
            "description": "Unit Fan Speed (with Syxthsense): 1=Vel.Night; 2=Vel.1; 3=Vel.2; 4=Vel.3; 5=Vel.4; 7=Vel.5; 8=Vel.6; 9=Vel.Auto Unit Fan Speed (in other case): 1=Vel.Night; 2=Vel.1; 3=Vel.2; 4=Vel.3; 5=Vel.4; 6=Vel.5; 7=Vel.6; 8=Vel.7; 9=Vel.Auto",
            "reg_split": "21",
            "variable_name": "FAN_SPEED",
            "type": "ac",
        },
        {
            "register_name": "REG_SPLIT_21_READ_AIR_IN ",
            "address": 403,
            "description": "Unit Input Air Temperature: (hundredths of degrees Celsius) es: 2350 = 23.50 \u00b0C",
            "reg_split": "21",
            "variable_name": "AIR_IN",
            "type": "ac",
        },
        {
            "register_name": "REG_SPLIT_21_READ_STATUS ",
            "address": 404,
            "description": "Diagnostic Split Comunication Status: Bit 0=Unit not connected on the bus; Bit 1=Unit connected on the bus; Bit 2=Unit connected on the bus but offline; Bit 3=Unit in error.",
            "reg_split": "21",
            "variable_name": "STATUS",
            "type": "ac",
        },
        {
            "register_name": "REG_SPLIT_21_AHU_MODE ",
            "address": 405,
            "description": "AHU State 16 = Ventilation 32=Automatic ",
            "reg_split": "21",
            "variable_name": None,
            "type": "ac",
        },
        {
            "register_name": "REG_SPLIT_21_READ_HEATER_PWR ",
            "address": 406,
            "description": "Heater State 0 = OFF; 1 = ON ",
            "reg_split": "21",
            "variable_name": "HEATER_PWR",
            "type": "ac",
        },
        {
            "register_name": "REG_SPLIT_21_READ_HUMI ",
            "address": 407,
            "description": "Humidity 0..100% ",
            "reg_split": "21",
            "variable_name": "HUMI",
            "type": "ac",
        },
    ],
    "22": [
        {
            "register_name": "REG_SPLIT_22_READ_PWR ",
            "address": 410,
            "description": "Unit Power On/Off 0=OFF 1=ON",
            "reg_split": "22",
            "variable_name": "PWR",
            "type": "ac",
        },
        {
            "register_name": "REG_SPLIT_22_READ_SP_ROOM ",
            "address": 411,
            "description": 'Unit SetPoint: (hundredths of degrees Celsius) es: 2350 = 23.50 \u00b0C -> Range: 18..30\u00b0C"',
            "reg_split": "22",
            "variable_name": "SP_ROOM",
            "type": "ac",
        },
        {
            "register_name": "REG_SPLIT_22_READ_FAN_SPEED ",
            "address": 412,
            "description": "Unit Fan Speed (with Syxthsense): 1=Vel.Night; 2=Vel.1; 3=Vel.2; 4=Vel.3; 5=Vel.4; 7=Vel.5; 8=Vel.6; 9=Vel.Auto Unit Fan Speed (in other case): 1=Vel.Night; 2=Vel.1; 3=Vel.2; 4=Vel.3; 5=Vel.4; 6=Vel.5; 7=Vel.6; 8=Vel.7; 9=Vel.Auto",
            "reg_split": "22",
            "variable_name": "FAN_SPEED",
            "type": "ac",
        },
        {
            "register_name": "REG_SPLIT_22_READ_AIR_IN ",
            "address": 413,
            "description": "Unit Input Air Temperature: (hundredths of degrees Celsius) es: 2350 = 23.50 \u00b0C",
            "reg_split": "22",
            "variable_name": "AIR_IN",
            "type": "ac",
        },
        {
            "register_name": "REG_SPLIT_22_READ_STATUS ",
            "address": 414,
            "description": "Diagnostic Split Comunication Status: Bit 0=Unit not connected on the bus; Bit 1=Unit connected on the bus; Bit 2=Unit connected on the bus but offline; Bit 3=Unit in error.",
            "reg_split": "22",
            "variable_name": "STATUS",
            "type": "ac",
        },
        {
            "register_name": "REG_SPLIT_22_AHU_MODE ",
            "address": 415,
            "description": "AHU State 16 = Ventilation 32=Automatic ",
            "reg_split": "22",
            "variable_name": None,
            "type": "ac",
        },
        {
            "register_name": "REG_SPLIT_22_READ_HEATER_PWR ",
            "address": 416,
            "description": "Heater State 0 = OFF; 1 = ON ",
            "reg_split": "22",
            "variable_name": "HEATER_PWR",
            "type": "ac",
        },
        {
            "register_name": "REG_SPLIT_22_READ_HUMI ",
            "address": 417,
            "description": "Humidity 0..100% ",
            "reg_split": "22",
            "variable_name": "HUMI",
            "type": "ac",
        },
    ],
    "23": [
        {
            "register_name": "REG_SPLIT_23_READ_PWR ",
            "address": 420,
            "description": "Unit Power On/Off 0=OFF 1=ON",
            "reg_split": "23",
            "variable_name": "PWR",
            "type": "ac",
        },
        {
            "register_name": "REG_SPLIT_23_READ_SP_ROOM ",
            "address": 421,
            "description": 'Unit SetPoint: (hundredths of degrees Celsius) es: 2350 = 23.50 \u00b0C -> Range: 18..30\u00b0C"',
            "reg_split": "23",
            "variable_name": "SP_ROOM",
            "type": "ac",
        },
        {
            "register_name": "REG_SPLIT_23_READ_FAN_SPEED ",
            "address": 422,
            "description": "Unit Fan Speed (with Syxthsense): 1=Vel.Night; 2=Vel.1; 3=Vel.2; 4=Vel.3; 5=Vel.4; 7=Vel.5; 8=Vel.6; 9=Vel.Auto Unit Fan Speed (in other case): 1=Vel.Night; 2=Vel.1; 3=Vel.2; 4=Vel.3; 5=Vel.4; 6=Vel.5; 7=Vel.6; 8=Vel.7; 9=Vel.Auto",
            "reg_split": "23",
            "variable_name": "FAN_SPEED",
            "type": "ac",
        },
        {
            "register_name": "REG_SPLIT_23_READ_AIR_IN ",
            "address": 423,
            "description": "Unit Input Air Temperature: (hundredths of degrees Celsius) es: 2350 = 23.50 \u00b0C",
            "reg_split": "23",
            "variable_name": "AIR_IN",
            "type": "ac",
        },
        {
            "register_name": "REG_SPLIT_23_READ_STATUS ",
            "address": 424,
            "description": "Diagnostic Split Comunication Status: Bit 0=Unit not connected on the bus; Bit 1=Unit connected on the bus; Bit 2=Unit connected on the bus but offline; Bit 3=Unit in error.",
            "reg_split": "23",
            "variable_name": "STATUS",
            "type": "ac",
        },
        {
            "register_name": "REG_SPLIT_23_AHU_MODE ",
            "address": 425,
            "description": "AHU State 16 = Ventilation 32=Automatic ",
            "reg_split": "23",
            "variable_name": None,
            "type": "ac",
        },
        {
            "register_name": "REG_SPLIT_23_READ_HEATER_PWR ",
            "address": 426,
            "description": "Heater State 0 = OFF; 1 = ON ",
            "reg_split": "23",
            "variable_name": "HEATER_PWR",
            "type": "ac",
        },
        {
            "register_name": "REG_SPLIT_23_READ_HUMI ",
            "address": 427,
            "description": "Humidity 0..100% ",
            "reg_split": "23",
            "variable_name": "HUMI",
            "type": "ac",
        },
    ],
    "24": [
        {
            "register_name": "REG_SPLIT_24_READ_PWR ",
            "address": 430,
            "description": "Unit Power On/Off 0=OFF 1=ON",
            "reg_split": "24",
            "variable_name": "PWR",
            "type": "ac",
        },
        {
            "register_name": "REG_SPLIT_24_READ_SP_ROOM ",
            "address": 431,
            "description": 'Unit SetPoint: (hundredths of degrees Celsius) es: 2350 = 23.50 \u00b0C -> Range: 18..30\u00b0C"',
            "reg_split": "24",
            "variable_name": "SP_ROOM",
            "type": "ac",
        },
        {
            "register_name": "REG_SPLIT_24_READ_FAN_SPEED ",
            "address": 432,
            "description": "Unit Fan Speed (with Syxthsense): 1=Vel.Night; 2=Vel.1; 3=Vel.2; 4=Vel.3; 5=Vel.4; 7=Vel.5; 8=Vel.6; 9=Vel.Auto Unit Fan Speed (in other case): 1=Vel.Night; 2=Vel.1; 3=Vel.2; 4=Vel.3; 5=Vel.4; 6=Vel.5; 7=Vel.6; 8=Vel.7; 9=Vel.Auto",
            "reg_split": "24",
            "variable_name": "FAN_SPEED",
            "type": "ac",
        },
        {
            "register_name": "REG_SPLIT_24_READ_AIR_IN ",
            "address": 433,
            "description": "Unit Input Air Temperature: (hundredths of degrees Celsius) es: 2350 = 23.50 \u00b0C",
            "reg_split": "24",
            "variable_name": "AIR_IN",
            "type": "ac",
        },
        {
            "register_name": "REG_SPLIT_24_READ_STATUS ",
            "address": 434,
            "description": "Diagnostic Split Comunication Status: Bit 0=Unit not connected on the bus; Bit 1=Unit connected on the bus; Bit 2=Unit connected on the bus but offline; Bit 3=Unit in error.",
            "reg_split": "24",
            "variable_name": "STATUS",
            "type": "ac",
        },
        {
            "register_name": "REG_SPLIT_24_AHU_MODE ",
            "address": 435,
            "description": "AHU State 16 = Ventilation 32=Automatic ",
            "reg_split": "24",
            "variable_name": None,
            "type": "ac",
        },
        {
            "register_name": "REG_SPLIT_24_READ_HEATER_PWR ",
            "address": 436,
            "description": "Heater State 0 = OFF; 1 = ON ",
            "reg_split": "24",
            "variable_name": "HEATER_PWR",
            "type": "ac",
        },
        {
            "register_name": "REG_SPLIT_24_READ_HUMI ",
            "address": 437,
            "description": "Humidity 0..100% ",
            "reg_split": "24",
            "variable_name": "HUMI",
            "type": "ac",
        },
    ],
    "25": [
        {
            "register_name": "REG_SPLIT_25_READ_PWR ",
            "address": 440,
            "description": "Unit Power On/Off 0=OFF 1=ON",
            "reg_split": "25",
            "variable_name": "PWR",
            "type": "ac",
        },
        {
            "register_name": "REG_SPLIT_25_READ_SP_ROOM ",
            "address": 441,
            "description": 'Unit SetPoint: (hundredths of degrees Celsius) es: 2350 = 23.50 \u00b0C -> Range: 18..30\u00b0C"',
            "reg_split": "25",
            "variable_name": "SP_ROOM",
            "type": "ac",
        },
        {
            "register_name": "REG_SPLIT_25_READ_FAN_SPEED ",
            "address": 442,
            "description": "Unit Fan Speed (with Syxthsense): 1=Vel.Night; 2=Vel.1; 3=Vel.2; 4=Vel.3; 5=Vel.4; 7=Vel.5; 8=Vel.6; 9=Vel.Auto Unit Fan Speed (in other case): 1=Vel.Night; 2=Vel.1; 3=Vel.2; 4=Vel.3; 5=Vel.4; 6=Vel.5; 7=Vel.6; 8=Vel.7; 9=Vel.Auto",
            "reg_split": "25",
            "variable_name": "FAN_SPEED",
            "type": "ac",
        },
        {
            "register_name": "REG_SPLIT_25_READ_AIR_IN ",
            "address": 443,
            "description": "Unit Input Air Temperature: (hundredths of degrees Celsius) es: 2350 = 23.50 \u00b0C",
            "reg_split": "25",
            "variable_name": "AIR_IN",
            "type": "ac",
        },
        {
            "register_name": "REG_SPLIT_25_READ_STATUS ",
            "address": 444,
            "description": "Diagnostic Split Comunication Status: Bit 0=Unit not connected on the bus; Bit 1=Unit connected on the bus; Bit 2=Unit connected on the bus but offline; Bit 3=Unit in error.",
            "reg_split": "25",
            "variable_name": "STATUS",
            "type": "ac",
        },
        {
            "register_name": "REG_SPLIT_25_AHU_MODE ",
            "address": 445,
            "description": "AHU State 16 = Ventilation 32=Automatic ",
            "reg_split": "25",
            "variable_name": None,
            "type": "ac",
        },
        {
            "register_name": "REG_SPLIT_25_READ_HEATER_PWR ",
            "address": 446,
            "description": "Heater State 0 = OFF; 1 = ON ",
            "reg_split": "25",
            "variable_name": "HEATER_PWR",
            "type": "ac",
        },
        {
            "register_name": "REG_SPLIT_25_READ_HUMI ",
            "address": 447,
            "description": "Humidity 0..100% ",
            "reg_split": "25",
            "variable_name": "HUMI",
            "type": "ac",
        },
    ],
    "26": [
        {
            "register_name": "REG_SPLIT_26_READ_PWR ",
            "address": 450,
            "description": "Unit Power On/Off 0=OFF 1=ON",
            "reg_split": "26",
            "variable_name": "PWR",
            "type": "ac",
        },
        {
            "register_name": "REG_SPLIT_26_READ_SP_ROOM ",
            "address": 451,
            "description": 'Unit SetPoint: (hundredths of degrees Celsius) es: 2350 = 23.50 \u00b0C -> Range: 18..30\u00b0C"',
            "reg_split": "26",
            "variable_name": "SP_ROOM",
            "type": "ac",
        },
        {
            "register_name": "REG_SPLIT_26_READ_FAN_SPEED ",
            "address": 452,
            "description": "Unit Fan Speed (with Syxthsense): 1=Vel.Night; 2=Vel.1; 3=Vel.2; 4=Vel.3; 5=Vel.4; 7=Vel.5; 8=Vel.6; 9=Vel.Auto Unit Fan Speed (in other case): 1=Vel.Night; 2=Vel.1; 3=Vel.2; 4=Vel.3; 5=Vel.4; 6=Vel.5; 7=Vel.6; 8=Vel.7; 9=Vel.Auto",
            "reg_split": "26",
            "variable_name": "FAN_SPEED",
            "type": "ac",
        },
        {
            "register_name": "REG_SPLIT_26_READ_AIR_IN ",
            "address": 453,
            "description": "Unit Input Air Temperature: (hundredths of degrees Celsius) es: 2350 = 23.50 \u00b0C",
            "reg_split": "26",
            "variable_name": "AIR_IN",
            "type": "ac",
        },
        {
            "register_name": "REG_SPLIT_26_READ_STATUS ",
            "address": 454,
            "description": "Diagnostic Split Comunication Status: Bit 0=Unit not connected on the bus; Bit 1=Unit connected on the bus; Bit 2=Unit connected on the bus but offline; Bit 3=Unit in error.",
            "reg_split": "26",
            "variable_name": "STATUS",
            "type": "ac",
        },
        {
            "register_name": "REG_SPLIT_26_AHU_MODE ",
            "address": 455,
            "description": "AHU State 16 = Ventilation 32=Automatic ",
            "reg_split": "26",
            "variable_name": None,
            "type": "ac",
        },
        {
            "register_name": "REG_SPLIT_26_READ_HEATER_PWR ",
            "address": 456,
            "description": "Heater State 0 = OFF; 1 = ON ",
            "reg_split": "26",
            "variable_name": "HEATER_PWR",
            "type": "ac",
        },
        {
            "register_name": "REG_SPLIT_26_READ_HUMI ",
            "address": 457,
            "description": "Humidity 0..100% ",
            "reg_split": "26",
            "variable_name": "HUMI",
            "type": "ac",
        },
    ],
    "27": [
        {
            "register_name": "REG_SPLIT_27_READ_PWR ",
            "address": 460,
            "description": "Unit Power On/Off 0=OFF 1=ON",
            "reg_split": "27",
            "variable_name": "PWR",
            "type": "ac",
        },
        {
            "register_name": "REG_SPLIT_27_READ_SP_ROOM ",
            "address": 461,
            "description": 'Unit SetPoint: (hundredths of degrees Celsius) es: 2350 = 23.50 \u00b0C -> Range: 18..30\u00b0C"',
            "reg_split": "27",
            "variable_name": "SP_ROOM",
            "type": "ac",
        },
        {
            "register_name": "REG_SPLIT_27_READ_FAN_SPEED ",
            "address": 462,
            "description": "Unit Fan Speed (with Syxthsense): 1=Vel.Night; 2=Vel.1; 3=Vel.2; 4=Vel.3; 5=Vel.4; 7=Vel.5; 8=Vel.6; 9=Vel.Auto Unit Fan Speed (in other case): 1=Vel.Night; 2=Vel.1; 3=Vel.2; 4=Vel.3; 5=Vel.4; 6=Vel.5; 7=Vel.6; 8=Vel.7; 9=Vel.Auto",
            "reg_split": "27",
            "variable_name": "FAN_SPEED",
            "type": "ac",
        },
        {
            "register_name": "REG_SPLIT_27_READ_AIR_IN ",
            "address": 463,
            "description": "Unit Input Air Temperature: (hundredths of degrees Celsius) es: 2350 = 23.50 \u00b0C",
            "reg_split": "27",
            "variable_name": "AIR_IN",
            "type": "ac",
        },
        {
            "register_name": "REG_SPLIT_27_READ_STATUS ",
            "address": 464,
            "description": "Diagnostic Split Comunication Status: Bit 0=Unit not connected on the bus; Bit 1=Unit connected on the bus; Bit 2=Unit connected on the bus but offline; Bit 3=Unit in error.",
            "reg_split": "27",
            "variable_name": "STATUS",
            "type": "ac",
        },
        {
            "register_name": "REG_SPLIT_27_AHU_MODE ",
            "address": 465,
            "description": "AHU State 16 = Ventilation 32=Automatic ",
            "reg_split": "27",
            "variable_name": None,
            "type": "ac",
        },
        {
            "register_name": "REG_SPLIT_27_READ_HEATER_PWR ",
            "address": 466,
            "description": "Heater State 0 = OFF; 1 = ON ",
            "reg_split": "27",
            "variable_name": "HEATER_PWR",
            "type": "ac",
        },
        {
            "register_name": "REG_SPLIT_27_READ_HUMI ",
            "address": 467,
            "description": "Humidity 0..100% ",
            "reg_split": "27",
            "variable_name": "HUMI",
            "type": "ac",
        },
    ],
    "28": [
        {
            "register_name": "REG_SPLIT_28_READ_PWR ",
            "address": 470,
            "description": "Unit Power On/Off 0=OFF 1=ON",
            "reg_split": "28",
            "variable_name": "PWR",
            "type": "ac",
        },
        {
            "register_name": "REG_SPLIT_28_READ_SP_ROOM ",
            "address": 471,
            "description": 'Unit SetPoint: (hundredths of degrees Celsius) es: 2350 = 23.50 \u00b0C -> Range: 18..30\u00b0C"',
            "reg_split": "28",
            "variable_name": "SP_ROOM",
            "type": "ac",
        },
        {
            "register_name": "REG_SPLIT_28_READ_FAN_SPEED ",
            "address": 472,
            "description": "Unit Fan Speed (with Syxthsense): 1=Vel.Night; 2=Vel.1; 3=Vel.2; 4=Vel.3; 5=Vel.4; 7=Vel.5; 8=Vel.6; 9=Vel.Auto Unit Fan Speed (in other case): 1=Vel.Night; 2=Vel.1; 3=Vel.2; 4=Vel.3; 5=Vel.4; 6=Vel.5; 7=Vel.6; 8=Vel.7; 9=Vel.Auto",
            "reg_split": "28",
            "variable_name": "FAN_SPEED",
            "type": "ac",
        },
        {
            "register_name": "REG_SPLIT_28_READ_AIR_IN ",
            "address": 473,
            "description": "Unit Input Air Temperature: (hundredths of degrees Celsius) es: 2350 = 23.50 \u00b0C",
            "reg_split": "28",
            "variable_name": "AIR_IN",
            "type": "ac",
        },
        {
            "register_name": "REG_SPLIT_28_READ_STATUS ",
            "address": 474,
            "description": "Diagnostic Split Comunication Status: Bit 0=Unit not connected on the bus; Bit 1=Unit connected on the bus; Bit 2=Unit connected on the bus but offline; Bit 3=Unit in error.",
            "reg_split": "28",
            "variable_name": "STATUS",
            "type": "ac",
        },
        {
            "register_name": "REG_SPLIT_28_AHU_MODE ",
            "address": 475,
            "description": "AHU State 16 = Ventilation 32=Automatic ",
            "reg_split": "28",
            "variable_name": None,
            "type": "ac",
        },
        {
            "register_name": "REG_SPLIT_28_READ_HEATER_PWR ",
            "address": 476,
            "description": "Heater State 0 = OFF; 1 = ON ",
            "reg_split": "28",
            "variable_name": "HEATER_PWR",
            "type": "ac",
        },
        {
            "register_name": "REG_SPLIT_28_READ_HUMI ",
            "address": 477,
            "description": "Humidity 0..100% ",
            "reg_split": "28",
            "variable_name": "HUMI",
            "type": "ac",
        },
    ],
    "29": [
        {
            "register_name": "REG_SPLIT_29_READ_PWR ",
            "address": 480,
            "description": "Unit Power On/Off 0=OFF 1=ON",
            "reg_split": "29",
            "variable_name": "PWR",
            "type": "ac",
        },
        {
            "register_name": "REG_SPLIT_29_READ_SP_ROOM ",
            "address": 481,
            "description": 'Unit SetPoint: (hundredths of degrees Celsius) es: 2350 = 23.50 \u00b0C -> Range: 18..30\u00b0C"',
            "reg_split": "29",
            "variable_name": "SP_ROOM",
            "type": "ac",
        },
        {
            "register_name": "REG_SPLIT_29_READ_FAN_SPEED ",
            "address": 482,
            "description": "Unit Fan Speed (with Syxthsense): 1=Vel.Night; 2=Vel.1; 3=Vel.2; 4=Vel.3; 5=Vel.4; 7=Vel.5; 8=Vel.6; 9=Vel.Auto Unit Fan Speed (in other case): 1=Vel.Night; 2=Vel.1; 3=Vel.2; 4=Vel.3; 5=Vel.4; 6=Vel.5; 7=Vel.6; 8=Vel.7; 9=Vel.Auto",
            "reg_split": "29",
            "variable_name": "FAN_SPEED",
            "type": "ac",
        },
        {
            "register_name": "REG_SPLIT_29_READ_AIR_IN ",
            "address": 483,
            "description": "Unit Input Air Temperature: (hundredths of degrees Celsius) es: 2350 = 23.50 \u00b0C",
            "reg_split": "29",
            "variable_name": "AIR_IN",
            "type": "ac",
        },
        {
            "register_name": "REG_SPLIT_29_READ_STATUS ",
            "address": 484,
            "description": "Diagnostic Split Comunication Status: Bit 0=Unit not connected on the bus; Bit 1=Unit connected on the bus; Bit 2=Unit connected on the bus but offline; Bit 3=Unit in error.",
            "reg_split": "29",
            "variable_name": "STATUS",
            "type": "ac",
        },
        {
            "register_name": "REG_SPLIT_29_AHU_MODE ",
            "address": 485,
            "description": "AHU State 16 = Ventilation 32=Automatic ",
            "reg_split": "29",
            "variable_name": None,
            "type": "ac",
        },
        {
            "register_name": "REG_SPLIT_29_READ_HEATER_PWR ",
            "address": 486,
            "description": "Heater State 0 = OFF; 1 = ON ",
            "reg_split": "29",
            "variable_name": "HEATER_PWR",
            "type": "ac",
        },
        {
            "register_name": "REG_SPLIT_29_READ_HUMI ",
            "address": 487,
            "description": "Humidity 0..100% ",
            "reg_split": "29",
            "variable_name": "HUMI",
            "type": "ac",
        },
    ],
    "30": [
        {
            "register_name": "REG_SPLIT_30_READ_PWR ",
            "address": 490,
            "description": "Unit Power On/Off 0=OFF 1=ON",
            "reg_split": "30",
            "variable_name": "PWR",
            "type": "ac",
        },
        {
            "register_name": "REG_SPLIT_30_READ_SP_ROOM ",
            "address": 491,
            "description": 'Unit SetPoint: (hundredths of degrees Celsius) es: 2350 = 23.50 \u00b0C -> Range: 18..30\u00b0C"',
            "reg_split": "30",
            "variable_name": "SP_ROOM",
            "type": "ac",
        },
        {
            "register_name": "REG_SPLIT_30_READ_FAN_SPEED ",
            "address": 492,
            "description": "Unit Fan Speed (with Syxthsense): 1=Vel.Night; 2=Vel.1; 3=Vel.2; 4=Vel.3; 5=Vel.4; 7=Vel.5; 8=Vel.6; 9=Vel.Auto Unit Fan Speed (in other case): 1=Vel.Night; 2=Vel.1; 3=Vel.2; 4=Vel.3; 5=Vel.4; 6=Vel.5; 7=Vel.6; 8=Vel.7; 9=Vel.Auto",
            "reg_split": "30",
            "variable_name": "FAN_SPEED",
            "type": "ac",
        },
        {
            "register_name": "REG_SPLIT_30_READ_AIR_IN ",
            "address": 493,
            "description": "Unit Input Air Temperature: (hundredths of degrees Celsius) es: 2350 = 23.50 \u00b0C",
            "reg_split": "30",
            "variable_name": "AIR_IN",
            "type": "ac",
        },
        {
            "register_name": "REG_SPLIT_30_READ_STATUS ",
            "address": 494,
            "description": "Diagnostic Split Comunication Status: Bit 0=Unit not connected on the bus; Bit 1=Unit connected on the bus; Bit 2=Unit connected on the bus but offline; Bit 3=Unit in error.",
            "reg_split": "30",
            "variable_name": "STATUS",
            "type": "ac",
        },
        {
            "register_name": "REG_SPLIT_30_AHU_MODE ",
            "address": 495,
            "description": "AHU State 16 = Ventilation 32=Automatic ",
            "reg_split": "30",
            "variable_name": None,
            "type": "ac",
        },
        {
            "register_name": "REG_SPLIT_30_READ_HEATER_PWR ",
            "address": 496,
            "description": "Heater State 0 = OFF; 1 = ON ",
            "reg_split": "30",
            "variable_name": "HEATER_PWR",
            "type": "ac",
        },
        {
            "register_name": "REG_SPLIT_30_READ_HUMI ",
            "address": 497,
            "description": "Humidity 0..100% ",
            "reg_split": "30",
            "variable_name": "HUMI",
            "type": "ac",
        },
    ],
    "31": [
        {
            "register_name": "REG_SPLIT_31_READ_PWR ",
            "address": 500,
            "description": "Unit Power On/Off 0=OFF 1=ON",
            "reg_split": "31",
            "variable_name": "PWR",
            "type": "ac",
        },
        {
            "register_name": "REG_SPLIT_31_READ_SP_ROOM ",
            "address": 501,
            "description": 'Unit SetPoint: (hundredths of degrees Celsius) es: 2350 = 23.50 \u00b0C -> Range: 18..30\u00b0C"',
            "reg_split": "31",
            "variable_name": "SP_ROOM",
            "type": "ac",
        },
        {
            "register_name": "REG_SPLIT_31_READ_FAN_SPEED ",
            "address": 502,
            "description": "Unit Fan Speed (with Syxthsense): 1=Vel.Night; 2=Vel.1; 3=Vel.2; 4=Vel.3; 5=Vel.4; 7=Vel.5; 8=Vel.6; 9=Vel.Auto Unit Fan Speed (in other case): 1=Vel.Night; 2=Vel.1; 3=Vel.2; 4=Vel.3; 5=Vel.4; 6=Vel.5; 7=Vel.6; 8=Vel.7; 9=Vel.Auto",
            "reg_split": "31",
            "variable_name": "FAN_SPEED",
            "type": "ac",
        },
        {
            "register_name": "REG_SPLIT_31_READ_AIR_IN ",
            "address": 503,
            "description": "Unit Input Air Temperature: (hundredths of degrees Celsius) es: 2350 = 23.50 \u00b0C",
            "reg_split": "31",
            "variable_name": "AIR_IN",
            "type": "ac",
        },
        {
            "register_name": "REG_SPLIT_31_READ_STATUS ",
            "address": 504,
            "description": "Diagnostic Split Comunication Status: Bit 0=Unit not connected on the bus; Bit 1=Unit connected on the bus; Bit 2=Unit connected on the bus but offline; Bit 3=Unit in error.",
            "reg_split": "31",
            "variable_name": "STATUS",
            "type": "ac",
        },
        {
            "register_name": "REG_SPLIT_31_AHU_MODE ",
            "address": 505,
            "description": "AHU State 16 = Ventilation 32=Automatic ",
            "reg_split": "31",
            "variable_name": None,
            "type": "ac",
        },
        {
            "register_name": "REG_SPLIT_31_READ_HEATER_PWR ",
            "address": 506,
            "description": "Heater State 0 = OFF; 1 = ON ",
            "reg_split": "31",
            "variable_name": "HEATER_PWR",
            "type": "ac",
        },
        {
            "register_name": "REG_SPLIT_31_READ_HUMI ",
            "address": 507,
            "description": "Humidity 0..100% ",
            "reg_split": "31",
            "variable_name": "HUMI",
            "type": "ac",
        },
    ],
}

# Copied in from the AC_ADRESSES json that have a None reg_split
AC_MISC_ADDRESSES = [
    {
        "register_name": "REG_SPLIT_ENGINE_BOX_COMPRESSOR_SPEED ",
        "address": 140,
        "description": "Engine Box Inverter Compressor Speed: (percentage) Range: 0..100% es. 500 = 50.0%",
        "reg_split": None,
        "variable_name": "ENGINE_BOX_COMPRESSOR_SPEED ",
        "type": "ac_misc",
    },
    {
        "register_name": "REG_SPLIT_ENGINE_BOX_WATER_PUMP_SPEED ",
        "address": 141,
        "description": "Engine Box Inverter Water Pump Speed: (percentage) Range: 0..100% es. 500 = 50.0%",
        "reg_split": None,
        "variable_name": "ENGINE_BOX_WATER_PUMP_SPEED ",
        "type": "ac_misc",
    },
    {
        "register_name": "REG_SPLIT_CURRENT_REQ_PRESSURE ",
        "address": 142,
        "description": "Engine Box Max Air Handler Required Pressure: (thousandths of Bar) es: 22543 = 22.543 Bar",
        "reg_split": None,
        "variable_name": "CURRENT_REQ_PRESSURE ",
        "type": "ac_misc",
    },
    {
        "register_name": "REG_SPLIT_ENGINE_BOX_T_SEA_WATER ",
        "address": 145,
        "description": "Engine Box Sea Water Temperature: (hundredths of degrees Celsius) es: 2350 = 23.50 \u00b0C",
        "reg_split": None,
        "variable_name": "ENGINE_BOX_T_SEA_WATER ",
        "type": "ac_misc",
    },
    {
        "register_name": "REG_SPLIT_ENGINE_BOX_P_GAS ",
        "address": 149,
        "description": "Engine Box Gas Pressure: (thousandths of Bar) es: 22543 = 22.543 Bar",
        "reg_split": None,
        "variable_name": "ENGINE_BOX_P_GAS ",
        "type": "ac_misc",
    },
    {
        "register_name": "REG_SPLIT_ENGINE_BOX_P_LIQUID ",
        "address": 150,
        "description": "Engine Box Liquid Pressure: (thousandths of Bar) es: 22543 = 22.543 Bar",
        "reg_split": None,
        "variable_name": "ENGINE_BOX_P_LIQUID ",
        "type": "ac_misc",
    },
    {
        "register_name": "REG_SPLIT_ENGINE_BOX_P_CONDENSER ",
        "address": 151,
        "description": "Engine Box Condenser Pressure: (thousandths of Bar) es: 22543 = 22.543 Bar",
        "reg_split": None,
        "variable_name": "ENGINE_BOX_P_CONDENSER ",
        "type": "ac_misc",
    },
    {
        "register_name": "REG_SPLIT_ENGINE_BOX_COMPRESSOR2_SPEED ",
        "address": 155,
        "description": "Engine Box Inverter Compressor2 Speed: (percentage) Range: 0..100% es. 500 = 50.0%",
        "reg_split": None,
        "variable_name": "ENGINE_BOX_COMPRESSOR2_SPEED ",
        "type": "ac_misc",
    },
    {
        "register_name": "REG_ABSORPTION_WATT_AC_COMPRESSOR_1 ",
        "address": 182,
        "description": "Instantaneous absorption control of the AC compressor 1 (1=0,01 Watt)",
        "reg_split": None,
        "variable_name": None,
        "type": "ac_misc",
    },
    {
        "register_name": "REG_ABSORPTION_WATT_AC_COMPRESSOR_2 ",
        "address": 183,
        "description": "Instantaneous absorption control of the AC compressor 2 (1=0,01 Watt)",
        "reg_split": None,
        "variable_name": None,
        "type": "ac_misc",
    },
    {
        "register_name": "REG_ABSORPTION_WATT_SEA_WATER_PUMP ",
        "address": 184,
        "description": "Instantaneous absorption control of the AC Sea Water Pump (1=0,01 Watt)",
        "reg_split": None,
        "variable_name": None,
        "type": "ac_misc",
    },
    {
        "register_name": "REG_ABSORPTION_AC_COMPRESSOR_1 ",
        "address": 185,
        "description": "Instantaneous absorption control of the AC compressor 1 (1=0,01 Ampere)",
        "reg_split": None,
        "variable_name": None,
        "type": "ac_misc",
    },
    {
        "register_name": "REG_ABSORPTION_AC_COMPRESSOR_2 ",
        "address": 186,
        "description": "Instantaneous absorption control of the AC compressor 2 (1=0,01 Ampere)",
        "reg_split": None,
        "variable_name": None,
        "type": "ac_misc",
    },
    {
        "register_name": "REG_ABSORPTION_SEA_WATER_PUMP ",
        "address": 187,
        "description": "Instantaneous absorption control of the AC Sea Water Pump (1=0,01 Ampere)",
        "reg_split": None,
        "variable_name": None,
        "type": "ac_misc",
    },
    {
        "register_name": "REG_ACTIVE_ERROR ",
        "address": 190,
        "description": "General Active Error: bit 0: Engine Box Error bit 1: Split Error bit 2: reserved bit 3: reserved bit 4: not used bit 5: not used bit 6: not used bit 7: not used bit 8: not used bit 9: not used bit 10: not used bit 11: not used bit 12: not used bit 13: not used bit 14: not used bit 15: Cumulative error",
        "reg_split": None,
        "variable_name": None,
        "type": "ac_misc",
    },
]


@dataclass
class Address:
    register: int
    topic: str
    field_name: str
    scale_factor: float = 1


ADDRESSES = [
    Address(
        register=address["address"],
        topic=f"termodinamica/{address['type']}{'/' + address['reg_split'] if address['reg_split'] is not None else ''}",
        field_name=address["variable_name"],
    )
    for address in chain(
        chain.from_iterable(AC_ADRESSES.values()),
        AC_MISC_ADDRESSES,
    )
]
