directive @jsonSchemaDirective(yardTag: String = null, componentType: String = null, valveType: String = null) on FIELD_DEFINITION

type BoilersControlModeType {
  boostingMode: String!
  fillingMode: String!
}

type BoilersControlValuesType {
  boilersPump: ControlPumpType! @jsonSchemaDirective(yardTag: "50001022", componentType: "pump", valveType: null)
  boilersHeatpump: ControlHeatPumpType! @jsonSchemaDirective(yardTag: "50001035", componentType: "heatpump", valveType: null)
  boilersFlowcontrolLt2: ControlValveType! @jsonSchemaDirective(yardTag: "50001064-03", componentType: "valve", valveType: "flowcontrol")
  boilersFlowcontrolLt1: ControlValveType! @jsonSchemaDirective(yardTag: "50001064-08", componentType: "valve", valveType: "flowcontrol")
  boilersSwitchTank3Fill: ControlValveType! @jsonSchemaDirective(yardTag: "50001067-03", componentType: "valve", valveType: "switch")
  boilersSwitchTank3BoostingReturn: ControlValveType! @jsonSchemaDirective(yardTag: "50001067-04", componentType: "valve", valveType: "switch")
  boilersSwitchTank3Empty: ControlValveType! @jsonSchemaDirective(yardTag: "50001067-05", componentType: "valve", valveType: "switch")
  boilersSwitchTank3BoostingSupply: ControlValveType! @jsonSchemaDirective(yardTag: "50001067-06", componentType: "valve", valveType: "switch")
  boilersSwitchTank2Fill: ControlValveType! @jsonSchemaDirective(yardTag: "50001067-07", componentType: "valve", valveType: "switch")
  boilersSwitchTank2BoostingReturn: ControlValveType! @jsonSchemaDirective(yardTag: "50001067-08", componentType: "valve", valveType: "switch")
  boilersSwitchTank2Empty: ControlValveType! @jsonSchemaDirective(yardTag: "50001067-09", componentType: "valve", valveType: "switch")
  boilersSwitchTank2BoostingSupply: ControlValveType! @jsonSchemaDirective(yardTag: "50001067-10", componentType: "valve", valveType: "switch")
  boilersSwitchTank1Fill: ControlValveType! @jsonSchemaDirective(yardTag: "50001067-11", componentType: "valve", valveType: "switch")
  boilersSwitchTank1BoostingReturn: ControlValveType! @jsonSchemaDirective(yardTag: "50001067-12", componentType: "valve", valveType: "switch")
  boilersSwitchTank1Empty: ControlValveType! @jsonSchemaDirective(yardTag: "50001067-13", componentType: "valve", valveType: "switch")
  boilersSwitchTank1BoostingSupply: ControlValveType! @jsonSchemaDirective(yardTag: "50001067-14", componentType: "valve", valveType: "switch")
  boilersSwitchLowTemperature: ControlValveType! @jsonSchemaDirective(yardTag: "50001067-16", componentType: "valve", valveType: "switch")
  boilersSwitchHeatpump: ControlValveType! @jsonSchemaDirective(yardTag: "50001067-17", componentType: "valve", valveType: "switch")
  boilersSwitchHighTemperature: ControlValveType! @jsonSchemaDirective(yardTag: "50001067-18", componentType: "valve", valveType: "switch")
  boilersTanksController: ControllerTanksControllerValuesType! @jsonSchemaDirective(yardTag: "", componentType: null, valveType: null)
  boilersPumpFlowController: ControllerPidControllerValuesType! @jsonSchemaDirective(yardTag: "", componentType: null, valveType: null)
  boilersPumpTemperatureController: ControllerPidControllerValuesType! @jsonSchemaDirective(yardTag: "", componentType: null, valveType: null)
  boilersLt1FlowController: ControllerPidControllerValuesType! @jsonSchemaDirective(yardTag: "", componentType: null, valveType: null)
  boilersLt2FlowController: ControllerPidControllerValuesType! @jsonSchemaDirective(yardTag: "", componentType: null, valveType: null)
}

type BoilersParametersType {
  heatpumpFlowSetpoint: Float!
  heatpumpTemperatureSetpoint: Float!
  htBoostingTemperatureSetpoint: Float!
  minimumTankTemperature: Float!
  maximumTankTemperature: Float!

  """Required delta T between boosting source and tank temperature"""
  boostingDelta: Float!

  """
  Minimum pump dutypoint to guarantee sufficient flow for a temperature measurement
  """
  lt1FlowcontrolMinimumSetpoint: Float!

  """
  Minimum pump dutypoint to guarantee sufficient flow for a temperature measurement
  """
  lt2FlowcontrolMinimumSetpoint: Float!
  fillingTemperatureSetpoint: Float!
  minimumTankLevel: Float!
  maximumTankLevel: Float!
  tank1Disabled: Boolean!
  tank2Disabled: Boolean!
  tank3Disabled: Boolean!
  pumpTemperatureTuning: [Float!]!
  pumpFlowTuning: [Float!]!
  lt2FlowTuning: [Float!]!
  lt1FlowTuning: [Float!]!
}

type BoilersSensorValuesType {
  boilersPump: SensorPumpType! @jsonSchemaDirective(yardTag: "50001022", componentType: "pump", valveType: null)
  boilersTemperatureHvacExchangerReturn: SensorTemperatureSensorType! @jsonSchemaDirective(yardTag: "50001038-25", componentType: "temperature_sensor", valveType: null)
  boilersTemperatureLt2Return: SensorTemperatureSensorType! @jsonSchemaDirective(yardTag: "50001038-26", componentType: "temperature_sensor", valveType: null)
  boilersTemperatureTank3: SensorTemperatureSensorType! @jsonSchemaDirective(yardTag: "50001038-27", componentType: "temperature_sensor", valveType: null)
  boilersTemperatureTank2: SensorTemperatureSensorType! @jsonSchemaDirective(yardTag: "50001038-44", componentType: "temperature_sensor", valveType: null)
  boilersTemperatureTank1: SensorTemperatureSensorType! @jsonSchemaDirective(yardTag: "50001038-45", componentType: "temperature_sensor", valveType: null)
  boilersTemperatureLt1Return: SensorTemperatureSensorType! @jsonSchemaDirective(yardTag: "50001038-46", componentType: "temperature_sensor", valveType: null)
  boilersTemperatureFreshwaterSupply: SensorTemperatureSensorType! @jsonSchemaDirective(yardTag: "50001038-47", componentType: "temperature_sensor", valveType: null)
  boilersTemperatureFahrenheitReturn: SensorTemperatureSensorType! @jsonSchemaDirective(yardTag: "50001038-51", componentType: "temperature_sensor", valveType: null)
  boilersTemperatureBoostingSupply: SensorTemperatureSensorType! @jsonSchemaDirective(yardTag: "50001038-65", componentType: "temperature_sensor", valveType: null)
  boilersTemperatureBoostingReturn: SensorTemperatureSensorType! @jsonSchemaDirective(yardTag: "50001038-66", componentType: "temperature_sensor", valveType: null)
  boilersLevelTank1: SensorLevelSensorType! @jsonSchemaDirective(yardTag: "50001056-01", componentType: "level_sensor", valveType: null)
  boilersLevelTank2: SensorLevelSensorType! @jsonSchemaDirective(yardTag: "50001056-02", componentType: "level_sensor", valveType: null)
  boilersLevelTank3: SensorLevelSensorType! @jsonSchemaDirective(yardTag: "50001056-03", componentType: "level_sensor", valveType: null)
  boilersFlowLt2: SensorFlowSensorType! @jsonSchemaDirective(yardTag: "50001057-17", componentType: "flow_sensor", valveType: null)
  boilersFlowLt1: SensorFlowSensorType! @jsonSchemaDirective(yardTag: "50001057-24", componentType: "flow_sensor", valveType: null)
  boilersFlowBoosting: SensorFlowSensorType! @jsonSchemaDirective(yardTag: "50001058-11", componentType: "flow_sensor", valveType: null)
  boilersFlowcontrolLt2: SensorValveType! @jsonSchemaDirective(yardTag: "50001064-03", componentType: "valve", valveType: "flowcontrol")
  boilersFlowcontrolLt1: SensorValveType! @jsonSchemaDirective(yardTag: "50001064-08", componentType: "valve", valveType: "flowcontrol")
  boilersSwitchTank3Fill: SensorValveType! @jsonSchemaDirective(yardTag: "50001067-03", componentType: "valve", valveType: "switch")
  boilersSwitchTank3BoostingReturn: SensorValveType! @jsonSchemaDirective(yardTag: "50001067-04", componentType: "valve", valveType: "switch")
  boilersSwitchTank3Empty: SensorValveType! @jsonSchemaDirective(yardTag: "50001067-05", componentType: "valve", valveType: "switch")
  boilersSwitchTank3BoostingSupply: SensorValveType! @jsonSchemaDirective(yardTag: "50001067-06", componentType: "valve", valveType: "switch")
  boilersSwitchTank2Fill: SensorValveType! @jsonSchemaDirective(yardTag: "50001067-07", componentType: "valve", valveType: "switch")
  boilersSwitchTank2BoostingReturn: SensorValveType! @jsonSchemaDirective(yardTag: "50001067-08", componentType: "valve", valveType: "switch")
  boilersSwitchTank2Empty: SensorValveType! @jsonSchemaDirective(yardTag: "50001067-09", componentType: "valve", valveType: "switch")
  boilersSwitchTank2BoostingSupply: SensorValveType! @jsonSchemaDirective(yardTag: "50001067-10", componentType: "valve", valveType: "switch")
  boilersSwitchTank1Fill: SensorValveType! @jsonSchemaDirective(yardTag: "50001067-11", componentType: "valve", valveType: "switch")
  boilersSwitchTank1BoostingReturn: SensorValveType! @jsonSchemaDirective(yardTag: "50001067-12", componentType: "valve", valveType: "switch")
  boilersSwitchTank1Empty: SensorValveType! @jsonSchemaDirective(yardTag: "50001067-13", componentType: "valve", valveType: "switch")
  boilersSwitchTank1BoostingSupply: SensorValveType! @jsonSchemaDirective(yardTag: "50001067-14", componentType: "valve", valveType: "switch")
  boilersSwitchLowTemperature: SensorValveType! @jsonSchemaDirective(yardTag: "50001067-16", componentType: "valve", valveType: "switch")
  boilersSwitchHeatpump: SensorValveType! @jsonSchemaDirective(yardTag: "50001067-17", componentType: "valve", valveType: "switch")
  boilersSwitchHighTemperature: SensorValveType! @jsonSchemaDirective(yardTag: "50001067-18", componentType: "valve", valveType: "switch")
  boilersPressureBoosting: SensorPressureSensorType! @jsonSchemaDirective(yardTag: "50001097-11", componentType: "pressure_sensor", valveType: null)
  lt1FlowRecovery: SensorFlowSensorType! @jsonSchemaDirective(yardTag: "50001058-03", componentType: "flow_sensor", valveType: null)
  lt1TemperatureRecovery: SensorTemperatureSensorType! @jsonSchemaDirective(yardTag: "50001038-16", componentType: "temperature_sensor", valveType: null)
  lt1TemperatureRecoveryReturn: SensorTemperatureSensorType! @jsonSchemaDirective(yardTag: "50001038-59", componentType: "temperature_sensor", valveType: null)
  lt2FlowRecovery: SensorFlowSensorType! @jsonSchemaDirective(yardTag: "50001058-04", componentType: "flow_sensor", valveType: null)
  lt2TemperatureRecovery: SensorTemperatureSensorType! @jsonSchemaDirective(yardTag: "50001038-52", componentType: "temperature_sensor", valveType: null)
  lt2TemperatureRecoveryReturn: SensorTemperatureSensorType! @jsonSchemaDirective(yardTag: "50001038-58", componentType: "temperature_sensor", valveType: null)
  consumersFlowBoosting: SensorFlowSensorType! @jsonSchemaDirective(yardTag: "50001058-07", componentType: "flow_sensor", valveType: null)
  consumersTemperatureBoostingSupply: SensorTemperatureSensorType! @jsonSchemaDirective(yardTag: "50001038-53", componentType: "temperature_sensor", valveType: null)
  consumersTemperatureBoostingReturn: SensorTemperatureSensorType! @jsonSchemaDirective(yardTag: "50001038-48", componentType: "temperature_sensor", valveType: null)
  fahrenheitFlowBoilers: SensorFlowSensorType! @jsonSchemaDirective(yardTag: "50001058-10", componentType: "flow_sensor", valveType: null)
  fahrenheitTemperatureWasteReturn: SensorTemperatureSensorType! @jsonSchemaDirective(yardTag: "50001038-38", componentType: "temperature_sensor", valveType: null)
  fahrenheitTemperatureBoilersReturn: SensorTemperatureSensorType! @jsonSchemaDirective(yardTag: "50001038-56", componentType: "temperature_sensor", valveType: null)
  freshwaterHotwaterFlow: SensorFlowSensorType! @jsonSchemaDirective(yardTag: "25001123-1", componentType: null, valveType: null)
  freshwaterHotwaterTemperature: SensorTemperatureSensorType! @jsonSchemaDirective(yardTag: "25001038-1", componentType: null, valveType: null)
  lt1Delta: SensorTemperatureDeltaType!
  lt2Delta: SensorTemperatureDeltaType!
  consumersDelta: SensorTemperatureDeltaType!
  fahrenheitDelta: SensorTemperatureDeltaType!
  freshwaterFlowSupply: SensorCalculatedFlowType!
  boilersHvacExchanger: SensorHvacExchangerType!
  boilersHeatpump: SensorHeatPumpType!
  boilersFahrenheitExchanger: SensorHeatExchangerType!
  boilersConsumersExchanger: SensorHeatExchangerType!
  boilersLt2Exchanger: SensorHeatExchangerType!
  boilersLt1Exchanger: SensorHeatExchangerType!
}

type BoilersSensorValuesTypeBoilersControlValuesTypeBoilersParametersTypeBoilersControlModeTypeControlModule {
  sensorValues: BoilersSensorValuesType
  controlValues: BoilersControlValuesType
  parameters: BoilersParametersType
  controlMode: BoilersSensorValuesTypeBoilersControlValuesTypeBoilersParametersTypeBoilersControlModeTypeSwitchingControlModeType
}

type BoilersSensorValuesTypeBoilersControlValuesTypeBoilersParametersTypeBoilersControlModeTypeSwitchingControlModeType {
  automaticMode: BoilersControlModeType
  automatic: Boolean!
}

type BoilersSimulationInputsType {
  boilersLt1Supply: BoundarySimulationType!
  boilersLt2Supply: BoundarySimulationType!
  boilersFahrenheitSupply: BoundarySimulationType!
  boilersHtSupply: BoundarySimulationType!
  boilersFreshwaterSupply: OverpressureTemperatureBoundarySimulationType!
  boilersHvacExchanger: HvacExchangerSimulationType!
  boilersSeawaterSupply: TemperatureBoundarySimulationType!
  boilersHotwaterDemand: FlowBoundarySimulationType!
}

type BoilersSimulationOutputsType {
  boilersLt1Return: TemperatureBoundarySimulationType!
  boilersLt2Return: TemperatureBoundarySimulationType!
  boilersFahrenheitReturn: TemperatureBoundarySimulationType!
  boilersHtReturn: TemperatureBoundarySimulationType!
  boilersSeawaterReturn: TemperatureBoundarySimulationType!
  boilersSeawaterSupply: FlowBoundarySimulationType!
  boilersFreshwaterReturn: FlowBoundarySimulationType!
}

type BoolStampedType {
  value: Boolean!
  timestamp: DateTime!
}

input BoundaryInputType {
  temperature: Float!
  flow: Float!
}

type BoundarySimulationType {
  temperature: FloatStampedType!
  flow: FloatStampedType!
}

type ConsumersControlModeType {
  Empty: Void
}

type ConsumersControlValuesType {
  consumersFlowcontrolFahrenheit: ControlValveType! @jsonSchemaDirective(yardTag: "50001061", componentType: "valve", valveType: "flowcontrol")
  consumersFlowcontrolBypass: ControlValveType! @jsonSchemaDirective(yardTag: "50001062-01", componentType: "valve", valveType: "flowcontrol")
  consumersFlowcontrolBoosting: ControlValveType! @jsonSchemaDirective(yardTag: "50001065-01", componentType: "valve", valveType: "flowcontrol")
  consumersSwitchFahrenheitExchanger: ControlValveType! @jsonSchemaDirective(yardTag: "50001066-02", componentType: "valve", valveType: "switch")
  consumersSwitchBoosting: ControlValveType! @jsonSchemaDirective(yardTag: "50001067-15", componentType: "valve", valveType: "switch")
}

type ConsumersParametersType {
  boostingEnabled: Boolean!
  boostingFlowRatioSetpoint: Float!
  fahrenheitEnabled: Boolean!
  fahrenheitFlowRatioSetpoint: Float!
  boostingFlowBalanceTuning: [Float!]!
  bypassFlowBalanceTuning: [Float!]!
  fahrenheitFlowBalanceTuning: [Float!]!
}

type ConsumersSensorValuesType {
  consumersTemperatureBoostingReturn: SensorTemperatureSensorType! @jsonSchemaDirective(yardTag: "50001038-48", componentType: "temperature_sensor", valveType: null)
  consumersTemperatureFahrenheitReturn: SensorTemperatureSensorType! @jsonSchemaDirective(yardTag: "50001038-49", componentType: "temperature_sensor", valveType: null)
  consumersTemperatureBoostingSupply: SensorTemperatureSensorType! @jsonSchemaDirective(yardTag: "50001038-53", componentType: "temperature_sensor", valveType: null)
  consumersTemperatureFahrenheitSupply: SensorTemperatureSensorType! @jsonSchemaDirective(yardTag: "50001038-54", componentType: "temperature_sensor", valveType: null)
  consumersFlowBoosting: SensorFlowSensorType! @jsonSchemaDirective(yardTag: "50001058-07", componentType: "flow_sensor", valveType: null)
  consumersFlowFahrenheit: SensorFlowSensorType! @jsonSchemaDirective(yardTag: "50001058-08", componentType: "flow_sensor", valveType: null)
  consumersFlowBypass: SensorFlowSensorType! @jsonSchemaDirective(yardTag: "50001192", componentType: "flow_sensor", valveType: null)
  consumersFlowcontrolFahrenheit: SensorValveType! @jsonSchemaDirective(yardTag: "50001061", componentType: "valve", valveType: "flowcontrol")
  consumersFlowcontrolBypass: SensorValveType! @jsonSchemaDirective(yardTag: "50001062-01", componentType: "valve", valveType: "flowcontrol")
  consumersFlowcontrolBoosting: SensorValveType! @jsonSchemaDirective(yardTag: "50001065-01", componentType: "valve", valveType: "flowcontrol")
  consumersSwitchFahrenheitExchanger: SensorValveType! @jsonSchemaDirective(yardTag: "50001066-02", componentType: "valve", valveType: "switch")
  consumersSwitchBoosting: SensorValveType! @jsonSchemaDirective(yardTag: "50001067-15", componentType: "valve", valveType: "switch")
}

type ConsumersSensorValuesTypeConsumersControlValuesTypeConsumersParametersTypeConsumersControlModeTypeControlModule {
  sensorValues: ConsumersSensorValuesType
  controlValues: ConsumersControlValuesType
  parameters: ConsumersParametersType
  controlMode: ConsumersSensorValuesTypeConsumersControlValuesTypeConsumersParametersTypeConsumersControlModeTypeSwitchingControlModeType
}

type ConsumersSensorValuesTypeConsumersControlValuesTypeConsumersParametersTypeConsumersControlModeTypeSwitchingControlModeType {
  automaticMode: ConsumersControlModeType
  automatic: Boolean!
}

type ConsumersSimulationInputsType {
  consumersFahrenheitSupply: BoundarySimulationType!
  consumersBoostingSupply: BoundarySimulationType!
  consumersModuleSupply: BoundarySimulationType!
}

type ConsumersSimulationOutputsType {
  consumersFahrenheitReturn: TemperatureBoundarySimulationType!
  consumersBoostingReturn: TemperatureBoundarySimulationType!
  consumersModuleReturn: BoundarySimulationType!
}

type ControlHeatPumpType {
  on: BoolStampedType!
  temperatureSetpoint: FloatStampedType!
}

type ControlModules {
  thrusters: ThrustersSensorValuesTypeThrustersControlValuesTypeThrustersParametersTypeThrustersControlModeTypeControlModule!
  pvt: PvtSensorValuesTypePvtControlValuesTypePvtParametersTypePvtControlModeTypeControlModule!
  pcm: PcmSensorValuesTypePcmControlValuesTypePcmParametersTypePcmControlModeTypeControlModule!
  consumers: ConsumersSensorValuesTypeConsumersControlValuesTypeConsumersParametersTypeConsumersControlModeTypeControlModule!
  boilers: BoilersSensorValuesTypeBoilersControlValuesTypeBoilersParametersTypeBoilersControlModeTypeControlModule!
}

type ControlPcmType {
  on: BoolStampedType!
}

type ControlPumpType {
  dutypoint: FloatStampedType!
  on: BoolStampedType!
}

type ControlValveType {
  setpoint: FloatStampedType!
}

type ControllerPidControllerValuesType {
  setpoint: FloatStampedType!
  measurement: FloatOptionalStampedType!
  output: FloatOptionalStampedType!
  error: FloatOptionalStampedType!
  enabled: BoolStampedType!
  tuning: FloatListStampedType!
  components: FloatListStampedType!
}

type ControllerTanksControllerValuesType {
  tank1State: TankStateStampedType!
  tank2State: TankStateStampedType!
  tank3State: TankStateStampedType!
  timeToFill: FloatOptionalStampedType!
}

"""Date with time (isoformat)"""
scalar DateTime

type FloatListStampedType {
  value: [Float!]!
  timestamp: DateTime!
}

type FloatOptionalStampedType {
  value: Float
  timestamp: DateTime!
}

type FloatStampedType {
  value: Float!
  timestamp: DateTime!
}

input FlowBoundaryInputType {
  flow: Float!
}

type FlowBoundarySimulationType {
  flow: FloatStampedType!
}

input HeatPumpInputType {
  on: Boolean!
  temperatureSetpoint: Float!
}

input HeatSourceInputType {
  heatFlow: Float!
}

type HeatSourceSimulationType {
  heatFlow: FloatStampedType!
}

type HighTemperatureSimulationInputsType {
  thrustersAft: ThrusterSimulationType!
  thrustersFwd: ThrusterSimulationType!
  thrustersSeawaterSupply: BoundarySimulationType!
  thrustersPcs: PcsSimulationType!
  pvtMainFwd: HeatSourceSimulationType!
  pvtMainAft: HeatSourceSimulationType!
  pvtOwners: HeatSourceSimulationType!
  pvtSeawaterSupply: BoundarySimulationType!
  pcmFreshwaterSupply: BoundarySimulationType!
  consumersFahrenheitSupply: BoundarySimulationType!
  consumersBoostingSupply: BoundarySimulationType!
}

type HighTemperatureSimulationOutputsType {
  thrustersSeawaterReturn: TemperatureBoundarySimulationType!
  thrustersModuleSupply: FlowBoundarySimulationType!
  thrustersModuleReturn: BoundarySimulationType!
  pvtModuleReturn: BoundarySimulationType!
  pvtModuleSupply: FlowBoundarySimulationType!
  pvtSeawaterReturn: TemperatureBoundarySimulationType!
  consumersFahrenheitReturn: TemperatureBoundarySimulationType!
  consumersBoostingReturn: TemperatureBoundarySimulationType!
  consumersModuleReturn: BoundarySimulationType!
  pcmConsumersReturn: BoundarySimulationType!
  pcmProducersReturn: BoundarySimulationType!
  pcmFreshwaterReturn: BoundarySimulationType!
}

input HvacExchangerInputType {
  heatFlow: Float!
  maximumTemperature: Float!
}

type HvacExchangerSimulationType {
  heatFlow: FloatStampedType!
  maximumTemperature: FloatStampedType!
}

type Mutation {
  thrustersSetAutomationMode(automatic: Boolean!): Boolean!
  thrustersParameterSetMaximumSupplyTemperature(value: Float!): ThrustersParametersType!
  thrustersParameterSetCoolingTemperature(value: Float!): ThrustersParametersType!
  thrustersParameterSetCoolingFlow(value: Float!): ThrustersParametersType!
  thrustersParameterSetRecoveryTemperature(value: Float!): ThrustersParametersType!
  thrustersParameterSetWarmupTemperature(value: Float!): ThrustersParametersType!
  thrustersParameterSetThrustersMinimumFlow(value: Float!): ThrustersParametersType!
  thrustersParameterSetThrustersMaximumFlow(value: Float!): ThrustersParametersType!
  thrustersParameterSetPumpTuning(value: [Float!]!): ThrustersParametersType!
  thrustersParameterSetWarmupMixTuning(value: [Float!]!): ThrustersParametersType!
  thrustersParameterSetHeatDumpTuning(value: [Float!]!): ThrustersParametersType!
  thrustersParameterSetAftFlowBalanceTuning(value: [Float!]!): ThrustersParametersType!
  thrustersParameterSetFwdFlowBalanceTuning(value: [Float!]!): ThrustersParametersType!
  thrustersParameterSetAftTemperatureTuning(value: [Float!]!): ThrustersParametersType!
  thrustersParameterSetFwdTemperatureTuning(value: [Float!]!): ThrustersParametersType!
  thrustersControlSetThrustersPump1(component: PumpInputType!): ThrustersControlValuesType!
  thrustersControlSetThrustersPump2(component: PumpInputType!): ThrustersControlValuesType!
  thrustersControlSetThrustersMixRecovery(component: ValveInputType!): ThrustersControlValuesType!
  thrustersControlSetThrustersMixExchanger(component: ValveInputType!): ThrustersControlValuesType!
  thrustersControlSetThrustersFlowcontrolAft(component: ValveInputType!): ThrustersControlValuesType!
  thrustersControlSetThrustersFlowcontrolFwd(component: ValveInputType!): ThrustersControlValuesType!
  thrustersControlSetThrustersShutoffRecovery(component: ValveInputType!): ThrustersControlValuesType!
  thrustersControlSetThrustersSwitchAft(component: ValveInputType!): ThrustersControlValuesType!
  thrustersControlSetThrustersSwitchFwd(component: ValveInputType!): ThrustersControlValuesType!
  pvtSetAutomationMode(automatic: Boolean!): Boolean!
  pvtParameterSetMaximumSupplyTemperature(value: Float!): PvtParametersType!
  pvtParameterSetRecoveryTemperature(value: Float!): PvtParametersType!
  pvtParameterSetWarmupTemperature(value: Float!): PvtParametersType!
  pvtParameterSetRecoveryActivationStringTemperature(value: Float!): PvtParametersType!
  pvtParameterSetMinimumReturnTemperature(value: Float!): PvtParametersType!
  pvtParameterSetMainFwdMinimumPumpDutypoint(value: Float!): PvtParametersType!
  pvtParameterSetMainAftMinimumPumpDutypoint(value: Float!): PvtParametersType!
  pvtParameterSetOwnersMinimumPumpDutypoint(value: Float!): PvtParametersType!
  pvtParameterSetHeatDumpTuning(value: [Float!]!): PvtParametersType!
  pvtParameterSetMainFwdMixTuning(value: [Float!]!): PvtParametersType!
  pvtParameterSetMainAftMixTuning(value: [Float!]!): PvtParametersType!
  pvtParameterSetOwnersMixTuning(value: [Float!]!): PvtParametersType!
  pvtParameterSetMainFwdPumpTuning(value: [Float!]!): PvtParametersType!
  pvtParameterSetMainAftPumpTuning(value: [Float!]!): PvtParametersType!
  pvtParameterSetOwnersPumpTuning(value: [Float!]!): PvtParametersType!
  pvtControlSetPvtPumpMainFwd(component: PumpInputType!): PvtControlValuesType!
  pvtControlSetPvtPumpMainAft(component: PumpInputType!): PvtControlValuesType!
  pvtControlSetPvtPumpOwners(component: PumpInputType!): PvtControlValuesType!
  pvtControlSetPvtMixMainFwd(component: ValveInputType!): PvtControlValuesType!
  pvtControlSetPvtMixMainAft(component: ValveInputType!): PvtControlValuesType!
  pvtControlSetPvtMixOwners(component: ValveInputType!): PvtControlValuesType!
  pvtControlSetPvtSwitchMainFwd(component: ValveInputType!): PvtControlValuesType!
  pvtControlSetPvtSwitchMainAft(component: ValveInputType!): PvtControlValuesType!
  pvtControlSetPvtSwitchOwners(component: ValveInputType!): PvtControlValuesType!
  pvtControlSetPvtMixExchanger(component: ValveInputType!): PvtControlValuesType!
  pcmSetAutomationMode(automatic: Boolean!): Boolean!
  pcmParameterSetPcmDischargeFlow(value: Float!): PcmParametersType!
  pcmParameterSetPcmChargeFlow(value: Float!): PcmParametersType!
  pcmParameterSetMinimumChargingDt(value: Float!): PcmParametersType!
  pcmParameterSetMinimumChargingTemperature(value: Float!): PcmParametersType!
  pcmParameterSetPumpTuning(value: [Float!]!): PcmParametersType!
  pcmParameterSetSupplyingEnabled(value: Boolean!): PcmParametersType!
  pcmParameterSetChargingEnabled(value: Boolean!): PcmParametersType!
  pcmParameterSetModule1FlowBalanceTuning(value: [Float!]!): PcmParametersType!
  pcmParameterSetModule2FlowBalanceTuning(value: [Float!]!): PcmParametersType!
  pcmParameterSetModule3FlowBalanceTuning(value: [Float!]!): PcmParametersType!
  pcmParameterSetModule4FlowBalanceTuning(value: [Float!]!): PcmParametersType!
  pcmControlSetPcmPump(component: PumpInputType!): PcmControlValuesType!
  pcmControlSetPcmSwitchChargingReturn(component: ValveInputType!): PcmControlValuesType!
  pcmControlSetPcmFlowcontrolModule1(component: ValveInputType!): PcmControlValuesType!
  pcmControlSetPcmFlowcontrolModule2(component: ValveInputType!): PcmControlValuesType!
  pcmControlSetPcmFlowcontrolModule3(component: ValveInputType!): PcmControlValuesType!
  pcmControlSetPcmFlowcontrolModule4(component: ValveInputType!): PcmControlValuesType!
  pcmControlSetPcmSwitchDischarging(component: ValveInputType!): PcmControlValuesType!
  pcmControlSetPcmSwitchChargingSupply(component: ValveInputType!): PcmControlValuesType!
  pcmControlSetPcmSwitchConsumers(component: ValveInputType!): PcmControlValuesType!
  pcmControlSetPcmModule1(component: PcmInputType!): PcmControlValuesType!
  consumersSetAutomationMode(automatic: Boolean!): Boolean!
  consumersParameterSetBoostingEnabled(value: Boolean!): ConsumersParametersType!
  consumersParameterSetBoostingFlowRatioSetpoint(value: Float!): ConsumersParametersType!
  consumersParameterSetFahrenheitEnabled(value: Boolean!): ConsumersParametersType!
  consumersParameterSetFahrenheitFlowRatioSetpoint(value: Float!): ConsumersParametersType!
  consumersParameterSetBoostingFlowBalanceTuning(value: [Float!]!): ConsumersParametersType!
  consumersParameterSetBypassFlowBalanceTuning(value: [Float!]!): ConsumersParametersType!
  consumersParameterSetFahrenheitFlowBalanceTuning(value: [Float!]!): ConsumersParametersType!
  consumersControlSetConsumersFlowcontrolFahrenheit(component: ValveInputType!): ConsumersControlValuesType!
  consumersControlSetConsumersFlowcontrolBypass(component: ValveInputType!): ConsumersControlValuesType!
  consumersControlSetConsumersFlowcontrolBoosting(component: ValveInputType!): ConsumersControlValuesType!
  consumersControlSetConsumersSwitchFahrenheitExchanger(component: ValveInputType!): ConsumersControlValuesType!
  consumersControlSetConsumersSwitchBoosting(component: ValveInputType!): ConsumersControlValuesType!
  boilersSetAutomationMode(automatic: Boolean!): Boolean!
  boilersParameterSetHeatpumpFlowSetpoint(value: Float!): BoilersParametersType!
  boilersParameterSetHeatpumpTemperatureSetpoint(value: Float!): BoilersParametersType!
  boilersParameterSetHtBoostingTemperatureSetpoint(value: Float!): BoilersParametersType!
  boilersParameterSetMinimumTankTemperature(value: Float!): BoilersParametersType!
  boilersParameterSetMaximumTankTemperature(value: Float!): BoilersParametersType!
  boilersParameterSetBoostingDelta(value: Float!): BoilersParametersType!
  boilersParameterSetLt1FlowcontrolMinimumSetpoint(value: Float!): BoilersParametersType!
  boilersParameterSetLt2FlowcontrolMinimumSetpoint(value: Float!): BoilersParametersType!
  boilersParameterSetFillingTemperatureSetpoint(value: Float!): BoilersParametersType!
  boilersParameterSetMinimumTankLevel(value: Float!): BoilersParametersType!
  boilersParameterSetMaximumTankLevel(value: Float!): BoilersParametersType!
  boilersParameterSetTank1Disabled(value: Boolean!): BoilersParametersType!
  boilersParameterSetTank2Disabled(value: Boolean!): BoilersParametersType!
  boilersParameterSetTank3Disabled(value: Boolean!): BoilersParametersType!
  boilersParameterSetPumpTemperatureTuning(value: [Float!]!): BoilersParametersType!
  boilersParameterSetPumpFlowTuning(value: [Float!]!): BoilersParametersType!
  boilersParameterSetLt2FlowTuning(value: [Float!]!): BoilersParametersType!
  boilersParameterSetLt1FlowTuning(value: [Float!]!): BoilersParametersType!
  boilersControlSetBoilersPump(component: PumpInputType!): BoilersControlValuesType!
  boilersControlSetBoilersHeatpump(component: HeatPumpInputType!): BoilersControlValuesType!
  boilersControlSetBoilersFlowcontrolLt2(component: ValveInputType!): BoilersControlValuesType!
  boilersControlSetBoilersFlowcontrolLt1(component: ValveInputType!): BoilersControlValuesType!
  boilersControlSetBoilersSwitchTank3Fill(component: ValveInputType!): BoilersControlValuesType!
  boilersControlSetBoilersSwitchTank3BoostingReturn(component: ValveInputType!): BoilersControlValuesType!
  boilersControlSetBoilersSwitchTank3Empty(component: ValveInputType!): BoilersControlValuesType!
  boilersControlSetBoilersSwitchTank3BoostingSupply(component: ValveInputType!): BoilersControlValuesType!
  boilersControlSetBoilersSwitchTank2Fill(component: ValveInputType!): BoilersControlValuesType!
  boilersControlSetBoilersSwitchTank2BoostingReturn(component: ValveInputType!): BoilersControlValuesType!
  boilersControlSetBoilersSwitchTank2Empty(component: ValveInputType!): BoilersControlValuesType!
  boilersControlSetBoilersSwitchTank2BoostingSupply(component: ValveInputType!): BoilersControlValuesType!
  boilersControlSetBoilersSwitchTank1Fill(component: ValveInputType!): BoilersControlValuesType!
  boilersControlSetBoilersSwitchTank1BoostingReturn(component: ValveInputType!): BoilersControlValuesType!
  boilersControlSetBoilersSwitchTank1Empty(component: ValveInputType!): BoilersControlValuesType!
  boilersControlSetBoilersSwitchTank1BoostingSupply(component: ValveInputType!): BoilersControlValuesType!
  boilersControlSetBoilersSwitchLowTemperature(component: ValveInputType!): BoilersControlValuesType!
  boilersControlSetBoilersSwitchHeatpump(component: ValveInputType!): BoilersControlValuesType!
  boilersControlSetBoilersSwitchHighTemperature(component: ValveInputType!): BoilersControlValuesType!
  boilersControlSetBoilersTanksController(component: TanksControllerValuesInputType!): BoilersControlValuesType!
  boilersControlSetBoilersPumpFlowController(component: PidControllerValuesInputType!): BoilersControlValuesType!
  boilersControlSetBoilersPumpTemperatureController(component: PidControllerValuesInputType!): BoilersControlValuesType!
  boilersControlSetBoilersLt1FlowController(component: PidControllerValuesInputType!): BoilersControlValuesType!
  boilersControlSetBoilersLt2FlowController(component: PidControllerValuesInputType!): BoilersControlValuesType!
  boilersSimulationSetBoilersLt1Supply(component: BoundaryInputType!): BoilersSimulationInputsType!
  boilersSimulationSetBoilersLt2Supply(component: BoundaryInputType!): BoilersSimulationInputsType!
  boilersSimulationSetBoilersFahrenheitSupply(component: BoundaryInputType!): BoilersSimulationInputsType!
  boilersSimulationSetBoilersHtSupply(component: BoundaryInputType!): BoilersSimulationInputsType!
  boilersSimulationSetBoilersFreshwaterSupply(component: OverpressureTemperatureBoundaryInputType!): BoilersSimulationInputsType!
  boilersSimulationSetBoilersHvacExchanger(component: HvacExchangerInputType!): BoilersSimulationInputsType!
  boilersSimulationSetBoilersSeawaterSupply(component: TemperatureBoundaryInputType!): BoilersSimulationInputsType!
  boilersSimulationSetBoilersHotwaterDemand(component: FlowBoundaryInputType!): BoilersSimulationInputsType!
  highTemperatureSimulationSetThrustersAft(component: ThrusterInputType!): HighTemperatureSimulationInputsType!
  highTemperatureSimulationSetThrustersFwd(component: ThrusterInputType!): HighTemperatureSimulationInputsType!
  highTemperatureSimulationSetThrustersSeawaterSupply(component: BoundaryInputType!): HighTemperatureSimulationInputsType!
  highTemperatureSimulationSetThrustersPcs(component: PcsInputType!): HighTemperatureSimulationInputsType!
  highTemperatureSimulationSetPvtMainFwd(component: HeatSourceInputType!): HighTemperatureSimulationInputsType!
  highTemperatureSimulationSetPvtMainAft(component: HeatSourceInputType!): HighTemperatureSimulationInputsType!
  highTemperatureSimulationSetPvtOwners(component: HeatSourceInputType!): HighTemperatureSimulationInputsType!
  highTemperatureSimulationSetPvtSeawaterSupply(component: BoundaryInputType!): HighTemperatureSimulationInputsType!
  highTemperatureSimulationSetPcmFreshwaterSupply(component: BoundaryInputType!): HighTemperatureSimulationInputsType!
  highTemperatureSimulationSetConsumersFahrenheitSupply(component: BoundaryInputType!): HighTemperatureSimulationInputsType!
  highTemperatureSimulationSetConsumersBoostingSupply(component: BoundaryInputType!): HighTemperatureSimulationInputsType!
  consumersSimulationSetConsumersFahrenheitSupply(component: BoundaryInputType!): ConsumersSimulationInputsType!
  consumersSimulationSetConsumersBoostingSupply(component: BoundaryInputType!): ConsumersSimulationInputsType!
  consumersSimulationSetConsumersModuleSupply(component: BoundaryInputType!): ConsumersSimulationInputsType!
  pcmSimulationSetPcmProducersSupply(component: BoundaryInputType!): PcmSimulationInputsType!
  pcmSimulationSetPcmConsumersSupply(component: TemperatureBoundaryInputType!): PcmSimulationInputsType!
  pcmSimulationSetPcmFreshwaterSupply(component: BoundaryInputType!): PcmSimulationInputsType!
  pvtSimulationSetPvtMainFwd(component: HeatSourceInputType!): PvtSimulationInputsType!
  pvtSimulationSetPvtMainAft(component: HeatSourceInputType!): PvtSimulationInputsType!
  pvtSimulationSetPvtOwners(component: HeatSourceInputType!): PvtSimulationInputsType!
  pvtSimulationSetPvtModuleSupply(component: TemperatureBoundaryInputType!): PvtSimulationInputsType!
  pvtSimulationSetPvtSeawaterSupply(component: BoundaryInputType!): PvtSimulationInputsType!
  thrustersSimulationSetThrustersAft(component: ThrusterInputType!): ThrustersSimulationInputsType!
  thrustersSimulationSetThrustersFwd(component: ThrusterInputType!): ThrustersSimulationInputsType!
  thrustersSimulationSetThrustersSeawaterSupply(component: BoundaryInputType!): ThrustersSimulationInputsType!
  thrustersSimulationSetThrustersModuleSupply(component: TemperatureBoundaryInputType!): ThrustersSimulationInputsType!
  thrustersSimulationSetThrustersPcs(component: PcsInputType!): ThrustersSimulationInputsType!
  simulationPlay(playbackRate: Float! = 1): Void
  simulationPause: Void
  simulationStep(seconds: Float!): Void
}

input OverpressureTemperatureBoundaryInputType {
  temperature: Float!
  overpressure: Float!
}

type OverpressureTemperatureBoundarySimulationType {
  temperature: FloatStampedType!
  overpressure: FloatStampedType!
}

type PcmControlModeType {
  mode: String!
}

type PcmControlValuesType {
  pcmPump: ControlPumpType! @jsonSchemaDirective(yardTag: "50001017", componentType: "pump", valveType: null)
  pcmSwitchChargingReturn: ControlValveType! @jsonSchemaDirective(yardTag: "50001062-02", componentType: "valve", valveType: "switch")
  pcmFlowcontrolModule1: ControlValveType! @jsonSchemaDirective(yardTag: "50001064-04", componentType: "valve", valveType: "flowcontrol")
  pcmFlowcontrolModule2: ControlValveType! @jsonSchemaDirective(yardTag: "50001064-05", componentType: "valve", valveType: "flowcontrol")
  pcmFlowcontrolModule3: ControlValveType! @jsonSchemaDirective(yardTag: "50001064-06", componentType: "valve", valveType: "flowcontrol")
  pcmFlowcontrolModule4: ControlValveType! @jsonSchemaDirective(yardTag: "50001064-07", componentType: "valve", valveType: "flowcontrol")
  pcmSwitchDischarging: ControlValveType! @jsonSchemaDirective(yardTag: "50001066-01", componentType: "valve", valveType: "switch")
  pcmSwitchChargingSupply: ControlValveType! @jsonSchemaDirective(yardTag: "50001090-01", componentType: "valve", valveType: "switch")
  pcmSwitchConsumers: ControlValveType! @jsonSchemaDirective(yardTag: "50001071-02", componentType: "valve", valveType: "switch")
  pcmModule1: ControlPcmType! @jsonSchemaDirective(yardTag: "50001049", componentType: "pcm", valveType: null)
}

input PcmInputType {
  on: Boolean!
}

type PcmParametersType {
  pcmDischargeFlow: Float!
  pcmChargeFlow: Float!
  minimumChargingDt: Float!
  minimumChargingTemperature: Float!
  pumpTuning: [Float!]!
  supplyingEnabled: Boolean!
  chargingEnabled: Boolean!
  module1FlowBalanceTuning: [Float!]!
  module2FlowBalanceTuning: [Float!]!
  module3FlowBalanceTuning: [Float!]!
  module4FlowBalanceTuning: [Float!]!
}

type PcmSensorValuesType {
  pcmPump: SensorPumpType! @jsonSchemaDirective(yardTag: "50001017", componentType: "pump", valveType: null)
  pcmTemperatureProducersReturn: SensorTemperatureSensorType! @jsonSchemaDirective(yardTag: "50001038-31", componentType: "temperature_sensor", valveType: null)
  pcmTemperatureProducersSupply: SensorTemperatureSensorType! @jsonSchemaDirective(yardTag: "50001038-55", componentType: "temperature_sensor", valveType: null)
  pcmTemperatureModule1Out: SensorTemperatureSensorType! @jsonSchemaDirective(yardTag: "50001038-60", componentType: "temperature_sensor", valveType: null)
  pcmTemperatureModule2Out: SensorTemperatureSensorType! @jsonSchemaDirective(yardTag: "50001038-33", componentType: "temperature_sensor", valveType: null)
  pcmTemperatureModule3Out: SensorTemperatureSensorType! @jsonSchemaDirective(yardTag: "50001038-34", componentType: "temperature_sensor", valveType: null)
  pcmTemperatureModule4Out: SensorTemperatureSensorType! @jsonSchemaDirective(yardTag: "50001038-35", componentType: "temperature_sensor", valveType: null)
  pcmModule1: SensorPcmType! @jsonSchemaDirective(yardTag: "50001049", componentType: "pcm", valveType: null)
  pcmModule2: SensorPcmType! @jsonSchemaDirective(yardTag: "50001050", componentType: "pcm", valveType: null)
  pcmModule3: SensorPcmType! @jsonSchemaDirective(yardTag: "50001051", componentType: "pcm", valveType: null)
  pcmModule4: SensorPcmType! @jsonSchemaDirective(yardTag: "50001052", componentType: "pcm", valveType: null)
  pcmFlowModule1: SensorFlowSensorType! @jsonSchemaDirective(yardTag: "50001057-18", componentType: "flow_sensor", valveType: null)
  pcmFlowModule2: SensorFlowSensorType! @jsonSchemaDirective(yardTag: "50001057-19", componentType: "flow_sensor", valveType: null)
  pcmFlowModule3: SensorFlowSensorType! @jsonSchemaDirective(yardTag: "50001057-20", componentType: "flow_sensor", valveType: null)
  pcmFlowModule4: SensorFlowSensorType! @jsonSchemaDirective(yardTag: "50001057-21", componentType: "flow_sensor", valveType: null)
  pcmSwitchChargingReturn: SensorValveType! @jsonSchemaDirective(yardTag: "50001062-02", componentType: "valve", valveType: "switch")
  pcmFlowcontrolModule1: SensorValveType! @jsonSchemaDirective(yardTag: "50001064-04", componentType: "valve", valveType: "flowcontrol")
  pcmFlowcontrolModule2: SensorValveType! @jsonSchemaDirective(yardTag: "50001064-05", componentType: "valve", valveType: "flowcontrol")
  pcmFlowcontrolModule3: SensorValveType! @jsonSchemaDirective(yardTag: "50001064-06", componentType: "valve", valveType: "flowcontrol")
  pcmFlowcontrolModule4: SensorValveType! @jsonSchemaDirective(yardTag: "50001064-07", componentType: "valve", valveType: "flowcontrol")
  pcmSwitchDischarging: SensorValveType! @jsonSchemaDirective(yardTag: "50001066-01", componentType: "valve", valveType: "switch")
  pcmSwitchChargingSupply: SensorValveType! @jsonSchemaDirective(yardTag: "50001090-01", componentType: "valve", valveType: "switch")
  pcmSwitchConsumers: SensorValveType! @jsonSchemaDirective(yardTag: "50001071-02", componentType: "valve", valveType: "switch")
}

type PcmSensorValuesTypePcmControlValuesTypePcmParametersTypePcmControlModeTypeControlModule {
  sensorValues: PcmSensorValuesType
  controlValues: PcmControlValuesType
  parameters: PcmParametersType
  controlMode: PcmSensorValuesTypePcmControlValuesTypePcmParametersTypePcmControlModeTypeSwitchingControlModeType
}

type PcmSensorValuesTypePcmControlValuesTypePcmParametersTypePcmControlModeTypeSwitchingControlModeType {
  automaticMode: PcmControlModeType
  automatic: Boolean!
}

type PcmSimulationInputsType {
  pcmProducersSupply: BoundarySimulationType!
  pcmConsumersSupply: TemperatureBoundarySimulationType!
  pcmFreshwaterSupply: BoundarySimulationType!
}

type PcmSimulationOutputsType {
  pcmConsumersReturn: BoundarySimulationType!
  pcmProducersReturn: BoundarySimulationType!
  pcmFreshwaterReturn: BoundarySimulationType!
}

input PcsInputType {
  mode: PcsMode!
}

enum PcsMode {
  OFF
  MANEUVERING
  PROPULSION
  REGENERATION
}

type PcsModeStampedType {
  value: PcsMode!
  timestamp: DateTime!
}

type PcsSimulationType {
  mode: PcsModeStampedType!
}

input PidControllerValuesInputType {
  setpoint: Float!
  measurement: Float
  output: Float
  error: Float
  enabled: Boolean!
  tuning: [Float!]!
  components: [Float!]!
}

input PumpInputType {
  dutypoint: Float!
  on: Boolean!
}

type PvtControlModeType {
  aft: PvtGroupControlModeType!
  fwd: PvtGroupControlModeType!
  owners: PvtGroupControlModeType!
}

type PvtControlValuesType {
  pvtPumpMainFwd: ControlPumpType! @jsonSchemaDirective(yardTag: "50001018", componentType: "pump", valveType: null)
  pvtPumpMainAft: ControlPumpType! @jsonSchemaDirective(yardTag: "50001019", componentType: "pump", valveType: null)
  pvtPumpOwners: ControlPumpType! @jsonSchemaDirective(yardTag: "50001021", componentType: "pump", valveType: null)
  pvtMixMainFwd: ControlValveType! @jsonSchemaDirective(yardTag: "50001044-01", componentType: "valve", valveType: "mix")
  pvtMixMainAft: ControlValveType! @jsonSchemaDirective(yardTag: "50001044-02", componentType: "valve", valveType: "mix")
  pvtMixOwners: ControlValveType! @jsonSchemaDirective(yardTag: "50001043-01", componentType: "valve", valveType: "mix")
  pvtSwitchMainFwd: ControlValveType! @jsonSchemaDirective(yardTag: "50001067-01", componentType: "valve", valveType: "switch")
  pvtSwitchMainAft: ControlValveType! @jsonSchemaDirective(yardTag: "50001067-02", componentType: "valve", valveType: "switch")
  pvtSwitchOwners: ControlValveType! @jsonSchemaDirective(yardTag: "50001069-01", componentType: "valve", valveType: "switch")
  pvtMixExchanger: ControlValveType! @jsonSchemaDirective(yardTag: "50001047-02", componentType: "valve", valveType: "mix")
}

type PvtGroupControlModeType {
  mode: String!
}

type PvtParametersType {
  maximumSupplyTemperature: Float!
  recoveryTemperature: Float!
  warmupTemperature: Float!
  recoveryActivationStringTemperature: Float!
  minimumReturnTemperature: Float!
  mainFwdMinimumPumpDutypoint: Float!
  mainAftMinimumPumpDutypoint: Float!
  ownersMinimumPumpDutypoint: Float!
  heatDumpTuning: [Float!]!
  mainFwdMixTuning: [Float!]!
  mainAftMixTuning: [Float!]!
  ownersMixTuning: [Float!]!
  mainFwdPumpTuning: [Float!]!
  mainAftPumpTuning: [Float!]!
  ownersPumpTuning: [Float!]!
}

type PvtSensorValuesType {
  pvtPumpMainFwd: SensorPumpType! @jsonSchemaDirective(yardTag: "50001018", componentType: "pump", valveType: null)
  pvtPumpMainAft: SensorPumpType! @jsonSchemaDirective(yardTag: "50001019", componentType: "pump", valveType: null)
  pvtPumpOwners: SensorPumpType! @jsonSchemaDirective(yardTag: "50001021", componentType: "pump", valveType: null)
  pvtTemperatureMainFwdReturn: SensorTemperatureSensorType! @jsonSchemaDirective(yardTag: "50001038-03", componentType: "temperature_sensor", valveType: null)
  pvtTemperatureMainFwdSupply: SensorTemperatureSensorType! @jsonSchemaDirective(yardTag: "50001038-23", componentType: "temperature_sensor", valveType: null)
  pvtTemperatureMainAftReturn: SensorTemperatureSensorType! @jsonSchemaDirective(yardTag: "50001038-73", componentType: "temperature_sensor", valveType: null)
  pvtTemperatureMainAftSupply: SensorTemperatureSensorType! @jsonSchemaDirective(yardTag: "50001038-22", componentType: "temperature_sensor", valveType: null)
  pvtTemperatureOwnersSupply: SensorTemperatureSensorType! @jsonSchemaDirective(yardTag: "50001038-21", componentType: "temperature_sensor", valveType: null)
  pvtTemperatureOwnersReturn: SensorTemperatureSensorType! @jsonSchemaDirective(yardTag: "50001038-04", componentType: "temperature_sensor", valveType: null)
  pvtMixMainFwd: SensorValveType! @jsonSchemaDirective(yardTag: "50001044-01", componentType: "valve", valveType: "mix")
  pvtMixMainAft: SensorValveType! @jsonSchemaDirective(yardTag: "50001044-02", componentType: null, valveType: "mix")
  pvtMixOwners: SensorValveType! @jsonSchemaDirective(yardTag: "50001043-01", componentType: "valve", valveType: "mix")
  pvtFlowMainFwdRecovery: SensorFlowSensorType! @jsonSchemaDirective(yardTag: "50001058-12", componentType: "flow_sensor", valveType: null)
  pvtFlowMainAftRecovery: SensorFlowSensorType! @jsonSchemaDirective(yardTag: "50001058-13", componentType: "flow_sensor", valveType: null)
  pvtFlowOwnersRecovery: SensorFlowSensorType! @jsonSchemaDirective(yardTag: "50001057-03", componentType: "flow_sensor", valveType: null)
  pvtPressureMainFwd: SensorPressureSensorType! @jsonSchemaDirective(yardTag: "50001097-03", componentType: "pressure_sensor", valveType: null)
  pvtPressureMainAft: SensorPressureSensorType! @jsonSchemaDirective(yardTag: "50001097-04", componentType: "pressure_sensor", valveType: null)
  pvtPressureOwners: SensorPressureSensorType! @jsonSchemaDirective(yardTag: "50001097-05", componentType: "pressure_sensor", valveType: null)
  pvtPressureSupply: SensorPressureSensorType! @jsonSchemaDirective(yardTag: "50001097-06", componentType: "pressure_sensor", valveType: null)
  pvtSwitchMainFwd: SensorValveType! @jsonSchemaDirective(yardTag: "50001067-01", componentType: "valve", valveType: "switch")
  pvtSwitchMainAft: SensorValveType! @jsonSchemaDirective(yardTag: "50001067-02", componentType: "valve", valveType: "switch")
  pvtSwitchOwners: SensorValveType! @jsonSchemaDirective(yardTag: "50001069-01", componentType: "valve", valveType: "switch")
  pvtMixExchanger: SensorValveType! @jsonSchemaDirective(yardTag: "50001047-02", componentType: "valve", valveType: "mix")
  pvtTemperatureSupply: SensorTemperatureSensorType! @jsonSchemaDirective(yardTag: "50001038-24", componentType: "temperature_sensor", valveType: null)
  pvtTemperatureMainString11Return: SensorTemperatureSensorType! @jsonSchemaDirective(yardTag: "50009005-01", componentType: "temperature_sensor", valveType: null)
  pvtTemperatureMainString12Return: SensorTemperatureSensorType! @jsonSchemaDirective(yardTag: "50009005-19", componentType: "temperature_sensor", valveType: null)
  pvtTemperatureMainString21Return: SensorTemperatureSensorType! @jsonSchemaDirective(yardTag: "50009005-03", componentType: "temperature_sensor", valveType: null)
  pvtTemperatureMainString22Return: SensorTemperatureSensorType! @jsonSchemaDirective(yardTag: "50009005-04", componentType: "temperature_sensor", valveType: null)
  pvtTemperatureMainString3Return: SensorTemperatureSensorType! @jsonSchemaDirective(yardTag: "50009005-05", componentType: "temperature_sensor", valveType: null)
  pvtTemperatureMainString4Return: SensorTemperatureSensorType! @jsonSchemaDirective(yardTag: "50009005-06", componentType: "temperature_sensor", valveType: null)
  pvtTemperatureMainString51Return: SensorTemperatureSensorType! @jsonSchemaDirective(yardTag: "50009005-07", componentType: "temperature_sensor", valveType: null)
  pvtTemperatureMainString52Return: SensorTemperatureSensorType! @jsonSchemaDirective(yardTag: "50009005-08", componentType: "temperature_sensor", valveType: null)
  pvtTemperatureMainString61Return: SensorTemperatureSensorType! @jsonSchemaDirective(yardTag: "50009005-09", componentType: "temperature_sensor", valveType: null)
  pvtTemperatureMainString62Return: SensorTemperatureSensorType! @jsonSchemaDirective(yardTag: "50009005-10", componentType: "temperature_sensor", valveType: null)
  pvtFlowMainString11: SensorFlowSensorType! @jsonSchemaDirective(yardTag: "50009006-01", componentType: "flow_sensor", valveType: null)
  pvtFlowMainString12: SensorFlowSensorType! @jsonSchemaDirective(yardTag: "50009009-05", componentType: "flow_sensor", valveType: null)
  pvtFlowMainString21: SensorFlowSensorType! @jsonSchemaDirective(yardTag: "50009006-03", componentType: "flow_sensor", valveType: null)
  pvtFlowMainString22: SensorFlowSensorType! @jsonSchemaDirective(yardTag: "50009006-04", componentType: "flow_sensor", valveType: null)
  pvtFlowMainString3: SensorFlowSensorType! @jsonSchemaDirective(yardTag: "50009009-01", componentType: "flow_sensor", valveType: null)
  pvtFlowMainString4: SensorFlowSensorType! @jsonSchemaDirective(yardTag: "50009009-02", componentType: "flow_sensor", valveType: null)
  pvtFlowMainString51: SensorFlowSensorType! @jsonSchemaDirective(yardTag: "50009006-05", componentType: "flow_sensor", valveType: null)
  pvtFlowMainString52: SensorFlowSensorType! @jsonSchemaDirective(yardTag: "50009006-06", componentType: "flow_sensor", valveType: null)
  pvtFlowMainString61: SensorFlowSensorType! @jsonSchemaDirective(yardTag: "50009006-07", componentType: "flow_sensor", valveType: null)
  pvtFlowMainString62: SensorFlowSensorType! @jsonSchemaDirective(yardTag: "50009006-08", componentType: "flow_sensor", valveType: null)
  pvtTemperatureMainString1Supply: SensorTemperatureSensorType! @jsonSchemaDirective(yardTag: "50009005-26", componentType: "temperature_sensor", valveType: null)
  pvtTemperatureMainString2Supply: SensorTemperatureSensorType! @jsonSchemaDirective(yardTag: "50009005-25", componentType: "temperature_sensor", valveType: null)
  pvtTemperatureMainString3Supply: SensorTemperatureSensorType! @jsonSchemaDirective(yardTag: "50009005-24", componentType: "temperature_sensor", valveType: null)
  pvtTemperatureMainString4Supply: SensorTemperatureSensorType! @jsonSchemaDirective(yardTag: "50009005-23", componentType: "temperature_sensor", valveType: null)
  pvtTemperatureMainString5Supply: SensorTemperatureSensorType! @jsonSchemaDirective(yardTag: "50009005-22", componentType: "temperature_sensor", valveType: null)
  pvtTemperatureMainString6Supply: SensorTemperatureSensorType! @jsonSchemaDirective(yardTag: "50009005-21", componentType: "temperature_sensor", valveType: null)
  pvtTemperatureMainString71Return: SensorTemperatureSensorType! @jsonSchemaDirective(yardTag: "50009005-11", componentType: "temperature_sensor", valveType: null)
  pvtTemperatureMainString72Return: SensorTemperatureSensorType! @jsonSchemaDirective(yardTag: "50009005-12", componentType: "temperature_sensor", valveType: null)
  pvtTemperatureMainString81Return: SensorTemperatureSensorType! @jsonSchemaDirective(yardTag: "50009005-13", componentType: "temperature_sensor", valveType: null)
  pvtTemperatureMainString82Return: SensorTemperatureSensorType! @jsonSchemaDirective(yardTag: "50009005-14", componentType: "temperature_sensor", valveType: null)
  pvtTemperatureMainString9Return: SensorTemperatureSensorType! @jsonSchemaDirective(yardTag: "50009005-15", componentType: "temperature_sensor", valveType: null)
  pvtTemperatureMainString10Return: SensorTemperatureSensorType! @jsonSchemaDirective(yardTag: "50009005-16", componentType: "temperature_sensor", valveType: null)
  pvtTemperatureMainString111Return: SensorTemperatureSensorType! @jsonSchemaDirective(yardTag: "50009005-17", componentType: "temperature_sensor", valveType: null)
  pvtTemperatureMainString112Return: SensorTemperatureSensorType! @jsonSchemaDirective(yardTag: "50009005-18", componentType: "temperature_sensor", valveType: null)
  pvtTemperatureMainString13Return: SensorTemperatureSensorType! @jsonSchemaDirective(yardTag: "50009005-20", componentType: "temperature_sensor", valveType: null)
  pvtFlowMainString71: SensorFlowSensorType! @jsonSchemaDirective(yardTag: "50009006-09", componentType: "flow_sensor", valveType: null)
  pvtFlowMainString72: SensorFlowSensorType! @jsonSchemaDirective(yardTag: "50009006-10", componentType: "flow_sensor", valveType: null)
  pvtFlowMainString81: SensorFlowSensorType! @jsonSchemaDirective(yardTag: "50009006-11", componentType: "flow_sensor", valveType: null)
  pvtFlowMainString82: SensorFlowSensorType! @jsonSchemaDirective(yardTag: "50009006-12", componentType: "flow_sensor", valveType: null)
  pvtFlowMainString9: SensorFlowSensorType! @jsonSchemaDirective(yardTag: "50009009-03", componentType: "flow_sensor", valveType: null)
  pvtFlowMainString10: SensorFlowSensorType! @jsonSchemaDirective(yardTag: "50009009-04", componentType: "flow_sensor", valveType: null)
  pvtFlowMainString111: SensorFlowSensorType! @jsonSchemaDirective(yardTag: "50009006-13", componentType: "flow_sensor", valveType: null)
  pvtFlowMainString112: SensorFlowSensorType! @jsonSchemaDirective(yardTag: "50009006-14", componentType: "flow_sensor", valveType: null)
  pvtFlowMainString13: SensorFlowSensorType! @jsonSchemaDirective(yardTag: "50009009-06", componentType: "flow_sensor", valveType: null)
  pvtTemperatureMainString7Supply: SensorTemperatureSensorType! @jsonSchemaDirective(yardTag: "50009005-27", componentType: "temperature_sensor", valveType: null)
  pvtTemperatureMainString8Supply: SensorTemperatureSensorType! @jsonSchemaDirective(yardTag: "50009005-28", componentType: "temperature_sensor", valveType: null)
  pvtTemperatureMainString9Supply: SensorTemperatureSensorType! @jsonSchemaDirective(yardTag: "50009005-29", componentType: "temperature_sensor", valveType: null)
  pvtTemperatureMainString10Supply: SensorTemperatureSensorType! @jsonSchemaDirective(yardTag: "50009005-30", componentType: "temperature_sensor", valveType: null)
  pvtTemperatureMainString11Supply: SensorTemperatureSensorType! @jsonSchemaDirective(yardTag: "50009005-31", componentType: "temperature_sensor", valveType: null)
  pvtTemperatureMainString12Supply: SensorTemperatureSensorType! @jsonSchemaDirective(yardTag: "50009005-32", componentType: "temperature_sensor", valveType: null)
  pvtTemperatureMainString13Supply: SensorTemperatureSensorType! @jsonSchemaDirective(yardTag: "50009005-33", componentType: "temperature_sensor", valveType: null)
  pvtTemperatureOwnersString1Return: SensorTemperatureSensorType! @jsonSchemaDirective(yardTag: "50009005-34", componentType: "temperature_sensor", valveType: null)
  pvtTemperatureOwnersString2Return: SensorTemperatureSensorType! @jsonSchemaDirective(yardTag: "50009005-35", componentType: "temperature_sensor", valveType: null)
  pvtTemperatureOwnersString3Return: SensorTemperatureSensorType! @jsonSchemaDirective(yardTag: "50009005-36", componentType: "temperature_sensor", valveType: null)
  pvtTemperatureOwnersString4Return: SensorTemperatureSensorType! @jsonSchemaDirective(yardTag: "50009005-37", componentType: "temperature_sensor", valveType: null)
  pvtTemperatureOwnersString5Return: SensorTemperatureSensorType! @jsonSchemaDirective(yardTag: "50009005-38", componentType: "temperature_sensor", valveType: null)
  pvtTemperatureOwnersString6Return: SensorTemperatureSensorType! @jsonSchemaDirective(yardTag: "50009005-39", componentType: "temperature_sensor", valveType: null)
  pvtFlowOwnersString1: SensorFlowSensorType! @jsonSchemaDirective(yardTag: "50009009-07", componentType: "flow_sensor", valveType: null)
  pvtFlowOwnersString2: SensorFlowSensorType! @jsonSchemaDirective(yardTag: "50009009-08", componentType: "flow_sensor", valveType: null)
  pvtFlowOwnersString3: SensorFlowSensorType! @jsonSchemaDirective(yardTag: "50009009-09", componentType: "flow_sensor", valveType: null)
  pvtFlowOwnersString4: SensorFlowSensorType! @jsonSchemaDirective(yardTag: "50009009-10", componentType: "flow_sensor", valveType: null)
  pvtFlowOwnersString5: SensorFlowSensorType! @jsonSchemaDirective(yardTag: "50009009-11", componentType: "flow_sensor", valveType: null)
  pvtFlowOwnersString6: SensorFlowSensorType! @jsonSchemaDirective(yardTag: "50009009-12", componentType: "flow_sensor", valveType: null)
  pvtTemperatureOwnersString1Supply: SensorTemperatureSensorType! @jsonSchemaDirective(yardTag: "50009005-40", componentType: "temperature_sensor", valveType: null)
  pvtTemperatureOwnersString2Supply: SensorTemperatureSensorType! @jsonSchemaDirective(yardTag: "50009005-41", componentType: "temperature_sensor", valveType: null)
  pvtTemperatureOwnersString3Supply: SensorTemperatureSensorType! @jsonSchemaDirective(yardTag: "50009005-42", componentType: "temperature_sensor", valveType: null)
  pvtTemperatureOwnersString4Supply: SensorTemperatureSensorType! @jsonSchemaDirective(yardTag: "50009005-43", componentType: "temperature_sensor", valveType: null)
  pvtTemperatureOwnersString5Supply: SensorTemperatureSensorType! @jsonSchemaDirective(yardTag: "50009005-44", componentType: "temperature_sensor", valveType: null)
  pvtTemperatureOwnersString6Supply: SensorTemperatureSensorType! @jsonSchemaDirective(yardTag: "50009005-45", componentType: "temperature_sensor", valveType: null)
}

type PvtSensorValuesTypePvtControlValuesTypePvtParametersTypePvtControlModeTypeControlModule {
  sensorValues: PvtSensorValuesType
  controlValues: PvtControlValuesType
  parameters: PvtParametersType
  controlMode: PvtSensorValuesTypePvtControlValuesTypePvtParametersTypePvtControlModeTypeSwitchingControlModeType
}

type PvtSensorValuesTypePvtControlValuesTypePvtParametersTypePvtControlModeTypeSwitchingControlModeType {
  automaticMode: PvtControlModeType
  automatic: Boolean!
}

type PvtSimulationInputsType {
  pvtMainFwd: HeatSourceSimulationType!
  pvtMainAft: HeatSourceSimulationType!
  pvtOwners: HeatSourceSimulationType!
  pvtModuleSupply: TemperatureBoundarySimulationType!
  pvtSeawaterSupply: BoundarySimulationType!
}

type PvtSimulationOutputsType {
  pvtModuleReturn: BoundarySimulationType!
  pvtModuleSupply: FlowBoundarySimulationType!
  pvtSeawaterReturn: TemperatureBoundarySimulationType!
}

type Query {
  modules: ControlModules!
  simulation: SimulationState
}

type SensorCalculatedFlowType {
  flow: FloatStampedType!
}

type SensorFlowSensorType {
  flow: FloatStampedType!
  temperature: FloatStampedType!
}

type SensorHeatExchangerType {
  deltaT: FloatStampedType!
  heat: FloatStampedType!
}

type SensorHeatPumpType {
  deltaT: FloatStampedType!
  heat: FloatStampedType!
}

type SensorHvacExchangerType {
  deltaT: FloatStampedType!
  heat: FloatStampedType!
}

type SensorLevelSensorType {
  level: FloatStampedType!
}

type SensorPcmType {
  charged: BoolStampedType!
}

type SensorPcsType {
  mode: PcsModeStampedType!
}

type SensorPressureSensorType {
  pressure: FloatStampedType!
}

type SensorPumpType {
  speed: FloatStampedType!
  opTime: FloatStampedType!
  flow: FloatStampedType!
}

type SensorTemperatureDeltaType {
  deltaT: FloatStampedType!
}

type SensorTemperatureSensorType {
  temperature: FloatStampedType!
}

type SensorThrusterType {
  active: BoolStampedType!
}

type SensorValveType {
  positionRel: FloatStampedType!
}

union SimulationInputsType = ThrustersSimulationInputsType | PcmSimulationInputsType | PvtSimulationInputsType | ConsumersSimulationInputsType | HighTemperatureSimulationInputsType | BoilersSimulationInputsType

union SimulationOutputsType = ThrustersSimulationOutputsType | PcmSimulationOutputsType | PvtSimulationOutputsType | ConsumersSimulationOutputsType | HighTemperatureSimulationOutputsType | BoilersSimulationOutputsType

type SimulationState {
  time: DateTime!
  status: String!
  inputs: SimulationInputsType
  outputs: SimulationOutputsType
}

enum TankState {
  IN_USE
  FILLING
  BOOSTING
  DISABLED
  NEEDS_BOOST
  NEEDS_FILL
  STANDBY
}

type TankStateStampedType {
  value: TankState!
  timestamp: DateTime!
}

input TanksControllerValuesInputType {
  tank1State: TankState!
  tank2State: TankState!
  tank3State: TankState!
  timeToFill: Float
}

input TemperatureBoundaryInputType {
  temperature: Float!
}

type TemperatureBoundarySimulationType {
  temperature: FloatStampedType!
}

input ThrusterInputType {
  heatFlow: Float!
  active: Boolean!
}

type ThrusterSimulationType {
  heatFlow: FloatStampedType!
  active: BoolStampedType!
}

type ThrustersControlModeType {
  mode: String!
}

type ThrustersControlValuesType {
  thrustersPump1: ControlPumpType! @jsonSchemaDirective(yardTag: "50001194", componentType: "pump", valveType: null)
  thrustersPump2: ControlPumpType! @jsonSchemaDirective(yardTag: "50001195", componentType: "pump", valveType: null)
  thrustersMixRecovery: ControlValveType! @jsonSchemaDirective(yardTag: "50001074", componentType: "valve", valveType: "mix")
  thrustersMixExchanger: ControlValveType! @jsonSchemaDirective(yardTag: "50001214-01", componentType: "valve", valveType: "mix")
  thrustersFlowcontrolAft: ControlValveType! @jsonSchemaDirective(yardTag: "50001215", componentType: "valve", valveType: "flowcontrol")
  thrustersFlowcontrolFwd: ControlValveType! @jsonSchemaDirective(yardTag: "50001064-02", componentType: "valve", valveType: "flowcontrol")
  thrustersShutoffRecovery: ControlValveType! @jsonSchemaDirective(yardTag: "50001066-03", componentType: "valve", valveType: "shutoff")
  thrustersSwitchAft: ControlValveType! @jsonSchemaDirective(yardTag: "50001091-01", componentType: "valve", valveType: "switch")
  thrustersSwitchFwd: ControlValveType! @jsonSchemaDirective(yardTag: "50001091-02", componentType: "valve", valveType: "switch")
}

type ThrustersParametersType {
  maximumSupplyTemperature: Float!
  coolingTemperature: Float!
  coolingFlow: Float!
  recoveryTemperature: Float!
  warmupTemperature: Float!
  thrustersMinimumFlow: Float!
  thrustersMaximumFlow: Float!
  pumpTuning: [Float!]!
  warmupMixTuning: [Float!]!
  heatDumpTuning: [Float!]!
  aftFlowBalanceTuning: [Float!]!
  fwdFlowBalanceTuning: [Float!]!
  aftTemperatureTuning: [Float!]!
  fwdTemperatureTuning: [Float!]!
}

type ThrustersSensorValuesType {
  thrustersPump1: SensorPumpType! @jsonSchemaDirective(yardTag: "50001194", componentType: "pump", valveType: null)
  thrustersPump2: SensorPumpType! @jsonSchemaDirective(yardTag: "50001195", componentType: "pump", valveType: null)
  thrustersTemperatureAftReturn: SensorTemperatureSensorType! @jsonSchemaDirective(yardTag: "50001038-01", componentType: "temperature_sensor", valveType: null)
  thrustersTemperatureFwdReturn: SensorTemperatureSensorType! @jsonSchemaDirective(yardTag: "50001038-02", componentType: "temperature_sensor", valveType: null)
  thrustersTemperatureSupply: SensorTemperatureSensorType! @jsonSchemaDirective(yardTag: "50001038-28", componentType: "temperature_sensor", valveType: null)
  thrustersTemperatureRecoveryMix: SensorTemperatureSensorType! @jsonSchemaDirective(yardTag: "50001038-30", componentType: "temperature_sensor", valveType: null)
  thrustersMixRecovery: SensorValveType! @jsonSchemaDirective(yardTag: "50001074", componentType: "valve", valveType: "mix")
  thrustersMixExchanger: SensorValveType! @jsonSchemaDirective(yardTag: "50001214-01", componentType: "valve", valveType: "mix")
  thrustersFlowFwd: SensorFlowSensorType! @jsonSchemaDirective(yardTag: "50001057-22", componentType: "flow_sensor", valveType: null)
  thrustersFlowAft: SensorFlowSensorType! @jsonSchemaDirective(yardTag: "50001218-02", componentType: "flow_sensor", valveType: null)
  thrustersFlowcontrolAft: SensorValveType! @jsonSchemaDirective(yardTag: "50001215", componentType: "valve", valveType: "flowcontrol")
  thrustersFlowcontrolFwd: SensorValveType! @jsonSchemaDirective(yardTag: "50001064-02", componentType: "valve", valveType: "flowcontrol")
  thrustersShutoffRecovery: SensorValveType! @jsonSchemaDirective(yardTag: "50001066-03", componentType: "valve", valveType: "shutoff")
  thrustersSwitchAft: SensorValveType! @jsonSchemaDirective(yardTag: "50001091-01", componentType: "valve", valveType: "switch")
  thrustersSwitchFwd: SensorValveType! @jsonSchemaDirective(yardTag: "50001091-02", componentType: "valve", valveType: "switch")
  thrustersFlowRecovery: SensorFlowSensorType! @jsonSchemaDirective(yardTag: "50001218-01", componentType: "flow_sensor", valveType: null)
  thrustersPressurePump: SensorPressureSensorType! @jsonSchemaDirective(yardTag: "50001097-01", componentType: "pressure_sensor", valveType: null)
  thrustersPressureRelief: SensorPressureSensorType! @jsonSchemaDirective(yardTag: "50001097-02", componentType: "pressure_sensor", valveType: null)
  thrustersAft: SensorThrusterType! @jsonSchemaDirective(yardTag: "15001001", componentType: "thruster", valveType: null)
  thrustersFwd: SensorThrusterType! @jsonSchemaDirective(yardTag: "15001002", componentType: "thruster", valveType: null)
  thrustersPcs: SensorPcsType! @jsonSchemaDirective(yardTag: "1500", componentType: "pcs", valveType: null)
}

type ThrustersSensorValuesTypeThrustersControlValuesTypeThrustersParametersTypeThrustersControlModeTypeControlModule {
  sensorValues: ThrustersSensorValuesType
  controlValues: ThrustersControlValuesType
  parameters: ThrustersParametersType
  controlMode: ThrustersSensorValuesTypeThrustersControlValuesTypeThrustersParametersTypeThrustersControlModeTypeSwitchingControlModeType
}

type ThrustersSensorValuesTypeThrustersControlValuesTypeThrustersParametersTypeThrustersControlModeTypeSwitchingControlModeType {
  automaticMode: ThrustersControlModeType
  automatic: Boolean!
}

type ThrustersSimulationInputsType {
  thrustersAft: ThrusterSimulationType!
  thrustersFwd: ThrusterSimulationType!
  thrustersSeawaterSupply: BoundarySimulationType!
  thrustersModuleSupply: TemperatureBoundarySimulationType!
  thrustersPcs: PcsSimulationType!
}

type ThrustersSimulationOutputsType {
  thrustersSeawaterReturn: TemperatureBoundarySimulationType!
  thrustersModuleSupply: FlowBoundarySimulationType!
  thrustersModuleReturn: BoundarySimulationType!
}

input ValveInputType {
  setpoint: Float!
}

"""Represents NULL values"""
scalar Void
