- id: '1739785047573'
  alias: Owner's cabin - Ambient
  description: ''
  triggers:
  - trigger: state
    entity_id:
    - input_number.owners_cabin_ambient
  conditions: []
  actions:
  - action: light.turn_on
    metadata: {}
    data:
      brightness_pct: '{{ trigger.to_state.state | int }}'
    target:
      entity_id: light.owner_s_cabin_ambient
  mode: single
- id: '1739785071863'
  alias: Owner's cabin - Mood
  description: ''
  triggers:
  - trigger: state
    entity_id:
    - input_number.owners_cabin_mood
  conditions: []
  actions:
  - action: light.turn_on
    metadata: {}
    data:
      brightness_pct: '{{ trigger.to_state.state | int }}'
    target:
      entity_id: light.owner_s_cabin_mood
  mode: single
