# Loads default set of integrations. Do not remove.
default_config:

# Load frontend themes from the themes folder
frontend:
  themes: !include_dir_merge_named themes

light:
  - platform: b2p
    name: "Owner's cabin - Ambient"
    host: host.docker.internal
    pdc: 1
    channel: 1
  - platform: b2p
    name: "Owner's cabin - Mood"
    host: host.docker.internal
    pdc: 1
    channel: 2

cover:
  - platform: template
    covers:
      owners_cabin_main_shear:
        unique_id: template_owners_cabin_main_shear
        friendly_name: "Owner's cabin main shear"
        position_template: "{{ states.input_number.owners_cabin_main_shear.state | float }}"
        set_cover_position:
          service: input_number.set_value
          target:
            entity_id: input_number.owners_cabin_main_shear
          data:
            value: "{{position}}"
      owners_cabin_main_blind:
        unique_id: template_owners_cabin_main_blind
        friendly_name: "Owner's cabin main blind"
        position_template: "{{ states.input_number.owners_cabin_main_blind.state | float }}"
        set_cover_position:
          service: input_number.set_value
          target:
            entity_id: input_number.owners_cabin_main_blind
          data:
            value: "{{position}}"
      owners_cabin_port_shear:
        unique_id: template_owners_cabin_port_shear
        friendly_name: "Owner's cabin port shear"
        position_template: "{{ states.input_number.owners_cabin_port_shear.state | float }}"
        set_cover_position:
          service: input_number.set_value
          target:
            entity_id: input_number.owners_cabin_port_shear
          data:
            value: "{{position}}"
      owners_cabin_port_blind:
        unique_id: template_owners_cabin_port_blind
        friendly_name: "Owner's cabin port blind"
        position_template: "{{ states.input_number.owners_cabin_port_blind.state | float }}"
        set_cover_position:
          service: input_number.set_value
          target:
            entity_id: input_number.owners_cabin_port_blind
          data:
            value: "{{position}}"
      owners_cabin_starboard_shear:
        unique_id: template_owners_cabin_starboard_shear
        friendly_name: "Owner's cabin starboard shear"
        position_template: "{{ states.input_number.owners_cabin_starboard_shear.state | float }}"
        set_cover_position:
          service: input_number.set_value
          target:
            entity_id: input_number.owners_cabin_starboard_shear
          data:
            value: "{{position}}"
      owners_cabin_starboard_blind:
        unique_id: template_owners_cabin_starboard_blind
        friendly_name: "Owner's cabin starboard blind"
        position_template: "{{ states.input_number.owners_cabin_starboard_blind.state | float }}"
        set_cover_position:
          service: input_number.set_value
          target:
            entity_id: input_number.owners_cabin_starboard_blind
          data:
            value: "{{position}}"
      owners_cabin_skyline_main_shear:
        unique_id: template_owners_cabin_skyline_main_shear
        friendly_name: "Owner's cabin skyline main shear"
        position_template: "{{ states.input_number.owners_cabin_skyline_main_shear.state | float }}"
        set_cover_position:
          service: input_number.set_value
          target:
            entity_id: input_number.owners_cabin_skyline_main_shear
          data:
            value: "{{position}}"
      owners_cabin_skyline_main_blind:
        unique_id: template_owners_cabin_skyline_main_blind
        friendly_name: "Owner's cabin skyline main blind"
        position_template: "{{ states.input_number.owners_cabin_skyline_main_blind.state | float }}"
        set_cover_position:
          service: input_number.set_value
          target:
            entity_id: input_number.owners_cabin_skyline_main_blind
          data:
            value: "{{position}}"
      owners_cabin_skyline_port_shear:
        unique_id: template_owners_cabin_skyline_port_shear
        friendly_name: "Owner's cabin skyline port shear"
        position_template: "{{ states.input_number.owners_cabin_skyline_port_shear.state | float }}"
        set_cover_position:
          service: input_number.set_value
          target:
            entity_id: input_number.owners_cabin_skyline_port_shear
          data:
            value: "{{position}}"
      owners_cabin_skyline_port_blind:
        unique_id: template_owners_cabin_skyline_port_blind
        friendly_name: "Owner's cabin skyline port blind"
        position_template: "{{ states.input_number.owners_cabin_skyline_port_blind.state | float }}"
        set_cover_position:
          service: input_number.set_value
          target:
            entity_id: input_number.owners_cabin_skyline_port_blind
          data:
            value: "{{position}}"
      owners_cabin_skyline_starboard_shear:
        unique_id: template_owners_cabin_skyline_starboard_shear
        friendly_name: "Owner's cabin skyline starboard shear"
        position_template: "{{ states.input_number.owners_cabin_skyline_starboard_shear.state | float }}"
        set_cover_position:
          service: input_number.set_value
          target:
            entity_id: input_number.owners_cabin_skyline_starboard_shear
          data:
            value: "{{position}}"
      owners_cabin_skyline_starboard_blind:
        unique_id: template_owners_cabin_skyline_starboard_blind
        friendly_name: "Owner's cabin skyline starboard blind"
        position_template: "{{ states.input_number.owners_cabin_skyline_starboard_blind.state | float }}"
        set_cover_position:
          service: input_number.set_value
          target:
            entity_id: input_number.owners_cabin_skyline_starboard_blind
          data:
            value: "{{position}}"
      dutch_cabin_blind:
        unique_id: template_dutch_cabin_blind
        friendly_name: "Dutch cabin blind"
        position_template: "{{ states.input_number.dutch_cabin_blind.state | float }}"
        set_cover_position:
          service: input_number.set_value
          target:
            entity_id: input_number.dutch_cabin_blind
          data:
            value: "{{position}}"
      french_cabin_blind:
        unique_id: template_french_cabin_blind
        friendly_name: "French cabin blind"
        position_template: "{{ states.input_number.french_cabin_blind.state | float }}"
        set_cover_position:
          service: input_number.set_value
          target:
            entity_id: input_number.french_cabin_blind
          data:
            value: "{{position}}"
      italian_cabin_blind:
        unique_id: template_italian_cabin_blind
        friendly_name: "Italian cabin blind"
        position_template: "{{ states.input_number.italian_cabin_blind.state | float }}"
        set_cover_position:
          service: input_number.set_value
          target:
            entity_id: input_number.italian_cabin_blind
          data:
            value: "{{position}}"
      californian_lounge_blind:
        unique_id: template_californian_lounge_blind
        friendly_name: "Californian cabin blind"
        position_template: "{{ states.input_number.californian_lounge_blind.state | float }}"
        set_cover_position:
          service: input_number.set_value
          target:
            entity_id: input_number.californian_lounge_blind
          data:
            value: "{{position}}"
      polynesian_cabin_blind:
        unique_id: template_polynesian_cabin_blind
        friendly_name: "Polynesian cabin blind"
        position_template: "{{ states.input_number.polynesian_cabin_blind.state | float }}"
        set_cover_position:
          service: input_number.set_value
          target:
            entity_id: input_number.polynesian_cabin_blind
          data:
            value: "{{position}}"
      galley_blind:
        unique_id: template_galley_blind
        friendly_name: "Galley blind"
        position_template: "{{ states.input_number.galley_blind.state | float }}"
        set_cover_position:
          service: input_number.set_value
          target:
            entity_id: input_number.galley_blind
          data:
            value: "{{position}}"
      crew_mess_blind:
        unique_id: template_crew_mess_blind
        friendly_name: "Crew mess blind"
        position_template: "{{ states.input_number.crew_mess_blind.state | float }}"
        set_cover_position:
          service: input_number.set_value
          target:
            entity_id: input_number.crew_mess_blind
          data:
            value: "{{position}}"
      mission_room_blind:
        unique_id: template_mission_room_blind
        friendly_name: "Mission room blind"
        position_template: "{{ states.input_number.mission_room_blind.state | float }}"
        set_cover_position:
          service: input_number.set_value
          target:
            entity_id: input_number.mission_room_blind
          data:
            value: "{{position}}"
      laundry_blind:
        unique_id: template_laundry_blind
        friendly_name: "Laundry blind"
        position_template: "{{ states.input_number.laundry_blind.state | float }}"
        set_cover_position:
          service: input_number.set_value
          target:
            entity_id: input_number.laundry_blind
          data:
            value: "{{position}}"
      engineers_office_blind:
        unique_id: template_engineers_office_blind
        friendly_name: "Engineers office blind"
        position_template: "{{ states.input_number.engineers_office_blind.state | float }}"
        set_cover_position:
          service: input_number.set_value
          target:
            entity_id: input_number.engineers_office_blind
          data:
            value: "{{position}}"
      captains_cabin_blind:
        unique_id: template_captains_cabin_blind
        friendly_name: "Captains cabin blind"
        position_template: "{{ states.input_number.captains_cabin_blind.state | float }}"
        set_cover_position:
          service: input_number.set_value
          target:
            entity_id: input_number.captains_cabin_blind
          data:
            value: "{{position}}"
      crew_sb_aft_cabin_blind:
        unique_id: template_crew_sb_aft_cabin_blind
        friendly_name: "Crew SB AFT cabin blind"
        position_template: "{{ states.input_number.crew_sb_aft_cabin_blind.state | float }}"
        set_cover_position:
          service: input_number.set_value
          target:
            entity_id: input_number.crew_sb_aft_cabin_blind
          data:
            value: "{{position}}"
      crew_sb_mid_cabin_blind:
        unique_id: template_crew_sb_mid_cabin_blind
        friendly_name: "Crew SB MID cabin blind"
        position_template: "{{ states.input_number.crew_sb_mid_cabin_blind.state | float }}"
        set_cover_position:
          service: input_number.set_value
          target:
            entity_id: input_number.crew_sb_mid_cabin_blind
          data:
            value: "{{position}}"
      crew_sb_fwd_cabin_blind:
        unique_id: template_crew_sb_fwd_cabin_blind
        friendly_name: "Crew SB FWD cabin blind"
        position_template: "{{ states.input_number.crew_sb_fwd_cabin_blind.state | float }}"
        set_cover_position:
          service: input_number.set_value
          target:
            entity_id: input_number.crew_sb_fwd_cabin_blind
          data:
            value: "{{position}}"
      crew_ps_mid_cabin_blind:
        unique_id: template_crew_ps_mid_cabin_blind
        friendly_name: "Crew PS MID cabin blind"
        position_template: "{{ states.input_number.crew_ps_mid_cabin_blind.state | float }}"
        set_cover_position:
          service: input_number.set_value
          target:
            entity_id: input_number.crew_ps_mid_cabin_blind
          data:
            value: "{{position}}"
      crew_ps_fwd_cabin_blind:
        unique_id: template_crew_ps_fwd_cabin_blind
        friendly_name: "Crew PS FWD cabin blind"
        position_template: "{{ states.input_number.crew_ps_fwd_cabin_blind.state | float }}"
        set_cover_position:
          service: input_number.set_value
          target:
            entity_id: input_number.crew_ps_fwd_cabin_blind
          data:
            value: "{{position}}"
      owners_deckhouse_blind:
        unique_id: template_owners_deckhouse_blind
        friendly_name: "Owner's deckhouse blind"
        position_template: "{{ states.input_number.owners_deckhouse_blind.state | float }}"
        set_cover_position:
          service: input_number.set_value
          target:
            entity_id: input_number.owners_deckhouse_blind
          data:
            value: "{{position}}"
      owners_deckhouse_shear:
        unique_id: template_owners_deckhouse_shear
        friendly_name: "Owner's deckhouse shear"
        position_template: "{{ states.input_number.owners_deckhouse_shear.state | float }}"
        set_cover_position:
          service: input_number.set_value
          target:
            entity_id: input_number.owners_deckhouse_shear
          data:
            value: "{{position}}"
      main_deckhouse_blind:
        unique_id: template_main_deckhouse_blind
        friendly_name: "Main deckhouse blind"
        position_template: "{{ states.input_number.main_deckhouse_blind.state | float }}"
        set_cover_position:
          service: input_number.set_value
          target:
            entity_id: input_number.main_deckhouse_blind
          data:
            value: "{{position}}"
      main_deckhouse_shear:
        unique_id: template_main_deckhouse_shear
        friendly_name: "Main deckhouse shear"
        position_template: "{{ states.input_number.main_deckhouse_shear.state | float }}"
        set_cover_position:
          service: input_number.set_value
          target:
            entity_id: input_number.main_deckhouse_shear
          data:
            value: "{{position}}"
      owners_stairway_blind:
        unique_id: template_owners_stairway_blind
        friendly_name: "Owner's stairway blind"
        position_template: "{{ states.input_number.owners_stairway_blind.state | float }}"
        set_cover_position:
          service: input_number.set_value
          target:
            entity_id: input_number.owners_stairway_blind
          data:
            value: "{{position}}"
      guest_corridor_blind:
        unique_id: template_guest_corridor_blind
        friendly_name: "Guest corridor blind"
        position_template: "{{ states.input_number.guest_corridor_blind.state | float }}"
        set_cover_position:
          service: input_number.set_value
          target:
            entity_id: input_number.guest_corridor_blind
          data:
            value: "{{position}}"

automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml
