apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
  name: temp-data-ingest
  namespace: zero
spec:
  selector:
    matchLabels:
      app: temp-data-ingest
  template:
    metadata:
      labels:
        app: temp-data-ingest
    spec:
      containers:
        - command:
            - uv
            - run
            - --script
            - /app/data_ingest.py
          envFrom:
            - secretRef:
                name: temp-data-ingest-secrets
          image: ghcr.io/astral-sh/uv:debian-slim
          imagePullPolicy: Always
          name: data-ingest
          resources:
            limits:
              cpu: 500m
              memory: 512Mi
            requests:
              cpu: 50m
              memory: 64Mi
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL
            readOnlyRootFilesystem: false
            runAsNonRoot: false
            seccompProfile:
              type: RuntimeDefault
          volumeMounts:
            - name: script-volume
              mountPath: /app
      securityContext:
        fsGroup: 1001
        fsGroupChangePolicy: Always
      terminationGracePeriodSeconds: 30
      volumes:
        - name: script-volume
          configMap:
            name: temp-data-ingest-script
            items:
              - key: data_ingest.py
                path: data_ingest.py
