apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - deployment.yaml
configMapGenerator:
  - name: temp-data-ingest-script
    namespace: zero
    files:
      - ./data_ingest.py
secretGenerator:
  - name: temp-data-ingest-secrets
    namespace: zero
    literals:
      - MQTT_HOST=rabbitmq.rabbitmq.svc.cluster.local
      - MQTT_PORT=1883
      - MQTT_USER=anon
      - MQTT_PASSWORD=anonanon

      - GREPTIMEDB_HOST=greptimedb-frontend.greptimedb.svc.cluster.local
      - GREPTIMEDB_PORT=4000
