<script setup lang="ts">
import { ComponentOrientation } from "../../../components";
import { MANUAL_VALVE_WIDTH, ManualValveType } from "../../../components/manual-valve";
import { ManualValveInstance } from "../../../instances";
import TagLabelInstance from "../../../instances/TagLabelInstance.vue";
import { DRIVES_MANUAL_VALVE_DATA } from "../data";

const manualValves = DRIVES_MANUAL_VALVE_DATA.ManualValve;
</script>

<template>
  <ManualValveInstance
    x="255.1582"
    y="67.916"
    :type="ManualValveType.Switch"
    :orientation="ComponentOrientation.Up"
    v-bind="manualValves['1087-04']"
  >
    <TagLabelInstance
      target-x="255.1582"
      :target-width="MANUAL_VALVE_WIDTH"
      y="100.916"
      :tag-id="manualValves['1087-04'].tooltip?.yardTag"
    />
  </ManualValveInstance>
  <ManualValveInstance
    x="255.1582"
    y="258.916"
    :type="ManualValveType.Switch"
    :orientation="ComponentOrientation.Up"
    v-bind="manualValves['1087-05']"
  >
    <TagLabelInstance
      target-x="255.1582"
      :target-width="MANUAL_VALVE_WIDTH"
      y="294.0029"
      :tag-id="manualValves['1087-05'].tooltip?.yardTag"
    />
  </ManualValveInstance>
  <ManualValveInstance
    x="256"
    y="502.8291"
    :type="ManualValveType.Switch"
    :orientation="ComponentOrientation.Up"
    v-bind="manualValves['1087-06']"
  >
    <TagLabelInstance
      target-x="256"
      :target-width="MANUAL_VALVE_WIDTH"
      y="537.916"
      :tag-id="manualValves['1087-06'].tooltip?.yardTag"
    />
  </ManualValveInstance>
  <ManualValveInstance
    x="256"
    y="714.916"
    :type="ManualValveType.Switch"
    :orientation="ComponentOrientation.Up"
    v-bind="manualValves['1087-07']"
  >
    <TagLabelInstance
      target-x="256"
      :target-width="MANUAL_VALVE_WIDTH"
      y="750.0029"
      :tag-id="manualValves['1087-07'].tooltip?.yardTag"
    />
  </ManualValveInstance>
  <ManualValveInstance
    x="566.1582"
    y="382.916"
    :type="ManualValveType.Switch"
    :orientation="ComponentOrientation.Up"
    v-bind="manualValves['1085-04']"
  >
    <TagLabelInstance
      target-x="566.1582"
      :target-width="MANUAL_VALVE_WIDTH"
      y="416.916"
      :tag-id="manualValves['1085-04'].tooltip?.yardTag"
    />
  </ManualValveInstance>
  <ManualValveInstance
    x="796.1582"
    y="383.916"
    :type="ManualValveType.Switch"
    :orientation="ComponentOrientation.Up"
    v-bind="manualValves['1085-05']"
  >
    <TagLabelInstance
      target-x="796.1582"
      :target-width="MANUAL_VALVE_WIDTH"
      y="413.916"
      :tag-id="manualValves['1085-05'].tooltip?.yardTag"
    />
  </ManualValveInstance>
  <ManualValveInstance
    x="566.1582"
    y="824.916"
    :type="ManualValveType.Switch"
    :orientation="ComponentOrientation.Up"
    v-bind="manualValves['1085-02']"
  >
    <TagLabelInstance
      target-x="566.1582"
      :target-width="MANUAL_VALVE_WIDTH"
      y="859"
      :tag-id="manualValves['1085-02'].tooltip?.yardTag"
    />
  </ManualValveInstance>
  <ManualValveInstance
    x="795.1582"
    y="825.916"
    :type="ManualValveType.Switch"
    :orientation="ComponentOrientation.Up"
    v-bind="manualValves['1085-03']"
  >
    <TagLabelInstance
      target-x="795.1582"
      :target-width="MANUAL_VALVE_WIDTH"
      y="855.916"
      :tag-id="manualValves['1085-03'].tooltip?.yardTag"
    />
  </ManualValveInstance>
  <ManualValveInstance
    x="1061.1582"
    y="680.916"
    :type="ManualValveType.Switch"
    :orientation="ComponentOrientation.Up"
    v-bind="manualValves['1086-01']"
  >
    <TagLabelInstance
      target-x="1061.1582"
      :target-width="MANUAL_VALVE_WIDTH"
      y="709.7832"
      :tag-id="manualValves['1086-01'].tooltip?.yardTag"
    />
  </ManualValveInstance>
  <ManualValveInstance
    x="1175"
    y="678.916"
    :type="ManualValveType.Switch"
    :orientation="ComponentOrientation.Up"
    v-bind="manualValves['1086-02']"
  >
    <TagLabelInstance
      target-x="1175"
      :target-width="MANUAL_VALVE_WIDTH"
      y="709"
      :tag-id="manualValves['1086-02'].tooltip?.yardTag"
    />
  </ManualValveInstance>
  <ManualValveInstance
    x="1320.1582"
    y="344.916"
    :type="ManualValveType.Switch"
    :orientation="ComponentOrientation.Up"
    v-bind="manualValves['1086-09']"
  >
    <TagLabelInstance
      target-x="1320.1582"
      :target-width="MANUAL_VALVE_WIDTH"
      y="377.916"
      :tag-id="manualValves['1086-09'].tooltip?.yardTag"
    />
  </ManualValveInstance>
  <ManualValveInstance
    x="1467.1582"
    y="346.916"
    :type="ManualValveType.Switch"
    :orientation="ComponentOrientation.Up"
    v-bind="manualValves['1086-10']"
  >
    <TagLabelInstance
      target-x="1467.1582"
      :target-width="MANUAL_VALVE_WIDTH"
      y="378.916"
      :tag-id="manualValves['1086-10'].tooltip?.yardTag"
    />
  </ManualValveInstance>
  <ManualValveInstance
    x="1368.2832"
    y="593.916"
    :type="ManualValveType.Switch"
    :orientation="ComponentOrientation.Up"
    v-bind="manualValves['1086-06']"
  >
    <TagLabelInstance
      target-x="1368.2832"
      :target-width="MANUAL_VALVE_WIDTH"
      y="628.916"
      :tag-id="manualValves['1086-06'].tooltip?.yardTag"
    />
  </ManualValveInstance>
  <ManualValveInstance
    x="1474.1582"
    y="593.916"
    :type="ManualValveType.Switch"
    :orientation="ComponentOrientation.Up"
    v-bind="manualValves['1086-05']"
  >
    <TagLabelInstance
      target-x="1474.1582"
      :target-width="MANUAL_VALVE_WIDTH"
      y="629.916"
      :tag-id="manualValves['1086-05'].tooltip?.yardTag"
    />
  </ManualValveInstance>
  <ManualValveInstance
    x="1368.2832"
    y="726.6006"
    :type="ManualValveType.Switch"
    :orientation="ComponentOrientation.Up"
    v-bind="manualValves['1086-07']"
  >
    <TagLabelInstance
      target-x="1368.2832"
      :target-width="MANUAL_VALVE_WIDTH"
      y="762.6006"
      :tag-id="manualValves['1086-07'].tooltip?.yardTag"
    />
  </ManualValveInstance>
  <ManualValveInstance
    x="1477.2832"
    y="726.6006"
    :type="ManualValveType.Switch"
    :orientation="ComponentOrientation.Up"
    v-bind="manualValves['1086-08']"
  >
    <TagLabelInstance
      target-x="1477.2832"
      :target-width="MANUAL_VALVE_WIDTH"
      y="763.6006"
      :tag-id="manualValves['1086-08'].tooltip?.yardTag"
    />
  </ManualValveInstance>
  <ManualValveInstance
    x="1653"
    y="192"
    :type="ManualValveType.Switch"
    :orientation="ComponentOrientation.Up"
    v-bind="manualValves['1084-02']"
  >
    <TagLabelInstance
      x="1612"
      y="201"
      :tag-id="manualValves['1084-02'].tooltip?.yardTag"
    />
  </ManualValveInstance>
  <ManualValveInstance
    x="1653"
    y="111.5"
    :type="ManualValveType.Switch"
    :orientation="ComponentOrientation.Up"
    v-bind="manualValves['1087-01']"
  >
    <TagLabelInstance
      target-x="1653"
      :target-width="MANUAL_VALVE_WIDTH"
      y="138"
      :tag-id="manualValves['1087-01'].tooltip?.yardTag"
    />
  </ManualValveInstance>
  <ManualValveInstance
    x="537.1582"
    y="663.916"
    :type="ManualValveType.Flow"
    :orientation="ComponentOrientation.Right"
    v-bind="manualValves['1073-02']"
  >
    <TagLabelInstance
      x="575.6582"
      y="675.916"
      :tag-id="manualValves['1073-02'].tooltip?.yardTag"
    />
  </ManualValveInstance>
  <ManualValveInstance
    x="537.1582"
    y="214.916"
    :type="ManualValveType.Flow"
    :orientation="ComponentOrientation.Right"
    v-bind="manualValves['1073-01']"
  >
    <TagLabelInstance
      x="575.6582"
      y="225.416"
      :tag-id="manualValves['1073-01'].tooltip?.yardTag"
    />
  </ManualValveInstance>
</template>
