<script setup lang="ts">
import { ComponentOrientation } from "../../../components";
import { TEMPERATURE_SENSOR_WIDTH } from "../../../components/temperature-sensor";
import { TemperatureSensorInstance } from "../../../instances";
import TemperatureLabelInstance from "../../../instances/TemperatureLabelInstance.vue";
import { DRIVES_TEMPERATURE_SENSOR_DATA } from "../data";

const temperatureSensors = DRIVES_TEMPERATURE_SENSOR_DATA.TemperatureSensor;
</script>

<template>
  <g>
    <TemperatureSensorInstance
      x="330.6582"
      y="56.166"
      :orientation="ComponentOrientation.Down"
      v-bind="temperatureSensors['1038-64']"
    >
      <TemperatureLabelInstance
        target-x="330.6582"
        :target-width="TEMPERATURE_SENSOR_WIDTH"
        y="15.916"
        :tag-id="temperatureSensors['1038-64'].tooltip?.yardTag"
        :temperature="temperatureSensors['1038-64'].source"
      />
    </TemperatureSensorInstance>
    <TemperatureSensorInstance
      x="326.6582"
      y="246.0791"
      :orientation="ComponentOrientation.Down"
      v-bind="temperatureSensors['1038-32']"
    >
      <TemperatureLabelInstance
        target-x="326.6582"
        :target-width="TEMPERATURE_SENSOR_WIDTH"
        y="206.916"
        :tag-id="temperatureSensors['1038-32'].tooltip?.yardTag"
        :temperature="temperatureSensors['1038-32'].source"
      />
    </TemperatureSensorInstance>
    <TemperatureSensorInstance
      x="326.6582"
      y="491.166"
      :orientation="ComponentOrientation.Down"
      v-bind="temperatureSensors['1038-72']"
    >
      <TemperatureLabelInstance
        target-x="326.6582"
        :target-width="TEMPERATURE_SENSOR_WIDTH"
        y="451.916"
        :tag-id="temperatureSensors['1038-72'].tooltip?.yardTag"
        :temperature="temperatureSensors['1038-72'].source"
      />
    </TemperatureSensorInstance>
    <TemperatureSensorInstance
      x="326.6582"
      y="702.166"
      :orientation="ComponentOrientation.Down"
      v-bind="temperatureSensors['1038-61']"
    >
      <TemperatureLabelInstance
        target-x="326.6582"
        :target-width="TEMPERATURE_SENSOR_WIDTH"
        y="662.916"
        :tag-id="temperatureSensors['1038-61'].tooltip?.yardTag"
        :temperature="temperatureSensors['1038-61'].source"
      />
    </TemperatureSensorInstance>
    <TemperatureSensorInstance
      x="476.1582"
      y="372.166"
      :orientation="ComponentOrientation.Down"
      v-bind="temperatureSensors['1038-63']"
    >
      <TemperatureLabelInstance
        target-x="476.1582"
        :target-width="TEMPERATURE_SENSOR_WIDTH"
        y="329.916"
        :tag-id="temperatureSensors['1038-63'].tooltip?.yardTag"
        :temperature="temperatureSensors['1038-63'].source"
      />
    </TemperatureSensorInstance>
    <TemperatureSensorInstance
      x="476.1582"
      y="812.0664"
      :orientation="ComponentOrientation.Down"
      v-bind="temperatureSensors['1038-62']"
    >
      <TemperatureLabelInstance
        target-x="476.1582"
        :target-width="TEMPERATURE_SENSOR_WIDTH"
        y="775.916"
        :tag-id="temperatureSensors['1038-62'].tooltip?.yardTag"
        :temperature="temperatureSensors['1038-62'].source"
      />
    </TemperatureSensorInstance>
    <TemperatureSensorInstance
      x="1008.9082"
      y="258.5278"
      :orientation="ComponentOrientation.Left"
      v-bind="temperatureSensors['1038-11']"
    >
      <TemperatureLabelInstance
        x="1044"
        y="250"
        :tag-id="temperatureSensors['1038-11'].tooltip?.yardTag"
        :temperature="temperatureSensors['1038-11'].source"
      />
    </TemperatureSensorInstance>
    <TemperatureSensorInstance
      x="1144.1582"
      y="331.166"
      :orientation="ComponentOrientation.Down"
      v-bind="temperatureSensors['1038-16']"
    >
      <TemperatureLabelInstance
        target-x="1144.1582"
        :target-width="TEMPERATURE_SENSOR_WIDTH"
        y="281.916"
        :tag-id="temperatureSensors['1038-16'].tooltip?.yardTag"
        :temperature="temperatureSensors['1038-16'].source"
      />
    </TemperatureSensorInstance>
    <TemperatureSensorInstance
      x="964.1582"
      y="581.166"
      :orientation="ComponentOrientation.Down"
      v-bind="temperatureSensors['1038-14']"
    >
      <TemperatureLabelInstance
        target-x="964.1582"
        :target-width="TEMPERATURE_SENSOR_WIDTH"
        y="540.916"
        :tag-id="temperatureSensors['1038-14'].tooltip?.yardTag"
        :temperature="temperatureSensors['1038-14'].source"
      />
    </TemperatureSensorInstance>
    <TemperatureSensorInstance
      x="1512.1582"
      y="333.166"
      :orientation="ComponentOrientation.Down"
      v-bind="temperatureSensors['1038-59']"
    >
      <TemperatureLabelInstance
        target-x="1512.1582"
        :target-width="TEMPERATURE_SENSOR_WIDTH"
        y="292.916"
        :tag-id="temperatureSensors['1038-59'].tooltip?.yardTag"
        :temperature="temperatureSensors['1038-59'].source"
      />
    </TemperatureSensorInstance>
    <TemperatureSensorInstance
      x="1611.1582"
      y="644.166"
      :orientation="ComponentOrientation.Down"
      v-bind="temperatureSensors['1038-57']"
    >
      <TemperatureLabelInstance
        target-x="1611.1582"
        :target-width="TEMPERATURE_SENSOR_WIDTH"
        y="597.916"
        :tag-id="temperatureSensors['1038-57'].tooltip?.yardTag"
        :temperature="temperatureSensors['1038-57'].source"
      />
    </TemperatureSensorInstance>
  </g>
</template>
