set dotenv-load := true

default: check

check: lint type_check test

lint:
    uv run ruff check

type_check:
    uv run pyright

test *args:
    uv run pytest {{ args }}

format:
    uv run ruff format --check src tests

refresh_io:
    uv run python ./scripts/excel_to_json.py --patches patches.json
