replicaCount: 1

image:
  repository: europe-west1-docker.pkg.dev/common-449414/common/zero-fiber-optics
  pullPolicy: IfNotPresent
  tag: ""

configPath: /app/example/config.xml
logLevel: info

mqtt:
  host: ""
  port: 1883
  prefix: fiber-optics
  username: fiber-optics
  existingSecret: ""
  existingSecretPasswordKey: password

udp:
  annotations: {}
  labels: {}
  externalIPs: []
  ports:
    - 50000

resources: {}

imagePullSecrets: []

nameOverride: ""
fullnameOverride: ""

podAnnotations: {}
podLabels: {}


nodeSelector: {}

tolerations: []

affinity: {}
