apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "zero-domestic-control.backend" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "zero-domestic-control.labels" . | nindent 4 }}
    app.kubernetes.io/part-of: domestic-control
    app.kubernetes.io/component: backend
spec:
  replicas: {{ .Values.replicaCount.backend }}
  selector:
    matchLabels:
      {{- include "zero-domestic-control.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/part-of: domestic-control
      app.kubernetes.io/component: backend
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "zero-domestic-control.labels" . | nindent 8 }}
        {{- with .Values.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
        app.kubernetes.io/part-of: domestic-control
        app.kubernetes.io/component: backend
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      securityContext:
        fsGroupChangePolicy: Always
        sysctls: []
        supplementalGroups: []
        fsGroup: 1001
      containers:
        - name: domestic-control-backend
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
              - ALL
            privileged: false
            readOnlyRootFilesystem: true
            runAsGroup: 1001
            runAsNonRoot: true
            runAsUser: 1001
            seLinuxOptions: {}
            seccompProfile:
              type: RuntimeDefault
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command: ["fastapi", "run", "./zero_domestic_control/app.py"]
          ports:
            - name: http
              containerPort: {{ .Values.service.backend.port }}
              protocol: TCP
          resources:
            {{- toYaml .Values.resources.backend | nindent 12 }}
          env:
            - name: TERMODINAMICA_HOST
              value: "0.0.0.0"
            - name: TERMODINAMICA_PORT
              value: {{ .Values.stub.port | quote }}
            {{- include "zero-domestic-control.postgresqlPasswordEnvFromSecret" . | nindent 12 }}
            {{- include "zero-domestic-control.hasuraJwtEnvFromSecret" . | indent 12 }}
            {{- include "zero-domestic-control.homeAssistantTokenEnvFromSecret" . | indent 12 }}
          envFrom:
            - configMapRef:
                name: {{ include "zero-domestic-control.envvars" . }}
