apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "zero-domestic-control.backend" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "zero-domestic-control.labels" . | nindent 4 }}
    app.kubernetes.io/part-of: domestic-control
    app.kubernetes.io/component: backend
spec:
  replicas: {{ .Values.replicaCount.backend }}
  selector:
    matchLabels:
      {{- include "zero-domestic-control.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/part-of: domestic-control
      app.kubernetes.io/component: backend
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "zero-domestic-control.labels" . | nindent 8 }}
        {{- with .Values.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
        app.kubernetes.io/part-of: domestic-control
        app.kubernetes.io/component: backend
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      securityContext:
        fsGroup: 1001
        seccompProfile:
          type: RuntimeDefault
      containers:
        - name: domestic-control-backend
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
              - ALL
            readOnlyRootFilesystem: true
            runAsNonRoot: true
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command: ["fastapi", "run", "/app/domestic_control/app.py", "--host", "0.0.0.0", "--port", "{{ .Values.service.backend.containerPort }}"]
          ports:
            - name: http
              containerPort: 5100
              protocol: TCP
          resources:
            {{- toYaml .Values.resources.backend | nindent 12 }}
          env:
            - name: AIR_CONDITIONING_HOST
              value: "0.0.0.0"
            - name: AIR_CONDITIONING_PORT
              value: {{ .Values.stub.port | quote }}
            - name: VENTILATION_HOST
              value: "0.0.0.0"
            - name: VENTILATION_PORT
              value: {{ .Values.stub.ventilationPort | quote }}
            {{- include "zero-domestic-control.postgresqlPasswordEnvFromSecret" . | nindent 12 }}
            {{- include "zero-domestic-control.hasuraJwtEnvFromSecret" . | indent 12 }}
            {{- include "zero-domestic-control.homeAssistantTokenEnvFromSecret" . | indent 12 }}
          envFrom:
            - configMapRef:
                name: {{ include "zero-domestic-control.envvars" . }}
