{{- if .Values.stub.enabled }}
apiVersion: v1
kind: Service
metadata:
  namespace: {{ .Release.Namespace }}
  name: {{ include "zero-domestic-control.stub" . }}
spec:
  ports:
  - name: ac
    port: {{ .Values.stub.port }}
    targetPort: ac
    protocol: TCP
  - name: ventilation
    port: {{ .Values.stub.ventilationPort }}
    targetPort: ventilation
    protocol: TCP
  selector:
    {{- include "zero-domestic-control.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/part-of: domestic-control
    app.kubernetes.io/component: stub
  type: ClusterIP
{{ end }}
