# run docker build . -t zero-power-tags:latest
# Push image to kind (through ui)
image:
  repository: localhost/zero-power-tags
  tag: latest

# Run mqtt in docker container
mqtt:
  host: "host.docker.internal"
  port: 1883
  username: ""
  existingSecret: ""

# Run stub locally
modbus:
  host: "host.docker.internal"
  port: 5020
  probe_interval: 2
