[project]
name = "data"
description = ""
readme = "README.md"
authors = [
    { name = "Boudewijn van Groos", email = "boudewijn.vangroos@foundationzero.org>" },
    { name = "Dustin van Weersel", email = "dustin.vanweersel@foundationzero.org>" }
]
requires-python = ">= 3.13.1,<4.0"
dependencies = [
    "dbt-core (>=1.9.8)",
    "dbt-risingwave (>=1.9.2)",
    "psycopg[binary] (>=3.2.3)",
    "pydantic-settings (>=2.7.1)",
    "python-dotenv (>=1.1.0)"
]
dynamic = ["version"]

[tool.poetry]
package-mode = false
version = "0.0.0"

[tool.poetry.requires-plugins]
poetry-dynamic-versioning = { version = ">=1.0.0,<2.0.0", extras = ["plugin"] }

[tool.poetry-dynamic-versioning]
enable = true

[build-system]
requires = ["poetry-core>=1.0.0", "poetry-dynamic-versioning>=1.0.0,<2.0.0"]
build-backend = "poetry_dynamic_versioning.backend"
