[project]
name = "domestic-control"
version = "0.7.2"
description = ""
readme = "README.md"
authors = [
    { name = "Boudewijn van Groos", email = "boudewijn.vangroos@foundationzero.org>" },
    { name = "Dustin van Weersel", email = "dustin.vanweersel@foundationzero.org>" }
]
requires-python = ">= 3.13.1,<4.0"
packages = [{ include = "domestic_control", from = "src" }]
dependencies = [
    "aiomqtt (>=2.3.0,<3.0.0)",
    "dbt-core (>=1.9.8,<2.0.0)",
    "dbt-risingwave (>=1.9.2,<2.0.0)",
    "fastapi[standard] (>=0.115.6,<1.0.0)",
    "homeassistant-api (>=5.0.0,<6.0.0)",
    "psycopg[binary] (>=3.2.3,<4.0.0)",
    "pyjwt (>=2.10.1,<3.0.0)",
    "pymodbustcp (>=0.3.0,<1.0.0)",
    "pydantic-settings (>=2.7.1,<3.0.0)",
    "strawberry-graphql[debug-server,fastapi] (>=0.256.1,<1.0.0)"
]

[project.scripts]
domestic_control = "domestic_control.__main__:run"

[tool.poetry.group.dev]
optional = true

[tool.poetry.group.dev.dependencies]
mypy = "^1.14.1"
ruff = "^0.9.5"
python-dotenv = "^1.1.0"

[tool.poetry.group.test]
optional = true

[tool.poetry.group.test.dependencies]
httpx = "^0.28.1"
pytest = "^8.3.4"
pytest-asyncio = "^0.25.1"
pytest-env = "^1.1.5"
pytest-mock = "^3.14.0"
pytest-timeout = "^2.3.1"

[tool.mypy]
plugins = "pydantic.mypy,strawberry.ext.mypy_plugin"
mypy_path = "./typings"
check_untyped_defs = true

[tool.pytest.ini_options]
asyncio_default_fixture_loop_scope = "function"
asyncio_mode = "auto"
testpaths = ["tests"]
log_level = "DEBUG"
log_format = "%(asctime)s.%(msecs)03d | %(levelname)-8s | %(message)s"

[tool.ruff]
fix = true

[tool.dotenv]
location = ".env"

[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"

