[project]
name = "domestic-control"
description = ""
authors = [
    { name = "Boudewijn van Groos", email = "boudewijn.vangroos@foundationzero.org" },
    { name = "Dustin van Weersel", email = "dustin.vanweersel@foundationzero.org" },
]
requires-python = ">= 3.13.1,<4.0"
readme = "README.md"
dependencies = [
    "aiomqtt (>=2.3.0,<3.0.0)",
    "dbt-core (>=1.9.8,<2.0.0)",
    "dbt-risingwave (>=1.9.2,<2.0.0)",
    "fastapi[standard] (>=0.115.6,<1.0.0)",
    "homeassistant-api (>=5.0.0,<6.0.0)",
    "psycopg[binary] (>=3.2.3,<4.0.0)",
    "pyjwt (>=2.10.1,<3.0.0)",
    "pymodbustcp (>=0.3.0,<1.0.0)",
    "pydantic-settings (>=2.7.1,<3.0.0)",
    "sqlmodel (>=0.0.22,<1.0.0)",
    "strawberry-graphql[debug-server,fastapi] (>=0.256.1,<1.0.0)",
    "greenlet (>=3.4.0,<4.0.0)",
    "aiomysql (>=0.3.2,<0.4.0)",
]
dynamic = ["version"]

[project.scripts]
domestic_control = "domestic_control.__main__:run"

[dependency-groups]
dev = [
    "ruff>=0.9.5,<0.10",
    "python-dotenv>=1.1.0,<2",
    "pyright>=1.1.408,<2",
]
test = [
    "httpx>=0.28.1,<0.29",
    "pytest>=8.3.4,<9",
    "pytest-asyncio>=0.25.1,<0.26",
    "pytest-env>=1.1.5,<2",
    "pytest-mock>=3.14.0,<4",
    "pytest-timeout>=2.3.1,<3",
]

[tool.mypy]
plugins = "pydantic.mypy,strawberry.ext.mypy_plugin"
mypy_path = "./typings"
check_untyped_defs = true

[tool.pytest.ini_options]
asyncio_default_fixture_loop_scope = "function"
asyncio_mode = "auto"
testpaths = ["tests"]
log_level = "DEBUG"
log_format = "%(asctime)s.%(msecs)03d | %(levelname)-8s | %(message)s"

[tool.ruff]
fix = true

[tool.ruff.lint]
select = ["E4", "E7", "E9", "F", "W", "I"]

[tool.dotenv]
location = ".env"

[build-system]
requires = ["hatchling>=1.26,<2", "hatch-vcs>=0.4,<1"]
build-backend = "hatchling.build"

[tool.hatch.version]
source = "vcs"

[tool.hatch.version.raw-options]
search_parent_directories = true
fallback_version = "0.0.0"

[tool.hatch.build.targets.wheel]
packages = ["src/domestic_control"]

[tool.uv]
default-groups = ["dev", "test"]
