apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "zero-data-gen.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "zero-data-gen.labels" . | nindent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "zero-data-gen.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "zero-data-gen.labels" . | nindent 8 }}
    spec:
      securityContext:
        fsGroupChangePolicy: Always
        sysctls: []
        supplementalGroups: []
        fsGroup: 1001
      containers:
        - name: data-gen
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
              - ALL
            privileged: false
            readOnlyRootFilesystem: true
            runAsGroup: 1001
            runAsNonRoot: true
            runAsUser: 1001
            seLinuxOptions: {}
            seccompProfile:
              type: RuntimeDefault
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          args: ["generate-data"]
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          envFrom:
            - configMapRef:
                name: {{ include "zero-data-gen.fullname" . }}-envvars
