<script setup lang="ts">
import { MimicComponentType } from "@/modules/thrapp/types";
import { ComponentOrientation } from "../../../components";
import { MANUAL_VALVE_WIDTH, ManualValveType } from "../../../components/manual-valve";
import { ManualValveInstance } from "../../../instances";
import TagLabelInstance from "../../../instances/TagLabelInstance.vue";
import { THRUSTERS_MIMIC_DATA } from "../data";

const manualValves = THRUSTERS_MIMIC_DATA[MimicComponentType.ManualValve];
</script>

<template>
  <g>
    <ManualValveInstance
      x="610"
      y="152"
      :type="ManualValveType.Switch"
      :orientation="ComponentOrientation.Up"
      v-bind="manualValves['1212-01']"
    >
      <TagLabelInstance
        :target-x="610"
        :target-width="MANUAL_VALVE_WIDTH"
        y="180"
        :tag-id="manualValves['1212-01'].tooltip?.yardTag"
      />
    </ManualValveInstance>
    <ManualValveInstance
      x="732"
      y="152"
      :type="ManualValveType.Switch"
      :orientation="ComponentOrientation.Up"
      v-bind="manualValves['1212-02']"
    >
      <TagLabelInstance
        :target-x="732"
        :target-width="MANUAL_VALVE_WIDTH"
        y="180"
        :tag-id="manualValves['1212-02'].tooltip?.yardTag"
      />
    </ManualValveInstance>
    <ManualValveInstance
      x="630"
      y="522"
      :type="ManualValveType.Switch"
      :orientation="ComponentOrientation.Up"
      v-bind="manualValves['1212-03']"
    >
      <TagLabelInstance
        :target-x="630"
        :target-width="MANUAL_VALVE_WIDTH"
        y="515"
        :tag-id="manualValves['1212-03'].tooltip?.yardTag"
      />
    </ManualValveInstance>
    <ManualValveInstance
      x="755"
      y="522"
      :type="ManualValveType.Switch"
      :orientation="ComponentOrientation.Up"
      v-bind="manualValves['1212-04']"
    >
      <TagLabelInstance
        :target-x="755"
        :target-width="MANUAL_VALVE_WIDTH"
        y="515"
        :tag-id="manualValves['1212-04'].tooltip?.yardTag"
      />
    </ManualValveInstance>
    <ManualValveInstance
      x="630"
      y="613"
      :type="ManualValveType.Switch"
      :orientation="ComponentOrientation.Up"
      v-bind="manualValves['1212-05']"
    >
      <TagLabelInstance
        :target-x="630"
        :target-width="MANUAL_VALVE_WIDTH"
        y="605"
        :tag-id="manualValves['1212-05'].tooltip?.yardTag"
      />
    </ManualValveInstance>
    <ManualValveInstance
      x="755"
      y="613"
      :type="ManualValveType.Switch"
      :orientation="ComponentOrientation.Up"
      v-bind="manualValves['1212-06']"
    >
      <TagLabelInstance
        :target-x="755"
        :target-width="MANUAL_VALVE_WIDTH"
        y="605"
        :tag-id="manualValves['1212-06'].tooltip?.yardTag"
      />
    </ManualValveInstance>
    <ManualValveInstance
      x="214"
      y="299"
      :type="ManualValveType.Switch"
      :orientation="ComponentOrientation.Up"
      v-bind="manualValves['1212-07']"
    >
      <TagLabelInstance
        :target-x="214"
        :target-width="MANUAL_VALVE_WIDTH"
        y="290"
        :tag-id="manualValves['1212-07'].tooltip?.yardTag"
      />
    </ManualValveInstance>
    <ManualValveInstance
      x="1045"
      y="190.5"
      :type="ManualValveType.Switch"
      :orientation="ComponentOrientation.Up"
      v-bind="manualValves['1084-01']"
    >
      <TagLabelInstance
        :target-x="1045"
        :target-width="MANUAL_VALVE_WIDTH"
        y="219"
        :tag-id="manualValves['1084-01'].tooltip?.yardTag"
      />
    </ManualValveInstance>
    <ManualValveInstance
      x="214"
      y="567"
      :type="ManualValveType.Switch"
      :orientation="ComponentOrientation.Up"
      v-bind="manualValves['1087-03']"
    >
      <TagLabelInstance
        :target-x="214"
        :target-width="MANUAL_VALVE_WIDTH"
        y="560.724"
        :tag-id="manualValves['1087-03'].tooltip?.yardTag"
      />
    </ManualValveInstance>
    <ManualValveInstance
      x="1045"
      y="140.5"
      :type="ManualValveType.Switch"
      :orientation="ComponentOrientation.Up"
      v-bind="manualValves['1087-08']"
    >
      <TagLabelInstance
        :target-x="1045"
        :target-width="MANUAL_VALVE_WIDTH"
        y="170"
        :tag-id="manualValves['1087-08'].tooltip?.yardTag"
      />
    </ManualValveInstance>
  </g>
</template>
