{{- if .Values.stub.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "zero-termodinamica.stub" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "zero-termodinamica.labels" . | nindent 4 }}
    app.kubernetes.io/component: stub
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "zero-termodinamica.stubSelectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "zero-termodinamica.stubSelectorLabels" . | nindent 8 }}
    spec:
      securityContext:
        fsGroup: 1001
      containers:
        - name: termodinamica-stub
          args: ["stub"]
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
              - ALL
            readOnlyRootFilesystem: true
            runAsGroup: 1001
            runAsNonRoot: true
            runAsUser: 1001
            seccompProfile:
              type: RuntimeDefault
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            - name: MODBUS_HOST
              value: {{ .Values.stub.host | quote }}
            - name: MODBUS_PORT
              value: {{ .Values.modbus.port | quote }}
            - name: DEFAULT_VALUE
              value: {{ .Values.stub.defaultValue | quote }}
            - name: MODBUS_BRIDGES_PATH
              value: {{ .Values.modbus.bridgesPath | quote }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
{{- end }}
