<template>
  <article class="grid gap-12 text-justify lg:grid-cols-2">
    <hgroup class="col-span-full grid gap-1">
      <h1 class="text-6xl font-extrabold">Scroll behaviour demo</h1>
      <p class="text-muted-foreground">
        Please scroll down to see the effect. Content was generated by CoPilot.
      </p>
    </hgroup>

    <section class="grid gap-4">
      <h2 class="text-3xl font-bold">Sail Design and Aerodynamics</h2>
      <p>
        The art of sail design combines centuries of maritime tradition with modern aerodynamic
        principles. A sail is fundamentally an airfoil, carefully shaped to generate lift when wind
        flows across its surface. The curvature, or camber, of a sail determines how efficiently it
        can capture wind energy and convert it into forward motion. Different sail shapes serve
        different purposes, from the triangular mainsail that provides primary propulsion to the
        genoa that maximizes upwind performance.
      </p>

      <p>
        Modern sail construction utilizes advanced materials like Dacron, Mylar, and carbon fiber
        composites. These materials offer superior strength-to-weight ratios while maintaining the
        flexibility needed for proper sail shape. The weave pattern of the fabric plays a crucial
        role in how the sail stretches and holds its shape under load. Tri-radial and cross-cut
        construction methods distribute stress across the sail panel, preventing distortion and
        extending the sail's useful life.
      </p>

      <p>
        The interaction between wind and sail creates complex aerodynamic forces. As wind flows
        across the curved surface, it accelerates on the leeward side, creating lower pressure
        compared to the windward side. This pressure differential generates lift, pulling the boat
        forward and to windward. Understanding these forces allows sailors to trim their sails
        optimally, adjusting tension, angle, and shape to match changing wind conditions.
      </p>

      <p>
        Sail trim involves adjusting multiple control lines to optimize sail shape. The halyard
        controls luff tension, the outhaul affects foot tension, and the cunningham influences draft
        position. The traveler and mainsheet control the boom's lateral position and twist. Each
        adjustment affects how the sail interacts with the wind, requiring constant attention from
        the crew to maintain optimal performance throughout different points of sail.
      </p>

      <p>
        Wind gradient effects significantly impact sail performance. Wind speed increases with
        height above the water surface, creating different apparent wind angles along the sail's
        vertical axis. This phenomenon explains why sail twist is desirable, allowing the upper
        portion of the sail to operate at a different angle than the lower section. Proper twist
        management maximizes efficiency across the entire sail area.
      </p>

      <p>
        The slot effect between the jib and mainsail creates additional aerodynamic advantages. As
        air accelerates through the narrow gap between these sails, it increases flow velocity over
        the mainsail's leeward surface. This enhanced airflow improves the mainsail's efficiency and
        overall boat performance. Careful attention to jib lead position and sheeting angle
        optimizes this interaction.
      </p>

      <p>
        Downwind sailing introduces different aerodynamic considerations. Running before the wind,
        sails operate primarily through drag rather than lift. Spinnakers and gennakers feature
        full, balloon-like shapes designed to capture maximum wind force. Their asymmetric designs
        allow modern boats to sail deep downwind angles while maintaining good speed, particularly
        when reaching.
      </p>

      <p>
        Weather helm and sail balance represent critical aspects of sail plan design. The center of
        effort, where aerodynamic forces concentrate, must align properly with the underwater center
        of lateral resistance. Excessive weather helm indicates too much power in the mainsail
        relative to the headsail, requiring reefing or sail adjustment to maintain comfortable
        handling and optimal performance.
      </p>

      <p>
        Reefing systems allow sailors to reduce sail area when wind strength increases. Slab reefing
        lowers the boom and reduces mainsail height, while roller furling systems wrap sail material
        around a rotating forestay. Modern boats often feature multiple reefing points, enabling
        progressive sail reduction as conditions deteriorate. Proper reefing technique maintains
        sail shape and boat balance.
      </p>

      <p>
        Sail care and maintenance extend the life and performance of these critical components.
        Regular washing removes salt and pollutants that degrade fabric. Proper storage in a dry,
        ventilated space prevents mildew growth. UV protection, through covers or treated fabrics,
        guards against sun damage to exposed sail areas. Professional inspection identifies wear
        patterns and potential failures before they become critical problems.
      </p>
    </section>

    <section class="grid gap-4">
      <h2 class="text-3xl font-bold">Sail Handling and Seamanship</h2>
      <p>
        Proper sail handling begins before leaving the dock with thorough preparation and
        inspection. Checking all halyards, sheets, and control lines for wear ensures safe
        operation. Verifying that reefing lines run freely through their blocks prevents
        complications when conditions deteriorate. Pre-bending on sails allows them to stretch
        initially under controlled conditions, improving subsequent performance and shape retention
        throughout their service life.
      </p>

      <p>
        Hoisting sails requires coordination and attention to detail. The head must track smoothly
        up the mast without twisting or catching. Maintaining moderate tension while raising
        prevents the sail from flogging excessively. Once fully hoisted, appropriate halyard tension
        sets the luff curve, with lighter winds requiring less tension than heavy conditions. A
        properly tensioned halyard eliminates wrinkles along the luff while allowing the sail to
        develop its designed shape.
      </p>

      <p>
        Tacking and jibing represent fundamental maneuvers requiring precise timing and execution.
        During a tack, the helmsman turns the bow through the wind while crew releases the jib sheet
        on one side and trims it on the other. Smooth, coordinated movements maintain boat speed
        through the maneuver. Jibing, particularly with larger boats, demands careful control as the
        boom swings across the boat, with the mainsail sheet eased and then trimmed on the new tack.
      </p>

      <p>
        Heavy weather sailing tests both equipment and crew skill. Progressive reefing reduces sail
        area to match increasing wind strength, maintaining control and comfort. The first reef
        typically goes in when wind speed approaches 20 knots, with subsequent reefs added as
        conditions intensify. Storm sails, including trysails and storm jibs, provide crucial
        options when conditions exceed normal sail inventory capabilities.
      </p>

      <p>
        Sail changes at sea require careful planning and execution. Preparing the new sail below
        deck ensures it's ready for rapid deployment. Timing the change during a relative lull
        minimizes crew exposure and maintains boat control. Team coordination becomes essential,
        with clear communication and assigned roles for each crew member. Practice in moderate
        conditions builds confidence for executing changes when weather deteriorates.
      </p>

      <p>
        Night sailing introduces additional challenges to sail handling. Reduced visibility makes
        sail shape assessment difficult, requiring greater reliance on telltales and feel. Red deck
        lights preserve night vision while providing adequate illumination for sail handling tasks.
        Familiarity with deck layout and line locations becomes crucial when working in darkness.
        Conservative sail selection provides extra safety margin during nighttime passages.
      </p>

      <p>
        Man overboard procedures demand immediate action and practiced response. The moment someone
        falls overboard, crew must mark the position, initiate recovery maneuvers, and maintain
        visual contact. Quick reaction sailing maneuvers, whether quick-stop or figure-eight
        approaches, bring the boat back to the victim efficiently. Proper sail handling during
        recovery maintains boat control while positioning for pickup.
      </p>

      <p>
        Single-handed sailing requires different techniques and preparation. All lines must be led
        to the cockpit for solo management. Self-tacking jibs and roller furling systems simplify
        sail handling when crew availability is limited. Careful planning and conservative sail
        selection reduce the need for frequent adjustments. Autopilots or wind vanes maintain course
        while the sailor manages sails.
      </p>

      <p>
        Docking under sail demonstrates advanced boat handling skills. Approaching the dock requires
        careful speed control through sail adjustment rather than engine power. Wind direction
        relative to the dock determines approach angle and which sails to use. Practice in open
        water builds confidence before attempting actual docking maneuvers. Having fenders and lines
        ready ensures smooth transitions from sailing to secured positions.
      </p>

      <p>
        Emergency sail repairs at sea demand improvisation and resourcefulness. Sail tape provides
        temporary fixes for small tears and worn areas. Sewing palm and needles allow more permanent
        repairs when time and conditions permit. Spare battens and slides address common failure
        points. Understanding basic sail construction helps crew execute effective emergency repairs
        that keep the vessel operational until professional repairs can be completed ashore.
      </p>
    </section>
  </article>
</template>
