set dotenv-load := true

default: run

run *args:
    uv run python -m zero_termodinamica run {{ args }}

run_stub *args:
    uv run python -m zero_termodinamica stub {{ args }}

refresh_io:
    uv run python ./scripts/io_list_to_json.py

check: lint type_check test

lint:
    uv run ruff check

type_check:
    uv run pyright ./src ./tests

test *args:
    uv run pytest {{ args }}

format:
    uv run ruff format --check src tests
