def get_bits_from_int(val_int, val_size: int = 16): ...
int2bits = get_bits_from_int

def byte_length(bit_length): ...
def test_bit(value, offset): ...
def set_bit(value, offset): ...
def reset_bit(value, offset): ...
def toggle_bit(value, offset): ...
def word_list_to_long(val_list, big_endian: bool = True, long_long: bool = False): ...
words2longs = word_list_to_long

def long_list_to_word(val_list, big_endian: bool = True, long_long: bool = False): ...
longs2words = long_list_to_word

def get_2comp(val_int, val_size: int = 16): ...
twos_c = get_2comp

def get_list_2comp(val_list, val_size: int = 16): ...
twos_c_l = get_list_2comp

def decode_ieee(val_int, double: bool = False): ...
def encode_ieee(val_float, double: bool = False): ...
def crc16(frame): ...
def valid_host(host_str): ...
