apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "..fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "..labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "..selectorLabels" . | nindent 6 }}
      app.kubernetes.io/part-of: iceburger
      app.kubernetes.io/component: worker
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "..labels" . | nindent 8 }}
        {{- with .Values.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
        app.kubernetes.io/part-of: iceburger
        app.kubernetes.io/component: worker
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      securityContext:
        fsGroupChangePolicy: Always
        sysctls: []
        supplementalGroups: []
        fsGroup: 1001
      containers:
        - name: iceburger
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
              - ALL
            privileged: false
            readOnlyRootFilesystem: true
            runAsGroup: 1001
            runAsNonRoot: true
            runAsUser: 1001
            seLinuxOptions: {}
            seccompProfile:
              type: RuntimeDefault
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          {{- with .Values.iceburger.resources }}
          resources:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          env:
            - name: RABBITMQ_HOST
              value: {{ .Values.rabbitmq.host | quote }}
            - name: RABBITMQ_PORT
              value: {{ .Values.rabbitmq.port | quote }}
            - name: RABBITMQ_USERNAME
              value: {{ .Values.rabbitmq.username | quote }}
            - name: RABBITMQ_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.rabbitmq.existingSecret }}
                  key: {{ .Values.rabbitmq.existingSecretPasswordKey }}
            - name: ICEBERG_CATALOG_TYPE
              value: {{ .Values.iceberg.catalogType | quote }}
            - name: ICEBERG_CATALOG_URI
              value: {{ .Values.iceberg.catalogUri | quote }}
            - name: ICEBERG_WAREHOUSE
              value: {{ .Values.iceberg.warehouse | quote }}
            - name: ICEBERG_NAMESPACE
              value: {{ .Values.iceberg.namespace | quote }}
            - name: S3_ENDPOINT
              value: {{ .Values.s3.endpoint | quote }}
            - name: S3_REGION
              value: {{ .Values.s3.region | quote }}
            - name: S3_ACCESS_KEY_ID
              value: {{ .Values.s3.accessKeyId | quote }}
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.s3.existingSecret }}
                  key: {{ .Values.s3.existingSecretAccessKeyIdKey }}
            - name: S3_SECRET_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.s3.existingSecret }}
                  key: {{ .Values.s3.existingSecretAccessKeyKey }}
            - name: SINK_WORKERS
              value: {{ .Values.iceburger.sinkWorkers | quote }}
          volumeMounts:
            - name: tmp
              mountPath: /tmp
      volumes:
        - name: tmp
          emptyDir: {}
      {{- with .Values.iceburger.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.iceburger.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.iceburger.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
