import json
from collections import defaultdict
from pathlib import Path
from typing import Any

from sailpack.parse import parse_directory
from sailpack.seed_utils import (
    build_load_case_records,
    escape_dollar_quoted_json,
    resolve_sail_set_id_sql,
)

AWA_RANGES: dict[str, tuple[float, float]] = {
    "upwind": (0.0, 60.0),
    "reaching": (60.0, 120.0),
    "downwind": (120.0, 180.0),
}

AWS_RANGES: list[tuple[float, float | None]] = [
    (0.0, 10.0),
    (10.0, 15.0),
    (15.0, 20.0),
    (20.0, 25.0),
    (25.0, 30.0),
    (30.0, 40.0),
    (40.0, None),
]


def _aws_distance(aws: float, lower: float, upper: float | None) -> float:
    if aws < lower:
        return lower - aws
    if upper is not None and aws >= upper:
        return aws - upper
    return 0.0


def _awa_contains(awa: float, range_id: str) -> bool:
    lower, upper = AWA_RANGES[range_id]
    if range_id == "downwind":
        return lower <= awa <= upper
    return lower <= awa < upper


def build_records(input_source: Path) -> list[dict[str, Any]]:
    sailpack_data = parse_directory(input_source)
    load_case_records = build_load_case_records(sailpack_data)

    by_sails: dict[tuple[str, ...], list[dict[str, Any]]] = defaultdict(list)
    for lc in load_case_records:
        key = tuple(sorted(lc["sail_abbreviations"]))
        by_sails[key].append(lc)

    records = [
        {
            "load_case_id": best["id"],
            "awa_range_id": awa_range_id,
            "aws_range_id": aws_range_id,
            "sail_abbreviations": list(sail_abbreviations),
        }
        for sail_abbreviations, candidates in sorted(by_sails.items())
        for awa_range_id in AWA_RANGES
        if (
            awa_candidates := [
                lc for lc in candidates if _awa_contains(lc["awa"], awa_range_id)
            ]
        )
        for aws_range_id, (aws_lower, aws_upper) in enumerate(AWS_RANGES)
        if (
            best := min(
                awa_candidates,
                key=lambda lc, lower=aws_lower, upper=aws_upper: (
                    _aws_distance(lc["aws"], lower, upper),
                    lc["id"],
                ),
            )
        )
    ]

    return records


def render_sql(records: list[dict[str, Any]]) -> str:
    mapping_json = escape_dollar_quoted_json(json.dumps(records, indent=2))

    return f"""-- Generated by src/sailpack/export_load_case_mapping_seed.py
-- Uses jsonb_to_recordset and resolves sail_set_id from sail abbreviations.

BEGIN;

WITH mapping_payload AS (
    SELECT *
    FROM jsonb_to_recordset($${mapping_json}$$::jsonb) AS t(
        load_case_id TEXT,
        awa_range_id TEXT,
        aws_range_id INT,
        sail_abbreviations TEXT[]
    )
),
resolved_mappings AS (
    SELECT
        payload.load_case_id,
        payload.awa_range_id,
        payload.aws_range_id,
        {resolve_sail_set_id_sql("payload")} AS sail_set_id
    FROM mapping_payload AS payload
)
INSERT INTO loads.load_case_mappings (
    load_case_id,
    awa_range_id,
    aws_range_id,
    sail_set_id
)
SELECT
    load_case_id,
    awa_range_id,
    aws_range_id,
    sail_set_id
FROM resolved_mappings
WHERE sail_set_id IS NOT NULL
ON CONFLICT (awa_range_id, aws_range_id, sail_set_id) DO UPDATE
SET
    load_case_id = EXCLUDED.load_case_id;

COMMIT;
"""


def export_load_case_mapping_seed_sql(
    input_source: Path, output_sql: Path
) -> tuple[int, int]:
    records = build_records(input_source)
    sql = render_sql(records)
    output_sql.write_text(sql, encoding="utf-8")
    return len(records), len(records)
