import json
from pathlib import Path
from typing import Any

import polars as pl

from sailpack.parse import parse_directory
from sailpack.seed_utils import (
    build_load_case_records,
    escape_dollar_quoted_json,
    extract_reference_values,
    read_reference_values_mapping,
    resolve_sail_set_id_sql,
)

NEWTON_PER_TONNE_FORCE = 9806.65


def build_reference_records(
    sailpack_data: pl.DataFrame, reference_values_mapping: pl.DataFrame
) -> list[dict[str, Any]]:
    reference_values = extract_reference_values(sailpack_data, reference_values_mapping)

    return [
        {
            "load_case_id": load_case_id,
            "variable_key": variable_key,
            "target": target,
            "alarm_low": None,
            "warning_low": None,
            "warning_high": None,
            "alarm_high": None,
        }
        for load_case_id, variable_key, target in reference_values.iter_rows()
    ]


def render_sql(
    load_case_records: list[dict[str, Any]], reference_records: list[dict[str, Any]]
) -> str:
    load_cases_json = escape_dollar_quoted_json(json.dumps(load_case_records, indent=2))
    reference_json = escape_dollar_quoted_json(json.dumps(reference_records, indent=2))

    return f"""-- Generated by src/sailpack/export_reference_values_seed.py
-- Uses jsonb_to_recordset and resolves sail_set_id from sail abbreviations.

BEGIN;

WITH load_case_payload AS (
    SELECT *
    FROM jsonb_to_recordset($${load_cases_json}$$::jsonb) AS t(
        id TEXT,
        name TEXT,
        tws NUMERIC,
        twa NUMERIC,
        aws NUMERIC,
        awa NUMERIC,
        bsp NUMERIC,
        heel NUMERIC,
        sail_abbreviations TEXT[]
    )
),
resolved_load_cases AS (
    SELECT
        payload.id,
        payload.name,
        payload.tws,
        payload.twa,
        payload.aws,
        payload.awa,
        payload.bsp,
        payload.heel,
        {resolve_sail_set_id_sql("payload")} AS sail_set_id
    FROM load_case_payload AS payload
),
upsert_load_cases AS (
    INSERT INTO loads.load_cases (id, name, tws, twa, aws, awa, bsp, heel, sail_set_id)
    SELECT
        id,
        name,
        tws,
        twa,
        aws,
        awa,
        bsp,
        heel,
        sail_set_id
    FROM resolved_load_cases
    ON CONFLICT (id) DO UPDATE
    SET
        name = EXCLUDED.name,
        tws = EXCLUDED.tws,
        twa = EXCLUDED.twa,
        aws = EXCLUDED.aws,
        awa = EXCLUDED.awa,
        bsp = EXCLUDED.bsp,
        heel = EXCLUDED.heel,
        sail_set_id = EXCLUDED.sail_set_id
    RETURNING id
),
reference_payload AS (
    SELECT *
    FROM jsonb_to_recordset($${reference_json}$$::jsonb) AS t(
        load_case_id TEXT,
        variable_key TEXT,
        target NUMERIC,
        alarm_low NUMERIC,
        warning_low NUMERIC,
        warning_high NUMERIC,
        alarm_high NUMERIC
    )
)
INSERT INTO loads.reference_values (
    load_case_id,
    variable_key,
    alarm_low,
    warning_low,
    target,
    warning_high,
    alarm_high
)
SELECT
    payload.load_case_id,
    payload.variable_key,
    payload.alarm_low,
    payload.warning_low,
    payload.target,
    payload.warning_high,
    payload.alarm_high
FROM reference_payload AS payload
JOIN upsert_load_cases AS load_case
    ON load_case.id = payload.load_case_id
ON CONFLICT (load_case_id, variable_key) DO UPDATE
SET
    alarm_low = EXCLUDED.alarm_low,
    warning_low = EXCLUDED.warning_low,
    target = EXCLUDED.target,
    warning_high = EXCLUDED.warning_high,
    alarm_high = EXCLUDED.alarm_high;

COMMIT;
"""


def export_reference_values_seed_sql(
    input_source: Path, output_sql: Path
) -> tuple[int, int]:
    sailpack_data = parse_directory(input_source)
    reference_values_mapping = read_reference_values_mapping(input_source)
    load_case_records = build_load_case_records(sailpack_data)
    reference_records = build_reference_records(sailpack_data, reference_values_mapping)
    sql = render_sql(load_case_records, reference_records)
    output_sql.write_text(sql, encoding="utf-8")

    return len(load_case_records), len(reference_records)
