import json
from pathlib import Path
from typing import Any

from sailpack.seed_utils import escape_dollar_quoted_json

AWA_RANGE_IDS = ["upwind", "reaching", "downwind"]
AWS_RANGE_IDS = [1, 2, 3, 4, 5, 6, 7]
LOAD_CASE_ID = "FM B Rchng"
SAIL_SET_ID = 1019


def build_records() -> list[dict[str, Any]]:
    # For now, just generate all combinations of AWA and AWS ranges for the FM B Reaching load case.
    records: list[dict[str, Any]] = []

    for awa_range_id in AWA_RANGE_IDS:
        for aws_range_id in AWS_RANGE_IDS:
            records.append(
                {
                    "load_case_id": LOAD_CASE_ID,
                    "awa_range_id": awa_range_id,
                    "aws_range_id": aws_range_id,
                    "sail_set_id": SAIL_SET_ID,
                }
            )

    return records


def render_sql(records: list[dict[str, Any]]) -> str:
    mapping_json = escape_dollar_quoted_json(json.dumps(records, indent=2))

    return f"""-- Generated by src/sailpack/export_load_case_mapping_seed.py
-- Uses jsonb_to_recordset and resolves load cases.

BEGIN;

WITH mapping_payload AS (
    SELECT *
    FROM jsonb_to_recordset($${mapping_json}$$::jsonb) AS t(
        load_case_id TEXT,
        awa_range_id TEXT,
        aws_range_id INT,
        sail_set_id INT
    )
)
INSERT INTO loads.load_case_mappings (
    load_case_id,
    awa_range_id,
    aws_range_id,
    sail_set_id
)
SELECT
    payload.load_case_id,
    payload.awa_range_id,
    payload.aws_range_id,
    payload.sail_set_id
FROM mapping_payload AS payload
ON CONFLICT (awa_range_id, aws_range_id, sail_set_id) DO UPDATE
SET
    load_case_id = EXCLUDED.load_case_id;

COMMIT;
"""


def export_seed_sql(output_sql: Path) -> tuple[int, int]:
    records = build_records()
    sql = render_sql(records)
    output_sql.write_text(sql, encoding="utf-8")

    return len(records), len(records)
