apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "zero-atpx-nmea.name" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "zero-atpx-nmea.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "zero-atpx-nmea.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "zero-atpx-nmea.labels" . | nindent 8 }}
        {{- with .Values.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      securityContext:
        fsGroup: 1001
      containers:
        - name: atpx-nmea
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
              - ALL
            readOnlyRootFilesystem: true
            runAsGroup: 1001
            runAsNonRoot: true
            runAsUser: 1001
            seccompProfile:
              type: RuntimeDefault
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          args: ["run"]
          env:
            - name: ATPX_MQTT_HOST
              value: {{ .Values.atpxMqtt.host | quote }}
            - name: ATPX_MQTT_PORT
              value: {{ .Values.atpxMqtt.port | quote }}
            - name: MQTT_HOST
              value: {{ .Values.mqtt.host | quote }}
            - name: MQTT_PORT
              value: {{ .Values.mqtt.port | quote }}
            {{- if .Values.mqtt.username }}
            - name: MQTT_USER
              value: {{ .Values.mqtt.username | quote }}
            {{- end }}
            {{- if .Values.mqtt.existingSecret }}
            - name: MQTT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.mqtt.existingSecret }}
                  key: {{ .Values.mqtt.existingSecretPasswordKey }}
            {{- end }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          volumeMounts:
            - mountPath: /tmp
              name: tmp
      volumes:
        - emptyDir: {}
          name: tmp
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
