replicaCount: 1

image:
  repository: europe-west1-docker.pkg.dev/common-449414/common/zero-loads-app
  pullPolicy: IfNotPresent
  tag: ""

mqtt:
  host:
  port: 1883
  username: loads
  existingSecret:
  existingSecretPasswordKey: password

postgresql:
  host:
  port: 5432
  user: loads
  db:
  existingSecret:
  existingSecretPasswordKey: password

api:
  env: production
  resources: {}
  nodeSelector: {}
  tolerations: []
  affinity: {}
  service:
    labels: {}
    annotations: {}
    externalIPs: []

  ingress:
    enabled: false
    hostname: ""
    className: "tailscale"

imagePullSecrets: []

nameOverride: ""
fullnameOverride: ""

podAnnotations: {}
podLabels: {}
