name: "Zero UI Apps: Test and push Docker image"
on:
  pull_request:
    paths:
      - .github/workflows/ci_apps.yaml
      - zero-ui/**
      - zero-loads-app/**
      - zero-thrs-control/**
  release:
    types: [released]
  push:
    branches:
      - main
    paths:
      - .github/workflows/ci_apps.yaml
      - zero-ui/**
      - zero-loads-app/**
      - zero-thrs-control/**

env:
  IMAGE: "europe-west1-docker.pkg.dev/common-449414/common/zero-ui"

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: pnpm/action-setup@v4
        with:
          package_json_file: zero-ui/package.json

      - uses: actions/setup-node@v4
        with:
          node-version: "22.x"
          cache: "pnpm"
          cache-dependency-path: zero-ui/pnpm-lock.yaml

      - name: Install dependencies
        working-directory: zero-ui
        run: pnpm install

      - name: Run ESLint
        working-directory: zero-ui
        run: pnpm lint --max-warnings 0

      - name: Run unit tests
        working-directory: zero-ui
        run: pnpm test:unit

      - name: Create .env file from secret in root for services
        run: |
          echo "${{ secrets.ENV }}" > .env

      - name: Create .env file from secret in Loads project
        run: |
          echo "${{ secrets.ENV_LOADS_APP }}" > .env
        working-directory: zero-loads-app

      - name: Create .env file from secret in THRS project
        run: |
          echo "${{ secrets.ENV_THRS }}" > .env
        working-directory: zero-thrs-control

      - name: Run services
        run: docker compose --profile loads --profile thrs up --quiet-pull --wait

      - name: Waiting for services to be ready
        run: sleep 30s
        shell: bash

      - name: Run api integration tests
        working-directory: zero-ui
        run: pnpm test:api

      - name: Build documentation
        working-directory: zero-ui
        run: pnpm docs:build

      - name: Install Playwright Browsers
        working-directory: zero-ui
        run: pnpm exec playwright install --with-deps chromium

      - name: Run Playwright tests
        working-directory: zero-ui
        run: pnpm exec playwright test
        env:
          PLAYWRIGHT_TEST_BASE_URL: http://localhost:5173
          VITE_GRAPHQL_WS_URL: ws://localhost:8080/v1/graphql
          VITE_GRAPHQL_URL: http://localhost:8080/v1/graphql
          VITE_GRAPHQL_TOKEN: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJodHRwczovL2hhc3VyYS5pby9qd3QvY2xhaW1zIjp7IngtaGFzdXJhLWRlZmF1bHQtcm9sZSI6InVzZXIiLCJ4LWhhc3VyYS1hbGxvd2VkLXJvbGVzIjpbInVzZXIiXX19.8brSVzCMabnkuvgO4ipCVAPaAWieM3sqWADXoUxgmEA
      - uses: actions/upload-artifact@v4
        if: ${{ !cancelled() }}
        with:
          name: playwright-report
          path: zero-ui/playwright-report/
          retention-days: 7
      - uses: actions/upload-artifact@v4
        if: ${{ !cancelled() }}
        with:
          name: screenshots
          path: zero-ui/screenshots/
          retention-days: 7
      - uses: actions/upload-artifact@v4
        if: ${{ !cancelled() }}
        with:
          name: zero-ui-docs
          path: zero-ui/docs/.vitepress/dist
          retention-days: 7

  docker-push:
    runs-on: ubuntu-latest
    needs: test
    permissions:
      contents: "read"
      id-token: "write"
    steps:
      - uses: actions/checkout@v4
      # Set up in https://github.com/foundation-zero/gcp-common
      - id: auth
        name: Authenticate with Google Cloud
        uses: google-github-actions/auth@v2
        with:
          token_format: access_token
          project_id: ${{ secrets.GCP_COMMON_PROJECT_ID }}
          workload_identity_provider: ${{ secrets.GCP_COMMON_WORKLOAD_IDENTITY_PROVIDER }}
          service_account: ${{ secrets.GCP_COMMON_SERVICE_ACCOUNT }}
          access_token_lifetime: 300s
      - name: Login to Artifact Registry
        uses: docker/login-action@v3
        with:
          registry: europe-west1-docker.pkg.dev
          username: oauth2accesstoken
          password: ${{ steps.auth.outputs.access_token }}
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: |
            ${{ env.IMAGE }}
          tags: |
            type=sha
            type=semver,pattern={{version}}
      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: zero-ui
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}

  push-cloudflare:
    runs-on: ubuntu-latest
    #needs: test
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
        with:
          package_json_file: zero-ui/package.json

      - uses: actions/setup-node@v4
        with:
          node-version: "22.x"
          cache: "pnpm"
          cache-dependency-path: zero-ui/pnpm-lock.yaml
      - name: Install dependencies
        working-directory: zero-ui
        run: pnpm install
      - name: Build
        run: pnpm build
        working-directory: zero-ui
      - name: Add env.json
        working-directory: zero-ui/dist
        run: |
          echo '{
            "VITE_THRS_API_SERVER_URL": "https://thrs-control-singel.tail0b4840.ts.net/graphql",
            "VITE_LOADS_API_SERVER_URL": "https://loads-app-singel.tail0b4840.ts.net/graphql",
            "VITE_GRAPHQL_URL": "https://hasura-singel.tail0b4840.ts.net/v1/graphql",
            "VITE_GRAPHQL_WS_URL": "ws://hasura-singel.tail0b4840.ts.net/v1/graphql",
            "VITE_GRAPHQL_TOKEN": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJodHRwczovL2hhc3VyYS5pby9qd3QvY2xhaW1zIjp7IngtaGFzdXJhLWRlZmF1bHQtcm9sZSI6InVzZXIiLCJ4LWhhc3VyYS1hbGxvd2VkLXJvbGVzIjpbInVzZXIiXX19.8brSVzCMabnkuvgO4ipCVAPaAWieM3sqWADXoUxgmEA"
          }' > env.json
      - name: Deploy preview
        id: deploy
        uses: cloudflare/pages-action@1
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          projectName: zero-ui
          directory: "zero-ui/dist"
          wranglerVersion: 3
      - name: PR Comments
        uses: mshick/add-pr-comment@v2
        if: ${{ steps.deploy.outputs.url != '' }}
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          message-id: deploy-preview
          message-failure: Unable to post deploy URL
          message: |
            Deploy preview available: ${{ steps.deploy.outputs.url }}
