name: "Zero Generator: Test"
on:
  pull_request:
    paths:
      - zero-generator/**
      - zero-loads-app/**
      - .github/workflows/ci_generator.yaml
  release:
    types: [released]

jobs:
  test:
    timeout-minutes: 15
    runs-on: ubuntu-latest
    outputs:
      image_tag: ${{ steps.image_tag.outputs.image_tag }}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: '0'
      - uses: actions/setup-python@v5
        with:
          python-version: 3.13
      - run: pipx install poetry==2.1.4
      - run: poetry check
        working-directory: zero-generator
      - uses: astral-sh/ruff-action@v3
        with:
          src: "./zero-generator"
      - run: poetry install --extras dev --extras test
        working-directory: zero-generator
      - run: poetry run mypy src
        working-directory: zero-generator
      - name: Create .env file from secret
        run: |
          echo "${{ secrets.ENV }}" > .env
      - name: Run services
        run: docker compose --profile zero up -d --quiet-pull --wait
      - name: Unit Test
        run: poetry run pytest . -vv
        working-directory: zero-generator
