name: "Zero Generator: Test"
on:
  pull_request:
    paths:
      - zero-generator/**
      - zero-loads-app/**
      - .github/workflows/ci_generator.yaml
  release:
    types: [released]
  push:
    branches:
      - main
    paths:
      - zero-generator/**
      - zero-loads-app/**
      - .github/workflows/ci_generator.yaml

jobs:
  test:
    timeout-minutes: 15
    runs-on: ubuntu-latest
    outputs:
      image_tag: ${{ steps.image_tag.outputs.image_tag }}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: "0"
      - uses: actions/setup-python@v5
        with:
          python-version: 3.13
      - uses: astral-sh/setup-uv@v8.1.0
      - run: uv sync --locked
        working-directory: zero-generator
      - run: uv run ruff check --no-fix src tests
        working-directory: zero-generator
      - run: uv run ruff format --check src tests
        working-directory: zero-generator
      - run: uv run mypy src
        working-directory: zero-generator
      - name: Create .env file from secret in root
        run: |
          echo "${{ secrets.ENV }}" > .env
      - name: Run services
        run: docker compose --profile zero up -d --quiet-pull --wait vernemq
      - name: Unit Test
        run: uv run pytest . -vv
        working-directory: zero-generator
