name: "Modbus Bridge: Test"
on:
  pull_request:
    paths:
      - zero-modbus-bridge/**
      - .github/workflows/ci_modbus_bridge.yaml
  push:
    branches:
      - main
    paths:
      - zero-modbus-bridge/**
      - .github/workflows/ci_modbus_bridge.yaml

jobs:
  test:
    timeout-minutes: 10
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
        with:
          fetch-depth: "0"
      - uses: actions/setup-python@v7
        with:
          python-version: 3.13
      - uses: astral-sh/setup-uv@v10.0.1
      - run: uv sync --locked --extra tui
        working-directory: zero-modbus-bridge
      - run: uv run ruff check --no-fix
        working-directory: zero-modbus-bridge
      - run: uv run pyright
        working-directory: zero-modbus-bridge
      - run: uv run pytest
        working-directory: zero-modbus-bridge
