name: "Prop Test: Test and push Docker image"
on:
  pull_request:
    paths:
      - zero-prop-test/**
      - .github/workflows/ci_prop_test.yaml
  release:
    types: [released]
  push:
    branches:
      - main
    paths:
      - zero-prop-test/**
      - .github/workflows/ci_prop_test.yaml

env:
  IMAGE: "europe-west1-docker.pkg.dev/common-449414/common/zero-prop-test"

jobs:
  test:
    timeout-minutes: 15
    runs-on: ubuntu-latest
    outputs:
      image_tag: ${{ steps.image_tag.outputs.image_tag }}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: "0"
      - uses: actions/setup-python@v5
        with:
          python-version: 3.13
      - name: Install the latest version of uv
        uses: astral-sh/setup-uv@v8.1.0
      - run: uv run ruff check src tests
        working-directory: zero-prop-test
      - run: uv run ruff format --check src tests
        working-directory: zero-prop-test
      - run: uv run pyright
        working-directory: zero-prop-test
      - run: uv run pytest -v
        working-directory: zero-prop-test
