name: "THRS Control: Test"
on:
  pull_request:
    paths:
      - zero-thrs-control/**
      - .github/workflows/ci_thrs_control.yaml
  release:
    types: [released]

jobs:
  test:
    timeout-minutes: 15
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: '0'

      - uses: actions/setup-python@v5
        with:
          python-version: 3.13

      - run: pipx install poetry==2.1.4
        working-directory: zero-thrs-control

      - name: Create .env file from secret in root for services
        run: |
          echo "${{ secrets.ENV }}" > .env

      - name: Create .env file from secret in project
        run: |
          echo "${{ secrets.ENV_THRS }}" > .env
        working-directory: zero-thrs-control

      - name: Setup Graphviz
        uses: ts-graphviz/setup-graphviz@v2

      - run: poetry install --with dev,test
        working-directory: zero-thrs-control

      - run: poetry run fmpy compile src/thrs/simulation/models/XRGTestModel/FMUInterfaceTester_MECS_regular.fmu
        working-directory: zero-thrs-control

      - run: poetry run fmpy compile src/thrs/simulation/models/thruster_moduleV18.fmu
        working-directory: zero-thrs-control

      - run: poetry run fmpy compile src/thrs/simulation/models/pvt_moduleV15_1.fmu
        working-directory: zero-thrs-control

      - run: poetry run fmpy compile src/thrs/simulation/models/consumers_moduleV7_1.fmu
        working-directory: zero-thrs-control

      - run: poetry run fmpy compile src/thrs/simulation/models/HT_systemV12_1.fmu
        working-directory: zero-thrs-control

      - run: poetry run fmpy compile src/thrs/simulation/models/pcm_moduleV7.fmu
        working-directory: zero-thrs-control

      - run: poetry run pyright
        working-directory: zero-thrs-control

      - run: poetry run ruff check src tests
        working-directory: zero-thrs-control

      - run: poetry run ruff format --check src tests
        working-directory: zero-thrs-control

      - run: docker compose --profile zero up -d --quiet-pull --wait

      - run: poetry run pytest -v
        working-directory: zero-thrs-control
