name: "Zero Data: Deploy zero-data-gen chart"
on:
  release:
    types: [released]

jobs:
  helm-push:
    uses: "./.github/workflows/job_helm_push.yaml"
    permissions:
      contents: "read"
      id-token: "write"
    secrets: inherit
    with:
      helm_chart: "zero-data/charts/data_gen"
