name: "THRS Control: Helm chart"
on:
  release:
    types: [released]

jobs:
  helm-push:
    uses: "./.github/workflows/job_helm_push.yaml"
    permissions:
      contents: "read"
      id-token: "write"
    secrets: inherit
    with:
      helm_chart: "zero-thrs-control/charts/zero-thrs-control"
