name: "Test Helm Push"

on:
  push:
    branches:
      - fix/fix-helm-push

jobs:
  helm-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Test Version Substitution
        id: chart_info
        run: |
          # will be feature branch in test (strip off fix/ to test)
          export GIT_REF=${{github.ref_name}}
          echo $GIT_REF
          export VERSION=${GIT_REF#fix/}

          echo $VERSION
