apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "zero-thrs-control.envvars" . }}
  namespace: {{ .Release.Namespace }}
  labels: {{- include "zero-thrs-control.labels" . | nindent 4 }}
data:
  MQTT_HOST: {{ .Values.mqtt.host }}
  MQTT_PORT: {{ .Values.mqtt.port | quote }}
  MQTT_DEVICES_TOPIC_PREFIX: {{ .Values.mqtt.devicesTopicPrefix }}
  MQTT_CONTROLLER_TOPIC_PREFIX: {{ .Values.mqtt.controllerTopicPrefix }}
  MQTT_SIMULATION_TOPIC_PREFIX: {{ .Values.mqtt.simulationTopicPrefix }}
  MQTT_CONTROL_TOPIC_SUFFIX: Command
  MQTT_USERNAME: {{ .Values.mqtt.username }}
