{{- if .Values.control.enabled }}
{{- $root := . }}
{{- range $index, $type_name := $root.Values.control.types }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ print (include "zero-thrs-control.control" $root) "-" $type_name }}
  namespace: {{ $root.Release.Namespace }}
  labels:
    {{- include "zero-thrs-control.labels" $root | nindent 4 }}
    app.kubernetes.io/part-of: thrs-control
    app.kubernetes.io/component: {{ print "control-" $type_name }}
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      {{- include "zero-thrs-control.selectorLabels" $root | nindent 6 }}
      app.kubernetes.io/part-of: thrs-control
      app.kubernetes.io/component: {{ print "control-" $type_name }}
  template:
    metadata:
      labels:
        {{- include "zero-thrs-control.labels" $root | nindent 8 }}
        app.kubernetes.io/part-of: thrs-control
        app.kubernetes.io/component: {{ print "control-" $type_name }}
    spec:
      {{- with $root.Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      securityContext:
        fsGroup: 1001
        seccompProfile:
          type: RuntimeDefault
      containers:
        - name: thrs-control
          args:
           - "control"
           - "--mode"
           - "{{ $type_name }}"
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
              - ALL
            readOnlyRootFilesystem: true
            runAsNonRoot: true
          image: "{{ $root.Values.control.image.repository }}:{{ $root.Values.control.image.tag | default $root.Chart.AppVersion }}"
          imagePullPolicy: {{ $root.Values.control.image.pullPolicy }}
          resources:
            {{- toYaml $root.Values.control.resources | nindent 12 }}
          env:
            - name: PG_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ $root.Values.postgresql.existingSecret }}
                  key: {{ $root.Values.postgresql.existingSecretPasswordKey }}
          envFrom:
            - configMapRef:
                name: {{ include "zero-thrs-control.envvars" $root }}
          volumeMounts:
            - mountPath: /tmp
              name: tmp-volume
          livenessProbe:
            {{- include "zero-thrs-control.livenessProbe" $root.Values.livenessPath | nindent 12 }}
      volumes:
        - name: tmp-volume
          emptyDir: {}
{{- end }}
{{- end }}
