{{- if .Values.control.enabled }}
apiVersion: v1
kind: Service
metadata:
  namespace: {{ .Release.Namespace }}
  name: {{ include "zero-thrs-control.control" . }}
  labels:
    {{- include "zero-thrs-control.labels" . | nindent 4 }}
spec:
  ports:
  - port: 5102
    targetPort: http
    protocol: TCP
  selector:
    {{- include "zero-thrs-control.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: control
  type: ClusterIP
{{- end }}
