{{/*
Compile all warnings into a single message, and call fail.
*/}}
{{- define "zero-thrs-control.validateValues" -}}
{{- $messages := list -}}
{{- $messages := append $messages (include "zero-thrs-control.validateValues.mqttHost" .) -}}
{{- $messages := append $messages (include "zero-thrs-control.validateValues.mqttPort" .) -}}
{{- $messages := without $messages "" -}}
{{- $message := join "\n" $messages -}}

{{- if $message -}}
{{-   printf "\nVALUES VALIDATION:\n%s" $message | fail -}}
{{- end -}}
{{- end -}}

{{/* Must provide a host for MQTT */}}
{{- define "zero-thrs-control.validateValues.mqttHost" -}}
{{- if not .Values.mqtt.host  -}}
    zero-thrs-control: mqtt.host is a required value
{{- end -}}
{{- end -}}

{{/* Must provide a port for MQTT */}}
{{- define "zero-thrs-control.validateValues.mqttPort" -}}
{{- if not .Values.mqtt.port  -}}
    zero-thrs-control: mqtt.port is a required value
{{- end -}}
{{- end -}}
